### ISSUE TITLE
Regression test for #1037

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1040]
#1037 was merged in quickly to make it for 0.6.1. A regression test would be useful.

**Comment by djrtwo** [comment]
The code path is known to be executed so that is good but need a test in which attestations vote on incorrect head but correct justified source and still get rewarded

**Comment by JustinDrake** [comment]
Closing for staleness, and in favour of fuzz testing to catch these edge cases.
