### ISSUE TITLE
Validator spec includes removed function

### ISSUE THREAD

**Issue by wemeetagain** [ethereum/eth2.0-specs#1047]
`get_committee_assignment` still references `get_crosslink_committees_at_slot` which was removed in v0.6.1

https://github.com/ethereum/eth2.0-specs/blob/v0.6.1/specs/validator/0_beacon-chain-validator.md#validator-assignments

**Comment by djrtwo** [comment]
oh thanks! will clean up today.

**Comment by wemeetagain** [comment]
Duplicate of #1082
