### ISSUE TITLE
Add "design goals" to the README?

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/eth2.0-specs#105]
There is much chat about the "design goals" of ETH2.0.

Is it worthwhile to add a section to the README that lists the design goals for this project?

I think this could be helpful in terms of communicating to the broader community about the context around ETH2.0.

**Comment by djrtwo** [comment]
I think that makes sense. I plan on adding links and other info to the readme and will do so with that.
Also thinking about adding an FAQ in there as well

**Comment by djrtwo** [comment]
some quick ones that come to mind:

- live through major network paritions (WWIII)
- all components are either quantum secure or can be easily swapped out for quantum secure counterparts when available
- utilize crypto and design techniques that allow for large participation of validators in total and per unit time
- a typical laptop with O(C) resources can process/validate O(1) shards (including any system level validation such as the beacon chain)

**Comment by vbuterin** [comment]
> live through major network paritions (WWIII)

I'd clarify this as "live through major network partitions and very large portions of nodes going offline". WWIII is more of a metaphor for big disaster in general; something like the Shanghai DoS attacks is a very real possibility that already happened.

I'd add a very big one, "minimize complexity, even at the cost of some losses in efficiency". IMO this spec is already at the upper limit of the level of complexity that is acceptable for this kind of system.
