### ISSUE TITLE
validator rotation halting 

### ISSUE THREAD

**Issue by terenc3t** [ethereum/eth2.0-specs#106]
The conditions for validator rotation says that all shard need to have a crosslink from a slot beyond `validatot_change_slot`, that means an attacker could potentially bribe validators of one shard to delay the rotation by not cross-linking. Especially in beginning, not all the shards are assigned to a committee per CYCLE_LENGTH. In that case, an attacker only needs to bribe MIN_COMMITTEE_SIZE * 2/3 validators to perform this kind of bribing attack. Should we loosen the validator rotation condition to 2/3 crosslink?

**Comment by JustinDrake** [comment]
Requiring out of band coordination to fix for (1) would be a liveness fail, in particular in regards to the "surviving WW3" design goal. IMO there should be some reshuffling/resampling mechanism.
