### ISSUE TITLE
Edge case issue in crosslink processing 

### ISSUE THREAD

**Issue by mkalinin** [ethereum/eth2.0-specs#1070]
## Issue
Encountered with crosslinks produced by committees of latest epoch slot.

#### Chain setup
```
shards = 4
slots  = 4
crosslinks[3] = (0 -> A)
```

#### Steps
```
epoch = 0
  crosslink (A -> B) for shard 3 is fired
epoch 0 -> 1 transition:
  crosslinks[3] = (0 -> A), has not been updated

epoch = 1
  crosslink `A -> B` is added to state as pending
  crosslink `A -> B'` for shard 3 is fired
epoch 1 -> 2 transition:
  crosslinks[3] = (A -> B), now B is wanted as parent crosslink
  (A -> B') is rejected as its parent still refers to A
  shard 3 committee got penalized
```

**Comment by JustinDrake** [comment]
Is this edge case still present? (Sorry, I'm not sure I understand all your notation.)

**Comment by mkalinin** [comment]
Yes, this one is still present. And this particular issues refers to a case when two conflicting crosslinks are produced by attesters. I'll try to bring more clarity to it.
Assume there is a chain with 4 slots per epoch and 4 shards (our default simulation):
```
slot 3:
  A1: AttestationData[shard=3, target_epoch=0, previous_crosslink_root=db56114e, source_epoch=0]

slot 4:
  epoch transition 0 --> 1
  new block with A1 proposed
  A1 added to state
  A2: AttestationData[shard=3, target_epoch=1, previous_crosslink_root=db56114e, source_epoch=0]

slot 5:
  new block with A2 proposed
  A2 added to state

...

slot 8:
  epoch transition 1 --> 2
```
At the beginning of `1 --> 2` epoch transition state has two pending attestations `A1` and `A2` with same `shard`, `previous_crosslink_root` and `source_epoch` but different `target_epoch`. 

`process_crosslinks` handles slots in ascending order and first attestation it processes is `A1`. Thus, current crosslink for `shard 3` is set to `A1`.

After that `A2` is discarded cause there is no more matching between its `previous_crosslink_root` and current crosslink root for `shard 3`.

**Comment by mkalinin** [comment]
Yet another issue related to crosslinks processing.
`get_winning_crosslink_and_attesting_indices` relays on `state.current_crosslinks` which is updated by epoch transition.
Therefore its result returned when crosslink is being processed may differ from result got an epoch later when reward for this crosslink is being calculated.

**Comment by mkalinin** [comment]
Will re-check this after an update to `v0.7.0`.

**Comment by JustinDrake** [comment]
> `process_crosslinks` handles slots in ascending order and first attestation it processes is `A1`. Thus, current crosslink for `shard 3` is set to `A1`.

A couple questions:

1) When you write "handles slots", do you mean "handles epochs"?
2) The code in `process_crosslinks` updates the crosslinks (i.e. `state.current_crosslinks[shard] = winning_crosslink`) under `for epoch in (get_previous_epoch(state), get_current_epoch(state)):`. This means that the winning crosslink when `epoch == get_current_epoch(state)` takes precedence over the winning crosslink when `epoch == get_previous_epoch(state)` because it is run after. As such I'm expecting `A2` to take precedence over `A1`.

> Therefore its result returned when crosslink is being processed may differ from result got an epoch later when reward for this crosslink is being calculated.

Can you expand on this? Are you saying that the incentivisation in `get_crosslink_deltas` is broken?

**Comment by mkalinin** [comment]
> Are you saying that the incentivisation in `get_crosslink_deltas` is broken?

Yes. Let me share logs grabbed from our simulation, I hope it'll help to bring more clarity.

#### Crosslink format
Log represents crosslink in following format:
```
shard: {[start_epoch..end_epoch], parent_root <~ root}
```
To identify roots it uses first eight symbols of its hexadecimal representation.
For example, crosslink message `1: {[1..2], cab378d7 <~ 0a592668}` reads as following:
```
shard = 1
start_epoch = 1
end_epoch = 2
parent_root = cab378d7
root = 0a592668
```

#### Simulation
```
spec: v0.7.1
registry size: 8
SHARD_COUNT: 4
SLOTS_PER_EPOCH: 4
```
_Note:_ slot specified in logs is a slot of crosslink creation; crosslinks are included on chain one slot later.
```
slot #0: v0, shard 0: {[0..0], c78009fd <~ 275d37ac}
slot #0: v7, shard 0: {[0..0], c78009fd <~ 275d37ac}
slot #1: v4, shard 1: {[0..0], c78009fd <~ a81cabce}
slot #1: v3, shard 1: {[0..0], c78009fd <~ a81cabce}
slot #2: v1, shard 2: {[0..0], c78009fd <~ 83974be1}
slot #2: v2, shard 2: {[0..0], c78009fd <~ 83974be1}
slot #3: v5, shard 3: {[0..0], c78009fd <~ ea585e86} // shard 3 crosslinks will be added
slot #3: v6, shard 3: {[0..0], c78009fd <~ ea585e86} // to state after epoch transition
Epoch transition 0 => 1:
prev: [0: {[0..0], 00000000 <~ c78009fd}, 0: {[0..0], 00000000 <~ c78009fd}, 0: {[0..0], 00000000 <~ c78009fd}, 0: {[0..0], 00000000 <~ c78009fd}]
curr: [0: {[0..0], c78009fd <~ 275d37ac}, 1: {[0..0], c78009fd <~ a81cabce}, 2: {[0..0], c78009fd <~ 83974be1}, 0: {[0..0], 00000000 <~ c78009fd}]
  Validators rewarded:  [] // rewards are not calculated
  Validators penalized: []

slot #4: v2, shard 3: {[0..1], c78009fd <~ fd1d95b9} // issue 1: we have pair of conflicting
slot #4: v7, shard 3: {[0..1], c78009fd <~ fd1d95b9} // crosslinks with same parent_root
slot #5: v1, shard 0: {[0..1], 275d37ac <~ 2f3a6cfb}
slot #5: v6, shard 0: {[0..1], 275d37ac <~ 2f3a6cfb}
slot #6: v3, shard 1: {[0..1], a81cabce <~ cab378d7}
slot #6: v0, shard 1: {[0..1], a81cabce <~ cab378d7}
slot #7: v5, shard 2: {[0..1], 83974be1 <~ cfc8c8f1}
slot #7: v4, shard 2: {[0..1], 83974be1 <~ cfc8c8f1}
Epoch transition 1 => 2:
prev: [0: {[0..0], c78009fd <~ 275d37ac}, 1: {[0..0], c78009fd <~ a81cabce}, 2: {[0..0], c78009fd <~ 83974be1}, 0: {[0..0], 00000000 <~ c78009fd}]
curr: [0: {[0..1], 275d37ac <~ 2f3a6cfb}, 1: {[0..1], a81cabce <~ cab378d7}, 2: {[0..0], c78009fd <~ 83974be1}, 3: {[0..0], c78009fd <~ ea585e86}]
  Validators rewarded: attestations:  [0,1,2,3,4,5,6,7] crosslinks:  [1,2,5,6]
  Validators penalized: crosslinks:   [0,3,4,7]  

// issue 2: 0 and 1 committees got penalized
// cause 'curr' crosslinks used in rewards calculation were updated by epoch transition
//
// in other words 'get_winning_crosslink_and_attesting_indices' is not an invariant
// before transition it would return [0: {[0..0], c78009fd <~ 275d37ac}, [0,7]]
// after transition it returns [0: {[0..1], 275d37ac <~ 2f3a6cfb, []]
```

**Comment by djrtwo** [comment]
Crosslinks removed from phase 0 and very much reworked for phase 1. Edge case no longer exists :)

closing!
