### ISSUE TITLE
Set genesis block body root to ssz hash of the empty struct rather than empty hash

### ISSUE THREAD

**Issue by sorpaas** [ethereum/eth2.0-specs#1089]
A block is not useful unless it has a way to point to its parent block, so that an importer knows how to import it. Although the spec does not define it, all block intrinsically has a block identifier. Currently our block identifier is defined by `previous_block_root`:

```
signing_root(BeaconBlockHeader {
  	slot: block.slot,
	previous_block_root: block.previous_block_root,
	state_root: self.0.state_root,
	block_body_root: if is_genesis {
		Default::default()
	} else {
		hash(&block.body)
	},
	..Default::default()
})
```

Notice the if statement just for genesis block. If, instead, we change genesis `block_body_root` to empty struct signing root, it can be avoided.

**Comment by JustinDrake** [comment]
I agree that we want to minimise special cases. I'm not sure though what the best genesis design is. Changing `genesis_block.parent_root` to `signing_root(BeaconBlock())` means having two beacon blocks with slot 0.
