### ISSUE TITLE
Document all intermediate values that are signed integers

### ISSUE THREAD

**Issue by sorpaas** [ethereum/eth2.0-specs#1090]
Values, like `(pivot - index)` in `get_shuffled_index`, are required to be signed (in the plain form represented there). So it would be great to document all cases of them (as some clients have the assumptions that integers are unsigned).

**Comment by JustinDrake** [comment]
> `(pivot - index)` in `get_shuffled_index`

Good catch! Fixed in #1092. Do you see other instances?

**Comment by sorpaas** [comment]
No I haven't found others.
