### ISSUE TITLE
Explicit unhandled exceptions

### ISSUE THREAD

**Issue by sorpaas** [ethereum/eth2.0-specs#1091]
The spec specifies that if the runtime "panics", the block is considered invalid. However, in real life, we need to properly return errors. In the specs, `assert` can be easily turned into errors. However, there're several cases where addition/subtraction can overflow (such as deposit counting), and array access can be out of bound (such as merkle proof validation) for invalid states/blocks. It would be great to add additional `assert` in the spec to clearly document them.

**Comment by JustinDrake** [comment]
I wouldn't be opposed to *all* unhandled exceptions being thrown by an explicit `assert` :) Fuzz testing can help detect lingering implicit exceptions.

**Comment by guidovranken** [comment]
I'll list IndexError exceptions found by my fuzzer here:

```process_proposer_slashing```:

```python
proposer = state.validator_registry[proposer_slashing.proposer_index]
```

```process_voluntary_exit```:

```python
validator = state.validator_registry[exit.validator_index]
```

```process_attestation```:

```
  File "/home/jhg/eth-2019/x/eth2.0-fuzzing/files/fuzzers/block/pythonlib/eth2spec/phase0/spec.py", line 1211, in process_attestation
    parent_crosslink = state.current_crosslinks[data.crosslink.shard]
  File "/home/jhg/eth-2019/x/eth2.0-fuzzing/files/fuzzers/block/pythonlib/eth2spec/utils/ssz/ssz_typing.py", line 269, in __getitem__
    return self.items[key]
IndexError: cannot fit 'int' into an index-sized integer
```

**Comment by djrtwo** [comment]
Closing. These additional asserts won't make it into the near-frozen spec.

pyspec/SSZ-typing do throw for under and overflows so at least this isn't blindly happening in the spec anymore
