### ISSUE TITLE
process_transfer balance checks

### ISSUE THREAD

**Issue by prestonvanloon** [ethereum/eth2.0-specs#1095]
Looking at `process_transfer`, I am wondering why do we check that balances are above zero? This would always be the case unless MIN_DEPOSIT_AMOUNT is zero. I'm not sure it's necessary to add this operation, but maybe I am missing something. 

```python
    # Verify balances are not dust
    assert not (0 < state.balances[transfer.sender] < MIN_DEPOSIT_AMOUNT)
    assert not (0 < state.balances[transfer.recipient] < MIN_DEPOSIT_AMOUNT)
```

**Comment by JustinDrake** [comment]
> why do we check that balances are above zero?

We don't—zero balances are allowed (notice the `not` after the `assert`). The assert is equivalent to

```python
assert state.balances[transfer.sender] == 0 or state.balances[transfer.sender] >= MIN_DEPOSIT_AMOUNT
```

**Comment by djrtwo** [comment]
This is to prevent an attack in which it is very cheap to bloat the state by leaving validator slots around with 1 GWEI (or something similarly small)

**Comment by prestonvanloon** [comment]
Sounds good. I think the `assert not` threw me off.
