### ISSUE TITLE
ancestor_hashes - description in comment

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#110]
The `BeaconBlock.ancestor_hashes` field has the following comment:

> i'th item is the most recent ancestor that is a multiple of 2**i for i = 0, ..., 31

Consider a block, `A`, that is at slot `2**31 + 1` for which we're are trying to compute `ancestor_hashes`. It's immediate ancestor, block `B`, is at slot `2**31`, so therefore it should occupy `ancestor_hashes[31]` because `2**31 % 2**31 = 0`. Block `B` should also occupy `ancestor_hashes[30]` because `2**31 % 2**30 = 0`. This continues all the way down until  `2**31 % 2**0 = 0`. Ultimately, `ancestor_hashes` will be completely filled with the hash of `B`.

I suspect this should not be the case?

I went back in git history and saw it has been changed by the venerable @rawfalafel in #81. Maybe he could shed some light?

**Comment by djrtwo** [comment]
The functionality is correct, but the comment might be misleading.

Think about what happens at the next block -- the 0th position changes.
what happens two blocks from now -- the 0th and 1st position update.
four blocks -- the 0, 1, and 2nd position update.

and so fourth.

The ancestor hash at 30th position stays stable until 2**30 blocks from now. Thus it serves as a point in history that you can easily walk back to. You can easily jump back 2**30 blocks and then block back two blocks. This mapping bounds the number of steps you need to take to walk back in the chain by log(n)

Open to a more descriptive comment/explanation.

**Comment by rawfalafel** [comment]
> I suspect this should not be the case?

From my understanding, its intentional. `ancestor_hashes` for block `2**31` (assuming the parent block is `2**31-1`) will contain many more hashes to jump back to.

**Comment by paulhauner** [comment]
Thanks for the replies :)

I'm still not sure I understand this, though. Are there any implementations you could point me towards, please?

**Comment by djrtwo** [comment]
Not sure if @rawfalafel has one already. Will be implementing in py-evm soon

**Comment by rawfalafel** [comment]
There's an implementation of `update_ancestor_hashes` in prysm [here](https://github.com/prysmaticlabs/prysm/blob/16b04699d01bd28871f5c57bfa45312dfb9bb738/beacon-chain/types/block.go#L239), but no code that actually uses the field. I'd be curious to see that as well.

**Comment by djrtwo** [comment]
`block.ancestor_hashes` is being removed in favor a double batch merkle accumulator inside state via #269
