### ISSUE TITLE
Expose xxHash-based state transition function for fuzzing

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1106]
As suggested by @guidovranken we can replace SHA256 by [xxHash](https://github.com/Cyan4973/xxHash) for fuzz testing. xxHash is a widely implemented non-cryptographic function which is several times faster than SHA256 and would accelerate fuzz testing.

The suggestion is for implementers to expose (e.g. with a flag, or with different executables) two versions of their clients, one with SHA256 and one with xxHash.

**Comment by dankrad** [comment]
Does it make a huge difference when a hash cache is present? (just playing the advocatus diaboli here, I don't know what percentage of time is spent on hashing but I would only want this if it's more than 50%)

**Comment by CarlBeek** [comment]
Out of interest, I ran some benchmarks with XXHash32 and 64 (repeated to the correct length) on the spec (in #1061). As discussed in #1110, the limiting factor in the spec tests is list comprehension. The results on my computer (which vary by a 4 or so seconds every time) are as follows:

| **Hash Algorithm**   | **Phase 0 [s]** | **Phase 1 [s]** |
|----------------------|-------------|-------------|
| Sha256 without Cache    | 81.88       | 108.71      |
| Sha256 with Cache | 62.90       | 103.08      |
| xxhash32 with Cache  | 64.38       | 105.92      |
| xxhash64 with Cache  | 61.31       | 99.25       |

If we are fuzzing in Go though, these results may be radically different.

**Comment by CarlBeek** [comment]
I just reallised that the cache I was using was a dictionary which in turn is based on hashing :/ No wonder the cache didn't really help.

**Comment by dankrad** [comment]
but dictionary hashes are simple hash functions, not cryptographic ones
like sha256

**Comment by CarlBeek** [comment]
>but dictionary hashes are simple hash functions, not cryptographic ones
like sha256

Yeah, but xxHash is also non cryptographic. That said, the Python3 hash function has a very strange (actually quite interesting) implementation and is faster for ints etc.

In other news, I added a xxHash64-sans-cache column for those who are interested.

**Comment by djrtwo** [comment]
This is just with the hash cache right? (rather than the committee cache)

**Comment by CarlBeek** [comment]
> This is just with the hash cache right? (rather than the committee cache)

Yes, indeed.

**Comment by guidovranken** [comment]
Now that fuzzing is working (at least for zrnt), I edited [zrnt](https://github.com/protolambda/zrnt) to use xxhash ([this](https://github.com/cespare/xxhash) implementation) instead of SHA256 and the fuzzing speed more than tripled. Caching might actually be a good idea too because not each fuzzer mutation results in an entirely new set of hashes to be computed across the board. Memory is not really a problem so a royally large cache would be fine (assuming that does improve speed, and the lookup times are reasonable).
Pinging @protolambda to gauge his interest in accepting a patch for this? I'll write one.

**Comment by JustinDrake** [comment]
> the fuzzing speed more than tripled

🎉

**Comment by protolambda** [comment]
@guidovranken Sounds good. ZSSZ, the ssz lib for zrnt, is already close to supporting any hash-function. It's just the zero-hashes (and higher-order hashes of combinations of the previous order) that are pre-computed with sha256 for efficiency. I'll make those overrideable, and then make the hash-function in zrnt replaceable, and then you can plug any hash you like :+1:

**Comment by protolambda** [comment]
See release `v0.6.4-3`, the hash function in ZRNT can be replaced now. How-to: https://github.com/protolambda/zrnt#replacing-the-hash-function

**Comment by JustinDrake** [comment]
@zedt3ster Is xxHash something you want to push forward for fuzzing? Feel free to close this issue if not.

**Comment by zedt3ster** [comment]
Thanks @JustinDrake. We're currently focusing on integrating more implementations and improving coverage with custom mutators. We can close this issue for now, and re-open when ready to swap to xxHash across all clients.
