### ISSUE TITLE
SSZ vector wrap-around

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1124]
To simplify the presentation we could implement index wrap-around for vectors. That is, `vector[i]` would be equivalent to `vector[i % len(vector)]`. This would shorten about 20 lines, and potentially improve readability. Examples below:

* `state.latest_block_roots[slot % SLOTS_PER_HISTORICAL_ROOT]` => `state.latest_block_roots[slot]`
* `state.latest_randao_mixes[epoch % LATEST_RANDAO_MIXES_LENGTH]` => `state.latest_randao_mixes[epoch]`
* `state.latest_active_index_roots[epoch % LATEST_ACTIVE_INDEX_ROOTS_LENGTH]`
* `state.latest_slashed_balances[current_epoch % LATEST_SLASHED_EXIT_LENGTH]`
* `state.latest_state_roots[state.slot % SLOTS_PER_HISTORICAL_ROOT]`

**Comment by vbuterin** [comment]
I'd say that sacrifices readability too much. It pushes the spec in the direction of "you have to read these other five sections first to understand any of this".

**Comment by dankrad** [comment]
I agree with @vbuterin here, and also, the advantage of having explicit wraparound (as in: having to write out the modulo operation) is that tests can catch out of bounds errors. Wraparound turns this into a silent failure, with much worse debuggability.

**Comment by JustinDrake** [comment]
The goal was to increase readability, which seems to not have been achieved 😂
