### ISSUE TITLE
Use libp2p ed25519, not RSA

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1143]
I'd suggest not going with RSA, and instead go with ed25519. One reason is efficiency. The other reason is that ed25519 pubkeys are much smaller and can be inlined in the peer ID. Using RSA creates a level of indirection where the peer ID contains the hash of the pubkey. This is generally awkward work with, and especially costly for example in the context of a DHT where an additional lookup must be performed to fetch the pubkey.

cc @zscole who apparently did some libp2p benchmarking using RSA

**Comment by zscole** [comment]
Within our tests, we actually used [ed25519 for peer identity](https://github.com/whiteblock/p2p-tests/blob/master/client/main.go#L108). Although we're only just beginning to touch the surface of our research and testing efforts, based on our initial findings, it appears to have resulted in a significant amount of overhead, but we weren't specifically evaluating this implementation, so I don't have enough data to provide anything conclusive at this time. Either way, ed25519 should technically be faster and more secure than RSA. 

This is something we can easily target and benchmark in future test series though. I'm currently working on designing the next test phase, so I'll keep this in mind and design a test case around it if the results would be of value. If anyone has any suggestions or ideas as to the specifics of what we should focus on, please feel free to share. You can also open a PR in our [p2p test repo](https://github.com/whiteblock/p2p-tests).

**Comment by JustinDrake** [comment]
> we actually used ed25519 for peer identity

Oh great :)

> it appears to have resulted in a significant amount of overhead

Looking forward to reading your final report!
