### ISSUE TITLE
Invalid sanity test block state root

### ISSUE THREAD

**Issue by sorpaas** [ethereum/eth2.0-specs#1146]
For `blocks` sanity test. Block state root is always zero, which makes it fail the final state root check required in the spec.

**Comment by JustinDrake** [comment]
I'm sorry, I don't understand the issue. Would you mind expanding?

**Comment by sorpaas** [comment]
@JustinDrake blocks provided in the sanity test have its block state root field set to ZERO_HASH, but that’s clearly a wrong value.

**Comment by djrtwo** [comment]
looking into this

**Comment by protolambda** [comment]
Possible solution for tests:
- transition up to some testing scenario (optional)
- sign block
- output pre
- transition block, verify-state-root is off
- update block state root
- sign block again
- output block
- output post

**Comment by djrtwo** [comment]
addressed in #1177.
to be released in `v0.7.1`
