### ISSUE TITLE
Invalid transfer sanity test

### ISSUE THREAD

**Issue by sorpaas** [ethereum/eth2.0-specs#1147]
For all our config the `MAX_TRANSFERS` value is 0. However, we have tests that contain transfer, and it's expected to not error!

**Comment by JustinDrake** [comment]
It may be clearer for testability to move the contents of `process_transfer` to the phase 1 doc. I'd even argue to remove the `transfers` field from `BeaconBlockBody` (see item 8 in #1054) but @djrtwo disagrees :)

**Comment by djrtwo** [comment]
In `v0.7.0`, the block tests for transfer are removed but the tests for `process_transfer` remain as these are isolated from the block operation size checks.

Will keep it in this state until we decide how we want to test forks. Then we'll have a fork test that tests changing config to activate transfers
