### ISSUE TITLE
[Feature] Some constants as constructor parameters

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/eth2.0-specs#1148]
It would be handy for testing to initialize some of the constants via constructor. 
Now I need to modify constants and recompile contract for my testing environment. 
If add constructor params one could use the same binary. 
I would like to see the following constants in the constructor: 
```
CHAIN_START_FULL_DEPOSIT_THRESHOLD: constant(uint256) = 16384  # 2**14
SECONDS_PER_DAY: constant(uint256) = 86400
```
(the second constant might need to be renamed imho in this case)

**Comment by JustinDrake** [comment]
Closing because the two constants `CHAIN_START_FULL_DEPOSIT_THRESHOLD` and `SECONDS_PER_DAY` are no longer part of the deposit contract. (See #1152.) Feel free to reopen.
