### ISSUE TITLE
Handle endianess in client implementation

### ISSUE THREAD

**Issue by dangerousfood** [ethereum/eth2.0-specs#1149]
This design seems like it would have a high gas cost. An alternative might be to expect the client implementers to provide little endian values for the contract.

https://github.com/ethereum/deposit_contract/blob/a251fa8bf27f2b0ac74182db98bc311046b08d54/deposit_contract/contracts/validator_registration.v.py#L28-L44

**Comment by JustinDrake** [comment]
Calling `to_little_endian_64` on `deposit_amount` is not optional because we are calculating the `hash_tree_root` of a `DepositData` object. (Separate from this issue we may change to big-endian—see #1046.)
