### ISSUE TITLE
Distinguish true constants from network-configurable parameters

### ISSUE THREAD

**Issue by wemeetagain** [ethereum/eth2.0-specs#1187]
Currently, the constants listed in the beacon chain spec are a combination of constants that will never change, eg: `ZERO_HASH`, and "constants" that may change for testing or other purposes, eg: `SHARD_COUNT`.

It could be helpful to separate constants from configuration to help implementers determine which variables can be set at compile time vs runtime, how much flexibility to give in editing certain variables, etc.

**Comment by djrtwo** [comment]
I'm on this

**Comment by djrtwo** [comment]
addressed in #1191
