### ISSUE TITLE
Missing BLS verification spec tests

### ISSUE THREAD

**Issue by prestonvanloon** [ethereum/eth2.0-specs#1195]
This issue is tracking the note at the bottom of the BLS test format [readme](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/test_formats/bls/README.md).

> Note: Signature-verification and aggregate-verify test cases are not yet supported.

Are there any plans to add this soon?

Relevant issues:
- #1074

**Comment by protolambda** [comment]
We do already support signature verification and aggregate-verify in the state-transition tests where applicable (afaik). The idea here is that implementers can cover the "invalid signature" path in their code, when following the same BLS implementation as the pyspec.
I have not prioritized these tests as much. Maybe someone would like to pick this up? (Writing test generators is easy, try it!)

**Comment by JustinDrake** [comment]
Closing this issue :) The BLS document no longer exists (we're now differing to the BLS standardisation process). Feel free to reopen if you still feel we are missing spec tests.
