### ISSUE TITLE
Test epoch processing rewards/penalties

### ISSUE THREAD

**Issue by protolambda** [ethereum/eth2.0-specs#1231]
This is a select set of tests isolated from the other tests that are included in the spec-freeze itself. Tests quality and feature-completeness was prioritized over rushing these in. Now after spec-freeze, the goal is to provide these as an addition (perfectly backwards compatible / not touching the spec itself), to complete the coverage.

Part of this functionality is already covered by the block tests and others. But to complete it, we need to dig into simulation of attestation (as done for earlier epoch processing justification/finalization tests), and crosslinks. Then see if we can cleanly model the balance changes for assertions.

TODO in `process_rewards_and_penalties`:
- [ ] matching penalties/rewards
  - [ ] matching head: penalty, reward, none, both
  - [ ] matching target: penalty, reward, none, both
  - [ ] matching source: penalty, reward, none, both
- [ ] proposer inclusion delay
- [ ] inactivity penalty
- [ ] crosslink committee:
  - [ ] penalty if not in committee, reward if in committee
  - [ ] no crosslink, empty participation, everyone penalty

**Comment by JustinDrake** [comment]
Are these tests still TODO?

**Comment by protolambda** [comment]
At the time it was considered too convoluted to setup tests for rewards/penalties, since the spec itself doesn't really isolate the computation from that of the chain inputs. But crosslinks have been removed, so it should be better now. I can pick it up now, but also want the phase1 pr merged first (and remaining complexities with factoring in phase 1 functionality). Maybe close this in favor of a phase1 ready testing issue?

**Comment by JustinDrake** [comment]
> Maybe close this in favor of a phase1 ready testing issue?

Sure, go ahead if you think that's the way forward :) I'm mainly doing a pass on old/stale issues.

**Comment by protolambda** [comment]
Closing in favor of #1526
