### ISSUE TITLE
Can you tell me the progress of VDF，Now I'm interested to know how do you generate two large prime Numbers

### ISSUE THREAD

**Issue by yyyyyp** [ethereum/eth2.0-specs#1254]

**Comment by JustinDrake** [comment]
> how do you generate two large prime Numbers

The goal is to have an (n-1)-secure RSA ceremony with ~1,000 participants. The MPC is being designed by Ligero, specifically Carmit Hazay, abhi shelat, and Muthu Venkitasubramaniam. They have an upcoming paper titled "Scalable RSA Modulus Generation with Dishonest Majority" where they bring down the communication complexity down to less than 10 rounds, with less than 100MB of total bandwidth per participant. I'm hoping the RSA ceremony will be completed in a handful of minutes.
