### ISSUE TITLE
Check attestation bit list length against committee size

### ISSUE THREAD

**Issue by wemeetagain** [ethereum/eth2.0-specs#1262]
In `get_attesting_indices`, we used to `verify_bitfield` to ensure the attestation bitfield length was the size the committee.
Now we've moved the verification of _a_ length to the ssz deserialization, but removed the committee size check.

**Comment by JustinDrake** [comment]
Good catch :) We are implicitly checking `len(committee) <= len(bits)` and we also want `len(committee) >= len(bits)`.

**Comment by protolambda** [comment]
Fixed in #1317
