### ISSUE TITLE
Clarify in docs on what is frozen

### ISSUE THREAD

**Issue by sorpaas** [ethereum/eth2.0-specs#1272]
With 0.8, we finally have a stable ground to work on and optimize our beacon chain implementations. It will be great if we can clarify what has actually been frozen, so that we can have more peace of mind when creating structures not defined in spec.

What is frozen:

- Beacon state transition function (`specs/core/0_beacon-chain.md`)
- Beacon fork choice rule (`specs/core/0_fork-choice.md`)
- Ssz merkleization (`specs/simple-serialize.md#merkleization`)

What is not frozen:

- BLS
- Ssz serialization (`specs/simple-serialize.md#serialization`)
- Networking
- Deposit contract

**Comment by JustinDrake** [comment]
The freeze relates to consensus:

1) **Deposit contract**: The [byte code](https://github.com/ethereum/eth2.0-specs/blob/dev/deposit_contract/contracts/validator_registration.json) will not change. 
2) **State transition function**: `hash_tree_root(state_transition (state, block, true))` will not change for any input `state` and `block`.
3) **Fork choice rule**: `get_head(store)`, `on_tick(store, time)`, `on_block(store, block)`, and `on_attestation(store, attestation)` will not change for any input `store`, `time`, `block`, and `attestation`.

For all the above, exceptions are made to critical bugs that prevent the formation of long-lived cross-client testnets. In addition to the above "substantive freeze" we abstain from disruptive cosmetic changes (e.g. significant renamings and refactors in `specs/core/0_beacon-chain.md`).

Substantive post-freeze changes will at minimum include:

* Fixes to non-critical bugs found during the freeze
* Change to BLS logic to comply with blockchain standards

**Comment by JustinDrake** [comment]
I think implementers are now well-aware of what is frozen—it's the phase 0 consensus. See also the bounties which go through the various frozen parts (state transition, fork choice, and deposit contract) https://github.com/ethereum/eth2.0-specs/issues/1345
