### ISSUE TITLE
Improved transfer replay protection, and removal of transfers in phase 0

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1274]
Replace the current slot-based transfer replay protection mechanism by adding `state.transfer_roots: Vector[Hash, MAX_TRANSFERS * SLOTS_IN_REPLAY_PROTECTION_PERIOD]`. We can also completely move transfers from phase 0 to phase 1.

**Comment by vbuterin** [comment]
So the only substantive thing here is removing `transfers` from the block structure, right?

**Comment by vbuterin** [comment]
It's also worth noting that this mechanism could be reused in phase 2 to prevent replay of withdrawals from execution environments into other execution environments.

**Comment by djrtwo** [comment]
Do you still have to specify a slot or epoch?

I'm not certain what problem this is actually solving. If a validator has a Transfer for a `slot` and it is not included in a chain and then broadcasts a repeat for `slot + N`, then both of these can still be replayed on a reorged chain even though the initial transfer was not included in the pre-reorged chain.

**Comment by djrtwo** [comment]
Or are you suggesting removing `slot` from `Transfer`? If this is the case, then I can just replay a transfer _after_ the replay protection period.

**Comment by JustinDrake** [comment]
> Do you still have to specify a slot or epoch?

Yes.

**Comment by JustinDrake** [comment]
> Or are you suggesting removing `slot` from `Transfer`?

As discussed on our call, `slot` stays there (or can be replaced with `epoch`).

**Comment by djrtwo** [comment]
So is the only thing this solving the ability to expand it to `epoch` instead of `slot`?

**Comment by JustinDrake** [comment]
> If a validator has a Transfer for a `slot` and it is not included in a chain and then broadcasts a repeat for `slot + N`

The point is that the re-broadcast would *not* have to modify `slot + N`, hence removing the risk of having two transfers accidentally go through.

**Comment by JustinDrake** [comment]
> So is the only thing this solving the ability to expand it to epoch instead of slot?

Nope. It expands slot to `SLOTS_IN_REPLAY_PROTECTION_PERIOD`. It's possible that `SLOTS_IN_REPLAY_PROTECTION_PERIOD >> SLOTS_PER_EPOCH`.

**Comment by protolambda** [comment]
> We can also completely move transfers from phase 0 to phase 1.

Then we move it to a new phase-1 beacon-chain updates document? Or will it live with the updated beacon-block body definition in the custody game doc?

**Comment by JustinDrake** [comment]
> Then we move it to a new phase-1 beacon-chain updates document?

A new phase 1 beacon chain update document makes sense. (Mixing transfers with the custody game is a bit awkward.) My guess is longer term the miscellaneous update documents will be collapsed into a unified beacon chain state transition document.

**Comment by djrtwo** [comment]
I'm thinking about organizing specs into new sub-directories (will break links... :/). These directories would be grouped by fork and ordered. This would open up easily putting transfer into it's own fork defined as a beacon chain file in `forks/`

That said, don't want to do this surgery until we discuss more

**Comment by djrtwo** [comment]
I'm still pro doing a transfer-enabling fork for practice independent of phase 1 fork

**Comment by protolambda** [comment]
Another replay case (although much rarer) is when validators change index after an Eth 1 re-org. Credits to @sorpaas for surfacing it and bringing it to our attention on discord.
A transfer could then be replayed (or re-used in a clean but unexpected state really...) to send the funds to the new validator now taking the receiver index.

This may be solved by modifying the other replay protection measures. Or we replace the receiver index with the receiver pubkey. And, as mentioned by Justin. When we have eth2 -> eth2 deposits, indices can get much more unstable, and transfers will need this replay protection. Something to keep in mind when revisiting the transfer design.

**Comment by JustinDrake** [comment]
@protolambda My favourite conservative fix is to replace indices in transfers by pubkeys.

**Comment by djrtwo** [comment]
transfers removed!
