### ISSUE TITLE
Edge case: crosslinks de-finalizing

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#1277]
Here's an edge case that we haven't thought about:

* In block B, 2/3 + epsilon of validators in the crosslink committee for some shard crosslink H
* H is now a dependency of B
* In the next block B', one of those validators gets slashed, and so the fraction voting for the crosslink drops to below 2/3
* H does not appear to be a dependency of B', and when the epoch ends, B never gets included

This creates a strange scenario where, if H is detected as being invalid or unavailable, B is not an acceptable block and should not be accepted or built on, but B', a child of B, should be. This is technically not fatal, but it is still very weird....

Edit: it's a little more subtle because _effective_ balances don't change intra-epoch, only at the end of the epoch, after crosslink processing takes place. But the above logic still applies with respect to slashings that are "destined" to process at the _end_ of the next epoch: consider the case where H gets included by 2/3 - epsilon validators, and then a slashing from a non-signer is included, pushing the fraction to 2/3 + epsilon - not for the current epoch, during which the slashing would not count, but for the next epoch. Such a chain should not be built upon because it's theoretically "not viable"; unless someone is slashed (unlikely) there's no way it can legally continue past the end of the next epoch, at which point it will have inducted a bad crosslink. But then if someone _does_ get slashed, the chain becomes viable again.

**Comment by vbuterin** [comment]
Honestly all of this is making in in favor of just throwing out all the machinery involving cross-epoch transitions (so a crosslink initiated during epoch N can only be included at the end of epoch N); this would also be a substantial simplification of the spec. That would be a one-line change; negative impacts to crosslinking latency can be remedied in a later patch (phase 1?) that would make the last 8 slots of an epoch do nothing crosslink-wise.

**Comment by djrtwo** [comment]
I see, this is more of the issues where work done in the next epoch might never be able to be included due to what might happen with the prior epoch crosslinks during the next epoch. By "not viable" this is what you mean, right? That a committee for a given epoch does not have the chance of successfully creating a crosslink?

Agreed that simplifying here is our current best solution. Are you proposing that we only allow crosslinks to be formed from attestation in the current epoch?

> the last 8 slots of an epoch do nothing crosslink-wise.

If this is the case, we would never be able to crosslink _all_ shards in a single epoch. Not a terrible tradeoff for simplicity.

**Comment by vbuterin** [comment]
By "not viable" I mean "any chain that is a sufficiently deep descendant of this chain will be invalid because the chain has a crosslink-in-progress to bad data". The idea being that this happens because you have a crosslink to bad data with 2/3-epsilon votes, which is destined to flip over to 2/3+epsilon in the _next_epoch because one of the nonvoters got slashed.

> Are you proposing that we only allow crosslinks to be formed from attestation in the current epoch?

Yep!

> If this is the case, we would never be able to crosslink all shards in a single epoch. Not a terrible tradeoff for simplicity.

Just increase the max shard count per slot!

**Comment by djrtwo** [comment]
I missed "if H is detected as being invalid or unavailable" when I read it the first time... got it!

**Comment by vbuterin** [comment]
I just realized that there is another edge case here. Suppose that there are two crosslinks for a particular shard that both get 2/3 within the same epoch (yes, a few people get slashed here). At the beginning, crosslink A is winning with 68%, but then crosslink B pulls ahead with 70%.

I think if we want to fix this, the simplest/most robust way to do it might be to make a data structure `List[Tuple[Crosslink, uint64]]` where for each crosslink we store the _percentage_ of validators that voted for it. We then automatically add any crosslink if it hits 2/3. We run a loop at the end of every epoch that cleans out any crosslinks whose parents no longer match the latest crosslinks in the state or any crosslinks that are more than 2 epochs old.

**Comment by JustinDrake** [comment]
A few questions/comments:

1) Are you suggesting two separate fixes for two separate edge cases?
2) I'm inclined to say the first edge case is not a high-priority fix. As you write, it's a bit weird but as I understand nothing is broken.
3) "throwing out all the machinery involving cross-epoch transitions" => The main think I want to avoid is not all shards being able to crosslink once per epoch. I'm inclined to either keep cross-epoch machinery, or say that a crosslink initiated during epoch N can only be included at the end of epoch N+1 (i.e. add one epoch of latency for all shards).
4) Could we fix the first edge case by removing `get_unslashed_attesting_indices` (i.e. count both unslashed and slashed indices)?
5) "At the beginning, crosslink A is winning with 68%, but then crosslink B pulls ahead with 70%." => To confirm, do you mean that at the end of epoch `e` A is winning with 68%, and at the end of epoch `e+1` B is winning with 70%? And if so, why is this problem?

**Comment by djrtwo** [comment]
Crosslinks don't exist in phase 0 and the structure has majjorly been overhauled in Phase 1.
Closing this issue
