### ISSUE TITLE
Cosmetic presentation of hash types and values.

### ISSUE THREAD

**Issue by protolambda** [ethereum/eth2.0-specs#1282]
It was recently brought to my attestation (by @nisdas) that although the `Hash` type seems clear, the default instantiation `Hash()` (32 zero bytes) is too close to `hash()` (hash of empty byte array).
We should consider renaming it to `Root` or sticking to `Bytes32`. Or, at the very least, make comparisons against `Bytes32()` or `ZERO_HASH` to avoid confusion.

cc @JustinDrake You had an initial preference for `Hash` over `Root`/other as type. Are there any counter arguments against changing `Hash`? What option do you like best?

**Comment by protolambda** [comment]
Tracked it down to being introduced in #1237 
Also, `someHashValue.is_zero()` may be a good solution.

**Comment by JustinDrake** [comment]
> Are there any counter arguments against changing `Hash`?

Renaming all `Hash` to `Root` does not work semantically everywhere (e.g. `withdrawal_credentials`, `proof`, `randao_mixes`, `hash`, `block_hash`). We could name the roots to `Root`s, and leave the non-roots as `bytes32`.

> the default instantiation `Hash()` (32 zero bytes) is too close to `hash()` (hash of empty byte array)

Probably the easiest fix for that is to reintroduce the `ZERO_HASH` constant.

> What option do you like best?

I'd say either status quo or reintroducing the `ZERO_HASH` constant is best.

**Comment by hwwhww** [comment]
> Also, `some_hash_value.is_zero()` may be a good solution.

FYI for the `assert ssz_value == Hash()` cosmetic, there is [`is_empty(obj)`](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md#is_empty) helper function which is used in phase 1 spec: https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/1_custody-game.md#replace_empty_or_append

**Comment by JustinDrake** [comment]
Right, `is_zero` is fine (the helper function `is_empty` would be better renamed `is_zero`).

**Comment by djrtwo** [comment]
Could define `ZERO_HASH` in constants as `Bytes32()`

**Comment by djrtwo** [comment]
closed via #1297
