### ISSUE TITLE
Clear store upon new finalized check point

### ISSUE THREAD

**Issue by terencechain** [ethereum/eth2.0-specs#1290]
Do you guys see a value in [spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_fork-choice.md#store) to clear dicts `blocks`, `block_states`, and `checkpoint_states` when there's a new finalized check point?

Not sure if it is an implementation detail that got left out, I do see value of clearing those caches/dbs when we write out fork choice yaml tests

**Comment by JustinDrake** [comment]
> clearing those caches/dbs when we write out fork choice yaml tests

Labelling as "CI/tests". I'm guessing @protolambda may be best informed :)

**Comment by protolambda** [comment]
Well, there are certain extremely reare edge-cases where you can argue about going farther back than that. (wrong eth1 head being tracked, and future super-rare phase 1+ things). So I am hesitant in declaring a hard fork-choice requirement that ignores these cases. I think @djrtwo may have a stronger opinion on whether or not to just trust the finalized checkpoint and never looking back. Maybe it can be translated into code otherwise, and then we can have the pruning on finalization.

**Comment by JustinDrake** [comment]
@terencechain Can you clarify what the question is about? Are you suggesting that we clear the store so that tests run faster (i.e. a cosmetic issue), or is this a more substantive issue such as the one Proto is talking about?

**Comment by terencechain** [comment]
The one is proto is talking about. Some recommendations on when we think it's "safe" to clear out storages. Right now we clear everything upon a new finalized epoch

**Comment by JustinDrake** [comment]
There's a bit of guidance in the fork choice document:

> The large `ETH1_FOLLOW_DISTANCE` specified in the honest validator document should ensure that `state.latest_eth1_data` of the canonical Ethereum 2.0 chain remains consistent with the canonical Ethereum 1.0 chain. If not, emergency manual intervention will be required.

My suggestion would be to clear data (blocks, attestations, etc.) that is a certain age (e.g. 3 days) relative to the latest finalised checkpoint. We don't expect the latest finalised checkpoint to get reverted but keeping a bit of data around for emergency manual intervention may be worthwhile.

**Comment by djrtwo** [comment]
The expectation of clients to start is to serve beacon blocks within the weak subjectivity period (~8M in the normal case) to allow for offline clients to sync to the head. Actively clearing out the store in your active fork choice alg after finality is certainly advisable, but pruning your blocks/state should be done in a much more conservative manner

**Comment by terencechain** [comment]
great, thanks for the guidance on this one. I think we can close it for now : )
