### ISSUE TITLE
ValidatorRecord doesn't define proof_of_possession

### ISSUE THREAD

**Issue by zincoshine** [ethereum/eth2.0-specs#130]
The PoW ValidatorRegistration contract description on the spec states that BLS proof of possession will be the final argument to the register function of the contract, however the ValidatorRecord structure doesn't define this item?

> A BLS proof_of_possession of types bytes is given as a final argument.

> A ValidatorRecord has the following fields:

```
{
    # BLS public key
    'pubkey': 'uint256',
    # Withdrawal shard number
    'withdrawal_shard': 'uint16',
    # Withdrawal address
    'withdrawal_address': 'address',
    # RANDAO commitment
    'randao_commitment': 'hash32',
    # Slot the RANDAO commitment was last changed
    'randao_last_change': 'uint64',
    # Balance in Gwei
    'balance': 'uint64',
    # Status code
    'status': 'uint8',
    # Slot when validator exited (or 0)
    'exit_slot': 'uint64'
}
```

**Comment by terenc3t** [comment]
ValidatorRecord doesn't need to store proof_of_posession, it's only checked once when we induct  validator into validator set

**Comment by djrtwo** [comment]
Yes, it is just verified once in `add_validator` and then discarded from the state.
