### ISSUE TITLE
Options for crosslink data

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#1304]
### Problem statement

Per epoch we have 128 shard block headers and 128 block bodies, where each block header is constant size (currently ~400 bytes, can be shrunk to ~224 with some effort), we need to verify availability of these. Our main tools for _scalable_ data availability verification are (i) proof of custody and (ii) data availability. Both depend on a "flat" (ie. serialized) data structure as input; this conflicts with the aesthetic goal of using `hash_tree_root` where possible.

### Status quo

Define `zpad(x, length) = x + b'\x00' * max(0, length - x)`. For every block, define `flatten(block) = zpad(serialize(block.header), 65536) + zpad(block.body, 65536)`. The crosslink data structure is just `b''.join([flatten(block) for block in blocks])`.

Pros: simple
Cons: a lot of "wasted space" in the header and body, leading to ~7-8x average inefficiency in data availability proof generation and erasure coded chunk storage.

### Pull #1278 

Define `flatten(block) = serialize(block.header) + block.body`. Let `blobs = [flatten(block) for block in blocks]`. The crosslink data structure is `b''.join([int_to_bytes8(8 + 8 * len(blobs) sum([len(d) for d in blobs[:i]])) for i in range(1, len(blobs)+1)] + blobs)`. That is, we start with a list of 8-byte entries denoting the positions of each tightly packed blob, followed by all the blobs.

Pros: no wasted space. **Another pro of the "no wasted space, variable position" approaches is that they make it easier to upgrade to increase block size in the future.**
Cons: much more complex, especially to access specific headers or use fraud proofs

### Offsets outside crosslink data

The crosslink data structure is just `b''.join([serialize(block.header) + block.body for block in blocks])`. The crosslink _object_ also contains the list of offsets (which can be compressed to 1 byte per block by requiring each block to be a multiple of 256).

Pros: simpler than the above, though not yet extremely simple
Cons: requires extra data field that must be put into a crosslink object; size of a crosslink object will increase by ~50% in the normal case, a few times in the worst case. Also, the crosslink data root stored in the state would need to be replaced by a `hash(Container(data, offsets))` structure.

### Headers outside crosslink

We can shrink the header to ~224 bytes, by (i) merging proposer and attester signatures, (ii) taking care to move things into the shard state, (iii) capping per-block committee size to 128. We can then just require everyone to separately download the headers to check availability. We also add to the header a field `total_bytes`, which measures the _total_ historical length of all headers in that shard; this can be used to calculate indexes into crosslink data for fraud proof purposes.

Pros: simpler than the above
Cons: requires extra data that must be verified to check availability, removes the clean "download the crosslink and you have everything" property, The size of this data is ~224 * 128 = 28k per epoch, so still less than the expected size of a data availability proof. Also, the crosslink data root stored in the state would need to be replaced by a `hash(Container(data, offsets))` structure.

### Headers inside crosslink but separate

The crosslink data structure is `b''.join([serialize(header) for header in headers]) + b''.join([serialize(body) for body in bodies])`

Pros: arguably simpler than header+body+header+body serialization; with the right data fiddling, header serialization can be made equivalent to SSZ tree hashing. Also ensures that everything is covered by the proof of custody and the data availability proofs.
Cons: not quite as simple as headers outside crosslink or offsets outside crosslink.

### Blocks ain't got no headers

A valid block is just a `Bytes` object, where we require the first 256 bytes to contain the "header" fields, so we can make the crosslink simply be the concatenation of these bodies. We can require offsets to be stored in the crosslink object.

Pros: simpler in some ways
Cons: no notion of headers adds complexity in some ways. Also, the crosslink data root stored in the state would need to be replaced by a `hash(Container(data, offsets))` structure.

## Two separate data structures

Another option (which can be used together with the above) is for the crosslink object to store multiple roots: (i) data root, (ii) most recent header, (iii) offsets list if needed. We then use fraud proofs to ensure that these roots are compatible, and use the crosslink data, which is formatted in a more "ugly" way for serialization reasons, for proof of custody and data availability but store the most recent header in the crosslink records in the state, and use the most recent header as an entry point to access that shard's state and history.

**Comment by djrtwo** [comment]
My current favorite combo is either (1278 or "headers inside crosslink but separate") + bringing in most recent header to crosslink. Even if we don't have fraud proofs, you could have a merkle proof that the header exists within the crosslink data root at the appropriate offset. What is storage requirement for a fraud proof?

This approach is super nice because we regain the ability to have ssz hash tree root proofs all the way down through the crosslink while still having the advantages of a flattened crosslink data. It is also nice because it is a minimally invasive change to the beacon chain (at either phase 0 or 1).

>  We can then just require everyone to separately download the headers to check availability.

what do you mean here -- no crypto-economic claim can be made on this data if not in the crosslink construct? Is this just a note that fully validating nodes should filter out crosslinks with unavailable associated header data?

> Headers inside crosslink but separate

This is kind of appealing especially if headers are of fixed size (say 256 bytes) and include the `total_bytes` field. Can use this to calculate the offsets of the subsequent bodies in the data. If I understand this correctly, currently leaning toward this approach.

**Comment by vbuterin** [comment]
> This approach is appealing especially if headers are of fixed size (say 256 bytes) and include the total_bytes field. Can use this to calculate the offsets of the subsequent bodies in the data

Yep! So the header doubles as the position list, reducing complexity.

> what do you mean here -- no crypto-economic claim can be made on this data if not in the crosslink construct? Is this just a note that fully validating nodes should filter out crosslinks with unavailable associated header data?

Basically yes.

**Comment by vbuterin** [comment]
> My current favorite combo is either (1278 or "headers inside crosslink but separate") 

I decided I like the latter (headers separate) over the former. The reason is that if the headers are all at the beginning, then headers have fixed generalized indices, and we can even access block data with fixed generalized indices by going through the data root in the header.

**Comment by djrtwo** [comment]
> we can even access block data with fixed generalized indices by going through the data root in the header.

:) In this case, don't need to necessarily add the explicit latest block/state root into the crosslink as an easy accessor, right?

**Comment by vbuterin** [comment]
Exactly!

**Comment by dankrad** [comment]
> Cons: much more complex, especially to access specific headers or use fraud proofs

I would like to understand why this adds so much complexity in your opinion? It seems a rather slight increase to me. It's just one offset essentially.
