### ISSUE TITLE
ETH2 fee market challenges

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#1309]
Our current roadmap for eth2 is one where few users hold ETH "directly" (mostly as validator slots), and most users interact with the system through "execution environments" (EEs), which sit on top of the base layer and provide functionality like state management, cross-shard transactions, privacy, etc. Moving ETH between EEs is expected to take a full crosslink cycle (~6 min), but actions within an EE can be very quick. A major reason why this is done is to simplify the base-layer protocol so that the consensus code that all validator nodes need to run can be much smaller.

But this presents a challenge: how do users pay fees? Currently, a user pays transaction fees directly from their ethereum account (which the protocol recognizes) to a miner as part of the transaction. However, in eth2 we run into a problem: _users will likely not have access to any base-level "ether"_, because all of their coins are in these execution environments.

There are three possible categories of solutions:

1. Block producers understand EE protocols (ie. they "speak" shadow chains, ZK rollup, plasma.....), so they can accept fees paid through these protocols directly.
2. Users also hold a small balance coins in a special EE that block producers understand, and pay fees through conditional transactions ("if a tx with hash H was included in this block, pay the producer 7124535 wei per gas that it consumed") out of that balance
3. Relayer markets, where an intermediary actor speaks the EE protocol and accepts fees within the EE protocol and pays fees using a special EE that block producers understand

[This list seems to me exhaustive; if it is not, I'd love to know!]

IMO (1) is nonviable as it removes much of the benefit of making this abstraction in the first place; the number of EE protocols would just keep increasing over time, raising the complexity of being a block producer, and increasing the incentive for validators to centralize so they can collect the most fees.

(2) is very promising, though care must be taken to avoid making it inefficient (eg. you do NOT need to have two actual transactions, one for the original tx and one for the fee). Here is a possible setup for how this could work:

* There exists a special EE, called the "fee market EE", where users hold ETH, and user can make ERC20-style authorizations ("I authorize EE #1727 to take coins from me"). All withdrawals and revocations of authorizations come with a 2-week waiting period.
* There exists a standard format of receipt that EEs are expected to issue, saying "user X wants to pay a fee of Y to address Z (often the proposer of the block)".
* Payment
    * Option A: these receipts get aggregated and turned into a single receipt within a block, and this can get Merkle-proven into the fee market EE and used to make the transfer.
    * Option B: future randomness can be used to probabilistically pay, so only ~1% of the time a receipt will be taken and used to charge 100x the normal fee
    * Option C: users can self-declare how much they need to pay within a given span of epochs; only if their declaration is incorrect can others challenge them by providing a collection of receipts that show they need to pay more, and by doing so steal the user's deposit

However, (2) has a key weakness: privacy. The special EE would not be privacy-preserving (unless of course we make it privacy-preserving, but that would be more complex and require standardizing on one scheme!), and so it would link together all of the transactions that users make.

Relayer markets involve a special class of actors that create a transaction containing a list of other users' transactions, collecting the fees from those transactions through EEs that they speak (which could be privacy-preserving) and paying the base-layer fees themselves. This is currently [being explored](https://ethresear.ch/t/burn-relay-registry-decentralized-transaction-abstraction-on-layer-2/5820) for eth1 use cases. The main concern that's been publicly discussed so far is centralization - whether or not being a relayer is a natural monopoly.

There is a natural class of actor that could serve as a relayer, which is a light client server that is already being compensated through channel payments to provide Merkle branches to light clients. The fee market EE could support basic payment channel functionality to allow a light client server market to be more easily universalized.

**Comment by dankrad** [comment]
I am still for (3), however, one more concern just popped up in my mind: Could it be an advantage to be both a relayer and producer? In that case, we would have centralization of both relayers and block producers, which is much worse...

**Comment by villanuevawill** [comment]
> I am still for (3), however, one more concern just popped up in my mind: Could it be an advantage to be both a relayer and producer? In that case, we would have centralization of both relayers and block producers, which is much worse...

This has been discussed in depth and historically - an overview can be found here - https://ethresear.ch/t/state-providers-relayers-bring-back-the-mempool/5647 which links to an older article by @benjaminion - https://ethresear.ch/t/exploring-the-proposer-collator-split/1632

The desirable properties as part of a relay market is that a user can package their own transaction by being their own relayer. @vbuterin suggested a system with a universal fee market where relayers can offer a fee for transactions and the block producer can collect that fee via a look-back mechanism. Additionally, each EE can have a merge function that gives instructions on merging different packages. This shows a lot of promise. However, one open question regarding this approach. Would it be too expensive to enforce a separate stated fee for each (wrapped ?) transaction by the relayer? If not, then how does the merge function work in practice if there are duplicated transactions? If there is a blanket fee for a package, the package would no longer be valid.

**Comment by vbuterin** [comment]
> If not, then how does the merge function work in practice if there are duplicated transactions? If there is a blanket fee for a package, the package would no longer be valid. If we can have it stated individually, then we can allow the merge function to also prioritize higher fee transactions from multiple packages and it makes it less likely that there is a dominating relayer that can censor.

This is definitely a really good point! It does seem like multiple relayers within one block would lead to collisions between transactions between those relayers, leading to the second one losing fees.

**Comment by dankrad** [comment]
My problem is this: If a block producer is also a relayer, they can just always select their own package. This probably means that the combination of being a block producer and relayer is more profitable than just being one of them, which will lead to not just a monopoly in the relayer market (which I'm willing to accept) but also a monopoly in the block producer (which is a fatal flaw in the protocol).

**Comment by naterush** [comment]
I don't think (2) and (3) are different solutions. In (2), users "hold a small balance coins in a special EE that block producers understand," and pay block producers through conditional transactions in this "special EE." In (3), relayers "pays fees using a special EE that block producers understand." As such, (2) is just _one specific implementation_ of (3) -- where the "special EE" from (3) is this conditional fees one specified in (2). Aka, relayers can totally exist in (2) as well; they just have eth in this special conditional payment EE.

> However, (2) has a key weakness: privacy.

By the above point, (2) is just as private as (3) is. Users pay relayers to forward their transaction by using some privacy preserving EE, and relayers can pay block producers in this special conditional transaction EE that the block producers understand.

**Comment by JustinDrake** [comment]
> Moving ETH between EEs is expected to take a full crosslink cycle (~6 min)

In the latest design the full crosslink cycle (in the default best-case scenario) has been brought down to one slot, partly to address fee market challenges. (This comes at the cost of reducing the number of shards to 64.) Cross-shard and cross-EE transactions can be fast (in the default best-case scenario) without fancy infrastructure, in particular facilitating fast gas payments.

(It is still possible that, in the longer term, fancy application-layer infrastructure (e.g. optimistic virtual crosslinks) will provide sub-slot communication as well as "backup" crosslinks whenever consensus-level crosslinking stalls or slows down. Such infrastructure now clearly falls outside the basic infrastructure expected from L1.)
