### ISSUE TITLE
Compact committees root uses incorrect start shard

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/eth2.0-specs#1315]
In the `process_final_updates` function we increment the start shard by the shard delta _before_ computing the compact committees root. This is problematic because `get_compact_committees_root` calls `get_start_shard` (alone and via `get_crosslink_committee`) to work out the start shard and committees for the next epoch. The `get_start_shard` function adds the shard delta to the state's already-incremented start shard, resulting in a start shard for the "next epoch" which has been double incremented. This shard is then used to calculate committees for the next epoch, yielding incorrect results (the committees it computes are not the committees that will be computed once the next epoch actually comes around).

For example, with the minimal config that's used for the sanity tests, if we begin with the start shard equal to **0**, it will get incremented to **7** as part of `process_final_updates`, and then when `get_compact_committees_root` runs it will incorrectly see the next epoch's start shard as **6**.

**Comment by djrtwo** [comment]
Indeed! fixing

**Comment by protolambda** [comment]
Fixed in #1319
