### ISSUE TITLE
Terminology: "Beacon Chain", "beacon chain", Ethereum Beacon Chain (EBC) ?

### ISSUE THREAD

**Issue by ethers** [ethereum/eth2.0-specs#1324]
Other blockchains may have/get a "beacon chain" and it's a generic term like blockchain. Should we start referring to it like EBC, short for Ethereum Beacon Chain?  (This is for future writings, specs, blog posts...)

**Comment by vbuterin** [comment]
I'd say "the beacon chain" is fine. We use terms like "the canonical chain", "the state", etc all the time without amgibuity.

**Comment by ethers** [comment]
With shard chains, "canonical chain" would become ambiguous? Unless focus is on "the", but may as well use the term for beacon chain.

"the state" could also be used less since transactions will be on shards, meaning more usage of something like ShardX state or ShardY state.  (Naming 1024 shards seems like it will be another "UX" topic.)

**Comment by vbuterin** [comment]
Canonical beacon chain, canonical shard chain, beacon chain state, protocol-level shard state, EE state / L2 state?

**Comment by JustinDrake** [comment]
"beacon chain" is fine—no need to get fancy :)
