### ISSUE TITLE
Messy documents

### ISSUE THREAD

**Issue by RmbRT** [ethereum/eth2.0-specs#133]
Everything is a huge wall of text (the beacon chain specs have over 5000 words), and although there are headings, there is no table of contents, so one has to read through everything just to learn the general structure of the document.
I seriously recommend that the documents are split into smaller documents, which are then grouped according to topic. I also recommend that tables of contents are added to the documents.
I also recommend that you do not solely use python scripts to explain something you propose.
**Explaining** should happen in plain text; Code should only be used for **definitions**.
I therefore recommend that you explain your concepts precisely in plain text, and provide your python code as a reference implementation.
It is way easier to find logical errors in prose than code, as code contains additional errors that happened to occur when transforming a thought into code.

Data type definitions would be way more legible if you used tables instead of pseudocode.

Cross-references within the documents would allow faster information retrieval and easier comprehension for non-maintainer readers.
I am trying to learn what your progress regarding sharding is, but it too tiring to read through your messy specification documents.
I think there are many others who feel the same way, and I am also convinced that the current state of affairs is not according to the spirit of rigorous community participation.

It would be in the best interest of the whole project to perform a clean-up of your documents, as it would also improve the outward appearance of the project.

**Comment by djrtwo** [comment]
We have shied away from extra structure in an effort to iterate rapidly on the spec. The phase 0 document is nearing the end of rapid iteration and we will begin focusing on cleaning it up from a content and structural perspective.

I expect in a months time for it to be both much more stable and more readable
