### ISSUE TITLE
Investigate attestation validation

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/eth2.0-specs#1332]
Before forwarding gossip messages, clients are expected to validate attestations and clients caught spreading malicious attestations should be disconnected. 

There is a concern however that validating signatures on attestations will lead to significant propagation delays - measure / evaluate and decide on minimal mandatory validations.

**Comment by djrtwo** [comment]
Validation conditions have been added to the spec. Will revisit this if we run into issues on testnet
