### ISSUE TITLE
Networking: protocol advertisement in discv5

### ISSUE THREAD

**Issue by raulk** [ethereum/eth2.0-specs#1335]
The networking spec introduced in #1328 relies on fine-grained, per-operation protocol IDs to univocally identify what operation a req/rep stream targets (negotiated and selected via multistream-select 1.0 / multiselect 2.0).

> _[For background on the rationale, see the answer to question ["Why segregate requests into dedicated protocol IDs?"](https://github.com/ethereum/eth2.0-specs/blob/d09d56bec8cec98e3d77a286c48972521dd2be96/specs/networking/p2p-interface.md#L649)]_

To efficiently advertise our supported protocol set on the discovery layer (discv5), I propose to introduce the concept of _protocol families OR protocol groups OR protocol suites OR protocol manifests_ that aggregate finer-grained protocols into a logical, versioned unit that can be advertised/enumerated efficiently on the ENR (max. size 300 bytes), e.g. `/eth/reqrep/attestation/v03`.

Another approach worth considering is bloom filters on the ENR, in order to compact advertisements in a probabilistic manner. Either:

1. a single, flat bloom filter.
2. one bloom filter per namespace, e.g. one bloom filter for `/eth/reqrep/attestation`, another one for `/eth/reqrep/slashing`

could potentially work well.

See the following discussions for context:

https://github.com/ethereum/eth2.0-specs/pull/1328#discussion_r310403895
https://github.com/ethereum/eth2.0-specs/pull/1328#discussion_r310099975
https://github.com/ethereum/eth2.0-specs/pull/1328/files#diff-9e07d955515655364c9a5f28c94f5627R236

**Comment by JustinDrake** [comment]
@raulk: I'm going through old/stale issues. Any update on this? cc @AgeManning

**Comment by AgeManning** [comment]
This is a good idea and a relatively easy implementation to advertise protocols. 

I think whether we adopt a solution like this, or another ENR-based advertised solution depends on whether we can get discv5 topics to a production state that everyone agrees on.

For the time being, we are discovering peers, then negotiating protocols via multistream select, rather than checking a bloom filter. 

If @raulk agrees, I think we can close this and re-address when looking into topic advertisements in discv5.

**Comment by djrtwo** [comment]
We certainly want to do shard-subnet advertisement via ENR. We plan to accomplish this via a  64-bit bitfield in phase 0. Getting this into spec and releasing a very minor `v0.9.4` is top of my list tomorrow

**Comment by JustinDrake** [comment]
> Getting this into spec and releasing a very minor `v0.9.4` is top of my list

It made it in `v0.9.4` https://github.com/ethereum/eth2.0-specs/pull/1534/files :)

> I think we can close this and re-address when looking into topic advertisements in discv5

Closing! @rauljordan—Feel free to reopen if you feel otherwise.
