### ISSUE TITLE
Policing storage requirements

### ISSUE THREAD

**Issue by shayzluf** [ethereum/eth2.0-specs#1336]
From my understanding of the storage requirements for policing the network it should be 
54000 * 300000 * 328 bytes per attestation ~5.4 Tb 
54000 * 2344 committees per epoch * 328 bytes ~ 41gb using aggregated attestations
8 months of proposals and validation data

if those are the requirements I guess we at Prysmatic labs will go with this design https://docs.google.com/presentation/d/1MkLraDsZJCX3k62bBtt8ziUdw308U2bW_w0lUmV-0YQ/edit?usp=sharing

**Comment by djrtwo** [comment]
See https://github.com/ethereum/eth2.0-pm/issues/63 for a discussion on the expectation that normal validating nodes will shard policing responsibility

**Comment by djrtwo** [comment]
Going to close this issue. I suggest taking the discussion to the issue linked above
