### ISSUE TITLE
Non ABI-standard return value of `get_deposit_count` of `deposit_contract`

### ISSUE THREAD

**Issue by daejunpark** [ethereum/eth2.0-specs#1341]
### What's wrong?

The return value of [the `get_deposit_count` function of `deposit_contract`](https://github.com/ethereum/eth2.0-specs/blob/v0.8.1/deposit_contract/contracts/validator_registration.v.py#L60) does *not* conform to [the ABI encoding](https://solidity.readthedocs.io/en/v0.5.10/abi-spec.html), having incorrect zero-padding, due to [a Vyper compiler bug](https://github.com/ethereum/vyper/issues/1563).

### How to reproduce?

For a quick reproduction of the buggy behavior, just add the following line at [the end of `test_deposit_tree`](https://github.com/ethereum/eth2.0-specs/blob/v0.8.1/deposit_contract/tests/contracts/test_deposit.py#L149) (inside the `for` loop):
```
registration_contract.functions.get_deposit_count().call()
```
(A more meaningful test would be to check the return value is equal to the loop index `i`, the number of `deposit` invocations made.)

Then you will get the following exception:
```
eth_abi.exceptions.NonEmptyPaddingBytes: Padding bytes were not empty: b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 '
```
which is generated by [`eth_abi/decoding.py`](https://github.com/ethereum/eth-abi/blob/v2.0.0/eth_abi/decoding.py#L530). (Note that the last character is an ascii character of `b'\x20`.)

### How to fix?

Well, wait until the compiler bug is fixed, and update the Vyper compiler version. :)

Also, add some tests for (or have [the existing tests](https://github.com/ethereum/eth2.0-specs/blob/v0.8.1/deposit_contract/tests/contracts/test_deposit.py) to invoke) `get_deposit_count`, to detect further regressions.

**Comment by JustinDrake** [comment]
Congrats on finding that compile bug! While we're at it, I suggest bundling in #1279 when we do the fix.

**Comment by JustinDrake** [comment]
Closing in favour of #1362 :)
