### ISSUE TITLE
Economic calculator for Eth2.0

### ISSUE THREAD

**Issue by dankrad** [ethereum/eth2.0-specs#1344]
Currently, in order to understand the exact economic implications of being a validator, a very careful reading of the spec is required in order to know what the exact risks and benefits are. We want to create more transparency around this issue by adding a visual calculator, that given a number of inputs will show what the individual validator stands to gain and lose.

Target group: Individuals running validators and economists analysing Eth2.0 incentives for validators

Technology: This should probably be a web app, ideally a node module that can either run standalone or be integrated into another app such as a validator client GUI to give more information to the user

Inputs:
 - Should be a number of sliders:
    - expected online time
    - cost to run validator node (electricity/hardware deprecation/cloud rental)
    - cost of capital
    - probability of failures that lead to penalties and/or slashing (equivocation, key reveals, incorrect custody bits, missing of custody deadlines, incorrect attestations (fraud proofs))
    - probability of those failures being caught by a second "don't slash" layer that polices validator client outputs
    - probability that these failures are correlated with other validators (fraction of other validators using the same client software)
    - number of competing validators (with same settings or different settings)
  - Ability to load custom configurations (mainnet, testnet, etc.)

Outputs:
 - numerical outputs showing the expected returns with variance and total probability of slashing
 - a graph that shows expected profits and losses as a diagram per time period
 - a graph that shows long-term development of the initial deposit with this expected return
 - a graph illustrating total ETH inflation

Further ideas on how to improve this are very welcome, this is just an initial set of ideas. The goal should be a tool that can allow people to gain a good intuition on validator rewards and penalties.

**Comment by hwwhww** [comment]
> Inputs:

Plus the functionality of custom configurations (with mainnet` setting by default):
- [Rewards and penalties configurations](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#rewards-and-penalties)
- [Gwei values](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#gwei-values)

**Comment by JustinDrake** [comment]
Would also be nice to show global ETH inflation based on number of active/online validators.

**Comment by dankrad** [comment]
Added these :)

**Comment by JustinDrake** [comment]
Pinging @econoar who may be interested in contributing :)

**Comment by vbuterin** [comment]
This seems easily doable with a spreadsheet. Haven't some of these crypto research orgs done one already?

**Comment by dankrad** [comment]
Good point, that may very well be a more maintainable solution to this problem. Would be interested if it exists already?

**Comment by vbuterin** [comment]
Here is a spreadsheet some Consensys people worked on: https://docs.google.com/spreadsheets/d/1zU1wzlDsw-BPWp5d4eJMJLHGuCbB_UJ2rPLP7eanW9I

**Comment by vbuterin** [comment]
I just updated it with the most recent formulas based on the frozen phase 0 spec.

Perhaps the most surprising (though really not so surprising) finding is just how low issuance gets if you assume even a slightly less than 100% average online rate (eg. 90% gets you 1.11% issuance instead of 1.51%)

**Comment by hwwhww** [comment]
> Here is a spreadsheet Collin Myers worked on: https://docs.google.com/spreadsheets/d/1zU1wzlDsw-BPWp5d4eJMJLHGuCbB_UJ2rPLP7eanW9I

Haven't seen it before, and it's very informative!
I think the point of this calculator is to get more attention and interactivity. But indeed maintainability is an important factor.

I will ping Collin to get more insight.

**Comment by collinjmyers** [comment]
Hey Everyone! Excited this topic is getting some traction as I have been focused on it for a while. Shoutout to V for updating the model with the Phase 0 freeze metrics. I am currently working to refine/simplify the model and produce insightful network level sensitivity charts. I will update the group and send the new model when finished!

**Comment by JustinDrake** [comment]
> I will update the group and send the new model when finished!

@collinjmyers Are you still working on the economic calculator? If so, could you share an update? :)

**Comment by collinjmyers** [comment]
https://docs.google.com/spreadsheets/d/15tmPOvOgi3wKxJw7KQJKoUe-uonbYR6HF7u83LR5Mj4

**Comment by collinjmyers** [comment]
Check out the Telegram group @eth2calculator - I will be doing a few updates to the model on Tuesday to model out the 500K threshold and include in the graphs

**Comment by hwwhww** [comment]
Closing in favor of ConsenSys Codefi team's work :)
