### ISSUE TITLE
5 ETH phase 0 bounties

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1345]
* **Prize**—5 ETH (or 1000 DAI, whichever largest) for any substantive change to [the `master` branch](https://github.com/ethereum/eth2.0-specs/tree/master) merged prior to the Eth2 genesis. Security fixes may be rewarded more at the discretion of the research team.
* **Scope**—Substantive changes to the phase 0 spec for either:
    * *state transition function*—`hash_tree_root(state_transition(state, block))` changes for some inputs `state` and `block`, or
    * *fork choice rule*—`get_head(store)` changes after some received sequence of `block`s and `attestation`s at specific `time`s, or
    * *deposit contract*—changes to the [contract bytecode](https://github.com/ethereum/eth2.0-specs/blob/dev/deposit_contract/contracts/validator_registration.json)
* **Exclusions**—The following are out of scope:
    * [configuration values](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#configuration), which are expected to be tweaked
    * [BLS signatures](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/bls_signature.md), which are undergoing standardisation
    * known open [issues](https://github.com/ethereum/eth2.0-specs/issues) and [PRs](https://github.com/ethereum/eth2.0-specs/pulls) (in particular, the first to file is rewarded in case of duplicates).
* **Participate**—To participate open an [issue](https://github.com/ethereum/eth2.0-specs/issues/new) or [PR](https://github.com/ethereum/eth2.0-specs/compare) with a description of the issue or suggested change. After the substantive change is merged into `master` ask @JustinDrake for payment.

**Comment by vbuterin** [comment]
> Scope—Substantive changes to the phase 0 state transition function, i.e. changes that modify hash_tree_root(state_transition(state, block)) for some inputs state and block.

And the fork choice rule?

**Comment by JustinDrake** [comment]
> And the fork choice rule?

Added :)

**Comment by ethers** [comment]
Although a known open issue, should https://github.com/ethereum/eth2.0-specs/issues/1303 be eligible?

Are there any other open issues that could use more help and where substantive feedback/changes could be rewarded?

**Comment by djrtwo** [comment]
This bounty is specifically for identifying bugs and other substantive changes that should be made  to the phase 0 related specs prior to mainnet launch.

Anything identified in an existing issue is not eligible for this bounty

**Comment by ethers** [comment]
Got it this is strictly phase0.

To the extent that bounties are helpful, maybe a separate bounty should be considered for open issues that could use more help or substantive feedback...

**Comment by djrtwo** [comment]
Note! This program is suspended until we make the next couple of releases. It will be re-instituted in mid-January

**Comment by djrtwo** [comment]
Closing this issue. 
This program was suspended due to some breaking changes going into the spec.

We are reformulating the program and will release details asap

**Comment by ethers** [comment]
The current Bounty Program is at
https://notes.ethereum.org/@djrtwo/phase0-bounty

per https://blog.ethereum.org/2020/03/31/eth2-quick-update-no-10/
