### ISSUE TITLE
Validators are able to censor new validators

### ISSUE THREAD

**Issue by daejunpark** [ethereum/eth2.0-specs#1349]
### Problem

In [`process_operations`](https://github.com/ethereum/eth2.0-specs/blob/v0.8.2/specs/core/0_beacon-chain.md#operations), we have the following assertion to prevent validators to censor new validators, but it is not sufficient.
```
# Verify that outstanding deposits are processed up to the maximum number of deposits
assert len(body.deposits) == min(MAX_DEPOSITS, state.eth1_data.deposit_count - state.eth1_deposit_index)
```

Here is a way to censor new validators by colluding validators.

1. Suppose the majority of existing validators decide to collude and selectively allow new validators to join.
2. Then, they make the MAX_DEPOSITS (= 16) number of *invalid* deposits to the deposit contract, at the cost of "only" 16 Ether. For example, `deposit(0x00..,0x00..,0x00..)` will simply go through and add an invalid deposit item in the Merkle tree.
3. Now, they can simply put the 16 invalid deposits in new blocks, passing the above assertion, and [`process_deposit()`](https://github.com/ethereum/eth2.0-specs/blob/v0.8.2/specs/core/0_beacon-chain.md#deposits) will simply skip all of them as follows:
```
if not bls_verify(pubkey, signing_root(deposit.data), deposit.data.signature, domain):
    return
```
4. In this way, the colluding validators can selectively allow new validators to join, or no new validators at all.

### How to fix?

Keep track of the number of invalid deposits, say `state.eth1_invalid_deposit_index`, whenever `process_deposit()` skip them, e.g.,
```
if not bls_verify(pubkey, signing_root(deposit.data), deposit.data.signature, domain):
    state.eth1_invalid_deposit_index += 1
    return
```
And then, consider it in the assertion of `process_operations()`, e.g.,
```
assert len(body.deposits) == min(MAX_DEPOSITS,
    state.eth1_data.deposit_count - state.eth1_deposit_index
                                  - state.eth1_invalid_deposit_index)
```

**Comment by daejunpark** [comment]
Even in the non-colluding case, the above assertion has the usability issue that benign validators have to keep including all the invalid deposits whenever they propose a new block, which could be quite annoying and may lead to unintended blocking new validators join properly.

BTW, I do not have a good idea how to prevent invalid deposits from being added in the (eth1) tree at the first place, without incorporating `bls_verify` in the deposit contract.

**Comment by JustinDrake** [comment]
> In this way, the colluding validators can selectively allow new validators to join

How does this follows from the invalid deposits? All deposits (valid or not) need to pass `assert is_valid_merkle_branch` and modify the state with `state.eth1_deposit_index += 1`.

**Comment by daejunpark** [comment]
@JustinDrake Sorry I was wrong. I somehow misunderstood that `state .eth1_deposit_index` does not increase when `bls_verify` fails. Sorry for bothering.
