### ISSUE TITLE
Add tests for executable validator guide

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#1352]
### Issue
Follow-up of #1227. The validator guide is executable after #1236. But these code snippets are not covered in tests. 

### How to fix it
Add unit tests for them.

**Comment by JustinDrake** [comment]
@hwwhww What is the status of this? Do we have tests now?

**Comment by hwwhww** [comment]
@JustinDrake validator guide is still not covered by unit tests. I'll pick it.

**Comment by hwwhww** [comment]
closing via #1745
