### ISSUE TITLE
Add clarity on SSZ deserialization

### ISSUE THREAD

**Issue by dankrad** [ethereum/eth2.0-specs#1359]
Giving implementers a bit more clarity on how to implement SSZ deserialization would be desirable. Idea is to add a few sentences on the principal ideas and desirable optimizations.

**Comment by vbuterin** [comment]
Any reason not to just link to a simple implementation of the deserialize function in the python code?

**Comment by djrtwo** [comment]
We've repeatedly had to explain this piece to implementers in addition to pointing to the relevant code. I'm pro adding a couple of sentences here
