### ISSUE TITLE
Minimum number of validators to progress the chain

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1367]
What is the minimum number of validators to progress the chain, and why?

I assumed it was 1 until @djrtwo suggested it was 64 and [SigmaPrime specifies 64](https://github.com/sigp/lighthouse/blob/468015f9bbc1d74522f041cc278740026d4e1893/eth2/types/src/beacon_state/beacon_state_types.rs#L92). (The design *intent* was for the beacon chain to have minimal liveness requirements, where a single validator is sufficient. Being able to run the beacon chain with, say, 3 validators may also be useful for testing and fuzzing. If it's an easy fix we may want to address the design flaw.)

**Comment by vbuterin** [comment]
Currently `get_beacon_proposer_index` will fail if the number of validators is less than 64, as then some committees will be empty and so `candidate_index = first_committee[(epoch + i) % len(first_committee)]` will fail. We could edit the code to return None in that case.

**Comment by JustinDrake** [comment]
I see. Another (possibly more natural) possibility is to not restrict oneself to the first committee and instead continue to the following committees. One advantage of this approach is (marginally) more fairness. Indeed, consider a scenario where there's exactly one validator per committee. Then every validator is equally likely to be selected as a proposer, regardless of their effective balance.

**Comment by vbuterin** [comment]
I'd say that's too much complexity to marginally improve a very marginal case :smile:

**Comment by JustinDrake** [comment]
What about:

```python
epoch = get_current_epoch(state)
indices = get_active_validator_indices(state, epoch)
seed = get_seed(state, epoch)
MAX_RANDOM_BYTE = 2**8 - 1
i = 0
while True:
    candidate_index = indices[compute_shuffled_index(ValidatorIndex(i % len(indices)), len(indices), seed)]
    effective_balance = state.validators[candidate_index].effective_balance
    random_byte = hash(seed + int_to_bytes(i // 32, length=8))[i % 32]
    if effective_balance * MAX_RANDOM_BYTE >= MAX_EFFECTIVE_BALANCE * random_byte:
        return ValidatorIndex(candidate_index)
    i += 1
```

Advantages beyond better liveness:

1) simpler (no `get_start_shard`, `get_committee_count`, or `get_crosslink_committee`)
2) more efficient (encourage implementers to "stream" candidate indices without computing a full committee)
3) more fairness

**Comment by JustinDrake** [comment]
What about:

```python
epoch = get_current_epoch(state)
indices = get_active_validator_indices(state, epoch)
seed = get_seed(state, epoch)
MAX_RANDOM_BYTE = 2**8 - 1
slot_counter = 0
i = 0
while True:
    candidate_index = indices[compute_shuffled_index(ValidatorIndex(i % len(indices)), len(indices), seed)]
    effective_balance = state.validators[candidate_index].effective_balance
    random_byte = hash(seed + int_to_bytes(i // 32, length=8))[i % 32]
    if effective_balance * MAX_RANDOM_BYTE >= MAX_EFFECTIVE_BALANCE * random_byte:
        if slot_counter == state.slot % SLOTS_PER_EPOCH:
            return ValidatorIndex(candidate_index)
        slot_counter += 1
    i += 1
```

Advantages beyond better liveness:

1) simpler (no `get_start_shard`, `get_committee_count`, or `get_crosslink_committee`)
2) more fairness
3) encourage implementers to "stream" candidate indices without computing a full committee

**Comment by JustinDrake** [comment]
Another possibility (cleaner):

```python
epoch = get_current_epoch(state)
indices = get_active_validator_indices(state, epoch)
seed = xor(get_seed(state, epoch), state.slot)
MAX_RANDOM_BYTE = 2**8 - 1
i = 0
while True:
    candidate_index = indices[compute_shuffled_index(ValidatorIndex(i % len(indices)), len(indices), seed)]
    effective_balance = state.validators[candidate_index].effective_balance
    random_byte = hash(seed + int_to_bytes(i // 32, length=8))[i % 32]
    if effective_balance * MAX_RANDOM_BYTE >= MAX_EFFECTIVE_BALANCE * random_byte:
        return ValidatorIndex(candidate_index)
    i += 1
```

**Comment by djrtwo** [comment]
I think there might be another component that fails at less than `SLOTS_PER_EPOCH` validators. I'll take a look and report back.

@JustinDrake I think `SLOTS_PER_EPOCH` validators is a very reasonable lower bound on min-validators and I'm not necessarily in favor of adding complexity to reduce it lower.

>  If there's only 3 validators we still want the chain to be able to progress every slot (as opposed to just 3 out of 64 slots).

Given the slashing conditions, this wouldn't be possible. Bare minimum wrt to slashing conditions is that the number of blocks possible per epoch is `min(SLOTS_PER_EPOCH, len(validators)`

**Comment by JustinDrake** [comment]
> I'm not necessarily in favor of adding complexity

Right. So I think we can actually *reduce* complexity. (See two proposals above.)

> Bare minimum wrt to slashing conditions is that the number of blocks possible per epoch is `min(SLOTS_PER_EPOCH, len(validators))`

Not sure I understand:

1) What is the relationship between slashing conditions and number of block possible per epoch?
2) Why would my proposals not yield at least `min(SLOTS_PER_EPOCH, len(validators))` possible blocks per epoch? (I believe they yield `SLOTS_PER_EPOCH`, i.e. every slot has a proposer.)

**Comment by djrtwo** [comment]
A proposer slashing is assessed on a per-epoch basis. If `len(active_validators) < SLOTS_PER_EPOCH` and `blocks_per_epoch == SLOTS_PER_EPOCH`, then some validators must be assigned to propose multiple times in an epoch. As the current proposer slashing condition is written, fulfilling multiple proposal duties would result in a slashable offense

**Comment by JustinDrake** [comment]
Closing in favour of #1371
