### ISSUE TITLE
CI spellcheck and toc check

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#1369]
As discussed in #1368, look into integrating a CI spellcheck and table of contents checker.

Suggested tools:
https://github.com/thlorenz/doctoc
https://github.com/codespell-project/codespell

Look into a link validator for CI:
https://github.com/webhintio/markdown-link-validator (gives a lot of false positives. Probably not suitable for ci. are there viable alternatives?)

**Comment by JustinDrake** [comment]
It looks like `doctoc` is now implemented, and possibly also `codespell` (judging from the [`.codespell-whitelist`](https://github.com/ethereum/eth2.0-specs/blob/dev/.codespell-whitelist) file).

Can this issue be closed? :)

**Comment by JustinDrake** [comment]
cc @MrChico

**Comment by djrtwo** [comment]
Yes! closing

**Comment by MrChico** [comment]
Actually, the codespell check is not yet in ci, but it is trivial to add. See https://github.com/ethereum/eth2.0-specs/pull/1527

**Comment by djrtwo** [comment]
oh shit. Thanks!
