### ISSUE TITLE
Refine beacon fork choice rule to take into account skip slots

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1386]
The beacon [fork choice rule](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_fork-choice.md#get_head) currently does not use the (implicit) slot corresponding to an attestation (which can be computed using `get_attestation_data_slot`). This means that the beacon fork choice rule is discarding information about skip slots, and can be made more granular.

The suggested fix is to replace the `LatestMessage` container with:

```
class BeaconCheckpoint(Container):
    slot: Slot
    root: Hash
```

(I.e. replace `epoch` with `slot`. For clarity, we could rename `Checkpoint`—e.g. to `FFGCheckpoint`, `EpochCheckpoint`, `FinalityCheckpoint`.) We then make `get_head` return a `BeaconCheckpoint` (as opposed to a plain `Hash`).

In addition to changing the fork choice rule, we could also replace `AttestationData. beacon_block_root` by a `BeaconCheckpoint` to make the slot explicit. This is something that @djrtwo suggested we do, and I now think it is the "natural" thing to do. (Part of the reason it is natural is that we want shard chains to vote on `ShardCheckpoint`s, not plain block roots which do not take into account skip slots.)

**Comment by JustinDrake** [comment]
> the granularity of `slot` for `LatestMessage` is incorrect

Disagree :) Consider the following situation. You have the genesis block `G` at slot 0, a block `B` at slot 1 (building on `G`), and a "virtual" skip block `S` also at slot 1 (building on `G`). You've received 3 attestations so far—1 attestation has GHOST vote for `B`, and 2 attestations have GHOST votes for `S`. Currently `get_head` returns `signing_root(B)`. This is incorrect. Instead, `get_head` should return `(Slot(1), signing_root(G))`.

**Comment by mkalinin** [comment]
> This is incorrect. Instead, `get_head` should return `(Slot(1), signing_root(G))`.

Isn't there is a rule that the longest chain always wins?

**Comment by JustinDrake** [comment]
> Isn't there is a rule that the longest chain always wins?

As I'm sure you know, Eth2 does not have a longest chain rule like Bitcoin. Instead, it uses LMD GHOST (or [FMD GHOST](https://ethresear.ch/t/decoy-flip-flop-attack-on-lmd-ghost/6001)).

**Comment by mkalinin** [comment]
Sorry, I must be saying _the heaviest chain_, of course. And the _heaviest chain_ in your case seem to be the one that have more votes, i.e. `G` is the head disregarding slot/epoch of the votes made to `G`. From my understanding in terms of fork choice slot and/or epoch don't matter, only _a chain of block roots_ and votes made to those roots has valuable meaning. Am I missing anything?

**Comment by JustinDrake** [comment]
Closing in favour of #1394. After discussing with Danny I agree that the

```
class BeaconCheckpoint(Container):
    slot: Slot
    root: Hash
```

approach is wrong :)
