### ISSUE TITLE
Flat containers

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1388]
Crosslinks are a generic place to "flatten" (i.e. serialise to bytes) objects to benefit from custody and availability proofs. Example objects we may want to flatten in the crosslinks:

* shard headers
* shard bodies
* shard state (once per crosslink)
* EE state (once per crosslink)
* receipts (once per crosslink)

When flattening an object `o` we want `hash_tree_root(o) == hash_tree_root(flatten(o))`, where `flatten(o)` is a flat serialisation to bytes. Containers do not, out of the box, have this property.

The suggestion is to define "flat" containers which have the same syntax as normal containers, except that the Merkleisation is "flattening-friendly". To achieve this, the data leaves in a flat container are greedily packed from left to right in a vector of bytes, with minimal padding added between leaves to avoid crossing tree boundaries.

Currently we are doing the flattening manually (see [here](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/1_shard-data-chains.md#flatten_shard_header)), and [carefully crafting embedded objects](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/1_shard-data-chains.md#shardblock) to make the flattening work out. This proposal is syntax sugar to abstract away those hacks.

**Comment by vbuterin** [comment]
I think that, at the cost of less efficient padding in some cases, we can make a `FlatContainer` type that preserves the "flat serialization" property (`hash_tree_root(o) == hash_tree_root(flatten(o))`) in all cases where all elements of the container preserve the flat serialization property, and also preserves the "transparency" property (for every element, some intermediate generalized index in the tree is the root hash of that element).

Here's the algorithm pseudocode. `hash_tree_root(FlatContainer)` would just be `hash_tree_root(flatten(FlatContainer))`.

```python
def flatten(input: FlatContainer) -> bytes:
    o = b''
    for value in input.get_fields().values():
        sub = flatten(value)
        o += b'\x00' * (-len(o) % len(sub)) + sub
    return o + b'\x00' * (next_power_of_two(len(o)) - len(o))
```

`flatten` for regular containers would just not bother with the `b'\x00' * (-len(o) % len(sub))` padding. For example, if a ShardBlock was a FlatContainer with `(block_root: bytes32, state_root: bytes32, parent_root: bytes32, slot: uint64, total_bytes: uint64, signatures: Vector[2](bytes96))`, the flattening would be (representing as chunks, B = block root, S = state root, P = parent root,  s = slot, t = total_bytes, $ = signature, 0 = padding):

* signatures[0]: `$ $ $ 0`
* signatures[1]: `$ $ $ 0`
* signatures: `$ $ $ 0 $ $ $ 0`
* the container: `B S P s t 0 0 0 $ $ $ 0 $ $ $ 0`

The generalized index 3 would represent the root of `signatures`, and the generalized indices 6 and 6 would represent the roots of `signatures[0]` and `signatures[1]`.

**Comment by JustinDrake** [comment]
Closing in favour of #1400.
