### ISSUE TITLE
Use attestation epoch in beacon fork choice rule

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1394]
Currently the fork choice rule ignores the attestation epoch. The suggestion (from @djrtwo [here](https://github.com/ethereum/eth2.0-specs/issues/1386#issuecomment-525901372)) is to replace

```python
if i not in store.latest_messages or target.epoch > store.latest_messages[i].epoch:
    store.latest_messages[i] = LatestMessage(epoch=target.epoch, root=attestation.data.beacon_block_root)
```

with

```python
attestation_epoch = compute_epoch_of_slot(get_attestation_data_slot(attestation.data))
if i not in store.latest_messages or attestation_epoch > store.latest_messages[i].epoch:
    store.latest_messages[i] = LatestMessage(epoch=attestation_epoch, root=attestation.data.beacon_block_root)
```

In addition, the suggestion is to add `slot` to `AttestationData`.

**Comment by mkalinin** [comment]
Shouldn't `attestation_epoch` and `attestation.data.target.epoch` be the same thing?

According to  [0_beacon-chain-validator.md#ffg-vote](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/validator/0_beacon-chain-validator.md#ffg-vote) `target.epoch` is the current epoch calculated for the state being attested to.

**Comment by mkalinin** [comment]
It looks like `attestation.data.slot` is enforced to be of `target.epoch` since https://github.com/ethereum/eth2.0-specs/pull/1509 PR is merged. We may close this issue I guess.

**Comment by djrtwo** [comment]
yup, good to go
