### ISSUE TITLE
`Version()` undefined

### ISSUE THREAD

**Issue by mcdee** [ethereum/eth2.0-specs#1430]
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#compute_domain the default value for the second parameter is `Version()` but this does not appear to be defined anywhere.

**Comment by ralexstokes** [comment]
`Version` is an alias for the custom type `Bytes4`.

Following the spec's convention for default types, this is the "empty" type for a value of a fixed-length bytestring of length 4, i.e. `0x00000000`.

Does this clarify the intention here? If not, we can definitely discuss a way to improve how this is communicated.

**Comment by mcdee** [comment]
It's the `Version=Version()` piece in the signature of `compute_domain()` that looks odd, because it suggests that `Version()` is a function that can be called rather than the default value for the type.

From what you say above it sounds like the signature should be this:

```
def compute_domain(domain_type: DomainType, fork_version: Version) -> Domain:
```

which is without a default value and hence falls back to `0x00000000`; would you agree?  Or are there situations in which the fork number at genesis can be something other than 0?  Test nets, third-party forks, _etc_?  In which case it seems that a `Version()` function makes sense and returns the fork number at genesis (but would then need to be defined).

**Comment by ralexstokes** [comment]
this may be unclear as it inherits some of the Python syntax facilitating the executable spec.

as you wrote, this is a function that takes two concrete parameters with the given types. omitting one or the other is an arity error. to provide a default argument you can write `def f(x=y): ...` where `y` is the default value. i'd make a distinction b/t this "default" value and the "empty" or "zero" value for a type (somewhat inherited from this notion in Go, where the idea is you instantiate a type where the underlying memory representation is the appropriate number of `0x00` bytes.).

given how the Python code wrapping the executable spec works, we can provide an instance of the "empty" value by just calling the class/type for it, e.g. see `BeaconBlockBody()` in `initialize_beacon_state_from_eth1` here: https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#genesis

**Comment by mcdee** [comment]
@ralexstokes thanks for the explanation; the bit I was missing was the instantiation of the empty value by calling the class.
