### ISSUE TITLE
SSZ summary/expansion definition should reference signing_root

### ISSUE THREAD

**Issue by wemeetagain** [ethereum/eth2.0-specs#1436]
In cases where full objects contain signatures (currently only `BeaconBlock`s), the `signing_root` is used as a summary instead of the `hash_tree_root`. The definition of a summary should be expanded (lol) to include this edge case.

eg:
a block header:
```
{
  slot: Slot,
  parent_root: Summary(BeaconBlock), // signing_root
  state_root: Summary(BeaconState), // hash_tree_root
  ...
}
```

**Comment by protolambda** [comment]
Yes, and we have a similar issue for partials; a root may represent the signing root of a Block; and although the two are compatible sometimes (sibling nodes don't tell anything about the field being ignored or not), the depth of the merkleization, along with convertability between the two roots are affected.

**Comment by protolambda** [comment]
Closing this, we won't have a signing-root anymore to worry about :). See #1491
