### ISSUE TITLE
Honest validator eth1 timestamp

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#1439]
Following up on conversations with @JustinDrake and @djrtwo, in the [Eth1 Data](https://github.com/ethereum/eth2.0-specs/blob/v0.8.3/specs/validator/0_beacon-chain-validator.md#eth1-data) section of the honest validator guide there is the following:

> Let get_eth1_data(distance: uint64) -> Eth1Data be the (subjective) function that returns the Eth 1.0 data at distance distance relative to the Eth 1.0 head at the start of the current Eth 1.0 voting period.

I have two points regarding this text:

### 1. Clarification

I wanted to clarify that we're looking for something like this (excuse my shabby pseudo-python):

```python
def entire_eth1_chain():
  # Returns all blocks in the eth1 chain in ascending block.number order. Timestamps never decrease.

def get_eth1_data(distance):
  time = state.genesis_time + eth1_voting_period_start_slot * SECONDS_PER_SLOT
  last_block_number = [block.number for block in entire_eth1_chain() if block.timestamp >= time][0]
  get_eth1_data_at_block_number(block_number - distance)
```

I think the primary thing to clarify here is that we observe eth1 block timing using timestamps, as opposed to "looking at my wall clock when I first see a block".

### 2. Eth1 staleness

A validators Eth1 node can go out of sync, perhaps it's on the wrong chain (eclipse attack) or it's _stale_ and hasn't seen a block in a long time.

Detecting an eclipse attack is out-of-scope for honest validator guide IMO, but I'm interested in staleness. Particularily:

1. How to detect when an eth1 node is stale.
2. What to do when you're trying to produce a block on a stale node.

Perhaps staleness could be defined as:

```python
import time

ETH1_STALE_TIME_SECONDS = SLOTS_PER_ETH1_VOTING_PERIOD * 15

def eth1_chain_is_stale():
  now = time.time()
  entire_eth1_chain()[-1].timestamp + ETH1_STALE_TIME_SECONDS <= now
```

Regarding what to do, it's not so clear to me. Perhaps the block proposer should just decide they're unfit to produce and skip the slot -- this would halt the eth2 chain if the eth1 chain did go down for ~4hrs, _but_ that seems pretty unlikely and we'd probably be very socially aware if eth1 halted for even a minute. An alternative method would be to just vote junk like in #1431.

**Comment by mkalinin** [comment]
> I think the primary thing to clarify here is that we observe eth1 block timing using timestamps, as opposed to "looking at my wall clock when I first see a block".

That said, eth1 block timestamps are prone to manipulations. Computation of _eth1_data_ based on  timestamps plus careless optimisation (e.g. caching `get_eth1_data` result) can potentially lead to a vulnerability when a miner needs to hold timestamp for a little bit near to voting period border to delay validator onboarding. From that perspective tracking eth1 block numbers locally is a better approach.

IMO, staleness is, also, out of scope of a validator doc. I think the best approach to coping with eth1 data failures is suggested by @vbuterin in https://github.com/ethereum/eth2.0-specs/issues/1431#issuecomment-542974071. 

A validator infrastructure will have to use several eth1 clients behind load balancer for diversity. It can use Infura instead or use a couple of pocket clients double checked with Infura, etc. There is a number of solutions to stabilize a source of eth1 data; it should be up to a user.

**Comment by paulhauner** [comment]
> From that perspective tracking eth1 block numbers locally is a better approach.

In this case we still have issues with validators delaying eth2 deposit on-boarding. I don't think there's any scenario where the eth1 miners don't have the ability to suppress/delay/re-order transactions to the deposit contract.

Tracking the times that block numbers arrive locally means you need to have your validator (or some specialized eth1 service) online for 8-12hrs before you can actually start to produce blocks. That combined with using #1431 means that proposers are just going to vote junk data until they have an observation time for ~8hrs worth of blocks, starting from ~4hrs ago. If you use timestamps you can start producing valid eth1 data much faster.

> There is a number of solutions to stabilize a source of eth1 data; it should be up to a user.

I agree that it should be "up to a user" to determine how they obtain/stabilize their eth1 chain. What I'm trying to do here is establish best practices for when things that are very likely to go wrong (e.g., someones HTTP connection to an eth1 node) do indeed go wrong.

I'm fine if there's no definition of staleness in the honest validator guide, but I do think there should be some advice about what to do if you don't have a sufficient connection to eth1. (e.g., should you produce junk eth1 data or just produce no blocks?).

**Comment by Mikerah** [comment]
> In this case we still have issues with validators delaying eth2 deposit on-boarding. I don't think there's any scenario where the eth1 miners don't have the ability to suppress/delay/re-order transactions to the deposit contract.

I brought this up with @adlerjohn a few month ago in this [issue](https://github.com/ethereum/eth2.0-specs/issues/832). Moreover, I discussed more in depth other ways in which validator onboarding can be delayed in [this recent ethresearch post](https://ethresear.ch/t/on-the-insecurity-of-the-eth1-eth2-one-way-bridge/6372).

**Comment by paulhauner** [comment]
#1464 is not directly related, but similar.

**Comment by mkalinin** [comment]
> I don't think there's any scenario where the eth1 miners don't have the ability to suppress/delay/re-order transactions to the deposit contract.

You're right @paulhauner. There is still a room to censor/manipulate deposit transactions and seems like avoiding timestamp manipulation is not giving us much of protection.

**Comment by paulhauner** [comment]
This can be closed due to the new eth1 voting scheme :)
