### ISSUE TITLE
Missing test case: deposit domain != fork domain

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#1445]
Background: https://github.com/prysmaticlabs/prysm/issues/3849

The spec declares that the domain for all deposits should be `[0, 0, 0, 0]`. Coincidentally, that is the same domain that is used as the `fork.current_version` for all the deposits tests.

In effect, this means that the tests do not cover the case where the client passes `beacon_state.fork.current_version` to deposit signature verification instead of `[0, 0, 0, 0]`.

This can be resolved by ensuring there is at least one deposit operation test where the fork versions are not `[0, 0, 0, 0]`.

**Comment by protolambda** [comment]
Good find :+1:  Testing this introduces the overhead of another config however :(

I have an alternative proposal: make fork versions and signing domain types explicitly non-overlapping. Although not strictly necessary, it avoids this kind of confusion in the future, and makes it easy to distinguish the data from logs/debug dumps, and eliminates the possibility of this bug.

We can set a high 1 bit in one, and not in the other, and reserve this bit for this purpose.

**Comment by protolambda** [comment]
Relevant PR: #1554, now we have deposit domain config option. Will add a test-case for having a deposit with different domain shortly
