### ISSUE TITLE
Manipulating deposit contract to gain an early majority

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#1446]
This issue describes a feasible way to gain a dishonest majority in the first two epochs.

### Assumptions
- The shuffling of the first two epochs is determined only by the number of active validators (`v`).
- `v` can only vary by at most `n`, where `n = eth1_gas_limit / gas_for_deposit` (I think this is ~100).

### Gaining an early dishonest majority

If an attacker can control their index in the deposit tree (this seems feasible), then it would take `n * (SLOTS_PER_EPOCH / 2)` validators to ensure they control 50% of the validators in either the first or second epochs.

#### Influencing future shuffling

An attacker with a block-producer majority gains the standard 1-bit of control by submitting/withholding a block.

Additionally, an attacker can also choose thier randao reveal (to some degree) by choosing their private key. Note that the attacker has a long time (now until genesis) to compute these private keys.

Some rough calculations show that gaining _full_ control of future shufflings is infeasible, but _some_ degree of control is possible.

#### Breaking eth1 linking

If used with above attack (influencing future shuffling), it may be feasible for the attacker to produce a majority of the blocks the `ETH1_VOTING_PERIOD` and break the eth1-linking.

We have not looked into the feasibility of this attack.

### Additional Comments

Setting `v` seems to be an instance of "eth1 transaction ordering attack" on smart contracts. Here are some ways to set `v`:

- Be an eth1 miner and supress transactions.
- Use known gas-war techniques to manipulate the ordering of deposits.
  - `1 ether` deposits can be used to cheapen this attack.

**Comment by djrtwo** [comment]
closed via #1447
