### ISSUE TITLE
Attestations and custody bits proposal for phase 1

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#1448]
### Challenges

* An attestation is signing over a maximum of 256 shard blocks and state roots (maximum 1024 shard blocks and state roots signed over per block in total)
* This is a lot of data, and we want to only store the data we need to store (eg. we don't need to store the shard blocks and state roots signed over by _losing_ attestations)
* We want verifying attestations to be efficient (i) in beacon blocks, (ii) over the wire during the aggregation process.

### Proposal

We define two data structures, `Attestation` and `AttestationShardData`. A beacon block contains one `AttestationShardData` for each shard that it is processing (min 1 max 64). `Attestation` objects only contain a hash of the `AttestationShardData` (the hash is still needed to verify signatures). We verify that the `AttestationShardData` hashes to the hash of the winning attestation, ie. the one that gets >=2/3 and updates that shard (or is empty if there is no winner).

An `Attestation` contains a 2D custody bits array, 1 bit per committee member (max 2048) per block processed by that attestation (max 256).

When an attestation is broadcasted over the wire, it _does not_ come with explicit `AttestationShardData`; instead, it is broadcasted in a wrapper that contains a pointer to a single "head". This is because `AttestationShardData` can be inferred from the head assuming that a given client has downloaded all of the shard blocks. 

We define the message hash that a validator is expected to sign over as follows. Let `bits[0]....bits[n-1]` be the validator's custody bits of the `n` blocks. Let `R` be the attestation data root. The validator signs `hash_to_point((R, 0, bits[0])) + ... + hash_to_point((R, n-1, bits[n-1]))`, where `+` is elliptic curve addition over G2.

Note that verifying this signature "on the wire" requires `n` hash to point operations and additions, though the hash-to-point operations need only be computed once for any particular attestation data; only G2 additions are per-attestation work.

Verifying an aggregate signature in a block can be done as follows. Let `custody_subset(i, b)` be the subset of validators whose i'th custody bit is `b`. We do `e(hash_to_point((R, 0, 0)), group_pubkey(custody_subset(0, 0))) * e(hash_to_point((R, 0, 1)), group_pubkey(custody_subset(0, 1))) * ... * e(hash_to_point((R, n-1, 1)), group_pubkey(custody_subset(n-1, 1)))` to compute the Fp12 element the signature is checked against. This requires `2n` pairings.

**Comment by djrtwo** [comment]
Clever! This or something similar seems like a reasonable approach.

The inclusion of only winning `AttestationShardData` is particularly nice.

The 2D custody bit array is max size -- `256 * 2048 = 32 kB`. For the case of unaggregated attestations on the wire this data will be highly compressible (almost all zeros). For the case of aggregates on the shared net, we just need to ensure that not too many can be broadcast (which is done in the simple aggregation strategy.

The main potential issue is the size requirement in the blocks which could at worst case be `32kb * 128 = ~4MB` of custody bits in the blocks. This isn't great but is still small wrt to some of the larger operations that can be included (attester slashings).

The IndexedAttestation (used by slashings) would need to be redesigned to be a list of indices with an associated max-256-bit bitfield each which ups the max size of `AttesterSlashing`s to `2 * (MAX_COMMITTEE_SIZE * BYTES_PER_VAL_INDEX + MAX_COMMITTEE_SIZE *  MAX_SIZE_OF_CUSTODY_BITFIELD)  = 2* (2048 * 8kb + 2048 * 32kb) = ~162MB` from the previous ~66MB so a moderately substantial increase here.

**Comment by vbuterin** [comment]
> The IndexedAttestation (used by slashings) would need to be redesigned to be a list of indices with an associated max-256-bit bitfield each which ups the max size of AttesterSlashings to 2 * (MAX_COMMITTEE_SIZE * BYTES_PER_VAL_INDEX + MAX_COMMITTEE_SIZE * MAX_SIZE_OF_CUSTODY_BITFIELD) = 2* (2048 * 8 + 2048 * 64) = ~300kb from the previous ~66kb so a moderately substantial increase here.

Yep, this is how I changed indexed attestations to work.
