### ISSUE TITLE
minimal testnet config

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#1474]
As discussed on the last call, there are some things we probably want to modified in the `minimal` config for _most_ initial testnets.

* Add `ETH1_FOLLOW_DISTANCE` to all configs and reduce it in `minimal`/`minimal_testnet`
* Add `TARGET_AGGREGATORS_PER_COMMITTEE` to all configs. The number _could_ be reduced for `minimal_testnet` if low # of validators (`~16-32 per committee`) are expected to participate 
* Reduce `MIN_DEPOSIT_AMOUNT` to 3.2 or 0.32 eth in `minimal_testnet` and scale other balance vars accordingly
* Increase `EJECTION_BALANCE` to be 90-95% of the `MIN_DEPOSIT_AMOUNT` in `minimal_testnet`
* add `INITIAL_FORK_VERSION` to config. modify it away from `0` for testnets. Maybe just prepend a 1-bit to generally separate testnet vs mainnet(s) domains.

Another question is where this config should live. I suppose it should live in `configs` as was originally intended, but need to make sure that it doesn't get auto-picked-up by the test infrastructure

**Comment by JustinDrake** [comment]
Is there any outstanding tasks from this issue?

**Comment by djrtwo** [comment]
Don't think we need the specific config anymore. 
One of the main motivating factors for was modding `INITIAL_FORK_VERSION` but the mix-in of `genesis_validators_root` to separate chains satisfies this safety requirement

closing!
