### ISSUE TITLE
BytesN SSZ Alias is Misleading

### ISSUE THREAD

**Issue by rauljordan** [ethereum/eth2.0-specs#1479]
Hi all, currently the SSZ spec [alias section](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/simple-serialize.md#aliases) mentions:

```
BytesN to Vector[byte, N] (this is not a basic type)
```
and we also have the type `Byte[N]` in some other places across the repo including the test generators for ssz generic containers [here](https://github.com/ethereum/eth2.0-specs/blob/40cb72ec112903a28cbfc9e310e14844680476e5/test_generators/ssz_generic/ssz_container.py#L35). This tricky nomenclature led us to some painful debugging and quite some time spent fixing broken tests in Prysm. The alias doesn't add much utility and we at @prylabs would just prefer to stick to the suggested naming conventions for lists vs. vectors:

```
List[byte, N]
Vector[byte, N]
```

**Comment by dankrad** [comment]
How is it misleading? Other than that we should probably add Byte[N] to our list of aliases?

**Comment by rauljordan** [comment]
Why need the alias and more complexity? Why not just stick to
```go
List[byte, N]
Vector[byte, N]
```
It was just a point of frustration when trying to pass spec tests and got confused between the types. Would have been just easier if we didn't introduce those custom aliases. Spent a good chunk of time fixing broken tests due to confusion, unfortunately.

**Comment by protolambda** [comment]
See #1480
