### ISSUE TITLE
possible get_validator_churn_limit() issue

### ISSUE THREAD

**Issue by jrhea** [ethereum/eth2.0-specs#1493]
For v9.2 of the phase 0 beacon chain, I am assuming that we calculate the max number of validators as follows: 

`MAX_VALIDATORS_PER_COMMITTEE` * `MAX_COMMITTEES_PER_SLOT` = 2^11 * 2^6 = 2^17 

if so, then this function:

```python
def get_validator_churn_limit(state: BeaconState) -> uint64:
    """
    Return the validator churn limit for the current epoch.
    """
    active_validator_indices = get_active_validator_indices(state, get_current_epoch(state))
    return max(MIN_PER_EPOCH_CHURN_LIMIT, len(active_validator_indices) // CHURN_LIMIT_QUOTIENT)
```
will always be equal to `MIN_PER_EPOCH_CHURN_LIMIT`.

**Comment by djrtwo** [comment]
Validators are still assigned to only one slot/committee per epoch. So the above calculation for max validators should be `MAX_VALIDATORS_PER_COMMITTEE * MAX_COMMITTEES_PER_SLOT * SLOTS_PER_EPOCH` which equals the same ~4M validators (or ~130M ETH deposited) as before

**Comment by jrhea** [comment]
Oh...right.  Makes sense 😀
