### ISSUE TITLE
sha3/blake mismatch in deposit merkle tree

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#151]
# Issue
We are building the `receipt_tree` in the pow deposit contract with `sha3`, but then are attempting to verify the merkle branch in the beacon chain with `hash` which is defined as `blake2b`. This won't work! :)

# Proposed Solution
Either:
* require `sha3` (actually `keccak256`) in beacon chain implementations
* deploy `blake2b` as a precompile on existing pow chain

**Comment by vbuterin** [comment]
The latter would make Zooko very happy!

Actual question though: are we sure we are using blake2b as the phase 0 hash function? Or could we end up switching to something stark friendly?

**Comment by JustinDrake** [comment]
Do we need to go through this process of explicitly and manually including Ethereum 1.0 logs on the beacon chain? Can't this happen implicitly and automatically when the `POW_RECEIPT_ROOT_VOTING_PERIOD` boundary is hit on the beacon chain?

**Comment by djrtwo** [comment]
hmmm I prefer explicit over implicit in general. I want a  node that is not syncing eth1.0 to be able to process and validate the deposit records.

As for the implicit vs explicit, it still doesnt resolve this mismatched hash issue.

**Comment by mkalinin** [comment]
Could `keccak256` be used as a proof-of-posession hash function? If yes then it makes it more reasonable to add `keccak256` to the beacon chain.

**Comment by djrtwo** [comment]
this is resolved via #227 
The beacon chain is to use keccak256 for now
