### ISSUE TITLE
Proposer index edge cases to test

### ISSUE THREAD

**Issue by protolambda** [ethereum/eth2.0-specs#1515]
So thanks to Prysm testnet, an under-tested proposer property was found: the proposer index and shuffling can both be correct, but if the active validators don't match regular indices there can still be a problem. And it only is off after the first inactive validator index in the system, so some tests could look like they test shuffling well (or indirectly as by rewards or otherwise), but just missed it.

TLDR: todo, add test cases for:
- `proposer index > len(active validators)` (already have proposals, but not this edge case)
- `proposer index > any slashed index` (already have slashings, but not this edge case).

Larger validator numbers move the proposer index to be more random and more likely to be bigger than those other numbers, while the current smaller validator sets in tests are generally only 512 validators. (and increasing that would increase the total test size by approx. the same factor).

**Comment by rauljordan** [comment]
This manifests itself a lot in the current testnet with many validators attesting over 10,000 times and without a single proposal:

**Comment by djrtwo** [comment]
closed via #1518
