### ISSUE TITLE
The amount of checking performed by the PoW chain contract

### ISSUE THREAD

**Issue by benjaminion** [ethereum/eth2.0-specs#152]
The spec says the following:

> The registration contract emits a log with the various arguments for consumption by the beacon chain. It does not do validation, pushing the registration logic to the beacon chain.

This is reflected in the proposed Vyper PoW chain contract that does no checking.

At a minimum it would be good to check that `msg.value==DEPOSIT_SIZE`. This avoids a least a couple of issues:

* If someone mistakenly sends a different value to the contract, their funds will be unrecoverable under the current scheme.
* I could call `deposit()` 16384 times with 0 value and junk data, and yet start the Beacon Chain without a single genuine, committed validator.

**Comment by vbuterin** [comment]
Our original rationale for this is that it adds more forward compatibility, for example later allowing top-up deposits or deposits of different sizes. That said, I see the safety argument too. I am honestly fine either way.

> I could call deposit() 16384 times with 0 value and junk data, and yet start the Beacon Chain without a single genuine, committed validator.

OK you are right this is a bug, and we should at the least wait for 16384 validators with 32 ETH as value.
