### ISSUE TITLE
Rename SECONDS_PER_DAY

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#1547]
The `SECONDS_PER_DAY` constant is only used to determine the period between the eth1 block that triggers eth2 genesis and the start of the first eth2 slot.

It is desirable to tweak this parameter when starting testnets but something feels wrong about setting `SECONDS_PER_DAY` to something other than it's title.

**Comment by djrtwo** [comment]
Suggestion on the name?... `MIN_GENESIS_WAIT_TIME` <- not quite right..

**Comment by protolambda** [comment]
Closed via #1557
