### ISSUE TITLE
Expose a constant that defines the genesis Fork

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#1548]
When running testnets it is desirable to set a wacky `Fork` version to avoid signature collisions when we go to mainnet.

Presently there's no way to express this in the [configs](https://github.com/ethereum/eth2.0-specs/tree/dev/configs), which is a little awkward for testnet interop.

If we could expose it as a "constant" then it would fit nicely into a config.

**Comment by djrtwo** [comment]
I'm in favor of adding `GENESIS_FORK_VERSION` instead of relying on default SSZ 0x0. This is certainly something we want to tune in testnets and other use cases
