### ISSUE TITLE
Forge aggregate attack

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#1570]
It's probably not a big deal though for the "naive" strategy, still, bringing up here to get feedback.

## Issue
If the attester reveal (i) their own unaggregated attestation at [Attesting](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/validator.md#attesting) and (ii) their [`aggregate_and_proof`](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/validator.md#broadcast-aggregate), the attacker can re-create a valid `aggregate_and_proof` by setting `aggregate_and_proof.aggregate` to any other aggregate that includes the aggregator's attestation.

The potential risk is that the attacker can do kind of dos attack on the global channel, and cause the honest aggregator has a bad reputation.

## Proposed solution

To avoid the forge attack, the aggregator `A1` can:
1. At [Attesting](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/validator.md#attesting) stage, `A1` choose **not** to broadcast their unaggregated (individual) attestation `attestation_1`.
2. `A1` only includes their unaggregated `attestation_1` in the `aggregate_and_proof` they created.

However, the chance that `attestation_1` gets included in the block will be decreased since the *other* aggregators will not involve `attestation_1` to their aggregate.

p.s. if we update the aggregator logic, it's related to https://github.com/ethereum/eth2.0-APIs/pull/15/

**Comment by djrtwo** [comment]
The proposed solution here creates up to num_aggregator non-aggregatable messages  per committee which would take up more attestation positions in each block. This would make it more costly to verify and reduce the optionality in a block proposer including missing attestations from previous slots. 

Thinking about how we might use subnet validation conditions to prevent this attack

**Comment by djrtwo** [comment]
Addressed in `v0.10.0` by adding an additional signature
