### ISSUE TITLE
Fork choice: justified_epoch <= finalized_epoch

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#1574]
In fork choice, I believe it's possible for `store.justified_checkpoint.epoch <= store.finalized_checkpoint.epoch`. As I understand it, this means that `filter_block_tree` will filter out all blocks.

Consider that we're syncing a fork and in the later `SLOTS_PER_EPOCH - SAFE_SLOTS_TO_UPDATE_JUSTIFIED` slots of the epoch. During this time we sync through several epochs, where each epoch justifies and finalizes the closest possible prior epochs (i.e., perfect validator participation).

As we call `on_block` we're delaying updating `store.current_justified_epoch` because we're in the later slots of the epoch. However, we _are_ updating `store.finalized_checkpoint`. It follows that we could now have a `store.finalized_epoch` that is from a block several epochs _later_ than `store.justified_epoch`.

**Comment by djrtwo** [comment]
closed via #1580
