### ISSUE TITLE
Version information unavailable for pyspec package at runtime and in package metadata.

### ISSUE THREAD

**Issue by gnattishness** [ethereum/eth2.0-specs#1596]
Although git tags are used to denote the spec version, this can be difficult (in general) to retrieve programmatically - especially if the installed package is no longer directly associated with a git repo.

Conventionally, python packages expose version info in metadata via the `version` parameter in `setuptools.setup`, and at runtime via a `<module>.__version__` attribute. This info is not currently available (e.g. a `pip freeze` shows `pyspec==0.0.0`)

It would be helpful for tools that may need to operate on/support multiple pyspec versions (with different behaviour depending on the version).

------

There are automated solutions available that save having to manually adjust the version strings e.g. https://github.com/pypa/setuptools_scm/ or https://github.com/warner/python-versioneer

I'm happy to provide a PR if there's interest.

**Comment by protolambda** [comment]
See PR #1584 for latest packaging efforts.

We have not fully decided on publishing it yet, and the name might still change, but it will at least be possible to install through a git link in a requirements file. Versioning and pypi is probably the best way to go for stable tooling however. Let me know if you have other suggestions, user feedback for this kind of thing is very useful.

Automation for versioning sounds great, but it may not fully match the spec versioning approach, which makes me hesitate there. Manually versioning, with a version check as part of `make check-dist` before uploading to pypi could work too. I will check with other ethereum python maintainers and see what they think.

**Comment by gnattishness** [comment]
Looks great!
Even being able to have a "`pip install`able" git dependency would be great.
I concur that PyPI is the best way to go in the longer term (`pip` can specify a version range for PyPI, but only a specific tag/commit/branch for git dependencies)

Immediate things that spring to mind re the PR:

- `setup()` isn't currently given a version parameter so the package metadata doesn't contain version info
- similarly an `eth2spec.__version__` attribute would be quite helpful to save the user from needing to read the package metadata at runtime (e.g. `pkg_resources.get_distribution('eth2spec').version`)
- It's also good practice to include a `pyproject.toml` to explicitly specify that you use setuptools: 
  ```
  [build-system]
  requires = ["setuptools>=34.4", "wheel"]
  build-backend = "setuptools.build_meta"
  ```
  pip>19.1 handles all this fine, so `pip install '.[test]'` is sufficient (though acknowledge pip#2195), or you could also build with the build-system agnostic [pep517](https://pypi.org/project/pep517/) tool.

I also have a personal preference for using [poetry](https://python-poetry.org/) for dependency management and package metadata, but isn't suitable here because you need to execute arbitrary python code at install-time  `setuptools`.

**Comment by gnattishness** [comment]
Please let me know if you'd prefer I comment on #1584 directly, and whether to keep this open or not.

**Comment by protolambda** [comment]
> `setup()`  isn't currently given a version parameter 

We can change that.

> similarly an `eth2spec.__version__`

It starts the whole discussion "where to put your version", and without duplication with the `setup.py`. And then we have the problem that this project that has releases that are not focused on the software, but rather the resources it was compiled from. And the most simple solution is to do exactly that, read it at runtime to fill in the `__version__`. [`setuptools` itself does it like that](https://github.com/pypa/setuptools/blob/master/setuptools/version.py). Do we really need it?

> `pyproject.toml`

Agree it's neat, but hesitant to introduce extra files into global scope of the specs repo. It's really just the regular `setuptools` setup, with some extra distutils commands. No exotic build system to reference.

> though acknowledge pip#2195)

Yes, commented in that issue a while ago. It was pulling in the complete test-data repository (multiple GB of data) into the build. Changed defaults to not have that output folder within the repo itself to avoid copy on install. Documented it in the pyspec readme.

Another note on versioning, is that I like to avoid tools like `bumpversion`, when there are strict versioning decisions outside of the scope of code. The spec is like that, so I would rather modify one single isolated place manually on release. And also avoid automated git tag pushes, that could end badly.

I'm thinking reading the version from a `VERSION` file may be the cleanest, as it's nice for the spec itself as well, and keeps the `setup.py` unchanged during regular updates. What do you think @gnattishness ?

**Comment by gnattishness** [comment]
> pyproject.toml


> `__version__` ... Do we really need it?

Certainly not a requirement (more a "nice-to-have") - a convenient and reasonably common convention/pseudo-standard.
It's also worth noting that the `pkg_resources` or `importlib.metadata` solutions (e.g. used by setuptools) require the package name, which may be different to the module name. 

User's code can definitely load from package metadata, but defining a `__version__` gives the library the choice of how it wants to expose the version info.

>  reading the version from a VERSION file

I don't think I can comment on the project's decision making process. There's tradeoffs where you maintain explicit control over the VERSION file, but can risk updating a tag but forgetting to update the `VERSION` and vice-versa. The setup.py could easily read from a `VERSION` file, and a __version__ attribute load from the metadata or the file. You would need to ensure that the non-python `VERSION` file is included in the package (e.g. via `MANIFEST.in`)

Other options for maintaining a single version: https://packaging.python.org/guides/single-sourcing-package-version/ Pip uses an [alternative](https://github.com/pypa/pip/blob/e9f461241032dbd540fb6271f1dbbb29a6a0db82/setup.py#L19) that is the opposite of setuptools - setup.py reads the version from the __init__.py

**Comment by djrtwo** [comment]
Version was added internal to the repo and is available in latest releases
