### ISSUE TITLE
Storage of SignedBeaconBlock

### ISSUE THREAD

**Issue by sgryphon** [ethereum/eth2.0-specs#1641]
The P2P specification lists validations before forwarding signed_beacon_block, which implies you will forward it, but doesn't have a requirement to. 

Similarly, the request/response section implies nodes should record signed_beacon_block in order to respond with it, "if they have it". 

However, in phase 0 fork choice on_block only signed_block.message, the BeaconBlock is stored. 

Note: In the current dev branch, the definition of Store has been changed to store BeaconBlockHeader, instead of BeaconBlock, although the change has not yet been propagated to all functions.

The specification does talk about messages without parents or in the future being delayed, again implying storage. 

Should there be an explicit mention, even if just something like "clients SHOULD keep a record of messages received, including signature", if not something formal like Store?

**EDIT** for clarity.

The relevant requirements in the 0.10.1 spec are:

> Clients MUST support requesting blocks since the start of the weak subjectivity period and up to the given head_block_root.
> Clients MUST support head_block_root values since the latest finalized epoch.
> Clients MUST respond with at least one block, if they have it and it exists in the range. Clients MAY limit the number of blocks in the response.

The current dev spec removes the duplication:

> Clients MUST support requesting blocks since the start of the weak subjectivity period and up to the given head_block_root.
> Clients MUST respond with at least one block, if they have it and it exists in the range. Clients MAY limit the number of blocks in the response.

In spec 0.9.2 and earlier, the signature was in BeaconBlock, and fork choice Store kept a record of all BeaconBlocks. This means the "if they have it" criteria would apply for all blocks you have in Store.

However, from 0.9.3 onwards, SignedBeaconBlock was introduced, and not explicitly stored, so clients would support the request, but simply send an empty response (they have no signed blocks stored anywhere).

**Comment by djrtwo** [comment]
The requirement of the fork choice is only validated the blocks/headers so that's why the naive spec stores them there, whereas the network spec needs signed blocks to be passed around for others to validate.

There are statements like
```
Clients MUST support requesting blocks since the latest finalized epoch.
```

I suppose we can change this to "signed blocks" to be more explicit

**Comment by sgryphon** [comment]
That's probably fair enough; I was concentrating on the "if they have it and it exists in the range" exception, and interpreting the "MUST support requesting" as simply sure, I'll accept your request, but because I never stored any blocks I don't have them and so support your request by responding with nothing. (Before the signing root change, the Store contained full blocks, including signatures, so the clients would have the blocks.)

But re-reading the criteria of "up to the given head_block_root", it is referring to your own head, which is basically the same thing, i.e. you must have seen blocks up you your head.

Changing it to explicit statement like "Clients MUST keep a record of signed blocks seen since the weak subjectivity period and MUST support requests for them up to the given head_block_root." would remove any ambiguity about the "if they have it" as an escape clause.

But not keeping blocks would probably be a silly thing to do anyway, so probably doesn't matter if you just want to close the issue.

**Comment by mcdee** [comment]
The latter part of "Clients MUST keep a record of signed blocks seen since the weak subjectivity period and MUST support requests for them up to the given head_block_root." is not desirable (assuming you mean "serve" for "support") as it opens the way for bad implementations (or just greedy peers) to be able to continually request blocks from you and you be obliged to return them.

**Comment by sgryphon** [comment]
> to be able to continually request blocks from you and you be obliged to return them

I should probably update the issue with the full text, so there is no confusion.

The current spec already says "MUST support requests", so that part hasn't changed.

The next line is "Clients MUST respond with at least one block, if they have it and it exists in the range. Clients MAY limit the number of blocks in the response."

Prior to the hash_signing_root change, the full messages were recorded in Store, so if a node had seen blocks, they would "have it" and must respond, with at least one block.

Since the change, only beacon_block is stored (not signed_beacon_block), and the upcoming dev changes cut this down to beacon_block_header.

Therefore, a client could throw away all blocks, and rely in the "if they have it" as an escape clause to respond with nothing, instead of a minimum of one block.

Adding in the "MUST keep a record of signed blocks" is simply re-instating the requirement to record them (as they are no longer in Store), which from the other discussions sounds like what the intention is.

**Comment by sgryphon** [comment]
I put up a pull request for consideration, especially seeing as @mcdee seems to be worried about the requirement that clients MUST store and respond with blocks, when I think that was what the intention is (and is what the spec required in 0.9.2 and earlier),

**Comment by djrtwo** [comment]
>  as it opens the way for bad implementations (or just greedy peers) to be able to continually request blocks from you and you be obliged to return them.

"Support" here means that you have the ability to serve. A client is never required to "serve" due to local bandwidth constraints, peer abuse, etc. A client that connects to a peer that won't serve them should drop and find better peers.

**Comment by djrtwo** [comment]
> Prior to the hash_signing_root change, the full messages were recorded in Store, so if a node had seen blocks, they would "have it" and must respond, with at least one block.

The "Store" is just an example of how the functionality of the fork choice _can_ be incredibly naively implemented. The "Store" is not prescriptive. The validation conditions on `on_block`, `on_attestation`, and the results of `get_head` are prescriptive.

I wouldn't get too hung up on the mechanics here in fork choice

> Clients MUST support requesting blocks since the start of the weak subjectivity period and up to the given `head_block_root`.

This statement dictates that a client must have access to SignedBeaconBlocks since weak subjectivity. I'm not certain we need to state explicitly to store them.

**Comment by sgryphon** [comment]
Clarification merged, so closing issue.
