### ISSUE TITLE
Latest Dev branch - partial change of Store to BeaconBlockHeader

### ISSUE THREAD

**Issue by sgryphon** [ethereum/eth2.0-specs#1642]
In the latest Dev branch, there is a change from 0.10.1, in Store to keep BeaconBlockHeader instead of BeaconBlock, which is used in get_forkchoice_store, however not all references have been updated.

First, I suggest changing the field name to block_headers, to be consistent with the data type, and make it easier to spot errors (when storing or retrieving a value).

Some of the reference that have not been updated yet include:

* filter_block_tree / get_filtered_block_tree, the logic works, but it is now retrieving Dict[Root, BeaconBlockHeader]; also update variable names to block_header

* on_block, attempts to store the block, but should instead calculate hash_tree_root of the body and store the header

* also, in general update names in routines such as get_ancestor, e.g. change first line to block_header = store.block_headers[root]

**Comment by djrtwo** [comment]
In practice, a client needs access to the blocks. A header and block map to the same id (root) so in practice a client can use headers in some cases, or just roots, or full blocks.

@protolambda made the change here in fork choice, I'm not 100% sure why. Probably because the full block was not needed so he wanted to reduce testing overhead. Maybe he can give some insight. 

Agreed names should be changed if we keep header around. My intuition is to just keep it as `BeaconBlock`.

> on_block, attempts to store the block, but should instead calculate hash_tree_root of the body and store the header

Note that `hash_tree_root(block) == hash_tree_root(block_header)` so this storage lookup is actually fine (although naming is off).

**Comment by sgryphon** [comment]
> > on_block, attempts to store the block, but should instead calculate hash_tree_root of the body and store the header
> 
> Note that `hash_tree_root(block) == hash_tree_root(block_header)` so this storage lookup is actually fine (although naming is off).

I was more talking about the discrepancy between:

```
class Store(object):
    blocks: Dict[Root, BeaconBlockHeader] 
```

and:

```
def on_block(store: Store, signed_block: SignedBeaconBlock) -> None:
    block = signed_block.message
    store.blocks[hash_tree_root(block)] = block
```

The hash_tree_root(block) would be correct, but in a strongly typed language trying to stick a BeaconBlock in a dictionary of BeaconBlockHeader isn't going to work.

So, hash the body first, to create the header, then insert.

```
    block = signed_block.message
    header = BeaconBlockHeader(slot=block.slot, parent_root=block.parent_root, state_root=block.state_root, body_root=hash_tree_root(block.body))
    store.blocks[hash_tree_root(block)] = header
```

And yes, for the insert hash_tree_root(block) and hash_tree_root(header) would be the same.

This probably isn't an issue for a weakly typed language, as the hash will always calculate the same, and I don't think we ever access anything in the body from the store (probably why it was removed).

**Comment by djrtwo** [comment]
The movement to `BeaconBlockHeader` might have been in error, and if it wasn't, agreed that all references, assignments, names, etc should be changed to reflect `header`. 

That said, in the spirit of keeping changes minimal as we approach Phase 0 mainnet, I suggest we change it back to `BeaconBlock`.

**Comment by protolambda** [comment]
The goal with fork-choice was to encapsulate it, and hide other spec components from it as much as possible. So signatures outside of fork-choice, and block contents as well. But that said, right now I think it is preferable to minimize changes for clients, and reverting sounds ok.

**Comment by sgryphon** [comment]
Keep the spec stable sounds reasonable.

In practice, an implementation could always see that the spec never users anything outside the header, and so only load the header part for processing (caching the body root, or lazy loading it, or whatever). 

There are lots of places where the spec (defining the required logic) does things inefficiently, and an implementation may optimise; so long as the eventual logic is the same that's fine.

Closing the issue.
