### ISSUE TITLE
Inconsistency in BeaconBlockHeader.StateRoot for skipped slots vs block slots

### ISSUE THREAD

**Issue by sgryphon** [ethereum/eth2.0-specs#1644]
BeaconState includes latest_block_header, which includes a recursive state_root.

Normally the recursive field has to be zeroed, to calculate the state_root. During block processing the value is temporarily inserted, to calculate block_root, but is then zeroed again during block processing.

However, where there is skipped slot (no block), the temporarily inserted value is not so temporary, as there is no block to zero it out, and it ends up in the calculated hash, e.g.

* State { slot=5 header={ slot=5 parent=0xa4a4 state=0x0000 body=0xb5b5 }} => state_root 0xc5c5 => Block { slot=5 parent=parent=0xa4a4 state=0xc5c5 body=0xb5b5 } => block_root 0xa5a5
* State { slot=6 header={ slot=6 parent=0xa5a5 state=0x0000 body=0xb6b6 }} => state_root 0xc6c6 => Block { slot=5 parent=parent=0xa5a5 state=0xc6c6 body=0xb6b6 } => block_root 0xa6a6
* State { slot=7 header={ slot=6 parent=0xa5a5 state=0xc6c6 body=0xb6b6 }} => state_root 0x1234, skipped block, but calculated state_root goes into history
* State { slot=8 header={ slot=6 parent=0xa5a5 state=0xc6c6 body=0xb6b6 }} => state_root 0x5678, second skipped block
* State { slot=9 header={ slot=9 parent=0xa6a6 state=0x0000 body=0xb9b9 }} => state_root 0xc9c9 => Block { slot=9 parent=parent=0xa6a6 state=0xc9c9 body=0xb9b9 } => block_root 0xa9a9

Note that for skipped slots state.slot increases, but latest_block_header.slot remains (correctly) at the previous block, as does body.

Slots 7, 8, and 9 are all processed at the same time, when block 9 is received.

At slot 7, the state_root is temporarily calculated and cached in the latest block header, and the values inserted into the history for state roots and block roots, but because there is no block for 7 or 8 the value is not cleared, so that means when processing the rest of the slots the header now contains the value.

This is inconsistent as the header for slots with a block has zeros, but for skipped slots has a value.

I suggest keeping the header consistent, which means not caching the previous state root in the state header (although you still need to calculate it for verification). (This removes the need for the field; see my other suggestion)

Note that when calculating previous block root for slot 8, and 9, you still need to hash the root of state 6, i.e. inside the loop would need a lookup of the past state corresponding to latest_block_slot. Rather than a lookup, this could be calculated before the slot processing loop and passed in as a parameter, a similar outcome to caching semi-temporarily it in the header.

**Comment by djrtwo** [comment]
This is purposeful. A slot, when processing, should have access to the latest block header in the chain prior to the slot in question. Embedding the state root here gives us access to this latest header for arbitrary skip slots in the future.

This also gives maximal simplicity to using components of the state transition in isolated ways (e.g. transitioning skipped slots when there is no new block to process) and keeps the function signature dependent only on the pre-state (and potentially a new block).

**Comment by sgryphon** [comment]
Note that state for slot 7 and 8, the skipped states, aren't actually stored anywhere, in the spec. (Store only contains states that correspond to blocks / block roots).

They are only referenced inside the ProcessSlots loop, although they do have an impact -- their hashes go into state_roots history.

I don't think it would be an issue to simply calculate pre-state, before the loop and pass as a parameter afterwards, but it's not going to make much difference anyway, just a little quirk to be aware of.

**Comment by JustinDrake** [comment]
@sgryphon I'm assuming @djrtwo addressed this issue. Please reopen if you feel otherwise :)
