### ISSUE TITLE
Division by zero in `get_attestation_deltas` or wrong min value of `get_total_balance`

### ISSUE THREAD

**Issue by MrChico** [ethereum/eth2.0-specs#1663]
A comment in `get_total_balance` reads that the function returns a minimum of 1 Gwei to avoid divisions by zero.

But since https://github.com/ethereum/eth2.0-specs/pull/1635, `total_balance` must be at least `EFFECTIVE_BALANCE_INCREMENT` in order to avoid a division by zero  in [this line](https://github.com/ethereum/eth2.0-specs/blame/dev/specs/phase0/beacon-chain.md#L1369) of `get_attestation_deltas`:
```
rewards[index] = reward_numerator // (total_balance // increment)
```

It seems that either the minimum of `total_balance` should be raised, or the reward calculation be adjusted to avoid this edge case.

**Comment by MrChico** [comment]
In a similar vein, if a slashed validators effective balance drops under EFFECTIVE_BALANCE_INCREMENT, it seems they will not suffer the anti-correlation penalty applied in `process_slashings`, as [the expression](https://github.com/ethereum/eth2.0-specs/blame/dev/specs/phase0/beacon-chain.md#L1441):
```
            penalty_numerator = validator.effective_balance // increment * min(sum(state.slashings) * 3, total_balance)
```
will evaluate to 0.

**Comment by djrtwo** [comment]
Right. The only way their effective balance could drop below `EFFECTIVE_BALANCE_INCREMENT` is if it went to 0 (because effective balance is only changed on that increment) which would give them zero penalty regardless.

That said, maybe `penalty_numerator` here should be in terms of `balance` rather than `effective_balance`

**Comment by djrtwo** [comment]
@MrChico I addressed the first issue here #1664 

Eating lunch, thinking about the second

**Comment by MrChico** [comment]
Ah, yes, I see now that the second concern is not an issue.
It seems that all other reward calculations are being weighted by total_balances and the validators effective balance, so I don't see why this one should be different?

**Comment by djrtwo** [comment]
Yeah, no need for this to be different.

Just an orthogonal thought, and one that I don't think I agree with.
