### ISSUE TITLE
Forgotten Password or Private Key Partial Solution

### ISSUE THREAD

**Issue by kclick91** [ethereum/eth2.0-specs#168]
On creation of a new account, an optional secondary account without the need of a key can be created with which a smart contract is attached. In the case of a forgotten password or lost key, the contract can restrict the usage of the secondary account so much that it would not be worth the trouble of using if it is not yours. An example would be to list two accounts that ether can be sent to and a very low maximum usage per week.  This is to keep funds from being completely lost and all this can only be determined on creation of the account and not in the aftermath including whether there is a secondary account or not. To keep anybody from transferring the funds of other accounts into other secondary accounts, if someone is in possession of their own private key and password, they can return those funds back to the primary account and send those funds all in one easy transaction.

**Comment by vbuterin** [comment]
I think you can implement all of this logic in a smart contract; if you want to stake the coins, the logic would live in the contract at the withdrawal address.

**Comment by kclick91** [comment]
If the transaction date and amount is yet to be determined for withdrawing funds from one account and the private key is inaccessible there can be a smart contract set before that key is lost that allows for withdrawal at that undetermined time and with that undetermined amount to another “regular” account? With solidity?

**Comment by vbuterin** [comment]
The point is that the withdrawal address is fixed when you deposit, so any logic around where the funds go when you withdraw them would go into the smart contract at the withdrawal address.

**Comment by kclick91** [comment]
Yea the smart contract is with the withdrawal address. I guess my question is if there is support for having this type of withdrawal address?

**Comment by kclick91** [comment]
Because you would not want to send coins to the smart contract address unless you have to in this situation.

**Comment by vbuterin** [comment]
> I guess my question is if there is support for having this type of withdrawal address?

I don't see why not. I think we are expecting all addresses in the shard chains to be contracts.

**Comment by kclick91** [comment]
You would need to have 32 eth to have tokens in a smart contract on that chain.

**Comment by kclick91** [comment]
Thanks for commenting vbuterin. I think it would be an idea to allow sending ether to a single smart contract set up in the beginning from a deposit account at any time without a key. I will close the issue.
