### ISSUE TITLE
Gossip snappy format

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#1727]
@AgeManning brought it to our attention that gossip `ssz_snappy` does not specify which snappy format to use -- block or frames. The intended spec is block format for gossip and frames format for RPC.

Gossip uses `Messages` and propagates them through the network. Streaming as multiple messages would fragment the single piece of data into multiple gossip messages which would not be the intended behavior

If instead stream framing was inside the gossipsub `Message`, this would just induce a small amount of overhead due to the frames container at little gain due to gossip messages being much smaller than the max we might expect on RPC.

**Comment by protolambda** [comment]
See #1729
