### ISSUE TITLE
DepositContract: support EIP-165

### ISSUE THREAD

**Issue by axic** [ethereum/eth2.0-specs#1728]
[EIP-165](https://eips.ethereum.org/EIPS/eip-165) provides a way for inspecting what interfaces contracts support.

Its use is picking up across contracts, but to name one big user, ENS, which has been using it since its inception. I also expect more users since Solidity's next release will contain some language level features to facilitate it more.

Considering there may be a "deposit contract proxy" which implements signature validation, there may be even more usefulness for such a feature.

The main benefit I can see is promoting the use of standard interfaces, while it puts a really small burden on the contract. The only addition is a new function, `supportsInterface(bytes4 interfaceId) -> bool`, which returns true in two cases only:
a) `interfaceId` equals to function selector of `supportsInterface`
b) `interfaceId` equals to the function selector of `deposit`

(We may need to consider whether the getter functions (`get_deposit_root` and `get_deposit_count`) are part of the public interface or not, if they are, the interfaceId of the deposit contract would be the xor of the three selectors. I considered them not part since the [specification only lists `deposit`](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/deposit-contract.md).)

**Comment by djrtwo** [comment]
eip165 support was added to the solidity contract! closing
