### ISSUE TITLE
missing check on one case of surrounding votes?

### ISSUE THREAD

**Issue by lucianyao** [ethereum/eth2.0-specs#1733]
at version 676e216,  in the method is_slashable_attestation_data(), we have:

`# Surround vote
        (data_1.source.epoch < data_2.source.epoch and data_2.target.epoch < data_1.target.epoch)`

Did we miss that:
`(data_2.source.epoch < data_1.source.epoch and data_1.target.epoch < data_2.target.epoch)`

**Comment by hwwhww** [comment]
The block proposer (i.e., whistleblower) is responsible for ordering the `data_1` and `data_2` correctly so that the `AttesterSlashing` is valid with the protocol. So we only need to check one format in `is_slashable_attestation_data`.
