### ISSUE TITLE
It would be great if we could clarify the types of the constants in the beacon chain "Misc" and other parts

### ISSUE THREAD

**Issue by lucianyao** [ethereum/eth2.0-specs#1750]
in the beacon chain "Misc", "Rewards and penalties", etc, there are no type stated for the constants,  I wonder if we could define the type for each constant, so as to avoid data conversion loss, though which looks not going to happen...

btw, in language like "Rust", the type of a vector index and count has to be  "usize", which is u64 on 64 bits cpu, u32 on 32bits cpu. In my mind regarding java, it has to be an integer, which is always 32-bits.

**Comment by hwwhww** [comment]
#1746 would clarify the constants types.
Also, the overflow issue has been discussed in #1701.
