### ISSUE TITLE
Eth1 follow distance not respected

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#1764]
@mpetrunic has noted that `ETH1_FOLLOW_DISTANCE` is not being respected during genesis.

His observation seems valid to me, we should look into this and ensure it is respected.

**Comment by djrtwo** [comment]
Is this the case when `ETH1_FOLLOW_DISTANCE * SECONDS_PER_ETH1_BLOCK` is greater than `2*MIN_GENESIS_TIME`?

**Comment by djrtwo** [comment]
If so, seems like should define min_vote_time as the current eth1_data in the state

**Comment by hwwhww** [comment]
@djrtwo where is `2 * MIN_GENESIS_TIME` come from?

**Comment by paulhauner** [comment]
Oh god, this is on the wrong repo. I'm so sorry!
