### ISSUE TITLE
DepositContract:deposit function requires withdrawal_credentials to be dynamic bytes instead of bytes32.

### ISSUE THREAD

**Issue by JuliusBrain** [ethereum/eth2.0-specs#1772]
We can see on line 6 of the contract code https://github.com/ethereum/eth2.0-specs/blob/dev/deposit_contract/contracts/validator_registration.vy#L6

withdrawal_credentials is only taking 32 bytes. Same thing inside an event definition but inside `deposit` function arguments we see a dynamic `bytes` array. https://github.com/ethereum/eth2.0-specs/blob/dev/deposit_contract/contracts/validator_registration.vy#L68
Is this deliberate? Couldn't we use `bytes32` type there instead of dynamic `bytes` array?

**Comment by hwwhww** [comment]
Hi @JuliusBrain 
Good question! Backgroud story: if we use `bytes32`:
1. If input `len(withdrawal_credentials) > 32`, it's clear that EVM would throw an error.
2. However, if `len(withdrawal_credentials) < 32`, EVM would pad zeroes and it's still a valid input. Although it would throw other error from the on chain Merkle tree validation with `deposit_data_root`.

Back to 2019, we didn't include `deposit_data_root` validation checks on chain. So we parameterized `WITHDRAWAL_CREDENTIALS_LENGTH` to do `assert len(withdrawal_credentials) == WITHDRAWAL_CREDENTIALS_LENGTH` check clearly.

I'd say for the spec stability, it's fine to keep this check unless we want to fix some major bug then we can refactor it together.

**Comment by djrtwo** [comment]
Deposit contract is frozen for phase 0! closing this issue
