### ISSUE TITLE
Spec clarification: attnet ENR field updates

### ISSUE THREAD

**Issue by jrhea** [ethereum/eth2.0-specs#1774]
Noticing high seq no's in the topaz testnet due to frequent `attnets` field updates.  I believe this is due to confusion regarding whether or not the `attnets` field in the ENR should be updated for only persistent committee changes.  

I suggested that a clarification should be made in the spec.  I believe @djrtwo is considering something like:

> Note: Short lived beacon committee assignments should not translate into updating attnets field in the ENR

CC: @nisdas

**Comment by hwwhww** [comment]
closing in favor of #1775
