### ISSUE TITLE
is the get_total_active_balance() at current epoch designed even handling previous justification? 

### ISSUE THREAD

**Issue by lucianyao** [ethereum/eth2.0-specs#1778]
at version 4b4fc32,  beacon_chain, in method`process_justification_and_finalization()`, there is:
`
if get_attesting_balance(state, matching_target_attestations) * 3 >= get_total_active_balance(state) * 2:`

the `get_total_active_balance` is not from previous epoch, I wonder if it is designed on purpose?
Maybe I don't understand it correctly but I am still wondering if it would be wrong in these cases:

Case 1: some validators exit at current epoch:
suppose we have 2 validators, A and B, each with 32 eth, both were active validators, and they voted to previous epoch, but A, B voted at two branches. And  only B exited at current epoch.
                       
A--votes--->state at prev epoch-------state at current epoch(b exited)--------> we are here 
B                                                     
|
votes
|
+---->another root at prev epoch

then:
total active balance:32 eth(b exited so her stake is not counted) 
attesting balance: 32 eth(A's stake) 
and then root at prev epoch is justified

But the root at prev epoch is not supposed to be justified because the  it only got 1/2 votes?

Case 2: some validators become active at current epoch
even if the root at previous epoch is supposed to be justified, it will never  be justified because the total balance were diluted by new validators at current epoch.
Even it could turn a justification from true to false, though it is not allowed and our spec doesn't handle it.

**Comment by djrtwo** [comment]
The change in the validator set is bounded slot to slot so the marginal difference (except in extreme cases of small amounts of validators) is very low and translates into a only a small marginal degradation in the max accountable safety of that epoch.

essentially this slightly affects the max security but in practice is so small that this approximation is fine and tracking historic total balances (in our calculation) was not worth added consensus complexity
