### ISSUE TITLE
Replace PERSISTENT_COMMITTEE_PERIOD with SHARD_COMMITTEE_PERIOD

### ISSUE THREAD

**Issue by mkalinin** [ethereum/eth2.0-specs#1779]
### Issue
Phase 0 spec of the beacon chain has `PERSISTENT_COMMITTEE_PERIOD = 2048` constant which is used in `process_voluntary_exit`. It should be replaced with `SHARD_COMMITTEE_PERIOD = 256` according to the recent version of Phase 1 spec.

**Comment by hwwhww** [comment]
closing via #1783
