### ISSUE TITLE
[BUG_BOUNTY] Recovery mechanisms from multiple-proposal-flood-attack need to be specified in the spec

### ISSUE THREAD

**Issue by kladkogex** [ethereum/eth2.0-specs#1786]
_High-level description of the bug [1 sentence]_

A proposer can attempt to crash the network by submitting multiple concurrent proposals, and losing 32 ETH.  Client behavior in case of proposal-flood-attack needs to be specified/discussed.

_Attack scenario_

In ETH2 a proposer is supposed to create a unique proposal.  In case of at least two conflicting
proposals, the proposer will be slashed (and will lose at least 32 ETH).

The spec needs to address the case where the proposer decides to lose 32 ETH and floods the network with multiple (say 100) conflicting blocks.

The goal of the malicious proposer will then be to :

- segment the network into 100 subgroups of nodes 
- present a separate proposal P to each subgroup
-  make each subgroup build on a different proposal P, so there are total of 100 very weak and almost equal branches in the network

Winning branch selection from such a split state may take a long time. If the attacker can make the network stall, say, for one hour, the attacker can short ETH  and easily recover ETH lost in the slashing.

Note that in addition to the malicious proposer node there may be multiple malicious injection nodes in the network, who's job will be to inject and disseminate malicious proposals.  The injection nodes will not be slashed, since communication of malicious proposals is not a slashable event. The attacker could use machine learning and simulations to inject blocks in an optimal way, where the goal is to stall the network.

_Impact: Describe the effect this may have in a production setting [1 to 2 sentences]_

The chain may stall for an extended period of time,  leading to a significant financial benefit for the attacker.

_Components: Point to the files, functions, and/or specific line numbers where the bug occurs [1 to 2 sentences]_

I reviewed the source code of the current ETH clients and was not able to identify active recovery mechanisms against the multiple-proposals-flood attack. The spec also does not seem to discuss this.

_Reproduction: If used any sort of tools/simulations to find the bug, describe in detail how to reproduce the buggy behavior. Showcasing the bug using the python spec and associated test infrastructure found in the spec repo is preferred!_

1. Start the chain.
2. Make a proposer generate 100 conflicting proposals and inject them in different places in the network.
3. Observer the network stalling.

If some type of protection exist, it needs to be documented. So it may be either a documentation bug or a more fundamental spec issue.

Fix: Description of suggested fix if available

The clients need mechanisms implemented not only to slash the block proposer post factum, but actively recover from the attack.

**Comment by JustinDrake** [comment]
> there are total of 100 very weak and almost equal branches in the network

This would be a fleeting unstable equilibrium handled by [the LMD GHOST fork choice](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/fork-choice.md#get_head). Thanks to the honesty assumption there will quickly be (likely within a few slots, and extremely likely within one epoch) at least one honest block proposer who submits a single block proposal on one of the weak and almost equal branches in the network. That becomes a tipping point where attestations pile on this one honest block proposal and the weak forks collapse into a single strong chain.

> If some type of protection exist, it needs to be documented.

Clients need to run their local fork choice rule when they attest :) This is documented in the [validator document](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/validator.md#attestation-data).

**Comment by kladkogex** [comment]
> This would be a fleeting unstable equilibrium handled by the LMD GHOST fork choice. Thanks to the honesty assumption there will quickly be (likely within a few slots, and extremely likely within one epoch) at least one honest block proposer who submits a single block proposal on one of the weak and almost equal branches in the network. 

I do not have a feeling that it is so simple.  Each honest block proposer will have its view of the network. These local views will be in contradiction.

Let the multiple blocks from the malicious proposer be X1, X2, X3 etc

Then even if the  first honest guy tips into

X1->A

Then another honest guy may not be able to build on this branch since its view will be 

X2->,  so 

he will not be able to switch to X1->A->B, since it assumes him replacing X2 to X1 in his established view.

I hope you understand what I mean ... The local view of each honest proposer will be DIFFERENT and CONTRADICTORY.   The software assumes that there are no malicious block duplicates.

Or what does it assume or is supposed to assume?

**Comment by JustinDrake** [comment]
> he will not be able to switch to X1->A->B, since it assumes him replacing X2 to X1 in his established view

If by "validator view" here you mean the chain whose tip is [`get_head`](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/fork-choice.md#get_head) then it is possible for clients to change to a view inconsistent with a previously-held view. For example, if a validator's view is currently Genesis->X2 it is possible to replace that view with the "contradictory" view Genesis->X1->A->B.

> The local view of each honest proposer will be DIFFERENT and CONTRADICTORY

For me a "validator view" is the set of blocks and attestations that validator have received. Validator views are by nature subjective—them being different is not unexpected :) It is also not unexpected that `get_head` be contradictory across validators.

**Comment by kladkogex** [comment]
Good point!

IMO for every complex system an experiment can be more useful than theory.

We, at SKALE are looking forward to ETH foundation announcing an ETH2 incentivized adversarial test net.  We will definitely participate :)

Then we can tinker with different types of attacks and hopefully improve security :)

**Comment by JustinDrake** [comment]
Awesome. Closing this one for now. Keep poking at it.
