### ISSUE TITLE
bitfield_bytes(bits) should return chunks

### ISSUE THREAD

**Issue by booleanfunction** [ethereum/eth2.0-specs#1787]
The [simple-serialise](https://github.com/ethereum/eth2.0-specs/blob/dev/ssz/simple-serialize.md)  (Merkleisation section) reads:

> bitfield_bytes(bits): return the bits of the bitlist or bitvector, packed in bytes, aligned to the start. Length-delimiting bit for bitlists is excluded.

However when this function is called for merkleisation of bitvectors or bitlists, the output expected from `bitfield_bytes` is `BYTES_PER_CHUNK`-byte chunks, as indicated by the specification of `merkleize`, generally, 

> `merkleize(chunks, limit=None)`

and then the specific definition for bitvectors or bitlists:

> `merkleize(bitfield_bytes(value), limit=chunk_count(type))` if `value` is a bitvector.
> `mix_in_length(merkleize(bitfield_bytes(value), limit=chunk_count(type)), len(value))` if `value` is a bitlist.

**Comment by hwwhww** [comment]
Thanks for the report!

I suppose the spec is misleading but the implementations are correct. /cc @protolambda

Ideally, maybe rename `bitfield_bytes` to `pack_bits` would be more clear.

> `pack(value)`: given ordered objects of the same basic type, serialize them, pack them into `BYTES_PER_CHUNK`-byte chunks, right-pad the last chunk with zero bytes, and return the chunks.
> `pack_bits(bits)`: Given the `bits` of bitlist or bitvector, get `bitfield_bytes` by packing them in bytes and aligning to the start. Length-delimiting bit for bitlists is excluded. And them pack `bitfield_bytes` into `BYTES_PER_CHUNK`-byte chunks, right-pad the last chunk with zero bytes, and return the chunks.


> `merkleize(pack_bits(value), limit=chunk_count(type))` if `value` is a bitvector.
> `mix_in_length(merkleize(pack_bits(value), limit=chunk_count(type)), len(value))` if `value` is a bitlist.

**Comment by protolambda** [comment]
Closing this, I think this is solved in #1806
