### ISSUE TITLE
Conflicting definitions of BeaconBlock

### ISSUE THREAD

**Issue by franck44** [ethereum/eth2.0-specs#1788]
According to [this repo](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#beaconblock), a beaconBlock is defined 

```
class BeaconBlock(Container):
    slot: Slot
    proposer_index: ValidatorIndex
    parent_root: Root
    state_root: Root
    body: BeaconBlockBody
```

However, [this note](https://notes.ethereum.org/@djrtwo/Bkn3zpwxB?type=view\#Beacon-blocks) seems to omit the `proposer_index` field:
```
class BeaconBlock(Container):
    slot: Slot
    parent_root: Root
    state_root: Root
    body: BeaconBlockBody
```

Any idea which definition is the correct one?

**Comment by franck44** [comment]
Forgot to mention, but the `BeaconBlockBody` does not seem to contain `proposer_index`, so it is not part of the second definition.

**Comment by hwwhww** [comment]
@franck44 Hi!
This spec repo [`dev`](https://github.com/ethereum/eth2.0-specs/tree/dev) branch is the latest development branch. And the [`master`](https://github.com/ethereum/eth2.0-specs/tree/master) branch is the latest release branch (currently v0.11.2). That note is for v0.10.0, so something is outdated now.

**Comment by franck44** [comment]
Thanks for clarifying @hwwhww 
So `proposer_index` is a field in `BeaconBlock`.
Unfortunately when I look at [this repo](https://github.com/ethereum/eth2.0-specs/tree/master) the version number is not apparent to me.

**Comment by hwwhww** [comment]
@franck44 
correct, we have `proposer_index` in `BeaconBlock` since https://github.com/ethereum/eth2.0-specs/pull/1626

> Unfortunately when I look at this repo the version number is not apparent to me.

Good point, I added #1790 to mitigate this issue. Thanks!

**Comment by franck44** [comment]
@hwwhww A nice badge with the version number may help :-)
