### ISSUE TITLE
Missing assert in state_transition?

### ISSUE THREAD

**Issue by franck44** [ethereum/eth2.0-specs#1789]
According to [this repo](https://github.com/ethereum/eth2.0-specs/blob/master/specs/phase0/beacon-chain.md#beacon-chain-state-transition-function) the `state_transition` function is defined as:
```
def state_transition(state: BeaconState, signed_block: SignedBeaconBlock, validate_result: bool=True) -> BeaconState:
    block = signed_block.message
    # Process slots (including those with no blocks) since block
    process_slots(state, block.slot)
    ...
```
and `process_slots` has a precondition (assert statement) as follows:
```
def process_slots(state: BeaconState, slot: Slot) -> None:
    assert state.slot <= slot
    while state.slot < slot:
        ...
```

To make sure the pre-condition of `process_slots` is not violated, we may have to add a pre-condition in the `state_transition` function as follows:
```
def state_transition(state: BeaconState, signed_block: SignedBeaconBlock, validate_result: bool=True) -> BeaconState:
    assert(state.slot <= block.slot)
```

**Comment by JustinDrake** [comment]
I don't understand. The function `state_transition` calls `process_slots(state, block.slot)` which itself has `assert state.slot <= slot` which is equivalent to `assert state.slot <= block.slot`.

**Comment by franck44** [comment]
@JustinDrake 

> which is equivalent to assert state.slot <= block.slot.

The details are probably in what equivalent means.
My understanding is the following (and If I am wrong, please correct me):

1. either the assert statements are used only at runtime, and when they are violated the program ends (possibly with an exception). 
2. the assert statements are logical conditions that should never be violated at runtime.

In the previous case (`assert state.slot <= slot`) it looks like option 2 applies: because this is the first statement in the body of `process_slot` it is somehow a _pre-condition_ that should hold true before we run `process_slot`. In that case, because `state_transition` does not enforce this condition, it can be violated by calling `state_transition(s, b)` where `b.slot = s.slot - 1`.
This can be avoided if we require `s.slot <= b.slot` as a pre-condition for `state_transition`.

If option 1 is the intended meaning for asserts, that can be risky: if for some reason `process_slot` exits with the assert violated, we may be in the middle of a computation which is aborted and can result in an inconsistent state (note that a lot of the specs function gradually modify the `state` so it looks to me that this can happen). This is somehow prevented to happen if `state_transition` has a pre-condition that ensures that the computation in its body (`process_slot, process_block`,...) can be performed without violating the asserts. 

To summarise:
1. if the assert statements  are meant to express conditions that should never be violated, they have to be used consistently and this may require adding asserts to a caller because a callee requires it. 
2. if the asserts are used only at runtime,  we may end up starting and aborting state updates and this could result in an inconsistent state. 

I hope that clarifies the question.

**Comment by JustinDrake** [comment]
> when they are violated the program ends (possibly with an exception)

Taken [from the spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#beacon-chain-state-transition-function) "State transitions that trigger an unhandled exception (e.g. a failed `assert` or an out-of-range list access) are considered invalid."

> we may be in the middle of a computation which is aborted and can result in an inconsistent state

Such an inconsistent state is considered invalid and should be discarded. Clients should revert back to a known good state.

> I hope that clarifies the question.

The only question I could find is in the title, namely "Missing assert in state_transition?". The answer to that question is "no" :)

**Comment by franck44** [comment]
> Such an inconsistent state is considered invalid and should be discarded. Clients should revert back to a known good state.

Right, but it may be more effective to just prevent this from happening. 
And if we know in advance that can be prevented, we may benefit from that.

If the failed assert is very deep in the call graph, it may fail after lots of computations have been performed.
It seems arbitrary to decide that assert statements are somewhere in some code snippets rather than others.
And reverting to a known good state does not look very precise and formal to me.
Is it the previous state before the computation started?  

> The only question I could find is in the title, namely "Missing assert in state_transition?". The answer to that question is "no" :)

So there is no missing assert in `state_transition` in the specs, but nothing prevents me to add it in my code if I want to  write something much safer than the specs (i.e. make sure the assert in `process_slots` is never violated), correct?

**Comment by JustinDrake** [comment]
> nothing prevents me from adding it in my code

Correct :)

**Comment by franck44** [comment]
You may be interested in the following [CWE-617: Reachable Assertion](https://cwe.mitre.org/data/definitions/617.html)

And also [MET01-J. Never use assertions to validate method arguments](https://wiki.sei.cmu.edu/confluence/display/java/MET01-J.+Never+use+assertions+to+validate+method+arguments) from the The CERT Oracle Secure Coding Standard for Java.

The specs, as guidelines for implementers,  may benefit from following standard coding practices to limit the number of security vulnerabilities. After all, the Beacon Chain is a critical component of the Eth2 infrastructure, and critical software components may be coded/specified following the highest  coding standards.

**Comment by franck44** [comment]
@JustinDrake As I see that this issue has been closed I'll raise a new one regarding my previous comment and the use of assert statements to validate arguments in the specs.
