### ISSUE TITLE
BLS link points to expired draft

### ISSUE THREAD

**Issue by prestonvanloon** [ethereum/eth2.0-specs#1798]
From the [BLS Signatures section](https://github.com/ethereum/eth2.0-specs/blob/master/specs/phase0/beacon-chain.md#bls-signatures) of the beacon chain spec, there is a link to the expired draft. https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-00

I also haven't seen any BLS changes in [v0.12 milestone ](https://github.com/ethereum/eth2.0-specs/milestone/3), but I believe are supposed to target a new IEFT draft. Which draft is required in v0.12 implementation?

**Comment by hwwhww** [comment]
closing via #1799
