### ISSUE TITLE
DepositContract: get_deposit_root and get_deposit_count

### ISSUE THREAD

**Issue by axic** [ethereum/eth2.0-specs#1805]
Are the above two functions part of the external API?

The [specification](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/deposit-contract.md) doesn't mention them, but the report by Runtime Verification talks about them.

It would be nice to mention them in the specification if indeed they are supposed to be public helpers.

**Comment by djrtwo** [comment]
Yes! We can add to the spec for v0.12 release coming very soon

**Comment by hwwhww** [comment]
Hi @axic @daejunpark, do you think it should be included in the next release and FV audit report?

**Comment by djrtwo** [comment]
I think it's sufficient just to add them to the specs repo. The function already exist and are included in the formal verification
