### ISSUE TITLE
Consider IANA registration of URI Scheme for ethereum? 

### ISSUE THREAD

**Issue by fred-wang** [ethereum/eth2.0-specs#1808]
@brunobar79 has requested to add ethereum to https://html.spec.whatwg.org/multipage/system-state.html#safelisted-scheme see https://github.com/whatwg/html/pull/4287

One suggestion by the WHATWG is to ensure schemes are registered as provisional schemes at https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml so I drafted a request to be sent to IANA:

https://raw.githubusercontent.com/fred-wang/iana-uri-schemes-provisional-registration-requests/master/ethereum.txt

Please take a look and tell me if that looks ok to you. In particular is anyone from your community willing to be a second "Change controller" (Organization or person including contact information, authorized to change this) so that you can update the info later?

Also, it would be good to have a reference (maybe of your ethereum spec) to where the ethereum scheme is actually defined. Thanks!

**Comment by axic** [comment]
I think this discussion belongs more under https://github.com/ethereum/EIPs

There are already multiple proposals defining the scheme of `ethereum:`
- https://eips.ethereum.org/EIPS/eip-831
- https://eips.ethereum.org/EIPS/eip-2400
- https://eips.ethereum.org/EIPS/eip-681

**Comment by fred-wang** [comment]
Thanks @axic I hesitated between the two repos and chose the wrong one :-/ 

Feel free to close this and move to a more appropriate place for discussion.

**Comment by fred-wang** [comment]
@axic I updated the draft and moved discussion to https://github.com/ethereum/EIPs/issues/2644
