### ISSUE TITLE
`CHUNK_SIZE` setting

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#181]
Per https://github.com/ethereum/eth2.0-specs/pull/180#issuecomment-442061966, currently, `SSZ_CHUNK_SIZE` is set to `128` bytes in SSZ spec while another `CHUNK_SIZE` constant is set to `256` bytes in phase 1 spec. IMO it seems logical to unify the chunk size.

@JustinDrake and co, do we have any concern, like the size of proof of custody regarding chunk size?

**Comment by JustinDrake** [comment]
My gut feel is to make the chunks in shard blocks small, maybe 32 bytes. Any reason 256 bytes was chosen @vbuterin?

**Comment by arnetheduck** [comment]
There are three chunk sizes that could be considered "special":

* aligned with hash function block size - this helps make good use of the hash function itself in terms of entropy and avoiding arbitrary padding
* aligned with hash output size - this would help make all nodes in the tree have the same size, after chunking
* aligned with the largest `tree_hash_root` output - all inputs have to pass through this function, so using the same here makes it easier to avoid arbitrary-length buffers in the tree hashing code

**Comment by vbuterin** [comment]
I'm ok with 32 bytes.

Sorry, I remembered that my original reason for wanting 256 bytes was erasure coding efficiency, but then I remembered that hash tree chunk size and erasure code chunk size do not need to be the same. So 32 byte shard chunks it is.

**Comment by hwwhww** [comment]
closing via #344
