### ISSUE TITLE
Clarify whether ETH1_FOLLOW_DISTANCE applies to all ETH1 related events

### ISSUE THREAD

**Issue by q9f** [ethereum/eth2.0-specs#1832]
While preparing the Witti multi-client testnet, we had Prysm and Lighthouse disagreeing on the correct genesis time.

The reason is that LH honors ETH1_FOLLOW_DISTANCE whereas Prysm only starts honoring this _after_ genesis.

It should be clarified whether ETH1_FOLLOW_DISTANCE applies to all ETH1 related events or only after the genesis event.

Lighthouse assumed that was the case whereas Prysm points out that this is not clearly defined in the spec.

**Comment by djrtwo** [comment]
@q9f Do they agree on the genesis time, but lighthouse doesn't know the genesis time until after the genesis time?

**Comment by djrtwo** [comment]
addressed in #1834
