### ISSUE TITLE
eth1 follow distance is greater than default pruning history

### ISSUE THREAD

**Issue by q9f** [ethereum/eth2.0-specs#1839]
Apparently, the `ETH1_FOLLOW_DISTANCE` of `1024` is greater than the default pruning history of the ETH1 clients. This leads to issues (e.g., ref https://github.com/PegaSysEng/teku/issues/1813) where ETH2 clients won't be able to read historical ETH1 data that has been pruned already.

Default pruning values:
* Geth  `128`
    ```
	bodyCacheLimit      = 256
	blockCacheLimit     = 256
	receiptsCacheLimit  = 32
	txLookupCacheLimit  = 1024
	maxFutureBlocks     = 256
	maxTimeFutureBlocks = 30
	badBlockLimit       = 10
	TriesInMemory       = 128
	BlockChainVersion uint64 = 7
    ```
* OpenEthereum `128`
    ```
    --pruning=[METHOD]
        Configure pruning of the state/storage trie. METHOD may be one of auto, archive, fast: archive - keep all state
        trie data. No pruning. fast - maintain journal overlay. Fast but 50MB used. auto - use the method most recently
    --pruning-history=[NUM]
        Set a minimum number of recent states to keep in memory when pruning is active. (default: 128)
    --pruning-memory=[MB]
        within this limit, and at least --pruning-history states will always be kept. (default: 64)
    ```
* Besu `1024`
    ```
      --pruning-block-confirmations=<INTEGER>
                             Minimum number of confirmations on a block before
                               marking begins (default: 10)
      --pruning-blocks-retained=<INTEGER>
                             Minimum number of recent blocks for which to keep
                               entire world state (default: 1024)
      --pruning-enabled      Enable disk-space saving optimization that removes
                               old state that is unlikely to be required
                               (default: true if fast sync is enabled, false
                               otherwise)
    ```

Even with Besu's `1024` we would be always on the edge of getting this pruned right away once we need it.

I would encourage the OpenEthereum and Geth teams to increase the default value to `1024`, however, there will be valid arguments against that, especially because in most cases they are retained in memory.

Forthermore -- and unfortunately -- it's not possible to customize this value in Geth. Meaning, to provide your own ETH1 endpoint for an ETH2 client, you would have to run an archive node or use a third-party client.

What were the considerations leading to an `ETH1_FOLLOW_DISTANCE` of `1024`? Would it be possible to consider a lower follow distance, e.g. `512`? Shall we approach ETH1 client teams to bump defaults?

**Comment by djrtwo** [comment]
I believe that most clients instead us logs to reconstruct the deposit root from logged deposits

**Comment by q9f** [comment]
ok.
