### ISSUE TITLE
Balance eligibility previous+1 vs current epoch

### ISSUE THREAD

**Issue by protolambda** [ethereum/eth2.0-specs#1846]
In `get_eligible_validator_indices` the previous epoch is used, then "converted" (not strictly the same for genesis epoch) back to current epoch:

```python
previous_epoch + 1 < v.withdrawable_epoch
```
Now the rewards and penalties, the only place where `get_eligible_validator_indices` is used, we don't run anything for genesis epoch:
```
def process_rewards_and_penalties(state: BeaconState) -> None:
    if get_current_epoch(state) == GENESIS_EPOCH:
        return
```
Does this mean the `previous_epoch + 1` could just have been a `current_epoch`, as there shouldn't be any effective difference?

Context: @terencechain is comparing Prysm and spec/zrnt balances code, upgrading to v0.12, and after discussing the inclusion delay part (which seems to be a subset of eligible validators regardless of the eligibility check, although a tricky/awkward edge case), this difference showed up.

If there is any special reason to use `previous_epoch + 1` instead of `current_epoch` I'd like to know, and we should add a comment as part of the spec function descriptions PR.

**Comment by hwwhww** [comment]
Found some previous discussion: https://github.com/ethereum/eth2.0-specs/pull/949#discussion_r277380008

It seems fine to me to use `current_epoch`.

**Comment by protolambda** [comment]
Closing this issue, `previous_epoch` is used in the same variable scope already, so it seems ok to just use that, instead of getting the current epoch as well.
