### ISSUE TITLE
Add tests for `compute_fork_digest` and `compute_subnet_for_attestation`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#1865]
### Issue

These `compute_fork_digest` and `compute_subnet_for_attestation` helpers have not been tested in our CI.

### How to fix it
Add tests in
https://github.com/ethereum/eth2.0-specs/blob/dev/tests/core/pyspec/eth2spec/test/validator/test_validator_unittest.py

**Comment by lsankar4033** [comment]
I'm happy to take a look at this
