### ISSUE TITLE
Incorrect usage of `shard_transition.shard_data_roots` in `process_crosslink_for_shard`

### ISSUE THREAD

**Issue by terencechain** [ethereum/eth2.0-specs#1881]
#1878 motivated me to think whether `shard_head_root` in `AttestationData` is necessary. 

To accept an `attestation`, the node must has seen the `ShardTransition` that corresponds to the `shard_transition_root`. With the seen `ShardTransition`, the node can get the `shard_head_root` via `shard_transition.shard_data_roots[len(shard_transition.shard_data_roots) - 1]`

I think it's a nice saving of 32bytes since attestations are the most frequent objects that propagate in the network

**Comment by terencechain** [comment]
I may have confused myself. Looks like `shard_transition.shard_data_roots` are used for dual purposes:

1.) To construct body root for `ShardBlockHeader` in `apply_shard_transition`
```python
 # Reconstruct shard headers
header = ShardBlockHeader(
          ...
          body_root=transition.shard_data_roots[i]
          ...
)
```

2.) To verify it's consistent with attestation data's `shard_head_root` 
```python
assert attestation.data.shard_head_root == shard_transition.shard_data_roots[
                len(shard_transition.shard_data_roots) - 1
            ]
```

Does that mean one of them is incorrect? (perhaps 2?)

**Comment by djrtwo** [comment]
yes, this is mixing purpose right now. The #2 consistency check is bad
