### ISSUE TITLE
Change to 2^14 epoch custody periods

### ISSUE THREAD

**Issue by dankrad** [ethereum/eth2.0-specs#1888]
Getting rid of any kind of punishment for late reveals makes most sense when the custody period has the same length as the reveal deadlines. Therefore we should change to

 * Custody periods of 2^14 epochs
 * Reveal deadline: Another round of 2^14 epochs
 * Chunk challenge/custody slashing deadline: [This could be either 2^11/2^14 epochs]

**Comment by vbuterin** [comment]
Yep! That's what I had in mind.

**Comment by dankrad** [comment]
I implemented this in #1889. I increased the chunk challenge deadline to 2^15 epochs -- this would imply that validators need to keep data around for chunk challenges and to check other validator's custody for roughly the same amount of time.
