### ISSUE TITLE
configurable genesis delay and time

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#1894]
The current genesis logic (last changed [here](https://github.com/ethereum/eth2.0-specs/commit/34412130c5a8df907680649adbae58ae45f3c0bc)) has a configurable genesis delay but does not allow for genesis to happen at a configurable time.

Supporting configurable delay and time can be done by replacing `genesis_time=eth1_timestamp + GENESIS_DELAY` with `genesis_time=eth1_timestamp + MIN_GENESIS_DELAY + GENESIS_ALIGNMENT - eth1_timestamp % GENESIS_ALIGNMENT`.

**Example 1**—A testnet wants genesis at 12:00 UTC with 3+ days of delay. This is achieved with `MIN_GENESIS_DELAY = 3.5 days` and `GENESIS_ALIGNMENT = 1 day`.
**Example 2**—Alignment can be disabled by setting `GENESIS_ALIGNMENT = 1 sec`, effectively falling back to the current logic.
**Example 3**—We can restore the invariant that mainet genesis happens at 00:00 UTC by setting `GENESIS_ALIGNMENT = 1 day` and `MIN_GENESIS_DELAY` to a multiple of 1 day.

**Comment by protolambda** [comment]
Already proposed this to Danny when I was reviewing the change. But what we needed was a simplification (the previous thing was a little error prone), and something that would work for testnets (midnight UTC was not working for some main contributors). I still expect it to change in the future, and for these things to inevitably involve more community feedback. So I would hold off on changing it again for now, and wait for new feedback based on larger testnet launches.

**Comment by djrtwo** [comment]
This does seem to capture the tune-ability of genesis that is desired, but ups the complexity even from the previous calculation.

@protolambda we do have genesis state initialization tests, but just don't have much coverage. Regardless of what we do here, we should increase the coverage to avoid more issues in genesis time calculations. With sufficient consensus tests here, I wouldn't expect this increase in complexity to be an issue. 

Or is the issue amplified by the eth1 tracking?

**Comment by protolambda** [comment]
Primary concern if we would introduce it now is not the tests, but clients and tooling going through the churn of changing it. If we're changing it again, then let's ask them for input.

**Comment by prestonvanloon** [comment]
I like the predictability of a configurable genesis time and would accept this complexity for this benefit.
