### ISSUE TITLE
Allow Only Snappy-Compressed Encoding

### ISSUE THREAD

**Issue by rauljordan** [ethereum/eth2.0-specs#1931]
Hi all,

Currently Prysm allows for both snappy compressed and regular ssz encoded messages via p2p. Our security audit concluded allowing these two options is a security risk that can result in a network partition of someone operates nodes without snappy and others operate nodes with snappy enabled. Is there still a need for non-snappy encoded messages in the networking spec, or should the spec enforce snappy-compressed only?

**Comment by protolambda** [comment]
We can discuss this during the implementers call today: https://github.com/ethereum/eth2.0-pm/issues/162#issuecomment-649079956

**Comment by djrtwo** [comment]
So we certainly shouldn't have non-snappy in gossip.
We have in currently in the req/resp which shouldn't be a security risk, but I don't see a particular use case for this

**Comment by djrtwo** [comment]
Thinking we remove this in the v0.12.2 release unless anyone is relying upon it and with good reason to continue to support

**Comment by djrtwo** [comment]
closed via #1982
