### ISSUE TITLE
Validator penalty issues

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#196]
# Issue
Within `get_changed_validators` there is a bug such that `validators_to_penalize` get penalized at every validator registry change. Penalties should only be applied at withdrawal.

# Proposed solution
* Either add withdrawal logic back in and keep validators in a holding pattern
* Just remove this penalty logic for now, but note the withdrawal process and associated penalties in an issue/doc

**Comment by vbuterin** [comment]
I'd be ok with adding withdrawal logic back in, and just setting the *deletion* time to infinity.

We should also add a receipt tree that includes withdrawal receipts (potentially doable as easily as just storing in the state a list of withdrawals in the last block, completely overwriting it each block, though this would make processing harder; the alternative is to have a `receipt_root` in the block, which would allow more unified receipt processing code on the beacon chain and the shards).

**Comment by djrtwo** [comment]
Related issue:

`COLLECTIVE_PENALTY_CALCULATION_PERIOD` and "withdrawal period": In the codes, we use `COLLECTIVE_PENALTY_CALCULATION_PERIOD` while it is described as "withdrawal period" everywhere.

**Comment by hwwhww** [comment]
link #354
