### ISSUE TITLE
SSZ definition serialize number unclear?

### ISSUE THREAD

**Issue by imnisen** [ethereum/eth2.0-specs#1963]
In the definition of serialize  [Vectors, containers, lists, unions](https://github.com/ethereum/eth2.0-specs/blob/dev/ssz/simple-serialize.md#vectors-containers-lists-unions):

```
assert sum(fixed_lengths + variable_lengths) < 2**(BYTES_PER_LENGTH_OFFSET * BITS_PER_BYTE)

# Interleave offsets of variable-size parts with fixed-size parts
variable_offsets = [serialize(sum(fixed_lengths + variable_lengths[:i])) for i in range(len(value))]
fixed_parts = [part if part != None else variable_offsets[i] for i, part in enumerate(fixed_parts)]
```

Also in the above note:
> Note: In the function definitions below (serialize, hash_tree_root, is_variable_size, etc.) objects implicitly carry their type.

It seems unclear while serializing `sum(fixed_lengths + variable_lengths[:i])`in  `variable_offsets` part. Which  `uintN` should we use to serialize the number?  as the max value would be `2**32`.

**Comment by imnisen** [comment]
It seems to use uint32, as the BYTES_PER_LENGTH_OFFSET is 4, which means 32bit for putting the serialized offset

**Comment by protolambda** [comment]
Sorry, didn't notice this issue was still open. It's definitely an `uint32`, and although the constant `BYTES_PER_LENGTH_OFFSET = 4` should make it clear, that `serialize` call with generic integer input could be improved indeed. I'll make a PR to do that. Thanks for pointing this out :+1:
