### ISSUE TITLE
Add finalized descendant check to `beacon_block` pubsub 

### ISSUE THREAD

**Issue by terencechain** [ethereum/eth2.0-specs#1964]
Chatting with @prestonvanloon, we think it'll be a great addition to include validation of finalized block descent check as part of `beacon_block`'s p2p propagation criteria. In short, to re-propagate the block, we should satisfy the following:
```python
assert get_ancestor(store, block.parent_root, finalized_slot) == store.finalized_checkpoint.root
```

We have been observing more propagations of bad blocks in Onyx. Those bad blocks are attributed to not descendant of local finalized block.

**Comment by prestonvanloon** [comment]
Related: https://github.com/ethereum/eth2.0-specs/issues/1959

Maybe a duplicate too, i'm not sure.

**Comment by djrtwo** [comment]
closing in favor of #1959

**Comment by djrtwo** [comment]
closing in favor of #1959
