### ISSUE TITLE
How to deploy smart contract

### ISSUE THREAD

**Issue by saarshah** [ethereum/eth2.0-specs#1965]
I have deployed a smart contract on ropsten network and interact with it through web3, Node js, JavaScript. Now I want to deploy the same contract on Ethereum 2.0 (Proof of Stake) Testnet to check the difference. Is it possible ?

**Comment by dankrad** [comment]
Unfortunately, Eth2 does not yet support code execution, and thus smart contracts cannot currently be deployed on any testnet. This will only become possible once we have a testnet for phase 2.
