### ISSUE TITLE
Port Solidity deposit contract to this repo

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#1968]
Solidity contract: https://github.com/axic/eth2-deposit-contract

- [ ] Relicense from Apache-2.0 to loosen license
- [ ] Port https://github.com/axic/eth2-deposit-contract with commit history
- [ ] Install solc in the CI and compile the Solidity contract
- [ ] Create a new script to replace `test_compile.py` (by stealing things from https://github.com/axic/eth2-deposit-contract/blob/master/Makefile)
- [ ] Use the same deposit contract tests (`test_deposit.py`) against the new ABI.

/cc @axic

**Comment by ethers** [comment]
> Relicense from Apache-2.0 to loosen license

Checking this means to dual license it with MIT?
See https://github.com/ipfs/js-ipfs/issues/2624

**Comment by hwwhww** [comment]
closing via #2019
