### ISSUE TITLE
`get_forkchoice_store` needs cleanup

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/eth2.0-specs#1977]
https://github.com/ethereum/eth2.0-specs/blob/6a7a47dd5f6ce39cb8fcdbf787325886140191c3/specs/phase0/fork-choice.md#get_forkchoice_store

> _The block for `anchor_root` is incorrectly initialized to the block header, rather than the full block. This does not affect functionality but will be cleaned up in subsequent releases._

Clean up either comment or code :)

**Comment by djrtwo** [comment]
oof

**Comment by hwwhww** [comment]
closing via #2061
