### ISSUE TITLE
Point to the next IETF BLS signature spec release

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#1978]
### Issue
See https://github.com/cfrg/draft-irtf-cfrg-bls-signature/issues/22

[The Eth2 spec is using the latest IETF BLS spec (draft **v2**)](https://github.com/ethereum/eth2.0-specs/blob/8e82ca5d1ad6d651ef3410552c4bc13c16325f63/specs/phase0/beacon-chain.md#bls-signatures), which points to IETF hash-to-curve spec draft **v6**. But we need IETF hash-to-curve spec draft **v7**. The status-quo BLS v2 + H2C v7 is an awkward custom version for us. Currently waiting for the IETF BLS working group to cut the next release.

There should be **no** substantive change of `BLS_SIG_BLS12381G2_XMD:SHA-256_SSWU_RO_POP_` ciphersuite that Eth2 is using.

**Comment by A2be** [comment]
Brief update on this.  The IETF "draft 2" for BLS signatures expired yesterday, 10 Sep 2020.  [https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-02](url)

The site does not seem to yet have the "draft 3" posted; but perhaps I'm looking in the wrong place.

Either way, the Eth2.0 spec doc comment re IETF and draft 2 is now out of date and incorrect.
[https://github.com/ethereum/eth2.0-specs/blob/dev/specs/phase0/beacon-chain.md#bls-signatures](url)
