### ISSUE TITLE
Add links to defined terms

### ISSUE THREAD

**Issue by burnburn** [ethereum/eth2.0-specs#199]
I will be sending a collection of PRs that are adding links to the defined terms in the terminology section.  This should help readability.
I have specifically only linked uses of the term in text, not in code, to keep from making the Python code updates harder (guessing that the code is largely copied from the reference implementation).  I also did not include them in section titles in case that helps with ToC creation.

I am submitting these changes as multiple independent PRs, one per term, in the hope that it will reduce merge conflicts.  I will link each one to this issue, so please don't close this issue until I comment that I have added all the related PRs I plan to.

**Comment by hwwhww** [comment]
IMO we can just make reference link when the first time the terminology appears in the content.

**Comment by djrtwo** [comment]
@hwwhww Are you worried about the maintenance overhead or just the excessive frequency some of these terms have in the text (like validator)?

**Comment by burnburn** [comment]
@hwwhww I am willing to do the work.  Regarding first reference only, I find that in practice often such links end up elsewhere and not at first use as text gets modified and moved around.

**Comment by djrtwo** [comment]
@hwwhww I'm inclined to go with this method at least for now, and if we decide it is too invasive/verbose, we can come to consensus on a more stripped down linking.

I think one of the benefits of linking repeatedly is that a user can come to the doc, select something from the TOC deep into the doc, and when the user comes across a new term, they'll still have the link available even though they didn't start reading from the beginning.

**Comment by hwwhww** [comment]
@djrtwo @burnburn 
I’m mostly worried about the timing - I suspect that the spec likely will be cleaned up multiple times, and this format will be a requirement. But I don’t strongly against it. :)

 @burnburn, definitely appreciated! :)

**Comment by burnburn** [comment]
I understand your concern and agree that the spec will likely be changed more than most may think before it's "done".  I think an occasional pass through to pick up any missed references will work fine, even if people have been editing extensively (without linking).  Let's see how it goes.

**Comment by djrtwo** [comment]
closing for now
