### ISSUE TITLE
Wonky calculation in WITHDRAWAL_PERIOD

### ISSUE THREAD

**Issue by benjaminion** [ethereum/eth2.0-specs#20]
> **WITHDRAWAL_PERIOD** - number of slots between a validator exit and the validator slot being withdrawable. Currently set to `2**19 = 524288` slots, or `2**23` seconds ~= 97 days.

`2**19` slots is `2**22` seconds ~= 48.5 days.

**Comment by djrtwo** [comment]
Yup, you're right. Getting this fix up shortly

**Comment by benjaminion** [comment]
Vitalik has since changed `SLOT_DURATION` from 8 to 16 seconds, so this calculation is now correct.

**Comment by djrtwo** [comment]
Indeed. I'm still gunning for 8 seconds!
Some of these constants won't get 100% locked down until some serious client testing.

Closing
