### ISSUE TITLE
suggestion: How about move the effective_balance out from struct Validator?

### ISSUE THREAD

**Issue by lucianyao** [ethereum/eth2.0-specs#2000]
It looks the validators data effect the hashing state the most(for those others , like historical_roots, attestations, since they are only modified by appending, it's easy to cache the hash). For the active validators,  the the fields except effective_balance in Validator change at most once in their lifecycle, while effective_balances change per epoch. If we move the effective balances together, we probably can reduce the footprints of tree hashing a lot.

**Comment by mcdee** [comment]
balance changes each epoch, but effective balance changes very rarely due to the hysteresis effect.

**Comment by lucianyao** [comment]
indeed.
