### ISSUE TITLE
Won't honest validators update ETH1 data every two voting periods?

### ISSUE THREAD

**Issue by rkapka** [ethereum/eth2.0-specs#2012]
[This issue](https://github.com/ethereum/eth2.0-specs/pull/1757) was raised because it was possible to vote for the same block in two successful voting periods because of block overlapping. The solution was to add the following condition: `get_eth1_data(block).deposit_count >= state.eth1data.deposit_count` (https://github.com/ethereum/eth2.0-specs/pull/1836)

I think that the current implementation of Honest Validator's `get_eth1_vote`, where the validator follows the majority's vote, will result in eth1data being oftentimes updated every two voting periods instead of every period. This is assuming that most validators have a reasonably up-to-date view of the Ethereum 1 chain.

Perhaps a visual representation will make it easier to understand.

![table](https://user-images.githubusercontent.com/28876818/89659514-4889a980-d8d0-11ea-891b-2950113a6852.png)

Additional explanation:
- We assume that each voting period is 4 slots.
- Valid ranges overlap as explained in https://github.com/ethereum/eth2.0-specs/pull/1757.
- Block `0x1` is valid during `P2` because its timestamp is within the valid range (`2 090 000 < 2 099 000 < 2 190 000`).
- `P2/S2`'s proposer sees only the vote from `P2/S1`. This is because in order to obtain the correct state for proposals (which is the state at `P2/S1`), the state transition function had to transition from `P1/S4` to `P2/S1` which cleared all votes from `P1`.
- Same thing will happen with `P3` and `P4`, `P5` and `P6` etc.

A possible solution would be to check if the vote is cast in the first slot of a voting period. If yes, ignore the majority vote and propose a new block.

**Comment by rkapka** [comment]
Perhaps a more visual representation will make it easier to understand.

![table](https://user-images.githubusercontent.com/28876818/89659514-4889a980-d8d0-11ea-891b-2950113a6852.png)

Additional explanation:
- We assume that each voting period is 4 slots.
- Block `0x1` is valid during `P2` because its timestamp is within the valid range (`2 090 000 < 2 099 000 < 2 190 000`).
- `P2/S2`'s proposer sees only the vote from `P2/S1`. This is because in order to obtain the correct state for proposals (which is `P2/S1`), the state transition function had to process the slot `P1/S4`, during which all votes from the previous voting period `P1` were cleared.
    ```
    if next_epoch % EPOCHS_PER_ETH1_VOTING_PERIOD == 0:
        state.eth1_data_votes = []
    ```

**Comment by djrtwo** [comment]
So the issue here is the definition of `state` to use when running `get_eth1_vote`. It is assumed throughout the instructions for block  that `state` is for the _slot of the block being created_. This requires a state transition of `process_slots` on the state from the previous slot. In doing so, the `eth1data_votes` would be cleared out in your example, not resulting in the double initial vote as you described.

Although this transition to the next slot is described explicitly in attestation production, it is just assumed in the block production.

I'll make the update to ensure it is explicit, although clients must already be using this logic otherwise they would be producing malformed blocks!

Thank you!

**Comment by rkapka** [comment]
Thank you for responding.

I think there is unwanted edge-case/side-effect of the proposed solution. `eth1data_votes` are used to advance the `eth1data` in case the threshold of >50% is reached. If the threshold was reached in the last slot of the previous epoch, then clearing votes before the proposal will not advance `eth1data`.
