### ISSUE TITLE
In fork choice, maybe we forget to obsolete the attestations with target epoch < previous epoch (which were updated into the latest message)when calculate the latest balances

### ISSUE THREAD

**Issue by lucianyao** [ethereum/eth2.0-specs#2026]
In fork choice at version  b239f61, we only collect the attestations in recent 2 epochs(current epoch and previous epoch), as we do in `validate_on_attestation()`, but in `update_latest_messages()` and `get_latest_attesting_balance()`, we don't obsolete the attestations before previous epoch, instead, we still take them into count, which means, we don't restrictively follow the rule: only collect attestations from recent 2 epochs.(which may cause a [decoy-flip-flop attack](https://ethresear.ch/t/decoy-flip-flop-attack-on-lmd-ghost/6001))

Let me explain with a simplified demonstration.
In the figure below, when "current epoch" was at epoch n+3, we collected 2 attestations: v1->block 1, v2->block2. And now the current epoch moves to epoch n+4,  we are supposed to obsolete the v1's attestation, only take v2's attestation into count, and block 2 is supposed to be the header. But in our implementation by now, we take into count both attestations, and block 1 as header. 
![fork_choice](https://user-images.githubusercontent.com/1046069/91244238-713dea00-e77e-11ea-9943-c21148ba0edc.png)

**Comment by djrtwo** [comment]
We don't retroactively remove attestations from the fork choice.
The decoy-flip-flop attack mitigations are only restrictions for _adding_ new attestations

**Comment by lucianyao** [comment]
You are right. I thought it carefully and found I was wrong so  closed the ticket. Thank you!
