### ISSUE TITLE
Add references section

### ISSUE THREAD

**Issue by burnburn** [ethereum/eth2.0-specs#203]
I'd like to propose the explicit addition of a References section to the end of the document.  In-text links would then point to the specific reference within that section, which would then point to the external resource.

While it does mean that following an in-text reference would then require two clicks, moving all external references to one section has several benefits:
1. It provides a way to make clear, in one place, all references that are Normative, meaning that they must be read in order to implement the specification.
2. It provides a single place to check the external references to ensure that the reference links are not stale, either in terms of the links themselves no longer being valid, or in terms of the most recent / most applicable version being the one referenced.
3. It provides an opportunity to give more details (such as the document name, etc.) than would be appropriate in the main body of the document.

I will follow with a PR creating the References section, then several PRs suggesting how existing links should be moved to and described in the References section.  My goal was to prioritize simplicity of in-text reference over simplicity of the Reference section content while ensuring that full Markdown was usable in the References section.

**Comment by djrtwo** [comment]
Closing as section was added. Feel free to continue to add references into the section on a continual basis
