### ISSUE TITLE
Refactor gossipsub message-id

### ISSUE THREAD

**Issue by blacktemplar** [ethereum/eth2.0-specs#2039]
Currently the gossipsub `message-id` is specified as:

```
message-id: base64(SHA256(message.data))
```

The base64 is there since in the earlier gossispub spec versions message-id had to be a string but this changed a while ago (see https://github.com/libp2p/specs/commit/8e5da407893d6e340b7ec68d849cb57b19449671#diff-b6f4ac67de1a41957e8f97f5728669b7), so now message-ids can be arbitrary bytes. I therefore propose changing the message-id to simply:

```
message-id: SHA256(message.data)
```

This will save us valuable bandwith (especially for IHAVE and IWANT messages that contain mostly only message ids). Furthermore, it is in my opinion cleaner than using the byte representation of a base64 string.

As we recently found out, until now Prysm used a different message id than defined in the spec (see https://github.com/prysmaticlabs/prysm/pull/7177) which was not really a problem for Medalla. We only found out about the inconsistency during testing gossipsub peer scoring. In fact if no peer scoring is active the only problem with inconsistent message id functions is that there will be more gossipping happening (since message ids in IHAVE will not coincide with the computed message ids of the received messages).

So I propose to do this change before most of the clients activate gossipsub scoring which would penalize inconsistent message id functions and would make it harder to switch.

**Comment by AgeManning** [comment]
Agree! I think all the clients can implement it asynchronously.

**Comment by raulk** [comment]
LGTM!

**Comment by prestonvanloon** [comment]
Looks good to me. Thanks!

>
