### ISSUE TITLE
More granular rewards

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#205]
# Issue
We currently only reward attestations for two things
* voting on the correct casper `target`
* voting on the  correct `shard_block_hash`

This ends up not granularly incentivizes two other components of the voting process:
* voting on the correct casper `source`
* voting on the correct `beacon_block_hash` for your assigned slot

# Proposed solution
* Give 1/4 of the total reward for individually satisfying each of the 4 above criteria
* multiply the sum of the 4 rewards above by the `adjust_for_inclusion_distance` to adjust for late inclusion
* An `AttestationRecord` can only be included in the block if voted on the correct `source` so the baseline reward for validators that got an attestation included is `1/4` of the total reward.
* rework `BASE_REWARD_QUOTIENT` and `reward_quotient` such that `1/reward_quotient` is actually the max amount by which your deposit can grow per cycle. (rather than right now, it is `2/reward_quotient`) That means that each of these items should be rewarded a max `1/(4 * reward_quotient)`

**Comment by vbuterin** [comment]
Agree!

Though I would also say multiply the sum of the 4 rewards above by the function which reduces your reward if the vote took longer than the minimum to include.

**Comment by djrtwo** [comment]
waiting for #217 to reduce merge conflicts

**Comment by djrtwo** [comment]
closed via #290
