### ISSUE TITLE
Clarify Deposit Contract Bytecode Generation

### ISSUE THREAD

**Issue by q9f** [ethereum/eth2.0-specs#2052]
The deposit contract hosted by @axic had a version of the byte-code that was formally verified.

I was able to deploy the contract bytecode to Goerli for the Medalla testnet launch and publish/verify the source-code on Etherscan: https://goerli.etherscan.io/address/0x07b39F4fDE4A38bACe212b546dAc87C58DfE3fDC#code

Now we have the contract and _some_ bytecode in this respository as version `r2` (#2019) but I cannot figure out which solidity version and parameters were used to compile the give bytecode.

I tried solidity compiler version 0.6.11 with 5000000 optimizations but ended up with a bytecode mismatch.

https://goerli.etherscan.io/address/0x48b597f4b53c21b48ad95c7256b49d1779bd5890#code

If possible, could we add these parameters to the contract subdirectory readme file? Is this bytecode the final one for the deposit contract?

**Comment by axic** [comment]
The original source had a [Makefile](https://github.com/axic/eth2-deposit-contract/blob/master/Makefile) showing all the settings. I believe what you may be missing is `--metadata-literal`. I'm not sure if these are not present in the main makefile of eth2.0-specs, but I see it is not in the contract repository.

**Comment by hwwhww** [comment]
@axic @q9f 
Here: https://github.com/ethereum/eth2.0-specs/blob/e5f110a37bc71221dba3350d5d8cc86f6f8f2906/Makefile#L119

The parameters are copied from the previous repo. :)

**Comment by hwwhww** [comment]
> If possible, could we add these parameters to the contract subdirectory readme file? Is this bytecode the final one for the deposit contract?

Good point. I will update the subdirectory README.

**Comment by q9f** [comment]
Yes, I found the parameters, but which solidity version was used?
