### ISSUE TITLE
Invalid deposit on ETH2

### ISSUE THREAD

**Issue by kristieguo** [ethereum/eth2.0-specs#2071]
Hello,

For test purpose, I deliberately included a invalid BLS signature in the deposit data and submitted the transaction to ETH1 deposit contract. Then I got the "invalid" deposit on ETH2. 

I previously sent a valid deposit so the validator is awaiting activation. But the explorer shows The current balance, effective balance and deposits received are all 32ETH. The invalid deposit of 32ETH was burned on ETH1 but considered "invalid" on ETH2. So does it mean the 32ETH was not transferred successfully to ETH2? Does this mean I forever lost this 32ETH? Is there any way to retrieve them on ETH1? Or maybe I can retrieve them once the transfer function launches on ETH2?

Appreciate any help. Thanks.

![image](https://user-images.githubusercontent.com/20232539/93443915-01e19300-f903-11ea-9e64-bc3eea15a41a.png)
![image](https://user-images.githubusercontent.com/20232539/93443833-fd1cdf00-f902-11ea-9871-81fe9f722ff5.png)

**Comment by hwwhww** [comment]
Hi!

>  I deliberately included a invalid BLS signature

> So does it mean the 32ETH was not transferred successfully to ETH2?

The Eth1 deposit contract doesn't check the BLS signature. When your deposit was being processed in Eth2, the Eth2 clients checked the signature and determined it was invalid.

> Does this mean I forever lost this 32ETH? Is there any way to retrieve them on ETH1?

Unfortunately, it won't be back. :'(

> Or maybe I can retrieve them once the transfer function launches on ETH2?

It's not about the transfer functionality. It can only be unlocked with a special hard fork.


---

That said, when we have BLS12-381 implementation in Eth1, we can have a new deposit contract with on-chain BLS signature verification to protect people from losing ETH with bad deposit signature in the future.
