### ISSUE TITLE
Bump to IETF BLS standard draft -04

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#2072]
### Issue

Upgrade to [draft-irtf-cfrg-bls-signature-04](https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-04) before the mainnet launch.

### TODOs
- [ ] Update documents
- [ ] Update the test vectors

**Comment by djrtwo** [comment]
Is py_ecc library ready for this?
I'd like to get a mainnet-candidate branch going asap and I think this is the primary blocker

**Comment by hwwhww** [comment]
@djrtwo 

Status updates:
- I have a `py_ecc` branch PR: https://github.com/ethereum/py_ecc/pull/103 ready to review.
- Also confirmed with @kirk-baird, rust milagro_bls will be ready next week. (since we currently use milagro for state tests testgen & CI)

Tomorrow I'll make a pyspec branch for updating the BLS test vector generator. (for edge cases)

**Comment by hwwhww** [comment]
closing via #2080
