### ISSUE TITLE
Re-introduce missing SSZ tests (v0.12.3 test release)

### ISSUE THREAD

**Issue by protolambda** [ethereum/eth2.0-specs#2076]
See comment: https://github.com/ethereum/eth2.0-specs/pull/1957#issuecomment-695331358

During the PR some test generators were temporarily disabled for quicker iteration on phase1 test gen debugging, and were not re-enabled for mainnet by the looks of it.

On this line: https://github.com/ethereum/eth2.0-specs/blob/87220f8c35181d6aaa7e4822d7e16576eefe17f7/tests/generators/ssz_static/main.py#L90

**Comment by djrtwo** [comment]
woo
I can handle this today

I'll just release the tests and backport the fix to dev. Won't cut a new release

**Comment by djrtwo** [comment]
Patched the release with complete tarballs
https://github.com/ethereum/eth2.0-spec-tests/releases/tag/v0.12.3

**Comment by protolambda** [comment]
Tests tarball was updated, confirmed by Prysm team (thanks), and `dev` branch has the fix so it won't happen for the future releases. Sorry everyone, we'll double review test building changes (even if phase1) next time, and check the tests output diff better. :)

Closing this now.
