### ISSUE TITLE
Container values tightly packed

### ISSUE THREAD

**Issue by atoulme** [ethereum/eth2.0-specs#208]
In the SSZ spec, the container values are serialized with the following instruction: 
>The serialized values should be tightly packed.

Does that mean we should prefer to serialize integers with the smallest possible number of bytes? If yes, how do we know to deserialize the container?

Take for example these 2 objects:
```
{"a":1, "b":65536, "c":32}
```
And:
```
{"a":1, "b":32, "c":65536}
```
In the first case, the container would serialize a with one byte, b with 3 bytes, c with one byte.
In the second case, you would serialize a and b with one byte, and c with 3 bytes.

I am truly confused by this sentence. Would it be possible to remove it from the spec?

**Comment by atoulme** [comment]
Got it now, thanks for clarifying. I think this advice is valid in general for this serialization system, be it a uint, or writing a list of integers.

To help answer your question with a question, sorry, is there a concern to avoid having leading zero bytes here?

**Comment by vbuterin** [comment]
> To help answer your question with a question, sorry, is there a concern to avoid having leading zero bytes here?

We want the serialization to have a fixed mapping of element to byte position in as many situations as possible (ie. every situation except those involving variable-sized objects, where this is not possible).

**Comment by atoulme** [comment]
Understood. I think this recommendation doesn't just apply to container values but to the uint and hash types directly. As such I propose the following change: https://github.com/atoulme/eth2.0-specs/commit/e59537d329b3e7ecf9f8d7bb37c47e249f337e55

**Comment by djrtwo** [comment]
Closing for now. Happy to review a PR if this is still an issue
