### ISSUE TITLE
A validator may be included both in a slashing and a voluntary exit in the same block, which causes the block invalid 

### ISSUE THREAD

**Issue by lucianyao** [ethereum/eth2.0-specs#2084]
In a case that a validator is to exit, while it triggers a slashing, then
In block proposal:
According to current spec of honest validators, the block proposer may include the same validator in both slashings and voluntary exits into the same block(since  the exits satisfies the verification conditions found in `exits processing` based on current beacon state).

But in state transition:
The block is not to be accepted by other validators, since, after `process_proposer_slashing` and `process_attester_slashing`, the exit_epoch will be set, while `process_voluntary_exit` will reject the voluntary exits whose exit epochs are set before.

I checked lighthouse, prysm and nimbus, according to my limited investigations, I haven't seen these versions are trying to avoid the conflict.

**Comment by JustinDrake** [comment]
Great point!
