### ISSUE TITLE
Prevent validator signing far into the future attestations

### ISSUE THREAD

**Issue by alonmuroch** [ethereum/eth2.0-specs#2085]
Current validator implementations put a lot of trust in constructing the attestation data object on the beacon node side, mostly the validator checks the attestation data is not slashable. 

A problem can occur if the attestation data includes a target epoch well into the future. If the validator signs it, from that point on, most slashing protection mechanism will prevent that validator from signing any attestation until that far into the future epoch is reached. 
That can cause major loses and potential inactivity slashing.

It might be a good idea to add some reference to this in the honest validator guide (thanks for the suggestion @dankrad )

**Comment by alonmuroch** [comment]
@hwwhww should I prepare a PR for this?

**Comment by djrtwo** [comment]
Agreed that we can put a note in the guide for clients to be aware of this pitfall and to add sanity checks on time and epochs skips

**Comment by alonmuroch** [comment]
@djrtwo @hwwhww  https://github.com/ethereum/eth2.0-specs/pull/2107/files
