### ISSUE TITLE
Prevent deposit double-spend

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#210]
Now that we're allowing for more than one deposit per identity we need a double-spend prevention mechanism.

**Comment by Swader** [comment]
> more than one deposit per identity

Can you please link to some discussion / clarification around this?

**Comment by JustinDrake** [comment]
The idea is that validator can "top up" their balance, in particular if their balance gets close to the automatic eviction balance. See for example [this commit](https://github.com/ethereum/eth2.0-specs/commit/4ec40f06f38f4b7d0633b60b8f565da0b8ea0746).

**Comment by JustinDrake** [comment]
Closing in favour of https://github.com/ethereum/eth2.0-specs/issues/218
