### ISSUE TITLE
BeaconBlockBody eth1Data could be nil?

### ISSUE THREAD

**Issue by alonmuroch** [ethereum/eth2.0-specs#2105]
Can eth1Data in a block be nil? if not I don't thing we are checking it.

**Comment by dankrad** [comment]
By default SSZ objects cannot be nil.

**Comment by alonmuroch** [comment]
But a received block struct can, what if the BN receives a block with eth1Data set to nil?

**Comment by dankrad** [comment]
There is no valid serialization for "nil". It simply is not a possible value.

All the fields can however be set to some nonsense anyway (including all zero bytes). This is dealt with through voting, and as long as a majority of proposers supply valid data will have no impact.
