### ISSUE TITLE
Specify withdrawal_credentials

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#211]
The idea is for `withdrawal_crenditials` to be include a versioning mechanism somehow, and version 0 to involve the hash of a BLS pubkey.

**Comment by vbuterin** [comment]
Byte 0 = `0x00`, bytes 1...31 = `hash(withdrawal_pubkey)[1:]`. Would that work?

`withdrawal_pubkey` would be serialized in the same way as it is in eg. the validator list and anywhere else in the protocol.

Would we want to add a protocol rule that only deposits with version byte `0x00` are currently permitted?

**Comment by JustinDrake** [comment]
Implemented [here](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#deposit-arguments)

**Comment by djrtwo** [comment]
We need to check the 1st byte of `withdrawal_credentials` either in the pow contract or in the deposit processing within blocks.

Right now we just say "One of the DepositParametersRecord fields is withdrawal_credentials which must satisfy:" near the pow contract but the protocol isn't enforcing this anywhere.

**Comment by JustinDrake** [comment]
> We need to check the 1st byte of `withdrawal_credentials` either in the pow contract

Good idea! We edit.

> the protocol isn't enforcing this anywhere

I was thinking the beacon chain will enforce this when we have withdrawal logic. Adding safety logic in the deposit contract sounds good! We could even require `withdrawal_pubkey` to be disclosed in the deposit contract, although this makes withdrawals non-quantum secure.

**Comment by djrtwo** [comment]
Do we expect that leading byte of `withdrawal_credentials` to ever change from 0x00? If so, shouldn't go in the deposit contract

**Comment by JustinDrake** [comment]
> Do we expect that leading byte of `withdrawal_credentials` to ever change from 0x00?

Not sure, good point. The leading byte is a version number.

**Comment by JustinDrake** [comment]
My current inclination is that we don't want to enforce `0x00` in either the Phase 0 beacon chain or the deposit contract. We should however be clear that not respecting the `withdrawal_crendentials` format will almost certainly mean you won't be able to withdraw in Phase 2. This is on my review/cleanup list, to add a big red warning.
