### ISSUE TITLE
Add slot number to `state` and make state transition function per slot

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#212]
Currently the state transition function is per block, not per slot. By adding `slot` to the `state` we make the state transition per slot. This means:

* Increased granularity in the `beacon_block_hash` (which should maybe to called `beacon_slot_hash`).
* Attestations for different slots are differentiated with the `beacon_slot_hash`, avoiding risk of confusion.
* The epoch boundary processing can happen at exact boundaries, which is cleaner than the current `while(block.slot - state.latest_state_recalculation_slot >= EPOCH_LENGTH)` logic.
* If there are many "skip slots" in a row the transition function progresses instead of queuing work. For example, inactivity penalties can be applied with a greater granularity.

**Comment by djrtwo** [comment]
So this allows state transition do to the following
`transition_to_next_slot(state, block)` where `block` is optional?

**Comment by JustinDrake** [comment]
@djrtwo Right :)

**Comment by djrtwo** [comment]
Thoughts on clients eagerly transitioning through slots during times of latency and having to perform windback when blocks for previous slots actually arrive?

**Comment by JustinDrake** [comment]
When clients do state transitions is up to them. They can do eager transitioning, or stick with the currently-suggested per-block transitioning.

**Comment by JustinDrake** [comment]
Closing in favour of https://github.com/ethereum/eth2.0-specs/issues/218
