### ISSUE TITLE
Mainnet Value of ETH1 Blocktime is Incorrect

### ISSUE THREAD

**Issue by nisdas** [ethereum/eth2.0-specs#2132]
Currently the mainnet value of the ETH1 Blocktime is set at 14 seconds, when in actuality it is 13 seconds. 
Current Value:
https://github.com/ethereum/eth2.0-specs/blob/dev/configs/mainnet/phase0.yaml#L48

Current ETH1 Blocktime(from etherscan) 
https://etherscan.io/chart/blocktime

The last time it was consistently 14 seconds was in 2018, whereas for the 2 years after it has been at about 13 seconds. 

This variable is used in a few important places, mainly when creating the genesis state here:
https://github.com/ethereum/eth2.0-specs/blob/ad48c82ba712b7ae8988d20221aa6045915b55d0/specs/phase0/beacon-chain.md#genesis

Or when determing a candidate eth1 block to vote on
https://github.com/ethereum/eth2.0-specs/blob/ad48c82ba712b7ae8988d20221aa6045915b55d0/specs/phase0/validator.md#eth1block

**Comment by djrtwo** [comment]
Although this is a bit off, the mechanism is safe as is, and over-estimating it ensures we look deeper into the eth1 pow chain than if we reduced to 13 so it only makes this pow voting mechanism marginally more secure.

For the sake of simplicity, I'd say we don't touch it

**Comment by nisdas** [comment]
That sounds good, just wanted to raise this and see if this something to focus on. Might be good in the future to instead use a dynamic value for block time rather than a config value. Would help to guard against cases where eth1 block-time can rise rapidly(large difficulty increases due to ice-age).
