### ISSUE TITLE
[testgen] enable HF1 testgen and temporarily disable phase 1 testgen 

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#2191]
If we are cutting a new spec release soon (e.g., in 1 week):
1. The light client patch in HF1 is more relatively ready for client teams to prototype.
2. The phase 1 tests are relatively useless until #2172 is merged.
    - It may also mitigate the file compression issue (#2186) a bit.

I think we should enable HF1 testgen. And want to confirm if (2) is true or not.

/cc @djrtwo

**Comment by djrtwo** [comment]
Yes, let's do this.
