### ISSUE TITLE
PoW chain contract does not compile in the latest version of Vyper

### ISSUE THREAD

**Issue by dangerousfood** [ethereum/eth2.0-specs#221]
Compilation of the [PoW chain contract](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#contract-code-in-vyper) must be done using using [v0.1.0-beta.4](https://github.com/ethereum/vyper/releases/tag/v0.1.0-beta.4). Compilation in the latest version [v0.1.0-beta.5](https://github.com/ethereum/vyper/releases/tag/v0.1.0-beta.5) results in the following error:

> vyper-0.1.0b5-py3.7.egg/vyper/types/types.py:328: DeprecationWarning: Mapping definitions using subscript have deprecated (see VIP564). Use map(type1, type2) instead.
Error compiling:  vrc.vy
vyper.exceptions.InvalidTypeException: line 11: Unknown list type.
receipt_tree: bytes32[uint256]
--------------^

**Comment by djrtwo** [comment]
Tried to change the line to `receipt_tree: map(uint256, bytes32)` but am getting the following error

```
vyper.exceptions.StructureException: map expects one arg (the type)
```

Pinged the vyper guys in gitter and am awaiting a response.

**Comment by djrtwo** [comment]
apparently it was a bug in v0.1.0-beta.5 that has already been fixed in master. Should be fixed in next release

**Comment by djrtwo** [comment]
Made vyper version explicit in the spec. Will update when next release

**Comment by realisation** [comment]
This is erroring out for me on v0.1.0b10

**Comment by jishankai** [comment]
> This is erroring out for me on v0.1.0b10

How did you solve this? I have the same issue with this version.

**Comment by ChiefGhostZero0x1** [comment]
I have found several bugs with the fix being to update to the same thing!! I think this can be assigned the /bug label as well![image](https://user-images.githubusercontent.com/89703573/150614756-a5ed4b31-c4e8-4ae6-b041-3609b2278d84.png)

These are from the dependabots
