### ISSUE TITLE
`next_start_shard` missing from `BeaconState`

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/eth2.0-specs#223]
.. but it's referenced in https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#validator-registry-change

**Comment by hwwhww** [comment]
Nice catch! I think it shouldn't be part of the `state`.
/cc @vbuterin per commit https://github.com/ethereum/eth2.0-specs/commit/0d26da4a7d0f7a6adcda9122b19c126e0c21dde5
