### ISSUE TITLE
Consider renaming ALTAIR_* constants

### ISSUE THREAD

**Issue by mcdee** [ethereum/eth2.0-specs#2231]
There are a number of constants in the spec such as 'ALTAIR_INACTIVITY_PENALTY_QUOTIENT'.  Having the fork name first makes it slightly harder to parse mentally, as well as being less amenable to reading after sorting the constants by name.

Swapping it around so the "what" goes first and the "when" comes after makes life a little bit easier, for example:

```
INACTIVITY_PENALTY_QUOTIENT: 67108864
INACTIVITY_PENALTY_QUOTIENT_ALTAIR: 50331648
```

It's not a major difference, but I think the benefit of having it this way around will increase with the number of hard forks.

**Comment by hwwhww** [comment]
I'm fine either way. /cc @djrtwo

**Comment by djrtwo** [comment]
ah, yeah. This makes sense

**Comment by djrtwo** [comment]
addressed!
