### ISSUE TITLE
Validator status transition issues

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#225]
### Issues
- [x] 1. **The current spec doesn't describe how `PENDING_EXIT` transits to `EXITED_WITHOUT_PENALTY`**. A draft diagram:
    ![validator_state_transition](https://user-images.githubusercontent.com/9263930/49433564-575fb500-f7ed-11e8-90f5-3a8b9d4d3936.png)
    (Please let me know if anything incorrect or unclear.)

- [x] 2. **Potential `min_empty_validator_index()` issue**: [follow up this comment](https://github.com/ethereum/eth2.0-specs/pull/185#discussion_r237649259). Agreed with @djrtwo. IMO It doesn't make sense to allow the validators who *have sent voluntary exit/withdraw message* to make a top-up deposit.
    **edited**: just noticed the second case: involuntary `ACTIVE` -> `PENDING_EXIT` when `v.balance < MIN_BALANCE`.

- [ ] 3. **`COLLECTIVE_PENALTY_CALCULATION_PERIOD` and "withdrawal period"**: In the codes, we use `COLLECTIVE_PENALTY_CALCULATION_PERIOD` while it is described as "withdrawal period" everywhere.

- [x] 4. [`get_active_validator_indices` returns both `ACTIVE` and `PENDING_EXIT` validators](https://github.com/ethereum/eth2.0-specs/blob/c2227a59de89a8b233974f58d55e8a4401568bce/specs/core/0_beacon-chain.md#get_active_validator_indices).
    ```python
    def get_active_validator_indices(validators: [ValidatorRecord]) -> List[int]:
        """
        Gets indices of active validators from ``validators``.
        """
        return [i for i, v in enumerate(validators) if v.status in [ACTIVE, PENDING_EXIT]]
    ```

    Maybe we should rename `ACTIVE` status to another name?

#### For issue 1
1.  @djrtwo suggested: https://github.com/ethereum/eth2.0-specs/pull/185/files#r237660001
`get_changed_validators()` needs to check `if state == PENDING_EXIT` and then immediately set `state = EXITED_WITHOUT_PENALTY`. 
2. [Add the stub of the actual withdraw](https://github.com/ethereum/eth2.0-specs/pull/185/files#diff-51a43328a58414e132a744f3771f018cL1309). For testing withdraw, maybe we can actually set `v.balance=0` and note that the balance will be transferred to shard chain in phase 1.

---

potentially related to #198?

**Comment by djrtwo** [comment]
1, 2, and 4 addressed in #228
