### ISSUE TITLE
Domains 0x08 and 0x09 missing from altair config

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/eth2.0-specs#2264]
In v1.1.0-alpha.2 the `DOMAIN_SYNC_COMMITTEE_SELECTION_PROOF` and  `DOMAIN_CONTRIBUTION_AND_PROOF` are absent from the `altair.yaml` config:

https://github.com/ethereum/eth2.0-specs/blob/c284078242620d3167473a2a29bf29a5c8f03f2d/configs/mainnet/altair.yaml#L33-L35

**Comment by ralexstokes** [comment]
resolved in #2266.

**Comment by michaelsproul** [comment]
Awesome, thanks!
