### ISSUE TITLE
Optimize Altair p2p validation order

### ISSUE THREAD

**Issue by terencechain** [ethereum/eth2.0-specs#2286]
The current Altair p2p validation order is not optimized comparing to phase 0. One example is `selection_proof`.

For `aggregate_and_proof` topic:
1.) Checks `selection_proof` selects validator as an aggregator for the slot…
2.) Checks aggregator’s index is within the committee…
3.) Checks `selection_proof` is valid signature… 

For `sync_committee_contribution_and_proof` topic:
1.) Checks aggregator’s index is within committee…
2.) Checks `selection_proof` Is valid signature…
3.) Checks `selection_proof` selects the validator as an aggregator for the slot…

I think there may be more validation order things to improve as well. Opening this issue to track the overall

**Comment by djrtwo** [comment]
oh great! thank you

I'm aiming to get a pre-release out on friday. We can track here and get a PR up in next couple of days.

**Comment by ralexstokes** [comment]
@terencechain thanks! updated that in #2293. happy to make further changes if we find better orderings in this thread

**Comment by terencechain** [comment]
Thanks @ralexstokes ! Closing this as I dont see any ordering improvement at this moment.
