### ISSUE TITLE
sync_committee_contribution_and_proof validators selection_proof signature incorrectly

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-specs#2297]
In https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/p2p-interface.md#sync_committee_contribution_and_proof there's the rule:

```
The contribution_and_proof.selection_proof is a valid signature of the contribution.slot by the validator with index contribution_and_proof.aggregator_index
```

But https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/validator.md#aggregation-selection looks like the signature should actually be over `SyncCommitteeSigningData(contribution.slot, contribution.subcommittee_index)`.

Have I mismatched where this signature comes from or did we copy/paste a rule from attestation aggregations and not adjust? :)

**Comment by ralexstokes** [comment]
Ah, thanks for catching this! Yeah, the signing data was changed at the last minute to help w/ the aggregation scheme and it led to some rushed edits so that it could be included in the pre-release.

I'll update the language in a PR later today.

**Comment by ralexstokes** [comment]
Closing w/ #2299, feel free to re-open or raise a new issue if there are further things to clarify -- thanks!
