### ISSUE TITLE
BLS Proof of Possession Explanations 

### ISSUE THREAD

**Issue by terenc3t** [ethereum/eth2.0-specs#23]
Can we include a short section on `BLS proof of possession`? Manly how do we generate? What's the standard formula? I think this needs to be a different hash function which beacon chain shall support

**Comment by mratsim** [comment]
See also @vbuterin here: https://github.com/ethereum/eth2.0-specs/issues/22#issuecomment-426625412, for the hash function it would be the 32 ..< 64 slice of blake2b-512

**Comment by djrtwo** [comment]
We generate by signing the hash of some message (likely the public key) where the hash is an alternative to the one we will be using.

This is noted as missing in the spec and will be added soon. closing this issue for now
