### ISSUE TITLE
SSZ question: maximum length of serialized integer

### ISSUE THREAD

**Issue by cleishm** [ethereum/eth2.0-specs#231]
The current [SSZ specification](https://github.com/ethereum/eth2.0-specs/blob/ff2551e754028260a619c1b538ac194568f1eff2/specs/simple-serialize.md#serializeencode) only specified that the integer length must conform to `int_size % 8 == 0`. It does not specify the maximum bit length.

However, the Tree Hash definition says to [return the serialization of `uintN` when creating the hash](https://github.com/ethereum/eth2.0-specs/blob/ff2551e754028260a619c1b538ac194568f1eff2/specs/simple-serialize.md#uintn-bool-address-hash32). If `int_size` is permitted to exceed 256, this will return more than 32 bytes for hashing.

So the question is: are we missing a constraint on the maximum bit length of an integer, or has the Tree Hash failed to account for intN where N > 256?

**Comment by hwwhww** [comment]
Hmm, we definitely want to serialize the integer that the size is larger than 256 bits (currently, `uint384` in the spec). I think maybe we can add a new rule for tree hash, e.g.,
* `uint0, ..., uint256`: return the serialization of the value.
* `uint264, ... uintN`: return the hash of the serialization of the value.

**Comment by mkalinin** [comment]
I would, also, propose to return plain value instead of its hash in case if field has `hashN, N <= 32` type. It could save us some hash operations.
