### ISSUE TITLE
Participation rewards are skipped for epoch prior to Altair upgrade

### ISSUE THREAD

**Issue by michaelsproul** [ethereum/eth2.0-specs#2314]
The [`upgrade_to_altair`](https://github.com/ethereum/eth2.0-specs/blob/v1.1.0-alpha.3/specs/altair/fork.md#upgrading-the-state) function which transitions the chain from phase0 to Altair initialises the participation bits in `previous_epoch_participation` to zero, which discards the information in the phase0 state's `previous_epoch_attestations`. This causes any validator who attested correctly in the epoch prior to the fork and had their attestation included on chain to be penalised as if they did not attest. The first epoch transition after the fork will consult `previous_epoch_participation` and find it mostly empty.

One solution would be to try to pack the prior epoch attestations into the blocks of the fork epoch. However, this doesn't interact well at all with the rewards for timeliness. Even if an attester was prompt in getting their attestation on chain in the previous epoch, by the time the fork epoch occurs they'll be too late for the timely head or source rewards (1 and 5 slots, respectively) and probably too late for the target reward (32 slots). Further, these late attestations would be competing with current epoch attestations for block space.

Alternatively, the `upgrade_to_altair` function could perform a translation of the data in `previous_epoch_attestations` so that rewards are computed correctly for the attestations that already made it on chain. I think we could afford to be generous if computing the participation bits precisely is too much effort, although I don't see any issues that would prevent us from doing it exactly.

**Comment by vbuterin** [comment]
I expect realistically the answer may well end up being "nobody cares about a single epoch messing up; it's not worth the added complexity". The challenge is that it's just harder to design and reason about a hard fork if you have to think about interaction effects between pre-fork and post-fork activity.

**Comment by ajsutton** [comment]
I wonder if its worth just going the other way then and have the transition set all participation flags to 1.  That avoids penalising honest validators and is effectively a payment to validators to upgrade and I don't mind the idea of incentivising that.

**Comment by michaelsproul** [comment]
Yeah, although it's only 1 epoch worth of rewards and users probably _shouldn't_ care, I think they'll be watching the fork and will notice a sea of red.

I'm happy with the "reward everyone" strategy which avoids the translation complexity.

**Comment by djrtwo** [comment]
I we do all 1's for the flags, we also trigger finality calculations artificially. Which is dangerous

options I can think of:

1. Just manually update balances to have +max base rewards to account for the degradation. Downside is that the wave of red will still happen at end of next epoch. It will just be cancelled out
2. attempt to manually map previous_epoch_attestations to flags. Can't get this 100% correct because timeliness is lost, but you can do a decent job. Major downside here is that it's complicated and would require a bunch of edgecase testing

**Comment by michaelsproul** [comment]
I've had a go at implementing the translation, as I think that's the best way to address this issue: no special casing in the accounting functions, no sea of red, and it's mostly expressible in terms of a helper function that's used in `process_attestation`: https://github.com/ethereum/eth2.0-specs/pull/2373
