### ISSUE TITLE
Should TARGET_AGGREGATORS_PER_SYNC_SUBCOMMITTEE be in config?

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-specs#2317]
In phase0 the `TARGET_AGGREGATORS_PER_COMMITTEE` constant is in the config files but for Altair the equivalent for sync committees, `TARGET_AGGREGATORS_PER_SYNC_SUBCOMMITTEE` is specified in the honest validator guide but not included in the config files.

Was it deliberately omitted or just missed?

**Comment by djrtwo** [comment]
should be!
