### ISSUE TITLE
SignedContributionAndProof gossip validation does not check validator is in subcommittee

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-specs#2324]
The honest validator spec says that each slot members of each subcommittee are selected to aggregate (https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/validator.md#sync-committee-contributions).  My understanding is that validators would only check if they are an aggregator for the subcommittees they are in, not all subcommittees.

But the gossip validation only checks that the aggregator's validator index is within the current sync committee, not the specific subcommittee (https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/p2p-interface.md#sync_committee_contribution_and_proof):
>[REJECT] The aggregator's validator index is within the current sync committee -- i.e. state.validators[contribution_and_proof.aggregator_index].pubkey in state.current_sync_committee.pubkeys.

I believe it should be checking that the aggregator's pub key is in the sublist of `state.current_sync_committee.pubkeys` that pertains to `contribution.subcommittee_index`.  So something like `state.current_sync_commitee.pubkeys[subcommitteeIndex * (SYNC_COMMITTEE_SIZE // SYNC_COMMITTEE_SUBNET_COUNT):(subcommitteeIndex + 1) * (SYNC_COMMITTEE_SIZE // SYNC_COMMITTEE_SUBNET_COUNT)` and I really hope there's a nicer way to write that in python.

**Comment by djrtwo** [comment]
yes you are correct on this. thanks!

**Comment by djrtwo** [comment]
A few more notes about the sync contribution gossip conditions: 

> contribution_and_proof.selection_proof selects the validator as an aggregator for the slot -- i.e. is_sync_committee_aggregator(state, contribution.slot, contribution_and_proof.selection_proof)

This condition is off. Incorrect function signature

> [IGNORE] The sync committee contribution is the first valid contribution received for the aggregator with index contribution_and_proof.aggregator_index for the slot contribution.slot.

This should also be subcommittee specific because the aggregator can be selected across multiple sub committees and it's an independent job

also, the bits set in this message should only be for the sub-committee. Otherwise, if we allow for inclusion outside the subcommittee, it would hurt aggregatability of separate subcommittee contributions. We actually assume this property in the following statement from validator guide block proposal:

> Proposers should select the best contribution seen across all aggregators for each subnet/subcommittee when preparing a block

**Comment by ajsutton** [comment]
> also, the bits set in this message should only be for the sub-committee. Otherwise, if we allow for inclusion outside the subcommittee, it would hurt aggregatability of separate subcommittee contributions.

Isn't that true by definition? From https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/validator.md#aggregation-bits:
```
Let contribution.aggregation_bits be a Bitvector[SYNC_COMMITTEE_SIZE // SYNC_COMMITTEE_SUBNET_COUNT], where the indexth bit is set in the Bitvector for each corresponding validator included in this aggregate from the corresponding subcommittee.
```

So bit 0 is the first validator in the subcommittee and the last bit in the vector is the last validator in the subcommittee.  Validators from other subcommittees don't have a bit representing them at all.

**Comment by djrtwo** [comment]
it is! 

sorry, we had 1024 bit length at some point but reduced
