### ISSUE TITLE
Use `ALTAIR_FORK_EPOCH` instead of `ALTAIR_FORK_SLOT`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#2326]
### Issue
It was pointed out by @mbaxter in https://github.com/ethereum/eth2.0-specs/pull/2287#issuecomment-809641372 that it seems we don't have a strong reason to use slot number instead of epoch number to define the fork boundary.

I'm 👍  on defining `ALTAIR_FORK_EPOCH` instead of `ALTAIR_FORK_SLOT`:
- It's easier to derive slot number from epoch number.
- Then it's no need to have config invariant `ALTAIR_FORK_SLOT % SLOTS_PER_EPOCH == 0`.

**Comment by djrtwo** [comment]
I agree. I can't really think of any reason to not do forks on epoch boundaries.

even if we wanted different logic at some slot. It is reasonable still to do as a small slot offset of some epoch boundary
