### ISSUE TITLE
Same Sync Committees Can Span Multiple Periods

### ISSUE THREAD

**Issue by nisdas** [ethereum/eth2.0-specs#2401]
In Altair:
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/altair/beacon-chain.md#get_sync_committee_indices

```
    base_epoch = Epoch((max(epoch // EPOCHS_PER_SYNC_COMMITTEE_PERIOD, 1) - 1) * EPOCHS_PER_SYNC_COMMITTEE_PERIOD)
```

The `base_epoch` will always be 0 for the first 2 committee periods. 
If `epoch` is in 
`0 <= epoch < EPOCHS_PER_SYNC_COMMITTEE_PERIOD` then:
`(max(epoch // EPOCHS_PER_SYNC_COMMITTEE_PERIOD, 1) - 1)` will equal 0.

If `epoch` is in 
`EPOCHS_PER_SYNC_COMMITTEE_PERIOD <= epoch < 2*EPOCHS_PER_SYNC_COMMITTEE_PERIOD` then:
`(max(epoch // EPOCHS_PER_SYNC_COMMITTEE_PERIOD, 1) - 1)` will still equal 0. 

While not an issue for mainnet as we are on epoch 36000, it might be relevant for any new devnet/testnets spun up. If this is an acceptable compromise at genesis then the issue can be ignored, thought it might be worth bringing up given how long lasting sync committees are.

**Comment by ralexstokes** [comment]
it is helpful to note and i do think it is ok to have the redundancy at genesis as this condition would only be reached in testnets like you noted -- we could extend the sampling to differentiate them but i don't think that would be worth the added complexity as we should not have this issue on mainnet

**Comment by djrtwo** [comment]
The sync committee is *always* applied to both current and next in the fork transition processing. This is for simplicity in calculation and allows for not having a truncated committee duty (instead you get a longer duty) in the event that a fork is not on a sync committee period boundary

closing!
