### ISSUE TITLE
`epoch_processing/participation_flag_updates` test type not defined

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-specs#2440]
In alpha.6 a new `epoch_processing/participation_flag_updates` test type appeared which isn't documented at https://github.com/ethereum/eth2.0-specs/blob/v1.1.0-alpha.6/tests/formats/epoch_processing/README.md

The tests pass when I treat them the same as `epoch_processing/participation_record_updates` so I suspect the naming has just gotten out of sync somewhere.

**Comment by ajsutton** [comment]
Ah, different names between phase0 and altair.  Teku maps them to the same logical operation which is why the tests pass, so test names make sense but probably good to update the README for completeness.

**Comment by hwwhww** [comment]
It will be addressed by #2435 (unmerged, yet)
