### ISSUE TITLE
Sync committee rewards occur with very low frequency. 

### ISSUE THREAD

**Issue by potuz** [ethereum/eth2.0-specs#2448]
In the current Altair Specs, only `SYNC_COMMITTEE_SIZE (512)` validators out of the current 150K on mainnet will earn rewards for over 2 days. Validators that aren't chosen to participate on the sync committee will forfeit 1/8 of their earnings until they are finally chosen. The probabilities of not being in a single sync committee for a single validator are 

```
1 month             |          95.65% 
6 months            |          76.33%
1 year              |          57.86%
2 years             |          33.37%
```

Which means that after two years of staking, we will still see at least 50K validators without earning 1/8 of their rewards. 

A proposal to remedy this is to simply get rid of the committee sync rewards, and apply a penalty to those validators that fail to participate in the committee. The total rewards can be guaranteed to be still one `base_rewards` by adjusting the weights as 

```

TIMELY_SOURCE_WEIGHT	uint64(14)
TIMELY_TARGET_WEIGHT	uint64(28)
TIMELY_HEAD_WEIGHT	uint64(14)
PROPOSER_WEIGHT	        uint64(8)
WEIGHT_DENOMINATOR	uint64(64)
```
And adding a penalty weight 

```
SYNC_PENALTY_WEIGHT	uint64(8)
```

 The changes to the current specs seem to be minimal, a WIP can be found in 

https://github.com/ethereum/eth2.0-specs/compare/dev...potuz:penalize-sync-comiittee?expand=1

Some dissadvantages of the minimal proposal above are

- Validators on the first sync committe may be penalized unfairly for the first few slots
- Validators that are offline and are assigned to a sync committee will be severely penalized

The first point can be fixed in-protocol by not penalizing on the first few epochs. The second one, under current conditions of participation rate above 99%, the probability than an offline validator is chosen for a sync committee is `3 * 10^-5` so it is negligible. 

Advantages are 

- Single stakers will be able to maintain their full rewards without the need of luck. Without this it would be beneficial for them to move to staking pools
- The penalty can be simply reduced by adjusting two parameters without modifing the invariant of one `base_reward`  earnings per epoch.

**Comment by djrtwo** [comment]
addressed in #2453
