### ISSUE TITLE
test_process_sync_committee.py does not have the right logic

### ISSUE THREAD

**Issue by potuz** [ethereum/eth2.0-specs#2460]
The current tests for Sync Committee Participation rewards do not reflect the current logic in `specs/altair/beacon-chain.md`. In particular, rewards in the former are dependent of the participant index via its effective balance, while the rewards in the latter are independent of this.

**Comment by djrtwo** [comment]
Is this addressed in current `dev` @potuz?

**Comment by potuz** [comment]
> Is this addressed in current `dev` @potuz?

Yes, it was addressed in #2465

**Comment by djrtwo** [comment]
thanks!
