### ISSUE TITLE
Better definition of winning_hash

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#248]
I'm still confused by `winning_hash`. The spec has:

> Let `winning_hash(shard_committee)` be the winning `shard_block_hash` value.

A definition with more code may be helpful. Also more intuition (e.g. via code comments) may help.

**Comment by vbuterin** [comment]
Replace:

* Let `attesting_validators(shard_committee)` be equal to `attesting_validators(shard_committee, shard_block_hash)` for the value of `shard_block_hash` such that `sum([get_effective_balance(v) for v in attesting_validators(shard_committee, shard_block_hash)])` is maximized (ties broken by favoring lower `shard_block_hash` values).
* Let `total_attesting_balance(shard_committee)` be the sum of the balances-at-stake of `attesting_validators(shard_committee)`.
* Let `winning_hash(shard_committee)` be the winning `shard_block_hash` value.

With:

* Let `winning_hash(shard_committee)` be equal to the value of `shard_block_hash` such that `sum([get_effective_balance(v) for v in attesting_validators(shard_committee, shard_block_hash)])` is maximized (ties broken by favoring lower `shard_block_hash` values).
* Let `attesting_validators(shard_committee)` be equal to `attesting_validators(shard_committee, winning_hash(shard_committee))` for convenience.
* Let `total_attesting_balance(shard_committee)` be the sum of the balances-at-stake of `attesting_validators(shard_committee)`.

**Comment by JustinDrake** [comment]
I get it now :) In words, `winning_hash(shard_committee)` is the `shard_block_hash` of the shard fork with the most votes from `shard_committee`.

A PR would be great.

**Comment by arnetheduck** [comment]
Also: make explicit where `shard_block_hash` candidates should be drawn from when maximizing
