### ISSUE TITLE
## Unit Test Results

### ISSUE THREAD

**Issue by Besiktas19033** [ethereum/eth2.0-specs#2495]
## Unit Test Results
     28 files   -        4     328 suites  +104   16m 44s :stopwatch: + 9m 39s
   628 tests +   105     610 :heavy_check_mark: +   107    18 :zzz:  -   2  0 :x: ±0 
3 440 runs  +1 084  3 336 :heavy_check_mark: +1 096  104 :zzz:  - 12  0 :x: ±0 

Results for commit 4ef784fa. ± Comparison against base commit 7ffa8c28.

<details>
  <summary>This pull request <b>removes</b> 60 and <b>adds</b> 165 tests. <i>Note that renamed tests count towards both.</i></summary>

```
Attestation gets processed at epoch [Preset: mainnet]
CONFIG_NAME                                       &quot;mainnet&quot;            [Preset: mainnet]
CONFIG_NAME                                       &quot;minimal&quot;            [Preset: minimal]
Compile
Final updates - effective_balance_hysteresis [Preset: mainnet]
Final updates - eth1_vote_no_reset [Preset: mainnet]
Final updates - eth1_vote_reset [Preset: mainnet]
Final updates - historical_root_accumulator [Preset: mainnet]
HashList
Passes from genesis state, empty block [Preset: mainnet]
…
```

```
  Testing    ContributionAndProof
  Testing    LightClientSnapshot
  Testing    LightClientUpdate
  Testing    SignedContributionAndProof
  Testing    SyncAggregate
  Testing    SyncAggregatorSelectionData
  Testing    SyncCommittee
  Testing    SyncCommitteeContribution
  Testing    SyncCommitteeSignature
Effective balance updates - effective_balance_hysteresis [Preset: mainnet]
…
```
</details>

:recycle: This comment has been updated with latest results.

_Originally posted by @github-actions in https://github.com/status-im/nimbus-eth2/pull/2663#issuecomment-865017941_

**Comment by Besiktas19033** [comment]
Wallet

**Comment by ralexstokes** [comment]
does not look actionable for this repo
