### ISSUE TITLE
Engage community on interest rate

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#251]
Started spreading the word in [this tweet](https://twitter.com/drakefjustin/status/1070785586917711872). So far everyone who replied seems to agree that interest rates need to be increased.

My suggestion is to have no more than 1% inflation with 2^24 ETH (~16.8 million ETH) effective stake, corresponding to 2^19 validators (~0.5m validators).

**Comment by nisdas** [comment]
@JustinDrake What would be the basis for 1% , or any other arbitrary percentage. Is there any hard data we can rely on when choosing the interest rate for staking ? Right now it feels like everyone is going on gut feeling when choosing the interest rate, which is not a good way of determining what would effectively be the annual increase in the supply of ether in ETH 2.0 .

**Comment by vindberg** [comment]
It seems low compared to other blockchains. Have you considered adding a warm-up period E.g. the first 5 years it should generally be higher while the validators industry matures and number of transactions are relatively low.

It might help stabilize the interest for validators if inflation is relative to the combined value from transaction fees (maybe of the last epoch).

**Comment by JustinDrake** [comment]
> What would be the basis for 1%

It's a convenient shelling point (nice round number). Telling the community "inflation is less than 1%!" is an easy sell, IMO.

**Comment by djrtwo** [comment]
I want to see better models on the costs to run a normal validator machine -- say ~5-10 validator instances. Without understanding the fixed costs of a normal consumer setup, discussions of appropriate interest rate are very difficult.

**Comment by vbuterin** [comment]
> I want to see better models on the costs to run a normal validator machine -- say ~5-10 validator instances. Without understanding the fixed costs of a normal consumer setup, discussions of appropriate interest rate are very difficult.

At present the simplest approximation is bandwidth, and for that we have fairly clear numbers: 16 KB per 6 seconds per shard, so minimum 2.67 KB/s, maximum 2.67 KB/s * 1024 = 2.67 MB/s.

**Comment by crsCR** [comment]
> I want to see better models on the costs to run a normal validator machine -- say ~5-10 validator instances. Without understanding the fixed costs of a normal consumer setup, discussions of appropriate interest rate are very difficult.

True - also any(?) 'labour' cost of operation needs factoring in.... (Opportunity cost and risk should be factored in too I guess.)

And I'm assuming you're talking about costs for the setup and running of beacon nodes and not just validator clients - referring to: https://github.com/ethereum/eth2.0-specs/issues/157

**Comment by IvanTheGreatDev** [comment]
I'd honestly favor an inflation closer to 1%, maybe even around 2%. 

Are there any systems planned for ETH2.0 like the difficulty bomb that will force organized upgrades? I'd really favor a automatic reducing inflation system like Bitcoin's.

**Comment by Swader** [comment]
Excellent analysis on the topic of profitability: https://tokeneconomy.co/validator-economics-of-ethereum-2-0-part-one-bc188173cdca
