### ISSUE TITLE
Clarify SyncCommittee aggregation behaviour when no participants are found

### ISSUE THREAD

**Issue by ajsutton** [ethereum/eth2.0-specs#2527]
On altair-devnet-0 we're getting some `SignedContributionAndProof` messages published with no aggregation_bits set. Currently Teku considers these invalid based on:

```
[REJECT] The aggregate signature is valid for the message beacon_block_root and aggregate pubkey derived from the participation info in aggregation_bits for the subcommittee specified by the contribution.subcommittee_index.
```

But we should clarify whether the correct behaviour is:

1. Publish an empty aggregate with the infinite signature (and thus verify the signature with `eth2_fast_aggregate_verify`)
2. Skip publishing the aggregate

Since there are no rewards for producing aggregates and an empty aggregate has no value, I'd suggest option 2 and just clarify that in the validator spec.

**Comment by djrtwo** [comment]
Ah, option 2 should be it, imo

Also at a minimum, the aggregator should ahve their single bit set... 

I'll get a pr up
