### ISSUE TITLE
about eth2.0 staking

### ISSUE THREAD

**Issue by puffanddmx** [ethereum/eth2.0-specs#2551]
Hello

I have a question.

I know people are staking eth to become a validator in eth 2.0. 

Is it possible to participate in eth staking even with a contract address that is not a general eth address?

If possible, ask how to delegate eth in the contract code.

**Comment by hwwhww** [comment]
Yes, you can use Ethereum mainnet contract address to make a deposit (staking) transaction to the deposit contract or to generate the [withdrawal credentials](https://launchpad.ethereum.org/en/faq#withdrawal-credentials).

This is a repository for the specification discussion. Please visit the launchpad FAQ and [ethstaker community](https://www.reddit.com/r/ethstaker) to get further supports. 🙂
