### ISSUE TITLE
Proposal of adding fork version to beacon block

### ISSUE THREAD

**Issue by mkalinin** [ethereum/eth2.0-specs#256]
### Rationale
With this improvement blocks from side chains that hasn't been forked for some reason could be rejected on early stage. This is something that eth1.0 lacking where blocks from invalid chains could be detected either if validating parameters (like difficulty) have been changed or after the import that is the worst case.

**Comment by JustinDrake** [comment]
I'm tempted to add the fork version to *all* messages that validators sign (and gossip) with middleware 
logic to verify the fork version alongside the signature. The relevant messages are:

1) beacon blocks
2) attestations
3) exits
4) withdrawals (for phase 2)

Deposit messages should probably *not* be specific to `fork_data`. That is, a deposit on Ethereum 1.0 should be reflected in all Ethereum 2.0 forks and the following snippet has a bug. cc @djrtwo @vbuterin

```
    assert BLSVerify(
        pub=pubkey,
        msg=hash(bytes32(pubkey) + withdrawal_credentials + randao_commitment),
        sig=proof_of_possession,
        domain=get_domain(
            fork_data,
            current_slot,
            DOMAIN_DEPOSIT
        )
    )
```

**Comment by vbuterin** [comment]
Why not just add forkdata to messages at the network layer? This seems like it probably should be done anyway, so that hard forks are clean at the network layer too.

**Comment by JustinDrake** [comment]
> Why not just add forkdata to messages at the network layer?

The forkdata can be manipulated at the network layer if it's not part of the consensus message, allowing replay attacks.

> This seems like it probably should be done anyway, so that hard forks are clean at the network layer too.

Doing it at the consensus layer is stronger than doing it at the network layer. That is, clients can just look at the fork data in the consensus messages for the network layer too.

**Comment by vbuterin** [comment]
> Doing it at the consensus layer is stronger than doing it at the network layer. That is, clients can just look at the fork data in the consensus messages for the network layer too.

Sure, but we _are_ doing it at consensus layer via domain separation.

In fact, our domain separation spec is almost literally equivalent to putting the fork version at the beginning of the message (I think the only difference is there's an extra layer of hashing sometimes).

**Comment by mkalinin** [comment]
> In fact, our domain separation spec is almost literally equivalent to putting the fork version at the beginning of the message (I think the only difference is there's an extra layer of hashing sometimes).

Indeed. Signature verification will be running for every message right _before_ any following steps (would it be block import or attestation propagation or anything else). Including `ForkData` in signature does the trick.

**Comment by JustinDrake** [comment]
I think this concern is addressed. Feel free to reopen @mkalinin :)
