### ISSUE TITLE
Do we *need* MIN_VALIDATOR_REGISTRY_CHANGE_INTERVAL?

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#260]
Originally `MIN_VALIDATOR_REGISTRY_CHANGE_INTERVAL` was added to prevent the validator registry from changing literally every slot when we were doing cycles. At this point, however, I'm not as sure that it's necessary, and I don't think it would break anything to remove it, and instead just have a simple condition `last_finalized_block > last_validator_set_change_slot`.

**Comment by JustinDrake** [comment]
In phases 0 and 1 we don't allow for re-registrations so I guess we're safe :)

For phase 2 I suggest either adding a withdrawal fee or an equivalent of `MIN_VALIDATOR_REGISTRY_CHANGE_INTERVAL`, otherwise polluting `validator_registry` with junk will be close to free.

**Comment by vbuterin** [comment]
Turned into a PR https://github.com/ethereum/eth2.0-specs/pull/340

**Comment by hwwhww** [comment]
closing in favor of #340.
