### ISSUE TITLE
Remove validators from persistent committees after exit

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#272]
At the moment `exit_validator` removes a validator from the persistent committees when updating the status `ACTIVE_PENDING_EXIT`. We should wait for an exit event (`EXITED_WITHOUT_PENALTY` or `EXITED_WITH_PENALTY`) to remove a validator from the persistent committees.

**Comment by djrtwo** [comment]
pulled this list from #253 

* Replace the code under # Exit validator with a call to exit_validator
* Only remove validator from persistent committees and update validator_registry_delta_chain_tip if there's an actual exit event (i.e. EXITED_WITH_PENALTY or EXITED_WITHOUT_PENALTY).
* Abstract away all the grunt work around status changes (e.g. regarding validator_registry_delta_chain_tip, status, latest_status_change_slot) into an update_validator_status function.

**Comment by djrtwo** [comment]
ah, closing in favor of #274
