### ISSUE TITLE
SSZ: when to do padding

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/eth2.0-specs#276]
> For the final output only (ie. not intermediate outputs), if the output is less than 32 bytes, right-zero-pad it to 32 bytes.

https://github.com/ethereum/eth2.0-specs/blob/ebc136a3bdfa6a07b1db7ba44f622683475bdacd/specs/simple-serialize.md#tree-hash

This probably deserves being firmed up a bit, so we agree on the same padding, for example when fixing #273

**Comment by arnetheduck** [comment]
I believe it may be useful to keep two functions around:

* `SSZTreeHash` for all intermediate updates
* `SSZTreeHashFinal` for cases where the final (padded) hash

this will help alleviate any ambiguities as to which one should be used in which situation, specially when referencing the hash function from outside

**Comment by JustinDrake** [comment]
I think this has been addressed (we now have `hash_tree_root_internal` and `hash_tree_root(x) = zpad(hash_tree_root_internal(x), 32)` 👍
