### ISSUE TITLE
Document error conditions

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/eth2.0-specs#293]
In several places, the specification notes that properties should be verified (ie `Verify that block.slot == state.slot`).

Since these checks are related to new blocks, it seems like simply ignoring the block and doing normal slot processing is the right thing, though this should be made clear in the spec, specially given the new per-slot processing.

**Comment by arnetheduck** [comment]
Another nasty condition: 
the last thing to check after applying a block is the state root - if this verification fails, all changes must be unwinded, and epoch processing must be done anew, without the "bad" block

**Comment by djrtwo** [comment]
@arnetheduck That could be the most convincing argument for putting per-block processing after per-epoch processing I've seen yet.

@nisdas you only write after successful processing but you still have to do a bunch of computation if you choose to try to process a block

**Comment by djrtwo** [comment]
@arnetheduck As per your original comment. It all depends on your local processing strategy.
That said, I'm more and more convinced that doing `per-slot` (which includes epoch) and then `per-block` gives us a more flexible configuration for clients to be clever about how they choose to do things locally

**Comment by arnetheduck** [comment]
@djrtwo what I like most of all about the epoch-first approach is that the block processing then no longer depends on an intermediate state where `state.slot` has been updated, but many of the fields that are linked to it have not - it keeps those related state changes closer to each other.

that said, I haven't analyzed the impact it would actually have in terms of simplicity, on the block-processing side of things, in terms of adjusting the various indices, making sure there's enough coverage of randomness etc

**Comment by arnetheduck** [comment]
ie one obvious downside is that when you do it that way, there's no state ever that has an empty work list - there will always be attestations waiting to be processed in the state..

**Comment by djrtwo** [comment]
Spec notes that unhandled failed asserts in blocks are considered invalid

https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#notation
