### ISSUE TITLE
Add aggregation description to BLS document

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#300]
- [x] Add `aggregate_pubkeys` function description
- [x] Add `aggregate_signatures` function description
- [x] Rename `bls_verify.md` -> `bls_signature.md`

TBD:
* Add more description: BLS signature scheme for Ethereum 2.0: Aggregate and Multi-Signatures based on BLS (Boneh–Lynn–Shacham) over BLS12-381.

**Comment by vbuterin** [comment]
Addressed with https://github.com/ethereum/eth2.0-specs/pull/316

**Comment by hwwhww** [comment]
closing in favor of #316
