### ISSUE TITLE
Target Committee Size inconsistency

### ISSUE THREAD

**Issue by benjaminion** [ethereum/eth2.0-specs#321]
Regarding `TARGET_COMMITTEE_SIZE`, the spec currently has a note as follows,

> For the safety of crosslinks a minimum committee size of 111 is recommended...  The shuffling algorithm generally ensures (assuming sufficient validators) committee sizes at least `TARGET_COMMITTEE_SIZE // 2`.

The second part seems incorrect: `get_new_shuffling()` produces committees of size at least `TARGET_COMMITTEE_SIZE` (not divided by two).

The current value for `TARGET_COMMITTEE_SIZE ` is 256. In view of the first part of the comment, ought it be 128?

**Comment by djrtwo** [comment]
Nice catch! Making a PR

My ramblings to further explain:

With the current algorithm `TARGET_COMMITTEE_SIZE` ends up being the min and the committee size fluctuates at or above that min as a function of vset size, epoch length, and num shards. (until you get to below `EPOCH_LENGTH * TARGET_COMMITTEE_SIZE` validators at which the committees start to drop below the target.

By making `TARGET_COMMITTEE_SIZE` 256 we are being twice as strict for active validator size requirements to crosslink X shards per epoch than if we went with 128. and 128 still guarantees we are above the 111 from the blog post (until times of very small v set and thus decreased security anyway)

**Comment by vbuterin** [comment]
Agree with cutting the committee size!

It's worth noting that cutting the committee size has another important benefit. If on average a committee has size n, then a validator with > 1/n of the stake will need to process almost the entire chain. Pushing n down reduces the number of validators who will need to do that.

**Comment by djrtwo** [comment]
And by chain, you mean _all_ the chains.

**Comment by vbuterin** [comment]
Yes :)
