### ISSUE TITLE
Be stricter with `get_attestation_participants`

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#329]
At the moment `get_attestation_participants` has a single `assert`:

> assert len(participation_bitfield) == ceil_div8(len(shard_committee.committee))

We also need to check that:

* `participation_bitfield` is not all zero (`bls_verify` isn't defined when the pubkey is 0—it would actually be natural to have it return `True`.)
* If `len(shard_committee.committee) % 8 != 0` the unused bits should be set to 0.

Something similar should be done for `custody_bitfield`.

**Comment by djrtwo** [comment]
handled in #488
