### ISSUE TITLE
Attestation inclusion rewards

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#335]
Currently, the proposer rewards for attestation inclusions are calculated as follows:

> For each v in previous_epoch_attesters, we determine the proposer `proposer_index = get_beacon_proposer_index(state, inclusion_slot(v))` and set `state.validator_registry[proposer_index].balance += base_reward(v) // INCLUDER_REWARD_QUOTIENT`.

Are we sure this is the formula that we want?

One possible alternative is a hard and universal rule that the proposer gains 1/32 of attestation rewards that occur during state execution of their blocks. This could make economic reasoning simpler, particularly around griefing factors and cooperation incentives, and the principle could be extended to other kinds of proposer rewards that get added later on if desired.

**Comment by djrtwo** [comment]
+1 for simplicity.

Also makes the value proposing not dependent upon the validator's current stake. There is no penalty for not proposing either so it make sense to cleanly incentivize this as a bonus based upon the work done.

**Comment by djrtwo** [comment]
This is no longer feasible given that proposer rewards happen per block and that a proposer cannot be reliable retrieved outside of the context of the exact slot.
