### ISSUE TITLE
`Block.parent_root` redundant?

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/eth2.0-specs#336]
Now that we have `BeaconState.latest_block_roots`, is `Block.parent_root` redundant, given that the block already maintains a `state_root` that can be followed to reach the the parent block?

 966f2bf

**Comment by vbuterin** [comment]
The hash of a block at slot N only gets included into the state during the execution of slot N+1 and that information is grabbed _from_ the block's parent root. So no, it's not redundant unfortunately.

**Comment by arnetheduck** [comment]
right.

should that be verified then, as part of block processing? that `BeaconState.latest_block_roots[-1] == `block.parent_root` by the time we enter the "Block processing" section - right at the time when `block.slot == state.slot`?

**Comment by vbuterin** [comment]
See the line:

* Set `state.latest_block_roots[(state.slot - 1) % LATEST_BLOCK_ROOTS_LENGTH] = previous_block_root`.

That's what it's doing.

**Comment by arnetheduck** [comment]
Right - though that part is run even when a new block is not available (part of "Per-slot processing"), so I'd presume `previous_block_root` has to passed to the state transition function separately rather than being taken from the the new presumptive block.

**Comment by djrtwo** [comment]
It depends on how you view the slot processing.

If you view it as the following, then everything is contained within the new block to process the state transition.
```python
state_transition(state, block):
    while state.slot < block.slot
        state = per_slot_transition(state, block.parent_root)
        if block.slot == state.slot:
            state = per_block_transition(state, block)
    return state
```

If instead, you are opportunistically processing slots without a new incoming block, you are implicitly assuming what the parent of the next incoming block will be. So you are doing the above state transition function but just halting before you get to the `per_block_transition` part for the future block.

If you happen to get an incoming block with a different parent than what you have been opportunistically processing slots for, then you would have to rewind to the different parent and do the full state transition as I showed in the above function.


Opportunistically processing slots is an exceptional case of doing the normal full block by block state transition. At the end of the day, this is a blockchain and the high level transition when processing chain is really block-by-block. We just have some granular bookkeeping happening in this block-by-block transition when slots were skipped between the blocks in the chain.

**Comment by arnetheduck** [comment]
alright, I think I found the lines that disambiguate this:

`* The parent block with root `block.parent_root` has been processed and accepted.` and `* Let `previous_block_root` be the `hash_tree_root` of the previous beacon block processed in the chain.` together dispel this ambiguity regardless of opportunism or not - thanks for the explanations!
