### ISSUE TITLE
In-place replacement for `shard_committees_at_slots`

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/eth2.0-specs#348]
Assuming `shard_committees_at_slots` is here to stay / #191 is not implemented, https://github.com/ethereum/eth2.0-specs/pull/331 would be nice to do for it: 

* no underflows at chain start
* less hashing all over
* no dependency on `state.slot` (this is problematic because of the timing dependency between `state.slot` and `shard_committees_at_slots` updates during state transitions)

**Comment by JustinDrake** [comment]
Closing this issue given that `shard_committees_at_slots` is not here to stay. Feel free to reopen @arnetheduck :)
