### ISSUE TITLE
`shard_committees_at_slots` missing when processing previous epoch attestations

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/eth2.0-specs#352]
The scenario is the following:

At slot 6, we included an attestation for slot 1. We advance through time all the way to slot 127. The next slot will be an epoch update. We start the slot processing by increasing `state.slot` to 128. Then we proceed through the functions until we pick out `previous_epoch_attestations = [a for a in state.latest_attestations if state.slot - 2 * EPOCH_LENGTH <= a.slot < state.slot - EPOCH_LENGTH]` - our attestation from slot 1 fits this criteria (`0 <= 1 < 64`). 

We call `get_attestation_participants` which calls `get_shard_committees_at_slot(state, 1)` which computes:
`earliest_slot_in_array = state.slot - (state.slot % EPOCH_LENGTH) - EPOCH_LENGTH` or `128 - 0 - 64 = 64`. 

subsequently, `    assert earliest_slot_in_array <= slot < earliest_slot_in_array + EPOCH_LENGTH * 2` fires.

related to #348, #92, #323

c8efdc7

**Comment by arnetheduck** [comment]
I'd love to, but that causes another error with `get_beacon_proposer_index(state, state.slot)` - at the epoch boundary there's no longer coverage for the proposer!

**Comment by djrtwo** [comment]
yeah, yeah, subtle quirks in shuffling and helpers.
on it!

**Comment by JustinDrake** [comment]
Is this addressed @djrtwo?
