### ISSUE TITLE
Only allow EXITED states to be overwritten

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#353]
# Issue
The current validator state transition technically allows for an `ACTIVE` validator of balance 0 to be overwritten by an incoming validator. Although I'm not even sure this scenario can occur due to ejections, it seems like a potential future source of error or reasoning complexity to leave this link open in the diagram below:

![screen shot 2018-12-22 at 7 21 07 am](https://user-images.githubusercontent.com/1433595/50374880-520ab480-05ba-11e9-993b-1d605235746d.jpg)

# Proposed Solution
Add `if is_exited_validator(validator)` helper and utilize within the overwrite conditional within `min_empty_validator_index`

```python
def min_empty_validator_index(validators: List[ValidatorRecord],
                              validator_balances: List[int],
                              current_slot: int) -> int:
for i, (v, vbal) in enumerate(zip(validators, validator_balances)):
    can_be_overwritten = (
        vbal == 0 and
        v.latest_status_change_slot + ZERO_BALANCE_VALIDATOR_TTL <= current_slot and
        v.state == WITHDRAWN
    )
    if can_be_overwritten:
        return i
return None
```

**Comment by hwwhww** [comment]
With #354, should the condition `is_exited_validator(v)` be changed to `v.status == WITHDRAWN`?

**Comment by djrtwo** [comment]
Yes

**Comment by djrtwo** [comment]
Might not need `vbal == 0` if we have a withdrawn status

**Comment by vbuterin** [comment]
Yep, that sounds correct.

**Comment by JustinDrake** [comment]
The state machine around validator statuses has been greatly simplified and I imagine this is no longer an issue. Feel free to reopen @djrtwo :)
