### ISSUE TITLE
Reduce justification/finalization threshold from 2/3 to 5/8

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#357]
Reasoning:

* Safety faults are relatively unlikely, because they are accountable and the easiest to extract large penalties for
* At least a small percentage of honest nodes is going to be offline regardless
* Users seem afraid of high inactivity leaks (eg. see https://www.reddit.com/r/ethereum/comments/a8jnrh/future_staking_questions/), this will reduce both the chance and the maximum net losses to inactivity leaks

Expected consequences:

* In the "model world" (everyone online, super-high network latency, attackers are optimal), this will reduce safety fault tolerance from ~30% to ~22%, but increase liveness fault tolerance from ~33% to ~37.5%.
* In the real world, because of unavoidable honest nodes going offline, it may well be the case that de facto safety fault tolerance is currently higher than de facto liveness fault tolerance, and this will correct for this.

**Comment by JustinDrake** [comment]
I'm tempted to stick with 2/3 purely for the sake of conceptual simplicity ("2/3" is a canonical threshold in various designs).

> Users seem afraid of high inactivity leaks

In the January AMA inactivity leaks didn't seem to be a significant worry.

Please reopen if you still think this is a good move :)
