### ISSUE TITLE
latest_penalized_exit_balances not updated correctly

### ISSUE THREAD

**Issue by arnetheduck** [ethereum/eth2.0-specs#360]
Some notes about `update_validator_registry`:

* there's a `return` at the end that shouldn't be there
* `latest_penalized_exit_balances` needs to be accessed through `state.latest_penalized_exit_balances`
* `state.latest_penalized_exit_balances` is initialized to empty list never grown, so accesses will be invalid

https://github.com/ethereum/eth2.0-specs/blob/a2422de686b026c9a85549331c2a3181fa369ccc/specs/core/0_beacon-chain.md#validator-registry

**Comment by vbuterin** [comment]
I think all three are now fixed since my recent big PR.
