### ISSUE TITLE
Add missing type hints

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#370]
A few functions definitions are missing type hints.

* `merkle_root`
* `to_penalize`
* `deposit`
* `get_ancestor`
* `lmd_ghost`
* `get_vote_count`
* `hash`
* `xor`

**Comment by hwwhww** [comment]
Currently, the type hinting is in Python style and Python doesn't have strict integer size. (e.g., we can't define an "unsigned 64-bit integer" variable in Python). In Py-EVM, [we are planning to do more custom typing like `Hash32`](https://github.com/ethereum/py-evm/issues/1383), and it could be also refect to the spec.

For example, in Py-EVM, we will define:
```python
SlotNumber = NewType('SlotNumber', int)  # uint64
```

And in the spec, maybe somewhere before `Constants` section:

### Custom Types

We define the following custom types for type hinting and readability:

| Name | Type | Description |
| - | - | - |
| `SlotNumber` | unsigned 64-bit integer | the number of a slot |
| `ShardNumber` | unsigned 64-bit integer | the  number of a shard |
| `ValidatorIndex` | unsigned 24-bit integer | the index number of validator in the registry |
| `Gwei` | unsigned 64-bit integer | the amount in Gwei |

...etc.

And in the helper functions, we can use the custom types, e.g.,:

```python
def min_empty_validator_index(validators: List[ValidatorRecord],
                              validator_balances: List[Gwei],
                              current_slot: SlotNumber) -> ValidatorIndex:
    for i, (v, vbal) in enumerate(zip(validators, validator_balances)):
        if vbal == 0 and v.latest_status_change_slot + ZERO_BALANCE_VALIDATOR_TTL <= current_slot:
            return i
    return None
```
