### ISSUE TITLE
`Exit` processing is not strict enough

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/eth2.0-specs#385]
Looking at the exit processing: https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#exits-1

we require validators to sign the `ZERO_HASH` to generate a signature for their `Exit` message.

This leaves an attack vector where the block proposer including such an `Exit` message can change the fields of the message -- in this case the `slot` could be moved far ahead in the future (moving it earlier in time would land us in the ground of general censorship which we will punt on here).

To nullify this type of attack, we can just require the validator to: 
(i) sign the full `Exit` message (with the `EMPTY_SIGNATURE` where appropriate like we do in a few other places in the spec)
or (ii) sign the slot number (the other fields should cause a verification error somewhere else in the message processing).

I would suggest (i) just to be consistent w/ the rest of the spec. If I don't see any further comments soon I'll put together a PR.

**Comment by JustinDrake** [comment]
> the block proposer including such an Exit message can change the fields of the message -- in this case the slot could be moved far ahead in the future

That's not the case. Notice the `domain` argument to `bls_verify` which contains `exit.slot`. That is, the BLS signature covers the `slot`.

**Comment by ralexstokes** [comment]
@JustinDrake i do see where we supply `slot` to `get_domain` which gives us the possibility of committing to `slot` with a BLS signature. However, there is still degeneracy in the signature space as the current implementation only uses `slot` to get the `fork_version`. This means that the attack I described could still be carried out within a fork.

let's say we are in `fork_version` 0 and i want to exit at `slot` 10 (e.g. because i find out that in fact i don't have the time/resources/etc to run a validating node). if `fork_version` 1 happens at `slot` 100 then in theory all validators could collude against me to prevent my exit until `slot` 99. And at that point I could have lost a bunch of ETH :(

i can say this is somewhat of an edge case so it may not be worth defending against -- we can close this issue if so. figured it was worth considering at the least :)

**Comment by JustinDrake** [comment]
> if `fork_version` 1 happens at slot 100 then in theory all validators could collude against me to prevent my exit until `slot` 99.

I'm not sure I understand how a collusion attack is related to signatures and fork versions. Validators could collude to censor exits simply by not including exit transactions in the beacon chain.

> the block proposer including such an `Exit` message can change the fields of the message

Which specific field(s) can a block proposer change in an `Exit` message?

**Comment by ralexstokes** [comment]
> I'm not sure I understand how a collusion attack is related to signatures and fork versions. Validators could collude to censor exits simply by not including exit transactions in the beacon chain.
>
> Which specific field(s) can a block proposer change in an `Exit` message?

Here is the example I have in mind.

1. I'm the validator at index 12. I want to exit so I assemble the following message and broadcast it.
```python
exit_slot = 25
validator_index = 12
privkey = load_privkey()
signature = bls_sign(ZERO_HASH, privkey, DOMAIN_EXIT)
msg = Exit(exit_slot, validator_index, signature)
broadcast_msg(msg)
```

2. Whoever receives this message can now modify the `slot` in the `Exit` message to a later slot, as long as the future slot is on the same fork, and still get a valid `Exit` message. This is because w/in a fork, the slot has no effect on the domain value.
```python
def verify_exit_message(msg, state):
    assert state.slot >= exit.slot
    return bls_verify(
        pubkey=state.validator_registry[msg.validator_index].pubkey,
        message=ZERO_HASH,
        signature=msg.signature,
        domain=get_domain(state.fork_data, msg.slot, DOMAIN_EXIT),
    )

exit_message = recv_exit_message() # Exit(exit_slot, validator_index, signature) from above
assert verify_exit_message(exit_message, state)

exit_message.slot = 99 # some slot later than what I requested, but still on the same fork.
assert verify_exit_message(exit_message, state)
```

I see two solutions, either should fix this problem:
1. Commit to the `slot` in the `Exit` message. This has the validator sign the full message (with the `EMPTY_SIGNATURE` in lieu of the actual signature) like we do in a few other places in the spec.
2. Roll the `slot` data into the domain computation like you were suggesting so that we commit to a given slot that way.

And re: collusion, the key step in realizing the above example as an attack depends on what happens when I broadcast my message. If it gets into the wrong hands then I may have to stay validating much longer than I wanted to and if I exited because I could no longer perform my validation duties then I'm risking my stake.

**Comment by JustinDrake** [comment]
> signature = bls_sign(ZERO_HASH, privkey, DOMAIN_EXIT)

The `domain` in `bls_sign` should be `get_domain(state.fork_data, exit.slot, DOMAIN_EXIT)` not `DOMAIN_EXIT`. (`DOMAIN_EXIT` would be the domain "type". Maybe it should be renamed for clarity.)

> Whoever receives this message can now modify the `slot` in the `Exit` message to a later slot

Good catch that's a bug 👍 (I incorrectly thought that the `domain` wrapped around the `slot`, but it's not the case.) My suggestion would be for the validator the sign the full message (instead of `message=ZERO_HASH`).

**Comment by ralexstokes** [comment]
> The `domain` in `bls_sign` should be `get_domain(state.fork_data, exit.slot, DOMAIN_EXIT)` not `DOMAIN_EXIT`. (`DOMAIN_EXIT` would be the domain "type". Maybe it should be renamed for clarity.)

good catch i was not being careful there but i think in general its clear enough (esp. once something resembling a type checker for a given impl lang kicks in)

> Good catch that's a bug 👍 (I incorrectly thought that the `domain` wrapped around the `slot`, but it's not the case.) My suggestion would be for the validator the sign the full message (instead of `message=ZERO_HASH`).

cool i'll put a PR together

**Comment by ralexstokes** [comment]
> > The `domain` in `bls_sign` should be `get_domain(state.fork_data, exit.slot, DOMAIN_EXIT)` not `DOMAIN_EXIT`. (`DOMAIN_EXIT` would be the domain "type". Maybe it should be renamed for clarity.)
> 
> good catch i was not being careful there but i think in general its clear enough (esp. once something resembling a type checker for a given impl lang kicks in)

i actually did this myself (i.e. https://github.com/ethereum/py-evm/pull/1697/commits/0c65f67ec47f9c4be87e199851f0b7b7896b7efb) so i now feel less confident that a type checker will catch it (as is...)

we could update the BLS spec so that something like the following exists:
```rust
type DomainType = u8; // or however many bits we want
type Domain = uint64;
```
and update the function signatures so that we consume a `DomainType` and generate a `Domain` for `get_domain` and all the places that take a `Domain` are typed.
```python
# update this one
def get_domain(fork_data: ForkData,
               slot: int,
               domain_type: DomainType) -> Domain: pass

# and for example...
def bls_verify(pubkey: uint384, 
               message: bytes32, 
               signature: [uint384], 
               domain: Domain): pass
```

thoughts?

**Comment by JustinDrake** [comment]
Adding more types such `DomainType` goes along the lines of [this](https://github.com/ethereum/eth2.0-specs/issues/370#issuecomment-450304051). I'm in favour.

**Comment by djrtwo** [comment]
Great catch! Note that the importance of the bug is that a proposer could move the slot sooner and exit you before you wanted.

The proposer gains nothing from moving the slot later because it would either do nothing if that slot had already occurred or it would just block that individual proposer from including the exit (but not affect other proposers that might include it).

**Comment by djrtwo** [comment]
Agreed that we should sign full exit message 👍
