### ISSUE TITLE
Why are validator balances no longer part of ValidatorRecord?

### ISSUE THREAD

**Issue by akhila-raju** [ethereum/eth2.0-specs#386]
Validator_balances was separated into its own UInt64 array, rather than being part of ValidatorRecord. What was the thought process behind this decision?

```
'validator_registry': [ValidatorRecord],
'validator_balances': ['uint64']
```

**Comment by JustinDrake** [comment]
It's an optimisation to minimise the amount of hashing when computing the beacon state root. The `validator_registry` (which contains most of the state) changes slowly and requires little hashing effort to maintain. The `validator_balances` is a smaller part of the state with much higher churn, hence why it is segregated.

**Comment by akhila-raju** [comment]
Thank you!
