### ISSUE TITLE
`ceil_div8` is undefined.

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/eth2.0-specs#387]
There is reference to a function in the spec (phase 0 and 1 it appears) called `ceil_div8`.

I'll suggest the following definition:

```python
def ceil_div8(x: int) -> int:
    return (x + 7) // 8
```

We should define it either as a helper or just add this text to the spec so that there is no ambiguity :)

**Comment by drozdziak1** [comment]
This expression is barely longer than the function call, and only used for `get_attestation_participants`, I'll open a PR to just inline it
