### ISSUE TITLE
Max Deposit and Max Deposits

### ISSUE THREAD

**Issue by terenc3t** [ethereum/eth2.0-specs#399]
I find it slightly confusing  `MAX_DEPOSIT` and `MAX_DEPOSITS` are so close. Given they define two very different meanings, but only one `s` apart. The developer can easily misconfigure block's max operation from 16 to 32...

**Comment by hwwhww** [comment]
What do people think about:
`MIN_DEPOSIT` -> `MIN_DEPOSIT_IN_ETHER`
`MAX_DEPOSIT` -> `MAX_DEPOSIT_IN_ETHER`
`GWEI_IN_ETH` -> `GWEI_IN_ETHER`

**Comment by Swader** [comment]
`MIN_VALIDATOR_DEPOSIT`? Clearly differentiates from the _number_ of max deposits in the other value.

**Comment by JustinDrake** [comment]
My vote is `MAX_DEPOSIT_AMOUNT` and `MIN_DEPOSIT_AMOUNT`. We no longer use "deposit" to refer to a `uint64`.

**Comment by terenc3t** [comment]
That sounds good. Happy to open a PR for` MAX_DEPOSIT_AMOUNT` and `MIN_DEPOSIT_AMOUNT` if there's no objection

**Comment by hwwhww** [comment]
@JustinDrake 
My point is indicating the denomination unit explicitly. Doesn't `MAX_DEPOSIT_AMOUNT` make it still/more confusing since we have `DepositData.amount` for the amount in gwei?

**Comment by djrtwo** [comment]
I like 
* `MIN_DEPOSIT_IN_ETH`
* `MAX_DEPOSIT_IN_ETH`
* `GWEI_PER_ETH`

I think "eth" is clear enough and very commonly used. Not opposed to "ether" if that's the consensus.
To echo @hwwhww, py-evm has had trouble in the past with denomination ambiguities, and ultimately resolved it by being very explicit in naming and typing. We've already had a number of small bugs around manipulating ether values in the spec up to this point. I think explicit in name will almost entirely eliminate these types of bugs.

**Comment by hwwhww** [comment]
#418 sounds like a great idea to solve the denomination issue.
If #418 is applied, `MAX_DEPOSIT_AMOUNT` sounds correct.

**Comment by terenc3t** [comment]
Sounds good. I'll open PR today. We can just use `MAX_DEPOSIT_AMOUNT` as `32 * 1e9`

**Comment by JustinDrake** [comment]
I believe this is address by #420 :)
