### ISSUE TITLE
Merkleise beacon chain blocks

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#40]
Currently beacon chain blocks are hashed as monoliths. This is not friendly to light clients because beacon chain blocks could be quite large (as currently specced, `attestations` and `specials` are unbounded arrays of records).

My suggestion is to hash the individual fields in a `BeaconChainBlock` (of which there are 8) and then consider those as leaves of a Merkle tree. We then replace `ancestor_hashes`, `oblique_parent_hashes`, `justified_block_hash`, etc. with `ancestor_roots`, `oblique_parent_roots`, `justified_block_root`, etc.

**Comment by JustinDrake** [comment]
For sure, (re)using the same logic as for state merkle-hashing is the way forward. (I'm just suggesting moving away from naive hashing for beacon blocks.)

**Comment by vbuterin** [comment]
Agree! And I'm suggesting doing what you want as part of a common general strategy for moving away from naive hashing for everything :)

**Comment by mkalinin** [comment]
It would be nice to make validator set a part of that strategy too.

**Comment by vbuterin** [comment]
https://github.com/ethereum/eth2.0-specs/issues/54

**Comment by JustinDrake** [comment]
Closing in favour of #54 👍
