### ISSUE TITLE
non-determinism in shuffling from `SEED_LOOKAHEAD` 

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#405]
# Issue
shufflings are calculated using a seed from `SEED_LOOKAHEAD` slots ago

```python
get_shuffling(state.latest_randao_mixes[(state.slot - SEED_LOOKAHEAD) % LATEST_RANDAO_MIXES_LENGTH], state.validator_registry, next_start_shard, state.slot)
```

The spec uses `SEED_LOOKAHEAD` for two reasons:
1. to provide more stability in the seed when used. The deeper in the chain the seed is picked from, the more likely there is consensus on the seed when used.
2. to provide lookahead on validator `shard_committee` shuffling so that the validator knows `SEED_LOOKAHEAD` slots in advance what shard they are going to have to crosslink and get get prepared.

(2) is broken as is. The call to `get_shuffling` utilizes a seed from the past but uses the active validators from present (because passes in `state.slot`).

# Proposed solution
One solution is to use the active_validators from `state.slot - SEEDLOOKAHEAD` slots ago to get the shard_committees rather than `state.slot`. This would ensure that committees are known `SEED_LOOKAHEAD` slots in advance, and this works fine as long as `SEED_LOOKAHEAD < ENTRY_EXIT_DELAY` (which it currently is).

**Comment by vbuterin** [comment]
I believe the idea is that `active_validators` should itself be predictable ENTRY_EXIT_DELAY slots in the future because all entry and exit events are delayed by ENTRY_EXIT_DELAY slots.

Am I missing some reason why this is not sufficient?

**Comment by djrtwo** [comment]
You are correct, but we need to get the validator set from when the prediction was made -- thus using `state.slot - SEED_LOOKAHEAD`

**Comment by djrtwo** [comment]
closing in favor of #407
