### ISSUE TITLE
get_shard_committees_at_slot out of range

### ISSUE THREAD

**Issue by terenc3t** [ethereum/eth2.0-specs#409]
Not sure If this is a bug, let me use an example to illustrate:

Assume the following:
* `state.slot = 128`
*  in order to get `previous_epoch_attester_indices`, we call `get_attestation_participants` with attestations from slots `0..63`
*  `get_attestation_participants` calls `get_shard_committees_at_slot`, and calculates the following:
`earliest_slot_in_array = state.Slot - (state.Slot % EPOCH_LENGTH) - EPOCH_LENGTH`
 so earliest_slot_in_array = 64
* Then asserts the following `earliest_slot_in_array <= slot < earliest_slot_in_array + EPOCH_LENGTH * 2`

Would assert fail because attestation.data.slot is `0..63`? should the earliest_slot_in_array be?
 `earliest_slot_in_array = state.Slot - (state.Slot % EPOCH_LENGTH) - 2 * EPOCH_LENGTH`

**Comment by djrtwo** [comment]
Yeah, this is a bug. I'll address it in #369 in one way or another

**Comment by djrtwo** [comment]
Closed via #492
