### ISSUE TITLE
Finalization rule 3 would return True in no case

### ISSUE THREAD

**Issue by ChihChengLiang** [ethereum/eth2.0-specs#410]
The spec says:
> Set `state.finalized_slot = state.previous_justified_slot` if any of the following are true:

where the third condition is: 

`state.previous_justified_slot == state.slot - 4 * EPOCH_LENGTH and state.justification_bitfield % 16 in (15, 14)`

Not sure if I misunderstood something, but I couldn't find a scenario that makes this condition true.

If we introduce the notation B4, ..., B1 from the [minispec](https://ethresear.ch/t/beacon-chain-casper-mini-spec/2760). This condition requires that `previous_justified_slot` stay at 4 epochs ago (B1), and the last 4 bits looks like `1110` or `1111`, that is B1, B2, and B3 in justification hashes.

Before this epoch, the bits for (B1, B2, B3) might look like `111`, `110`, or `10x`, but none of them is the case.
- `111`: The B1 would be finalized by rule 2 so no need rule 3 in next epoch.
- `110`: The previous justified slot would become B2.
- `10x`: The spec has `state.justification_bitfield |= 2` and `state.justification_bitfield |= 1` but no `state.justification_bitfield |= 4`. No way for B2 to become 1 in next epoch.

See the [test cases](https://github.com/ethereum/py-evm/pull/1690/files#diff-2f13bfb47df39a36b2fb37d93d170fcfR48).

<img width="831" alt="screen shot 2019-01-08 at 8 40 47 pm" src="https://user-images.githubusercontent.com/3391420/50831418-b8971d00-1385-11e9-8ad1-8eee0fc685d9.png">

**Comment by vbuterin** [comment]
Consider the following chain of events:

* B1 is justified, but the chain does not hear about it before the epoch ends (bitfield at time of B2: 0)
* B2 is justified, but the chain does not hear about it before the epoch ends; however, the chain does hear about B1 being justified (bitfield at time of B3: 10)
* B3 is justified, but the chain does not hear about it before the epoch ends; however, the chain does hear about B2 being justified (bitfield at time of B4: 110)
* B4 may or may not be justified, and the chain may or may not hear about it before the epoch ends; in either case, the chain does hear about B3 being justified (bitfield at time of B5: 1110 or 1111)

This way the third condition gets triggered without the second or first condition having been triggered earlier.

**Comment by ChihChengLiang** [comment]
In the 4th bullet point, `state.previous_justified_slot` becomes B2 and thus not triggering the condition.
It requires `state.previous_justified_slot == state.slot - 4 * EPOCH_LENGTH`, which should be `B1`.

**Comment by vbuterin** [comment]
Then maybe replacing that with `state.previous_justified_slot == state.slot - 3 * EPOCH_LENGTH` would fix it?

**Comment by ChihChengLiang** [comment]
If we have both:
- `state.previous_justified_slot == state.slot - 3 * EPOCH_LENGTH and state.justification_bitfield % 8 == 7`, and
- `state.previous_justified_slot == state.slot - 3 * EPOCH_LENGTH and state.justification_bitfield % 16 in (15, 14)`
This looks equivalent to 
- `state.previous_justified_slot == state.slot - 3 * EPOCH_LENGTH and state.justification_bitfield % 8 in (7, 6)`

**Comment by ChihChengLiang** [comment]
ah ... it's not. 😂

**Comment by vbuterin** [comment]
Thinking about it more, I think we may need to store additional information about justified slots and sources.

The general principle that we are claiming a subset of here is that we can call `B[1]` finalized when `B[1]` and `B[n]` are both justified, with `B[n]` having been justified using `B[1]` as a source, and additionally all epochs `B[1] ... B[n-1]` are all justified (we don't care with what source). The purpose of the latter clause is to verify that another chain's justified-block-chain can't "snake through" the gap between `B[1] .... B[n-1]` (as if it did, then there would be 2/3 justifying that block, but there would also be 2/3 justifying the block at that height in the current chain, so 1/3 get slashed).

So the real conditions that we want here are something like this:

* `B4` and `B3` are justified, `B3` being the source of `B4`
* `B4`, `B3`, `B2` are justified, `B2` being the source of `B4`
* `B3`, `B2`, `B1` are justified, `B1` being the source of `B3`

But we're not really keeping track of what is the source of what, and maybe we should?

@djrtwo @JustinDrake

**Comment by djrtwo** [comment]
* B1 is justified, but the chain does not hear about it before the epoch ends (bitfield at time of B2: 0)
* B2 is justified, but the chain does not hear about it before the epoch ends; however, the chain does hear about B1 being justified (bitfield at time of B3: 10)
> Because the chain does not know about B1 being justified during the epoch preceding B2, then valid attestations in this epoch will not target B1, but will target the same target as in the previous epoch. On chain justifications imply what a valid attestation can use as source (see attestation validity conditions below). I'm pretty sure this make the condition 3 unreachable in the current state of things.

_Relevant conditions to above note_:
* Verify that `attestation.data.justified_slot` is equal to `state.justified_slot if attestation.data.slot >= state.slot - (state.slot % EPOCH_LENGTH) else state.previous_justified_slot`
* Verify that `attestation.data.justified_block_root` is equal to `get_block_root(state, attestation.data.justified_slot)`.

**Comment by djrtwo** [comment]
Posted a comment in error -- deleted

**Comment by djrtwo** [comment]
I'm pretty sure the current surround slashing condition does not protect against this scenario. This reaches finality without having the source and target being sequential for any of the votes (ie meeting the `source_epoch_2 + 1 == target_epoch_2` condition in `is_surround_vote`).

Source is actually defined and enforced via the following validity conditions -- 
* Verify that `attestation.data.justified_slot` is equal to `state.justified_slot if attestation.data.slot >= state.slot - (state.slot % EPOCH_LENGTH) else state.previous_justified_slot`
* Verify that `attestation.data.justified_block_root` is equal to `get_block_root(state, attestation.data.justified_slot)`.

Let's break down the scenario described above. To be more explicit, let's define `J0` as some previously justified epoch some multiple of epochs before `B1`. This would be `justified_slot`/`hash` in `state` when the votes for `B1` are originally being made and thus the source of the justification of `B1`

* `B1` is justified using `J0` as source, but the chain does not hear about it before the epoch ends (bitfield at time of B2: 0) (`justified_slot`/`hash` remains `J0` at time of `B2`) [note `B1 -> J0` is not sequential]
* `B2` is justified using `J0` as source (enforced by validity conditions above), but the chain does not hear about it before the epoch ends; however, the chain does hear about `B1` being justified (bitfield at time of B3: 10) (`justified_slot`/`hash` is updated to `B1`) [note `B2 -> J0` is not sequential]
* `B3` is justified using `B1` as source (enforced by validity conditions above), but the chain does not hear about it before the epoch ends; however, the chain does hear about `B2` being justified (bitfield at time of B4: 110) (`justified_slot`/`hash` is updated to `B2`) [note `B3 -> B1` is not sequential]
* `B4` may or may not be justified (using `B2` as source), and the chain may or may not hear about it before the epoch ends; in either case, the chain does hear about `B3` being justified (bitfield at time of B5: 1110 or 1111)

If after this sequence we count `B1` as finalized, then the validator could do a surround using `J0` as source and begin finalizing a separate chain without triggering the either `no_surround_vote` or `no_double_vote`

**Comment by djrtwo** [comment]
Another potentially related note is that the phase 0 spec diverges from the mini-spec here:
> Attestations published can be included in the chain, but only if the attestation’s `justified_hash` equals the highest-slot hash in `justified_hashes`.

This diverges from the phase 0 spec in that the spec allows inclusion of second highest-slot justified_hash in state if attestations from the previous epoch are being included and a new justified hash was added at the most recent epoch boundary.

**Comment by djrtwo** [comment]
@vbuterin pointed out that we need to strengthen the "adjacent no surround" to a "full no surround" to catch these cases. 

Bringing in a third slashing condition with an additional attestation is overkill. It provides more proof that the messages signed could actually create the run of justifications to finalize, but the additional complexity isn't worth it compared to just strengthening `no_surround`

**Comment by djrtwo** [comment]
I suggest
* we strength the `is_surround_vote` as follows
* update the mini spec to reflect the disparity pointed out above
* spend additional effort on analysis of the many corner cases in this modification of FFG to handle opportunistic finality when attestations are being included quickly

```python
def is_surround_vote(attestation_data_1: AttestationData,
                     attestation_data_2: AttestationData) -> bool:
    source_epoch_1 = attestation_data_1.justified_slot // EPOCH_LENGTH
    source_epoch_2 = attestation_data_2.justified_slot // EPOCH_LENGTH
    target_epoch_1 = attestation_data_1.slot // EPOCH_LENGTH
    target_epoch_2 = attestation_data_2.slot // EPOCH_LENGTH
    return (
        (source_epoch_1 < source_epoch_2) and
        (target_epoch_2 < target_epoch_1)
    )

**Comment by vbuterin** [comment]
> update the mini spec to reflect the disparity pointed out above

Here's a concrete proposal. As I wrote above, the three conditions we need are:

* B4 and B3 are justified, B3 being the source of B4
* B4, B3, B2 are justified, B2 being the source of B4
* B3, B2, B1 are justified, B1 being the source of B3

We implement this via:

* `justification_bitfield % 4 == 3` and `justified_slot == state.slot - 2 * EPOCH_LENGTH`
* `justification_bitfield % 8 == 7` and `justified_slot == state.slot - 3 * EPOCH_LENGTH`
* `justification_bitfield % 16 in (14, 15)` and `previous_justified_slot == state.slot - 4 * EPOCH_LENGTH`

We also move the "Justification" section to after these checks, so `justified_slot` and `previous_justified_slot` actually do refer to the justified slots during the B4 and B3 epochs while this code is being run.

Does that look correct?

**Comment by JustinDrake** [comment]
If `B[i]` is finalized when `B[i], ..., B[j]` are justified and `B[i]` is the source of `B[j]`, can we include:

* B2 and B3 are justified, B2 being the source of B3

**Comment by vbuterin** [comment]
Yep, that seems reasonable.

**Comment by vbuterin** [comment]
I recommend we do this fix in the same PR that moves epoch processing to the last slot, so that we don't need to bugfix spec parts that we later immediately rewrite. @djrtwo were you going to make that PR?

**Comment by djrtwo** [comment]
Yeah, I have an outdated PR here #369 but been waiting for the invasive #408 to be merged before.

**Comment by djrtwo** [comment]
sorting through the structure of #369 and then adding this fix there
