### ISSUE TITLE
Idea: Convert to RST/Sphinx and use doctest.

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/eth2.0-specs#412]
I was perusing the spec and see there are a lot of code blocks with example code.

*If* this spec were to be converted to RST/Sphinx then you could benefit from using doctest allowing you to verify that your example implementations pass some set of test vectors, etc.

For Reference: http://www.sphinx-doc.org/en/stable/ext/doctest.html

We  use doctest in most of our python repositories and it is the single most important thing that ensures our documentation is up-to-date and doesn't diverge from the code itself.

**Comment by JustinDrake** [comment]
Executable or semi-executable specs are a good idea. I'm slowly working towards one in Go, Vitalik may be working on one in Python, and RuntimeVerification may write one in K.

Anyone who wants to take this on please reopen :)

**Comment by JustinDrake** [comment]
I think this can be closed given #835 is closed. Feel free to reopen :)
