### ISSUE TITLE
Normalize ETH units to Gwei.

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/eth2.0-specs#418]
Following up on this: https://github.com/ethereum/eth2.0-specs/pull/392#issuecomment-452381326

The proposal is to use a single unit type for ETH/wei amounts across the spec. The idea being that as soon as such an amount enters the scope of the spec, we convert to Gwei and *then* propagate the value. Doing so eliminates an entire class of errors as we don't have to worry about unit conversions in any other computations.

Looking at the Vyper code (ETH entry point) and the validator balances in the state, they already keep amounts in Gwei.  So the only places we would have to change are places where constants are being used (simply because they are in units of ETH).

The fix for this issue converts the ETH-based constants to Gwei units and removes the `_ * GWEI_PER_ETH` modifier used throughout the spec.

Happy to make a PR if this gets enough support.

**Comment by terenc3t** [comment]
I'm working on #399, it would make a lot of sense to combine the 2 issues in a single PR. 
Want me to do it? I'm happy for you to do it too =)

**Comment by ralexstokes** [comment]
@terenc3t go for it! it should just be `s/\* GWEI_PER_ETH//g`
