### ISSUE TITLE
Specify the honest behaviour for deposit_root voting

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#421]
Validators include a `deposit_root` in `BeaconBlock`s to vote for a Merkle root of the `deposit_tree` in the Ethereum 1.0 contract. For honest nodes to coordinate and reach the 1/2 vote threshold the honest behaviour for selecting the `deposit_root` needs to be specified. This may include constraints on the block height of the Ethereum 1.0 chain and a minimum number of confirmations.

**Comment by vbuterin** [comment]
Something like:

* Let D be the set of `DepositRootVote` objects `obj` in `state.deposit_root_votes` where `obj.deposit_root` is the deposit root of a block that is (i) part of the canonical chain, (ii) >= 1000 blocks behind the head, and (iii) newer than `state.latest_deposit_root`
* If D is empty, vote for the deposit root in the 1000th ancestor of the head of the canonical chain.
* If D is nonempty, vote for the member of D that has the highest `vote_count`

Does that look right?

**Comment by djrtwo** [comment]
Yeah, I added it into this WIP doc about validators https://github.com/ethereum/eth2.0-specs/pull/444

**Comment by djrtwo** [comment]
handled in #444.
fork choice is staying in beacon chain spec because it is needed to run a node independent of a validator
