### ISSUE TITLE
What is MAX_WITHDRAWALS_PER_EPOCH?

### ISSUE THREAD

**Issue by terenc3t** [ethereum/eth2.0-specs#423]
MAX_WITHDRAWALS_PER_EPOCH in `process_penalties_and_exits` was never defined. Is it a constant? do we calculate that from somewhere?

**Comment by vbuterin** [comment]
I think it should be 4; that allows 128 ETH to be withdrawn per 384 seconds, or 1/4 per second, so ~8m per year.

**Comment by terenc3t** [comment]
Cool. I'll open a PR

**Comment by djrtwo** [comment]
> I think it should be 4; that allows 128 ETH to be withdrawn per 384 seconds, or 1/4 per second, so ~8m per year.

128 eth in 384 seconds is 1/3 per second so ~10m per year.
