### ISSUE TITLE
Max length of specials

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#43]
# Issue
`Block.specials` currently has no max length. We also don't check the validity of `SpecialRecord`s until doing state recalcs. This can lead to a dos vector in which Blocks are filled with junk specials causing an increased load on block size as well as state recalc time.

# Proposed solution
- Add constant `MAX_SPECIALS_PER_BLOCK` such that block validity requires `len(block.specials) <= MAX_SPECIALS_PER_BLOCK`
- Check `SpecialRecord` validity (signature, format, etc) in block processing after checking attestation validity. Throw out block if any invalid specials
- During state recalc, `ActiveState.pending_specials` are valid so just process the related state transitions rather than the signatures at this point.

**Comment by djrtwo** [comment]
cc: @vbuterin, @JustinDrake

**Comment by JustinDrake** [comment]
Further questions:

1) How are duplicate specials handled?
2) What about specials of unknown type?
3) Is there a maximum number of `data` elements?
4) Is there a maximum byte length per special `data` element?

**Comment by vbuterin** [comment]
> How are duplicate specials handled?

More broadly, it seems like the issue is that specials are missing validity conditions. A slash should only be includable if the validator has not been already slashed, a logout should only be includable if the validator is logged in, etc. So we don't need explicit anti-duplicate rules.

> What about specials of unknown type?

I'm inclined to say ban them.

> Is the length of SpecialRecord.data bounded? Is the byte length of individual SpecialRecord.data members bounded?

I'm inclined to say not explicitly, but we can require the type-specific checkers to require exact byte length and element count.

**Comment by djrtwo** [comment]
> A slash should only be includable if the validator has not been already slashed

If we check special validity during block processing, but then only apply the effects of the special during a state recalc, then someone could easily slip in a duplicate (effect) of a special multiple times in cycle. I suppose this is also true for attestations in the current spec..

**Comment by djrtwo** [comment]
This is addressed at least in it's basic iteration in #124
