### ISSUE TITLE
SSZ: Add `bytesNN` and remove `Address`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#432]
- Add `bytesNN`
    - BLS points:
        - Per https://github.com/ethereum/eth2.0-specs/blob/c1a3b29145c84c6ac4422314b7b54898ac9f6693/specs/core/0_beacon-chain.md, it looks nice to use `bytes48` for the G1, G2 points (option 5).
    - StatusFlags:
        - the current `ValidatorRecord.status_flags: uint64` could also benefit from it. -> `bytes8` (edited)
    - (TBD) Replace `hash32` with `bytes32`.
- Remove `Address`: it's unused.

**Comment by djrtwo** [comment]
> the current ValidatorRecord.status_flags: uint64 could also benefit from it. -> bytes64

note: that `uint64` is  `bytes8`.

Also, I think it might generally be easier to bitwise manipulate integers in python rather than byte arrays. I don't feel very strongly, but @vbuterin made that argument here https://github.com/ethereum/eth2.0-specs/issues/371#issuecomment-450497143

**Comment by JustinDrake** [comment]
* +1 for removing `hash32` (in favour of `bytes32`).
* Similarly remove `hashN` (in favour of `bytesN`).
