### ISSUE TITLE
Beacon chain operations could be verified with wrong fork_data

### ISSUE THREAD

**Issue by mkalinin** [ethereum/eth2.0-specs#445]
### What's wrong
There is a BLS signature verification in chain operations that is based on `fork_data` taken from state of _current_ slot. 

If a fork had happened since a slot that operation data does refer to then BLS verification wouldn't be passed and operation would be considered as invalid.

Affected operations:
- ProposerSlashing
- CasperSlashing
- Attestation
- Exit

### Probable solution
Explicitly add `fork_data` to `data` records of each operation and pass `data.fork_data` to BLS verification.

**Comment by mkalinin** [comment]
Does it mean that when `ForkData` context is changed it becomes impossible to slash validator for the violation it made prior to this fork?

**Comment by djrtwo** [comment]
Seems that there is an implicit timing assumption that two forks that change the fork version won't happen within a single weak subjectivity period (say 4 months).

**Comment by djrtwo** [comment]
I fixed the issue in `verify_slashable_vote_data`. I think that is the only one.
Am I missing something?
