### ISSUE TITLE
Alternative hash_to_G2

### ISSUE THREAD

**Issue by mkalinin** [ethereum/eth2.0-specs#447]
### Abstract
Use HMAC based deterministic algorithm of `k` parameter generation ([rfc6979#section-3.2](https://tools.ietf.org/html/rfc6979#section-3.2)) to map a message onto `G2` point. Modified algorithm looks like:
```python
def hash_to_G2(message: bytes32, domain: uint64) -> [uint384]:
   k = generate_k(r, message, normalize_domain(domain))
   return multiply_in_G2(G2, k)
```
Where:
- `r` subgroup order;
- `generate_k` function denotes the original algorithm described in the RFC;
- `normalize_domain` function is described below.

### Specification
Original algorithm of `k` parameter generation described in the RFC uses three arguments as input. First one is a _private key_ that is eventually used to create a signature, second one is a message hash and the last one is a subgroup order `r`.

Current proposal suggests to replace _private key_ with the _domain_ parameter in the original algorithm. Since the RFC requires _private key_ parameter to belong to `[1, r-1]` range there should be a function that maps _domain_ parameter onto this range. Suggested function is:
```python
def normalize_domain(domain: uint64) -> bytes32
    result = hash(domain)
    while not 0 < result < r:
        result = hash(domain)
    
    return result
```
Where `hash` is any 256-bit hash function e.g. _keccak256_.

### Rationale
- relies on a cryptographic standard;
- an algorithm described in the RFC should have an implementation in all cryptographic libraries which provides DSA, hence, `generate_k` function implementation should be a matter of library API call;
- no `G2_cofactor` multiplication;
- no need in 384-bit hash function (if this is still actual).

### Criticism
It seems that replacing _private key_ with _domain_ parameter reduces entropy level of `generate_k` result and makes it less secure. And, indeed, if this replacement took place in the original scheme described by the standard then it would be true. But in our case it _should_ not be true.

Let's assume that input data in the original scheme, a pair `[private_key; message_hash]`, gives an output of a _certain_ level of entropy. Assuming that original scheme uses as much input data as it can to get as high level of the entropy as it could; and with a fact that in our case pair `[domain; message_hash]` is all the data that can impact on entropy level, we can assume that entropy level of `generate_k` function in our case will, also, be as high as it could be.

**Comment by vbuterin** [comment]
This is extremely insecure. The use of hashing to G2 crucially relies on the fact that nobody knows the discrete log of the point that is being generated. If the discrete log is known, as it is here, then BLS becomes attackable trivially: you can "sign" any message knowing only the public key by simply multiplying the public key by the discrete log of the message hash.

**Comment by mkalinin** [comment]
> you can "sign" any message knowing only the public key

Indeed!

**Comment by mkalinin** [comment]
@vbuterin actually, I don't see the way it's feasible. could you please elaborate? 
If signature and public key were points of the same curve then it's trivial. But they aren't.

Possible attack vector here could be based on this equation:
```
e(k * P, G2) = e(G1, d * M)

d - private key
k - message discrete log (known)
M = k * G2 - message point
P = d * G1 - public key
```
But I don't see any other way rather than brute forcing this equation that could discover `d`.

**Comment by vbuterin** [comment]
So there is a more sophisticated attack (notation: lowercase for numbers mod n, uppercase for curve points). If you see someone else's signature on a message m1, or SIG1 = priv * m1 * G2, then you can compute SIG2 = SIG1 * m2 / m1 = priv * m2 * G2, a valid signature on m2.

**Comment by mkalinin** [comment]
Got it, thanks!
