### ISSUE TITLE
Use of undefined value for ValidatorRecord.status_flags

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/eth2.0-specs#451]
@paulhauner brought up an important point we should clarify in the spec.

If you refer to the creation of a `ValidatorRecord` in `process_deposit`, the current spec provides a `0` for the `status_flags` field.

This issue requests greater clarity around how we should handle these flags to avoid consensus issues.

Is this field nullable? It seems that the use of `0` indicates "no status flags" and the values `1` and `2` are defined as given. It is assumed that decoding a value greater than `2` is an error.

How should we handle `0`? In keeping with the Pythonic nature of the spec code, I suggest we either set `status_flags` to `None` if the intent is "no status flag" or explicitly define `0` as `UNDEFINED`, `NONE` or something like this.

Other thoughts?

**Comment by djrtwo** [comment]
I'm okay with something like `DEFAULT_EMPTY_FLAGS`. These are bitflags that should be able to be set and unset. By initializing it to something non-integer, we don't have the ability to simply flip a bit to turn on a flag. Also beacuse `ValidatorRecord` is a state object, we need to keep this field defined wrt it's SSZ types. so `None` is a non-starter.

the next flags defined (if they do become defined) would be at `4`, `8`, `16,` etc for each subsequent bit

**Comment by JustinDrake** [comment]
I agree with @djrtwo that `0` does not need special handling :) Feel free to open a PR to add a constant (e.g. `GENESIS_STATUS_FLAGS`) for "all status flags set to zero".
