### ISSUE TITLE
`MAX_CASPER_VOTES` clarification

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#461]
# Issue
`MAX_CASPER_VOTES` is a constant in an attempt to put a limit on the load of processing attestations within the context of checking slashing conditions. Right now there is a limit that the sum of the number of indices across the two slashable messages cannot exceed `MAX_CASPER_VOTES`.

To clarify -- This is not some sort of in protocol limit on the size of committees, but instead a limit on the size of the bulk slashing that can be performed in one message. If for example 1200 people signed the same slashable messages, multiple `CASPER_SLASHING` messages would have to be submit utilizing different subsets (and thus different aggregate signatures).

This is a bit unclear in the current spec and with the current names. I suggested we
* Change `MAX_CASPER_VOTES` to `MAX_INDICES_IN_CASPER_SLASHING` (a bit verbose but something more descriptive)
* Add a note to the validator guide on how to handle this case

**Comment by djrtwo** [comment]
cc: @JustinDrake  to ensure I have the purpose of this constant correct

**Comment by djrtwo** [comment]
I think this is related to #271

**Comment by JustinDrake** [comment]
Yep, related to #271. Having a constant is possibly bad. Aggregated signatures that are exposed onchain cannot be unaggregated so with large committees the slashing would rely on more fine-grained aggregation to be cached offchain. One possibility is to cap the number of constituent signatures in the aggregated signatures that go onchain.

**Comment by djrtwo** [comment]
Which would force splitting committee sigs across multiple attestations (on chain) when committee size (`total_val / SHARD_COUNT`) exceeds this constant.

hmm

**Comment by vbuterin** [comment]
We can always set the constant to be >= 4096 so that it's always possible to slash a single committee. Anything wrong with that?

**Comment by JustinDrake** [comment]
> We can always set the constant to be >= 4096

`MAX_CASPER_VOTES = 4096` is definitely simple. The worry would be "vote stuffing" DoS attacks where bogus validator indices are included in Casper slashing transactions. In the worst case:

* **CPU**: `MAX_CASPER_SLASHINGS * MAX_CASPER_VOTES` pubkeys need to be retrieved from memory and added. One benchmark suggest the overhead per addition is about 1,350ns so the ballpark is ~100ms.
* **Data**: Each validator index is 3 bytes so an attacker can create a beacon block with ~197kB of validator indices.

**Comment by vbuterin** [comment]
> Each validator index is 3 bytes so an attacker can create a beacon block with ~197kB of validator indices.

Not sure where this comes from. Shouldn't it be 24576 bytes (4096 * 3 * 2 for two votes)? Or are you referring to the status quo?

>  One reason to keep pubkeys in the registry after withdrawals is to allow for Casper slashing transactions with old aggregated pubkeys to be processable

Right, this is exactly why I had the one-year post-withdrawal delay originally.

**Comment by JustinDrake** [comment]
> Shouldn't it be 24576 bytes (4096 * 3 * 2 for two votes)?

Right, I missed a factor of 2x. So the worst case overhead assuming we set `MAX_CASPER_VOTES = 4096` (and otherwise stick with the current spec) is `MAX_CASPER_SLASHINGS * MAX_CASPER_VOTES * 3b * 2 = 16 * 4096 * 3b * 2 = 393kB`.

> under the constraint of either max 8 votes or max 4096 indices

Oh I see. You're advocating to be able to slash one committee per `BeaconBlock`, not necessarily one committee per `CasperSlashing`. It's somewhat dissatisfying that the number of slashings per `BeaconBlock` decreases as committee sizes increase (we want it to increase, or at least stay constant).

> max 8 votes

(nitpick) `MAX_CASPER_SLASHINGS` is currently set to 16

> max 4096 indices

(nitpick) Is this max 4096 indices over all `SlashableVoteData` in all the `CasperSlashing` in a given `BeaconBlock`? In the extreme case where every individual `SlashableVoteData` consumes 4096 indices then slashing a single committee would not be possible. Max 8192 indices would account for the two `SlashableVoteData` per `CasperSlashing`.

**Comment by vbuterin** [comment]
> Oh I see. You're advocating to be able to slash one committee per BeaconBlock, not necessarily one committee per CasperSlashing. It's somewhat dissatisfying that the number of slashings per BeaconBlock decreases as committee sizes increase (we want it to increase, or at least stay constant).

OK thought about it for a bit; I would favor a limit of (i) one slashing per block, and (ii) 8192 indices per slashing. The withdrawal limit is 4 validators per epoch, so one per block (ie. 64 per epoch) is plenty of space to ensure that everyone gets slashed.

**Comment by djrtwo** [comment]
closed via #488
