### ISSUE TITLE
SSZ spec missing explicit checks container decoding

### ISSUE THREAD

**Issue by holiman** [ethereum/eth2.0-specs#479]
Regarding how `container`s are encoded and decoded, I looked at the py implementation (from the spec, not the actual implementation yet). 
```python
class Container:
    # this is the container; here we will define an empty class for demonstration
    pass

# get a reference to the type in some way...
container = Container()
typ = type(container)

assert(len(rawbytes) > current_index + LENGTH_BYTES)
total_length = int.from_bytes(rawbytes[current_index:current_index + LENGTH_BYTES], 'little')
new_index = current_index + LENGTH_BYTES + total_length
assert(len(rawbytes) >= new_index)
item_index = current_index + LENGTH_BYTES

values = {}
for field_name in get_field_names(typ):
    field_name_type = get_type_for_field_name(typ, field_name)
    values[field_name], item_index = deserialize(data, item_index, field_name_type)
assert item_index == new_index
return typ(**values), item_index
```

As I understand it, a `container` must be used if we want to to encode a list of dynamic-size things, e.g. `bytes`, like a list of `transactions`. The encoded form then becomes
`container_total_bytes | length_1 | data_1 | length_2 | data_2 | .. | data_n` . 
The implementation does verify that after decoding all items, the sums match up: `assert item_index == new_index`. However, 

1. This is not listed explicitly as a "Check to perform" in the spec. If this is not done, it would be possible to either overflow into the next element, or underflow so that after reading `n` items, the offset is not correct. Some implementations might choose to go with the total_length, some may choose to use the last `index`, and they'd be incompatible. 
2. The check implemented in python is made post-facto, meaning that if e.g. `length_1` overflows the buffer, there would be an out-of-bounds read, and possible crash. This is probably not a problem, if all lower-level decode-methods always checks bounds, however, an optimized implementation might skip that checking those individual fields if the envelope `container` is already checked.

**Comment by holiman** [comment]
Oh, thanks for the playground. The examples I was thinking about were

1. 
```
b = decode(
    b'\x00\x00\x00\x0f\x00\x00\x00\x01\xaa\x00\x00\x00\x01\xbb\x00\x00\x00\x01\xcc',
   ExampleType)
```
So the `container_total_bytes` is `15` bytes, but there are in fact three elements supplied. The python implementation happily reads the first two, and ignores the third one even though it has only consumed `10` out of those `15` bytes. 

2. 
In the second example, I thought it would be possible to read out of bounds. 
```
decode(
    b'\x00\x00\x00\x10\x00\x00\x00\x04\xaa\xaa\xaa\xaa\x00\x00\x00\x05\xbb\xbb\xbb\xbb'+
    b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'+
    b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'+
    b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'+
    b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00', ExampleType)```
```
Where the last (inner) length is `5`. However, it yields

```
ssz.exceptions.DeserializationError: Tried to read 5 bytes from 12 but the string is only 16bytes long
```
So that does not appear to be a problem with the python implementation -- but based from my reading of the spec (and the python snippets therein), I would have expected the opposite: that the too-short (case 1) is caught on  `assert item_index == new_index`, and the last aswell, but only _after_ actually reading the data.

**Comment by holiman** [comment]
To clarify.. Case 1, python handles this successfully:
```python

from ssz.sedes import Serializable, bytes_sedes,uint8
from ssz.codec import encode, decode


class ExampleType(Serializable):
    fields = [
        ('field1', bytes_sedes),
        ('field2', bytes_sedes),
    ]
class Override(Serializable):
  fields = [
    ('a', ExampleType), 
    ('b', uint8),
  ]

a = ExampleType(b'\xaa', b'\xbb')
print(encode(a))
# b'\x00\x00\x00\n\x00\x00\x00\x01\xaa\x00\x00\x00\x01\xbb'
b = Override(a, 3)
print(encode(b))
# b'\x00\x00\x00\x0f\x00\x00\x00\n\x00\x00\x00\x01\xaa\x00\x00\x00\x01\xbb\x03'


decode(
    b'\x00\x00\x00\x0f\x00\x00\x00\n\x00\x00\x00\x01\xaa\x00\x00\x00\x02\xbb\x03\x00'
  , Override)
```
An erroneous implementation could erroneously parse this as `[0xaa, 0xbb] , 0`. Is there some shared testbed where we can add these things?

**Comment by holiman** [comment]
I think the go-implementation would behave as rust: https://github.com/prysmaticlabs/prysm/blob/master/shared/ssz/decode.go#L207 , whereas I think the java implementation is probably fine.

**Comment by holiman** [comment]
Another example which demonstrates how the python implementation can be made to skip over some data.
```python

from ssz.sedes import Serializable, bytes_sedes,uint8
from ssz.codec import encode, decode

class ExampleTypeTriple(Serializable):
    fields = [
        ('field1', bytes_sedes),
        ('field2', bytes_sedes),
        ('field3', bytes_sedes),
    ]
class OverrideTriple(Serializable):
  fields = [
    ('a', ExampleTypeTriple), 
    ('b', uint8),
  ]

class ExampleType(Serializable):
    fields = [
        ('field1', bytes_sedes),
        ('field2', bytes_sedes),
    ]
class Override(Serializable):
  fields = [
    ('a', ExampleType), 
    ('b', uint8),
  ]

a = ExampleType(b'\xaa', b'\xbb')
print(encode(a))
oa = Override(a, 3)
print(encode(oa))
#  
b = ExampleTypeTriple(b'\xaa', b'\xbb',b'\xcc')
print(encode(b))
ob = OverrideTriple(b, 3)

# Encoding a larger type, but decoding it into a smaller one. The python decoder will ignore the `\xcc\ byte in 'field3'

newa = decode(encode(ob), Override)
print(newa.a.field1)
# b'\xaa'
print(newa.a.field2)
# b'\xbb'
print(newa.b)
# 3
```

**Comment by holiman** [comment]
This puts the python code into a recursion crash:
```
print(encode(('x', uint32 )))
```

**Comment by paulhauner** [comment]
Thanks @holiman. We'll jump onto this today.
