### ISSUE TITLE
Potential bug on updating previous_epoch_randao_mix

### ISSUE THREAD

**Issue by terenc3t** [ethereum/eth2.0-specs#485]
We only update `previous_epoch_randao_mix` if validator registry update happens.
In the meantime, `state.slot` gets incremented every incoming block. Will we run into an issue in `get_crosslink_committees_at_slot` under condition `slot < state_epoch_slot` for `get_previous_epoch_committee_count_per_slot` where  `state.previous_epoch_randao_mix` does not correlate to previous epoch's randao mix because it falls behind? 

Should [validator registry](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#validator-registry) start out with:
```
First, update previous_epoch_calculation_slot and previous_epoch_start_shard:

Set state.previous_epoch_calculation_slot = state.current_epoch_calculation_slot
Set state.previous_epoch_start_shard = state.current_epoch_start_shard
Set state.previous_epoch_randao_mix = state.current_epoch_randao_mix
```

**Comment by djrtwo** [comment]
Yes, I think you are correct

**Comment by terenc3t** [comment]
I'll open a PR 👌
