### ISSUE TITLE
SSZ spec ambiguity regarding Lists

### ISSUE THREAD

**Issue by holiman** [ethereum/eth2.0-specs#491]
The spec says

#### List/Vectors

Lists are a collection of elements of the same homogeneous type.

1. Get the number of raw bytes to serialize: it is ``len(list) * sizeof(element)``.
   * Encode that as a `4-byte` **little endian** `uint32`.

...

* *Note on efficiency*: consider using a container that does not need to iterate over all elements to get its length. For example Python lists, C++ vectors or Rust Vec.

--------
1.  the `len(list) * sizeof(element)` only works if all elements are of same fixed size. 
2. The 'Note on efficiency' is also only valid if all elements are of the same fixed size. 

The spec says that it's the same homogenous type, not same fixed-size type. So the recommendations are wrong. 
However, it would be nice to have a `fixed-size list` type, since that would make encoding/decoding certain types of data simpler, and allow for things like lazy lookup of particular pieces of data. 

It might be possible to define `bytes` and `bytesN` as subsets of those types of lists (where the size of each individual element is `1`).

**Comment by jannikluhn** [comment]
Referencing #232 and #484 

> However, it would be nice to have a fixed-size list type, since that would make encoding/decoding certain types of data simpler, and allow for things like lazy lookup of particular pieces of data.

Wouldn't a fixed-size list essentially be a container?

**Comment by holiman** [comment]
I guess this can be closed now, with the updates to the spec. 
Regarding more optimized implementation of lists with `fixed-size` elements, I've realized that _that_ particular optimization can be left to the encoders, and does not actually need any change in the protocol.
