### ISSUE TITLE
Contradictions with block.slot processing requirements

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#494]
In [Beacon chain processing](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#beacon-chain-processing) there is a block processing requirement that: 

> The node has processed its `state` up to slot, `block.slot - 1`.

In [Per-block processing](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#per-block-processing), there is a statement:

> Verify that `block.slot == state.slot`

I understand the intentions here but I think these statements contradict.

I suspect the first statement is a relic from back when there was a `while` loop during block processing.

**Comment by djrtwo** [comment]
After the couple big PRs are merged, I intend to clean up the description of the state transition and some of the logic around this. I'll leave this issue here until I do that PR.

thanks!

**Comment by djrtwo** [comment]
This is clarified in #512:
* removed "The node has processed its state up to slot, block.slot - 1"
* added explicit guidance on how to handle skipped slots when processing from parent to child block.

**Comment by djrtwo** [comment]
closed via #512
