### ISSUE TITLE
Extend SSZ hash type

### ISSUE THREAD

**Issue by mkalinin** [ethereum/eth2.0-specs#50]
### Proposal
~Replace SSZ hash type family with the type that has arbitrary length, something like `hash[32..128]`.~
**EDIT:**
Consider any `hashN` type, where `N` is positive integer, a valid `hash` type if `N` satisfies condition:
 `N % 8 == 0`

### Rationale
Using strict number of hash types has no forward compatibility. If there will be a need in a new e.g. `hash128` type then implementers will have to update their code that runs `hash` type validation or use `bytes` type as a workaround.

**Comment by vbuterin** [comment]
So a dynamic length type? That seems like a bad idea; introducing more dynamic length objects inherently makes it harder to serialize, deserialize, and poke into an object.

**Comment by mkalinin** [comment]
> So a dynamic length type?

I don't think so. It just proposes to expand a family of hash types that we have in SSZ spec so far to `[hash32, hash33, ..., hashN]`. Whatever `N` would be reasonable to use. Each of those types is a static length type.

Currently, spec describes only three `hash32/96/97` and validation is strictly tight to those three. Btw, `hash97` looks odd.

**Comment by mkalinin** [comment]
Hmm, maybe it would be just enough to make a list from all reasonable hash lengths and add them to the spec. what do you think?

**Comment by djrtwo** [comment]
I think it pretty reasonable to define `hashN` where `N % 8 == 0` for the time being and to address an exceptional case like `hash97` if we and when we do in fact need it.

**Comment by mkalinin** [comment]
> I think it pretty reasonable to define `hashN` where `N % 8 == 0`

Looks like the best solution to me. I am pretty confident that for `hash` type we won't need anything else than `N % 8 == 0`

**Comment by mratsim** [comment]
I always thought the current hashes were just examples cc @NatoliChris and it was indeed arbitrary fixed length;

**Comment by mkalinin** [comment]
I have updated original proposal with what we finally came up to. It should read better now.

**Comment by djrtwo** [comment]
checking back on this. Do we need to support  arbitrary byte length (like 97) or just where `N % 8 == 0`?
