### ISSUE TITLE
Expected system requirements for Eth 2

### ISSUE THREAD

**Issue by jamesray1** [ethereum/eth2.0-specs#506]
Will having a dedicated GPU(s) still be useful for Eth 2 with PoS instead of PoW?

Will the system requirements be expected to be similar to what they are now e.g. with https://wiki.parity.io/FAQ#what-are-the-parity-ethereum-disk-space-needs-and-overall-hardware-requirements. How will state size growth be managed; will storage economics sufficiently manage growth to keep system requirements reasonably within reach?

**Comment by JustinDrake** [comment]
> Will having a dedicated GPU(s) still be useful for Eth 2 with PoS instead of PoW?

It may be useful, but we don't assume validators have access to a GPU, i.e. it's not a requirement.

**Comment by vbuterin** [comment]
Required RAM for a beacon chain full node should be < 1 GB if you do it optimally, and required disk space maybe an order of magnitude more if you prune. There is definitely a goal of being relatively conservative about system requirements for the beacon chain.

It's too early to tell for shard chains. Having a GPU may be useful if you are validating and executing state on many shards, too many for a regular CPU to handle.

**Comment by jamesray1** [comment]
Yeah I figured it might be tricky to get a concrete answer at this stage. But yeah, it's good not to require it for the beacon chain.

> required disk space maybe an order of magnitude more if you prune

I think you mean if you don't prune? 

If you were going to validate and execute state on multiple shards then you would also want heaps of bandwidth and/or an efficient protocols for p2p, syncing and validating, (de)serialization, state and chain data storage and access. I/O may be another bottleneck so you would want a super-fast highest end SSD and similarly efficiency.

**Comment by JustinDrake** [comment]
I expect every client to specify their system requirements when they have more concrete numbers. From a spec standpoint the goal is for a mainstream laptop to be sufficient without making use of the GPU. Closing for now :)
