### ISSUE TITLE
Proposer & Casper Slashing

### ISSUE THREAD

**Issue by decanus** [ethereum/eth2.0-specs#507]
Currently there are both `Proposer` and `Casper` slashings defined. However the difference of the 2 is never explicitly defined. For clarity in the spec this should be done, ideally it would be documented what differentiates the 2 and why this differentiation needs to be made.

**Comment by JustinDrake** [comment]
* `Proposer` is about *proposers* making two distinct proposals on the same shard (the beacon chain counts as a shard for this purpose) at the same slot.
* `Casper` is about *attesters* making votes that could compromise safety in the context of Casper the Friendly Finality Gadget.

(I'm not a huge fan of "Casper" as a name for various reasons. What about `ProposerSlashing` and `AttesterSlashing`?)

**Comment by vbuterin** [comment]
Yeah, Proposer and Attester is definitely better.

**Comment by decanus** [comment]
@JustinDrake The name change definitely clarifies it more but we should have those explicit definitions which you've put there in the spec for anyone to easily look over.

**Comment by djrtwo** [comment]
addressed in #512 

Short descriptions can/should be added to helper functions and data structures througout

**Comment by djrtwo** [comment]
closed via #512

open new issue if we want to add more descriptions
