### ISSUE TITLE
Add network topology notes to validator doc

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#533]
# Issue
Still need to figure out if only one sub-net or multiple sub-nets within phase 0. After we figure that out, we need to provide explicit guidance on what subnets to broadcast messages to and who should be aggregating signatures

**Comment by Mikerah** [comment]
I created this issue (https://github.com/ethresearch/p2p/issues/12) a while ago to discuss this.

**Comment by JustinDrake** [comment]
Closing thanks to the recent progress agreeing on a networking spec for interop. For mainnet there is a discussion in https://github.com/ethereum/eth2.0-specs/issues/1331.
