### ISSUE TITLE
Deposit Inclusion Reward?

### ISSUE THREAD

**Issue by terenc3t** [ethereum/eth2.0-specs#539]
A honest proposer should pick deposit from contract logs and add it to the beacon block body to propose when it's his/her slot.

A rational proposer may not do that without proper incentives, the proposer could simply stop on boarding new validators, locking out new comers through self interest or just laziness.

I wonder if proposer should be rewarded for deposit inclusion and maybe penalized(?) for not including existed deposits?

**Comment by djrtwo** [comment]
One possibility here is to not only enforce ordering of deposits (using an additional counter in the state), but to use this in relationship to the max known from the recent eth1 info to make adding deposits to blocks a validity condition if `state.deposit_counter < state.latest_eth1_data.max_known_deposit_count`

**Comment by JustinDrake** [comment]
> make adding deposits to blocks a validity condition

:+1: This mitigates two problems:

1) beacon blocks not processing Eth1 deposits
2) validator's dilemma where Eth2 validators don't bother staying in sync with Eth1

**Comment by JustinDrake** [comment]
Closing in favour of #675 (we agreed on mandatory deposits).
