### ISSUE TITLE
Remove implicit big-int requirement

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#542]
# Issue
"ties broken by favoring lower `shard_block_root` values" requires big integer comparison. We intend to not have big integer requirement in the beacon chain.

**Comment by vbuterin** [comment]
That could be handled with string comparison.... although the fact that we now use little endian makes this ambiguous forcing us to explicitly state that we are using string comparison and not integer comparison (gah I hate little endian more :laughing:). Most programming languages support string comparison so I don't see this being a problem.

**Comment by arnetheduck** [comment]
string / lexicographical comparison of the byte sequence of the SSZ serialization of the hash seems like an easy and unambiguous way to do it? 

fwiw, in statically typed languages we usually don't look at the hash as an integer at all - it's just a blob,  so the bigint interpretation left things a bit open and would require going backwards through the serialization anyway, to actually implement it
