### ISSUE TITLE
potential bug in update_validator_registry?

### ISSUE THREAD

**Issue by terenc3t** [ethereum/eth2.0-specs#554]
Since `get_entry_exit_effect_epoch`'s return has a `+1`, in `update_validator_registry` 

Should:
`if validator.activation_epoch > get_entry_exit_effect_epoch(current_epoch)`
`validator.exit_epoch > get_entry_exit_effect_epoch(current_epoch)`

be:

`if validator.activation_epoch >= get_entry_exit_effect_epoch(current_epoch)`
`validator.exit_epoch >= get_entry_exit_effect_epoch(current_epoch)`

??

**Comment by djrtwo** [comment]
No, it should be `>`. We want it to no-op if someone tries to exit or activate twice in an epoch.

For example:
* Validator A (not previously exited) submits an `Exit`. It is included near the start of the epoch.
* Validator A's `exit_epoch` is set to `entry_exit_epoch(current_epoch)`
* Validator A submits another exit in the same epoch. It is attempted to be included in the block.
* Two possibilities:
    * If the condition is: "Verify that validator.exit_epoch > get_entry_exit_effect_epoch(get_current_epoch(state))", then we see that the exit_epoch is not greater than the entry exit epoch of the current epoch and it is a no-op.
    * If the condition is: "Verify that validator.exit_epoch >= get_entry_exit_effect_epoch(get_current_epoch(state))", then we see that the exit_epoch is greater than or equal (equal in this case) and this condition does not guard against the op.

**Comment by terenc3t** [comment]
got it, thx for the explanations!
