### ISSUE TITLE
Clarification on assertations

### ISSUE THREAD

**Issue by decanus** [ethereum/eth2.0-specs#559]
Currently in the block processing section under `attestations` there are a bunch of `assertions`. The behaviour of these should be clarified, if these fail should the iteration continue to the next item or should the error be bubbled up to end processing of `attestations`?

**Comment by djrtwo** [comment]
See the ["Notation" section](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#notation)

> Beacon blocks that trigger unhandled Python exceptions (e.g. out-of-range list accesses) and failed asserts are considered invalid.

This should arguable move out of notation and into processing or state transition sections to be coupled more closely with the relevant sections.

**Comment by JustinDrake** [comment]
Fixed by #606
