### ISSUE TITLE
Weaken and reformulate no-surround slashing condition

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#56]
See discussion [here](https://ethresear.ch/t/casper-ffg-leniency-tweak/2286), and [here](https://ethresear.ch/t/a-tight-and-intuitive-casper-slashing-condition/3359) for a more natural reformulation of the no-surround slashing condition.

**Comment by djrtwo** [comment]
To be clear. This requires keeping the no double vote condition, correct?

What's the argument for relaxing this condition? It seems to take roughly equivalent effort to code/test. Does it open up any scenarios that might benefit validators? (coordinating again attackers or something)

**Comment by JustinDrake** [comment]
> To be clear. This requires keeping the no double vote condition, correct?

Yes.

> What's the argument for relaxing this condition?

I think there's an argument purely on "design aesthetics" grounds: strive to not slash validators unnecessarily. From a practical standpoint, this may improve liveness in weird edge-case situations.

**Comment by JustinDrake** [comment]
Closing in favour of #128.
