### ISSUE TITLE
LOGOUT message versioning for replay protection

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#57]
`LOGOUT` special records need added versioning to handle replay protection in a similar way to Attestations. This version needs to be a component of the signed message. 

A simple solution would be to:
- add a data field for `version`
- ensure that the sig is from the correct validator and of the message `hash(LOGOUT_MESSAGE + version)`

We might want to consider what a more general solution to handle versioning across attestations and specialrecords (that require it) might look like

**Comment by ChihChengLiang** [comment]
Would it be better to specify the logout slot?
The benefit I can come up with is that the message can be expired if it failed to be included in the block when sent.

**Comment by ChihChengLiang** [comment]
Oops, sorry I missed the comments here https://github.com/ethereum/eth2.0-specs/pull/42#discussion_r222696741 .
The point is to create a fork version, so a logout message cannot be replayed on a forked chain.

**Comment by mkalinin** [comment]
Maybe we could re-use nonce mechanism from eth1.0? And make it obligatory for _any_ outgoing message that validator produces.

**Comment by vbuterin** [comment]
I would say keep it simple, and just add a version message and that's it.
