### ISSUE TITLE
Specify maximum revert period

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#577]
What is the desired behaviour if two beacon chain forks A and B do not advance justification for 4+ months, and then fork A (e.g. thanks to inactivity penalties) wins the race to justify first? We probably do not want fork B to honour the new justification in fork A.

**Comment by vbuterin** [comment]
I think clients should just refuse to revert further than some maximum revert period, though now that we're dynamically calculating that, it should be dynamically calculated....

I'd say one important first thing to do is to add the explicit criterion that a client does not revert finalized blocks.

**Comment by JustinDrake** [comment]
Closing in favour of #675.
