### ISSUE TITLE
Describe genesis

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#58]
# Issue
We don't plan on having a genesis block but rather just a genesis active and crystallized state which the first block will use for its state transition. This means that the 0th block in the chain might be a block from any slot _at or after_ the slot at `GENESIS_TIME`.

Although this is not a "genesis block" in the sense that it is entirely predefined, it does need some exceptions to be properly handled in the current framework

- the 0th block will have no parent so the entirety of `ancestor_hashes` will be `0x00`
- If `ancestor_hashes[0] == 0x00` then there is no parent. In this case, do not allow any attestations to be included in the block and do not impose the parent proposer attestation requirement on the block.
- There is no parent so `get_new_recent_block_hashes` does not have the appropriate params and should be called with `get_new_recent_block_hashes(old_block_hashes, -1, current_slot, 0x00)`
- `update_ancestor_hashes` should not be called

There might be a couple of other things. Just dumping this here and will make a more detailed PR soon.

**Comment by terenc3t** [comment]
I think we also should formally define a genesis crystallized state. For example, who gets to propose genesis block? This affect genesis block's `crystallized_state_root`

**Comment by djrtwo** [comment]
@hwwhww and I are working on cleaning up the `on_startup` function to instead be a `get_genesis_state` function that returns genesis active and crystallized state with _all_ fields explicitly set.

Work ongoing in this PR https://github.com/ethereum/eth2.0-specs/pull/55

**Comment by djrtwo** [comment]
As for the proposer of the "genesis block". I think we will just have the first block in the chain be an exceptional block that doesn't have a parent and is proposed by whatever proposer shows up at their assigned slot. So maybe it happens at slot 0 or 1 or 2 or....

So everyone knows the genesis state which orders proposers and then proposers show up to try to propose a block at their slot. If they have seen other blocks, they build on top of them. If not, they use the genesis state to build a parentless block.

**Comment by djrtwo** [comment]
closed vi #107
