### ISSUE TITLE
Abstract sharding to smart contract developers

### ISSUE THREAD

**Issue by lastmjs** [ethereum/eth2.0-specs#581]
I have a concern about Ethereum sharding. Why is the goal not to abstract away the concept of sharding to the smart contract developer? Traditional database sharding is abstracted, so why not Ethereum sharding? Unnecessary complexity for the developers :(

I have not been deeply involved in the design of Ethereum sharding, perhaps there are some technical reasons for why this type of abstraction is not being pursued. But, one of the design goals specified in the README of this repository is "to minimize complexity, even at the cost of some losses in efficiency". Not abstracting the concept of shards to the developer is going to be a major source of complexity for the developer. I don't understand why this abstraction is not one of the major design goals, and I'd love some elaboration.

Thanks!

**Comment by lastmjs** [comment]
So, apparently this idea is known as "transparent shards". Is that true? So it is something people have thought about, but no one has figured out how to do it yet? Is it being planned for a future "Ethereum 3.0"? All this from this Tweet: https://twitter.com/cdetrio/status/1093590129220956161

**Comment by protolambda** [comment]
You could take a look at the work of Vlad Zamfir if you're into load-balancing and cross-shard interactions. The current rationale is to keep things simple, as it is already complicated enough to implement sharding and POS. And abstractions for cross-shard interactions can still emerge on a simple protocol design. Take ERC-20 as an example, Ethereum just had to provide the lower ability to implement contracts, and people implemented their own currencies.

**Comment by protolambda** [comment]
@lastmjs If the above answer is sufficient, can you close the answer?

**Comment by JustinDrake** [comment]
Transparent shards is definitely an interesting idea, maybe for Ethereum 3.0 :) I'll close this issue and nudge the discussion towards ethresear.ch 👍
