### ISSUE TITLE
Per-block processing: min AttestationRecord count

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#59]
> A block can have 0 or more `AttestationRecord` objects

I understand it should have 1 or more `AttestationRecord` objects, considering the following:

> Verify that an attestation from this validator is part of the first (ie. item 0 in the array) `AttestationRecord` object

**Comment by terenc3t** [comment]
Unless it's a genesis block

**Comment by djrtwo** [comment]
I'll take this into account and try to be crystal clear between the requirements of the two different cases (first block ever vs block built on chain) clear when I clean up things for #58

**Comment by djrtwo** [comment]
It's 0 or more now! 
Proposer signature is being separated out in #143
