### ISSUE TITLE
Separate Single Attestation into its Own Wire Format 

### ISSUE THREAD

**Issue by terenc3t** [ethereum/eth2.0-specs#6]
**Background:**

`AttestationRecord` is currently used for aggregated attestation and single attestation when attester attest on a block or when proposer include its own attestation when it broadcasts the block at the network layer.

**Proposal:**

I wonder if it's worth it to separate out single attestation into its own object which looks below.
As you can see, we can save the network bandwidth on `oblique_parent_hashes` (don't need for single attestation) and `attester_bitfield` (bytes -> uint32) per attestation every time proposer or attester transmits over the wire. The down side is there's increasing complexity to manage two different attestation objects.

**SingleAttestation:**
```
fields = {
    'slot': 'int64',
    'shard_id': 'int16',
    'shard_block_hash': 'hash32',
    'attester_index': 'int32',
    'justified_slot': 'int64',
    'justified_block_hash': 'hash32',
    'aggregate_sig': ['int256']
}
```

**AttestationRecord (AggregatedAttestation):**
```
fields = {
    'slot': 'int64',
    'shard_id': 'int16',
    'oblique_parent_hashes': ['hash32'],
    'shard_block_hash': 'hash32',
    'attester_bitfield': 'bytes',
    'justified_slot': 'int64',
    'justified_block_hash': 'hash32',
    'aggregate_sig': ['int256']
}
```

**Comment by djrtwo** [comment]
I'm a bit mixed on this proposal. I wasn't particularly fond of it at first, but I just checked the savings by eliminating the `attester_bitfield` when a single attestation is being broadcast and they are worth considering.

> Assuming ~300k validators and 1024 shards, we expect committees to be of size ~300 validators. This is a 38 byte bitfield per attestation. If we switch to the SingleAttestation format, we save ~34 bytes per SingleAttestation as they are sent around the network.

It's roughly a 15-20% saving in byte size depending on the size of the bls signature.

Anyone else want to chime in on whether these savings are worth the additional data structure?

**Comment by rawfalafel** [comment]
From an implementation perspective, this brings clarity, particularly for the attestation that's attached to a new block. 

`AttestationRecord` has these fields:
```python
{
    # Slot number
    'slot': 'int64',
    # Shard number
    'shard': 'int16',
    # Block hashes not part of the current chain, oldest to newest
    'oblique_parent_hashes': ['hash32'],
    # Shard block hash being attested to
    'shard_block_hash': 'hash32',
    # Attester participation bitfield (1 bit per attester)
    'attester_bitfield': 'bytes',
    # Slot of last justified block
    'justified_slot': 'int64',
    # Hash of last justified block
    'justified_block_hash': 'hash32',
    # BLS aggregate signature
    'aggregate_sig': ['int256']
}
```

The proposer's attestation that comes attached with a block only requires `shard_block_hash` and `aggregate_sig`. Every other field is either irrelevant or derived by the block itself. 

However at the p2p layer, when aggregating attestations, it may not be worthwhile to separate attestations into two separate data structures.

**Comment by rawfalafel** [comment]
So maybe an alternate proposal is:
- Keep the name `AttestationRecord` the same.
- Specify that `shard_block_hash` and `proposer_sig` is included along with a new block.

**Comment by jannikluhn** [comment]
> It's roughly a 15-20% saving in byte size depending on the size of the bls signature.

I'm assuming we're going with Vitalik's idea of aggregating attestations in the shard networks (which I think is a good idea). Then we should compare the size savings to the whole shard network traffic, not only the attestation traffic. If I didn't make a miscalculate, attestations are roughly 10% of the 1MB/8s collation traffic (128kB/s vs 10kB/s). So the savings compared to this are only 1.5 - 2%.

**Comment by djrtwo** [comment]
good point @jannikluhn

**Comment by terenc3t** [comment]
Yeah. That's a great point. In this case, I don't feel strongly on having two wire formats. I'm ok with closing if everyone is ok too

**Comment by djrtwo** [comment]
Not currently going down this road. Only if we end up needing to optimize the netowrk layer and a simple compression alg (snappy compression or otherwise) doesn't work well for our purposes
