### ISSUE TITLE
Cross-blockchain BLS12-381 standardisation

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#605]
This is a heads-up that [the BLS spec](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/bls_signature.md) is likely to change. Many blockchain projects are converging towards BLS12-381 (Zcash Sapling, Chia, Ethereum 2.0, Filecoin, Dfinity, Algorand, etc.) and there is a strong desire for everyone to standardise on the fine details. This include standardising

- hash functions (to G1 and G2)
- generator points (for G1 and G2)
- point serialisation (for G1 and G2)
- possibly message hashing

Given that Zcash Sapling is already in production, one sensible approach may be to start from what Zcash has.

Dan Boneh and folks from Algorand have a [IETF draft](https://tools.ietf.org/id/draft-boneh-bls-signature-00.txt). I encourage anyone interested in this discussion to email Sergey Gorbunov (sgorbunov@uwaterloo.ca) who seems to be leading the effort.

**Comment by axic** [comment]
cc @Schaeff

**Comment by JustinDrake** [comment]
Announcement [tweet](https://twitter.com/Algorand/status/1095038841323483137) and [Medium post](https://medium.com/algorand/posting-bls-standard-draft-30a89723f386).

**Comment by JustinDrake** [comment]
Closing in favour of #675.
