### ISSUE TITLE
`crosslink_committee` type confusion

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#609]
I noticed that there are variables defined as `crosslink_committee` that have different types:

### As a `List[ValidatorIndex]`

- Inside [`get_attestation_participants(...)`](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#get_attestation_participants)
- [Per-block processing/attestations](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#attestations-1):  "Verify bitfields and aggregate signature..."

### As a `Tuple[List[ValidatorIndex], ShardNumber]`

- `get_crosslink_committees_at_slot(...)` returns `List[Tuple[List[ValidatorIndex], ShardNumber]]`, inferring that a `crosslink_committee` is `Tuple[List[ValidatorIndex], ShardNumber]`.

There are some other instances around the place, but I think you get the point.

Not a huge deal but I found it to be a bit confusing especially when trying to figure out the `winning_root` function.

**Comment by JustinDrake** [comment]
The "full" type of a crosslink committee is arguably `Tuple[List[ValidatorIndex], ShardNumber, SlotNumber]`. In most cases the slot number is known from context—hence `Tuple[List[ValidatorIndex], ShardNumber]`—and in some cases the shard number is also known from context—hence `List[ValidatorIndex]`.

Does that make sense? I think using the simplest "reduced" type based in context is fine, and using `Tuple[List[ValidatorIndex], ShardNumber]` or `Tuple[List[ValidatorIndex], ShardNumber, SlotNumber]` everywhere would be overkill.

Feel free to reopen :)
