### ISSUE TITLE
Confusion surrounding `winning_root`

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#610]
I found it quite difficult to discern what the `winning_root` function is.

My initial confusion arose from the following:

- It seems that `winning_root` takes `crosslink_committee` because it passes it to `attesting_validator_indices(...)`, however that function does not use it. 
- `winning_root(...)` takes `crosslink_committee` as an argument. When `winning_root` is called, it is passed `List[ValidatorIndex]` as the `crosslink_committee`. It was unclear to me where `shard` comes from.

I came to the conclusion that `crosslink_committee` should really be `Tuple[List[ValidatorIndex], ShardNumber]` and that `shard` in `attesting_validator_indices(..)` is actually `crosslink_committee.shard` (See #609).

Then, I just made a leap and figured that you're probably looking to pick the shard roots that have the most ETH voted for them.

As such, if you wanted to get the `winning_root` for some `shard`, you:

- Let `attestations` be `current_epoch_attestations + previous_epoch_attestations`.
- Let `shard_balances` be a map of `shard_block_root -> attesting_balance`.
- For each `attestation` in `attestations` if `attestation.shard == shard`:
   - Let `attesting_indices` be `get_attestation_participants(state, a.data, a.aggregation_bitfield)`.
   - Let `attesting_balance` be `get_total_balance(state, attesting_indices)`
   - Do `shard_balances[shard_block_root] += attesting_balance`.
- Let `winning_root` be the `shard_block_root` with the highest `attesting_balance` (ties are broken by favoring lower `shard_block_root` values).

## Summary

- I found the definition of `winning_root` to be confusing.
- Can you please confirm my understanding of the intention of the function is correct?

**Comment by hwwhww** [comment]
> I found the definition of `winning_root` to be confusing.

Agreed. It's still hard to digest and may be too abstract.

> Can you please confirm my understanding of the intention of the function is correct?

Here is our implementation. It turns out to be less functional programming than the spec:
1. https://github.com/ethereum/trinity/blob/2058916a589aa7854778d7dca331bfa292c2581a/eth2/beacon/state_machines/forks/serenity/epoch_processing.py#L93
2. https://github.com/ethereum/trinity/blob/2058916a589aa7854778d7dca331bfa292c2581a/eth2/beacon/epoch_processing_helpers.py#L124-L163

1. Just to point out, in your approach:
    > * Do `shard_balances[shard_block_root] += attesting_balance`.

    It's "Do `shard_balances[a.data.shard_block_root] += attesting_balance`.", right?
2. I think although there are some differences between our implementation and your approach, the result should be the same:
    1. We iterate `set([a.data.shard_block_root for a in attestations if a.data.shard == shard])`, not `shard`, because:
        - the spec uses notation `attesting_validator_indices(crosslink_committee, shard_block_root) ...`.
        - then we don't have the temporary map `shard_balances[shard_block_root] -> attesting_balance` in our implementation, instead, we use `(winning_root, winning_root_balance)` that stores the temporary winner during the iterations.
    2. We defined `get_total_attesting_balance` as a function that takes `state`, `shard`, and `attestations` of the given `shard` as the parameters.
    3. Note that it's possiblet that there's no winning root: https://github.com/ethereum/eth2.0-specs/issues/541

/cc @NIC619, please correct me if I'm wrong.

**Comment by terenc3t** [comment]
Agreed with Paul, I've brought up whether it's a good idea to use python code for `winning_root` but got pushed back

Here is our implementation: 
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/epoch/epoch_operations.go#L309
and it's used here:
https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/epoch/epoch_processing.go#L191

Hope that helps!

**Comment by paulhauner** [comment]
Thanks for the feedback @hwwhww!

>     3. Just to make it clear, in your approach:
>        > * Do `shard_balances[shard_block_root] += attesting_balance`.
>        
>        
>        It's "Do `shard_balances[a.data.shard_block_root] += attesting_balance`.", right?

Correct!

> Agreed with Paul, I've brought up whether it's a good idea to use python code for `winning_root` but got pushed back

After looking at the Python code I agree with @terenc3t's proposal for a Python definition of `winning_root`.

**Comment by cemozerr** [comment]
> * Let `winning_root` be the `shard_block_root` with the highest `attesting_balance` (ties are broken by favoring lower `shard_block_root` values).
Are we interpreting the `shard_block_root` in Little Endian byte order in this case?

**Comment by nisdas** [comment]
@cemozerr I think we would in this case, at least referencing this comment https://github.com/ethereum/eth2.0-specs/issues/556#issuecomment-461512041 . The only thing that is explicity big-endian would be the bls spec.

**Comment by cemozerr** [comment]
Thank you @nisdas!

**Comment by GregTheGreek** [comment]
My biggest confusion is around the idea that `winning_root()` is an internal function, but its used under the `crosslinks` section (below `eth1data`). I can't seem to understand why its within the assumed loop ?

**Comment by JustinDrake** [comment]
This is addressed in PR #711 :)
