### ISSUE TITLE
When to update validator balance during processing rewards and penalties

### ISSUE THREAD

**Issue by NIC619** [ethereum/eth2.0-specs#616]
`base_reward(state, index)` depends on validator's balance in that `state` so if we update validator's balance during each step we will get different `base_reward(state, index)` in each step.
If we bookkeeping the rewards/penalties for each validator and only update validator's balance at the end, the `base_reward(state, index)` will be the same throughout.

**Comment by djrtwo** [comment]
Good question. I think the intention here is that `base_reward` is fixed for each index at the start of the reward calculation section (thus not really mattering if reward/penalties are incrementally applied at each step or in bulk at the end of the section). 

Agreed that this intention is not made clear in the spec and will update accordingly.

**Comment by NIC619** [comment]
> thus not really mattering if reward/penalties are incrementally applied at each step or in bulk at the end of the section

Hmm…wouldn't this results in two different set of overall rewards/penalties applied on the validators? Since the base reward is constantly changing in the former case but remains the same throughout in the latter case.
If one implementation applies rewards/penalties at each step while the other applies them in bulk at the end of the section, in the end they will get different validator balances.

**Comment by djrtwo** [comment]
Not if we fix the base reward for each validator before starting the rewards section. So either apply rewards at end or make a base reward var at the beginning and use that to update. Either would result in the same

**Comment by NIC619** [comment]
Ah I see what you mean. I was mistaken.
