### ISSUE TITLE
previous_total_balance reflects the balance from the current_epoch

### ISSUE THREAD

**Issue by jrhea** [ethereum/eth2.0-specs#620]
### tl;dr

> The problem is that if `state.validator_balances` has been updated since `previous_epoch` (which i imagine it has), then we are now using the wrong balance.  Surely, the intention was to use a snapshot of validator_balances from previous_epoch, right?

At the time this issue was created, the [latest version of the spec](https://github.com/ethereum/eth2.0-specs/blob/fd5c3ee8b5c11c1b65d37c95ccc98027a333ae6f/specs/core/0_beacon-chain.md) defined `previous_total_balance` like this:

```
def get_effective_balance(state: State, index: ValidatorIndex) -> Gwei:
    return min(state.validator_balances[index], MAX_DEPOSIT_AMOUNT)

def get_total_balance(state: BeaconState, validators: List[ValidatorIndex]) -> Gwei:
    return sum([get_effective_balance(state, i) for i in validators])

previous_total_balance = get_total_balance(state, get_active_validator_indices(state.validator_registry, previous_epoch))
```

In other words, the `previous_total_balance` is calculated by passing the `active_validator_indices` from the `previous_epoch`.  These indices are used to return the `state.validator_balances[index]` for each active validator from the `previous_epoch`.

**Comment by djrtwo** [comment]
You are correct in that the balances from the previous epoch can be marginally affected by the next epoch and can have minor effects on safety margins. This is noted in the spec via the following:

> Note: previous_total_balance and previous_epoch_boundary_attesting_balance balance might be marginally different than the actual balances during previous epoch transition. Due to the tight bound on validator churn each epoch and small per-epoch rewards/penalties, the potential balance difference is very low and only marginally affects consensus safety.

We could keep the current and previous balances at the cost of having two balance arrays, but at a cost of hashing/state size

**Comment by jrhea** [comment]
thanks. makes sense.  i even saw the note, but it didn't register with me for some reason.
