### ISSUE TITLE
Initial state finalizes not yet finished epoch

### ISSUE THREAD

**Issue by mkalinin** [ethereum/eth2.0-specs#623]
### What's wrong
If `GENESIS_SLOT` is not the last slot in the epoch then `finalized_epoch` of initial state could point to the epoch which is still lasts in time, for example:
- `GENESIS_SLOT = EPOCH_LENGTH = 64`
- `GENESIS_EPOCH = slot_to_epoch(GENESIS_SLOT) = 1`

At the chain start attestations will be rejected until `GENESIS_EPOCH` run out. And in general there is no sense in producing block for already finalized epoch.

### Suggestion
~~`GENESIS_EPOCH = slot_to_epoch(GENESIS_SLOT) - 1`~~

**EDT:**
Use `GENESIS_EPOCH - 1` instead of `GENESIS_EPOCH`:
```python
justified_epoch=GENESIS_EPOCH - 1
finalized_epoch=GENESIS_EPOCH - 1
```
It turns out that minimal value of `GENESIS_SLOT` is `EPOCH_LENGTH - 1` which sets `finalized_epoch` to `0`, for lower `GENESIS_SLOT` values it would be an epoch before `0`.

**Comment by djrtwo** [comment]
> At the chain start attestations will be rejected until `GENESIS_EPOCH` run out.

Do you mean rejected as in they cannot be included on chain? Can you point me to the condition that would prevent the 1st epoch attestations from being included?

**Comment by mkalinin** [comment]
To be honest I don't quite remember what I meant by `rejected`. I have double checked with the spec and indeed there is no condition preventing attestations from being included into a chain even if epoch is finalized.

I was confused by the naming of `finalized_epoch` field, decided that it means that _every_ block of this epoch is finalized. While precisely it's an _epoch with finalized block_, not an _entirely finalized epoch_.

Closing this issue. It would be good to have a description on how finality gadget works in the beacon chain with references to beacon state fields that used by it.
