### ISSUE TITLE
Issue in validator spec attester responsibility

### ISSUE THREAD

**Issue by rauljordan** [ethereum/eth2.0-specs#628]
In the current honest validator spec's attester [section](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/validator/0_beacon-chain-validator.md#epoch-boundary-root), we see the following:

##### Epoch boundary root

Set `attestation_data.epoch_boundary_root = hash_tree_root(epoch_boundary)` where `epoch_boundary` is the block at the most recent epoch boundary in the chain defined by `head` -- i.e. the `BeaconBlock` where `block.slot == get_epoch_start_slot(head.slot)`.

_Note:_ This can be looked up in the state using `get_block_root(state, get_epoch_start_slot(head.slot))`.

##### Justified block root

Set `attestation_data.justified_block_root = hash_tree_root(justified_block)` where `justified_block` is the block at `state.justified_epoch` in the chain defined by `head`.

_Note:_ This can be looked up in the state using `get_block_root(state, justified_epoch)`.

The above does not make much sense, as get_epoch_start_slot is defined in terms of epochs, not slots, as `epoch * EPOCH_LENGTH`, but want we want here instead is to get the start slot of the epoch boundary defined by the canonical head, so instead we can do `get_epoch_start_slot(closest_epoch_boundary(head.Slot))`. Similarly for the justified block root, it should be `get_epoch_start_slot(state.justified_epoch)` instead.

See our Github gist for our implementation of this logic in Prysm.

https://gist.github.com/rauljordan/d4e57afb63e8caea4333ebe3e4d3588c

**Comment by djrtwo** [comment]
Right, we changed `get_epoch_start_slot` to take an epoch instead of a slot when we moved epochs to being more important. Looks like this can be fixed by ensuring we get the epoch of the slot in question and pass it to `get_epoch_start_slot` in both cases, correct?
