### ISSUE TITLE
What is vote_data in verify_slashable_attestation?

### ISSUE THREAD

**Issue by akhila-raju** [ethereum/eth2.0-specs#632]
What is vote_data referring to in [verify_slashable_attestation](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#verify_slashable_attestation)? I don't see this field used anywhere else.

**Comment by jrhea** [comment]
it looks like it is leftover from `SlashableVoteData`.  I think it should read:

```
        domain=get_domain(
            state.fork,
            slot_to_epoch(slashable_attestation.data.slot),
            DOMAIN_ATTESTATION,
        ),
```
