### ISSUE TITLE
Challenges in standardizing light client Merkle proofs

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#644]
A light client interacting with the beacon chain will often need to make many types of accesses, including calling functions like `get_persistent_committee(state, epoch)` to determine which validators are the committee at some epoch, accessing elements of `validator_registry` and other arrays, accessing specific ranges of data in shards, etc. Many of these operations will require Merkle branches for the specific variables that they access, and in some cases the required accesses are dynamic.

This presents challenges in specifying how light client proofs would work. Specifically, how do we specify what Merkle proofs a full client gives to a light client that is interested in computing the output of a function?

One approach is to be very function-specific, and specify "for operation X, we need Merkle proofs A, B and C".

Another approach is to be maximally general, and define a helper:

* `GenerateMerkleProof(f, args)`, which computes `f(args)`, and saves all Merkle proofs for all values in `args` that needed to be accessed to make the computation, and returns a `MerklePartial[arg]` object for every `arg` in `args`.
* A `MerklePartial[arg]` can be fully substituted in for `arg` in any computation (eg. the BeaconState is likely to be the most common use case), except that it triggers an error if an access is attempted that goes outside of what the Merkle proofs for the object can provide.

This would allow light client algorithms to be specified much more easily, eg. a light client syncing could work as follows:

* Ask for a `GenerateMerkleProof(get_persistent_committee, [state, state.slot])` where `state` is the state whose SSZ root is the state root of a block that is being provided.
* Set `committee` to `get_persistent_committee(merkle_partial_state, merkle_partial_state.slot)`.
* If `current_state` is the current state the light client knows about, ask for a `GenerateMerkleProof(lambda x: [x.validator_registry[c] for c in committee], current_state)`. Set `validator_registry_items` to equal  `[merkle_partial_state.validator_registry[c] for c in committee]`

And so forth. The `GenerateMerkleProof` on the full-node side, and the use of a `MerklePartial` in place of a regular complete object on the light-client side, does all of the heavy lifting.

Do people have any thoughts on which approach makes the most sense here?

In general, there are many light client syncing algorithms, but if we go this route it would make sense to standardize `GenerateMerkleProof` and `MerklePartial`, including the format for these Merkle proofs, fairly early.

See https://ethresear.ch/t/optimizing-merkle-tree-multi-queries/4912 for a thread on optimizing multi-proofs for single trees; though note that here the proofs would need to be generic and cover SSZ serialization of any object of arbitrary depth, and would ideally have optimal data-deduplication properties in these cases.

**Comment by JustinDrake** [comment]
> Do people have any thoughts on which approach makes the most sense here?

The generalised approach feels like a long-term winner, and we may be able to pull it off in the short-term also. One idea would be to have WASM be the standardised VM for such "light client queries" where `f` is a WASM executable. That would yield stronger synergies between light clients and stateless clients, and calling `GenerateMerkleProof` would be somewhat like executing a "beacon chain smart contract".

The work to find an optimal Merkle proof batching and data-deduplication technique sounds like nice piece of low-hanging fruit for someone to get their hands dirty.

**Comment by vbuterin** [comment]
> The work to find an optimal Merkle proof batching and data-deduplication technique sounds like nice piece of low-hanging fruit for someone to get their hands dirty.

Actually not that hard!

https://medium.com/@jgm.orinoco/understanding-sparse-merkle-multiproofs-9b9f049e8f08

**Comment by djrtwo** [comment]
The one thing I'm concerned about here is the requesting of particular functions with particular inputs and outputs by a particular name across clients. This either reduces optionality in client design _or_ at least requires them to maintain an interface to mapping these spec functions to their own internal structures.

An alternative is the maintain a clear mapping of these spec level functions to the parameters needed to execute them. Then we can use these functions in the light client specs freely, knowing that light clients know exactly what to request to be able to compute the outputs locally. So instead of requiring a full client to be able to come up with the require proofs depending on the function requested, the light client can instead just make the explicit requests for the required data. I suppose this comes at a small cost of bandwidth on the request side.

**Comment by vbuterin** [comment]
I'm not suggesting that we actually use function names in the spec as identifiers in the wire protocol. It's more just standardizing the idea that expected behavior of clients can be defined by "calculate this function of the state and return a Merkle proof of a sufficient set of values to allow recipients to recalculate the result".

**Comment by djrtwo** [comment]
How do you expect the request from a light client to be made then?

**Comment by djrtwo** [comment]
this is handled in [merkle_proofs.md](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/light_client/merkle_proofs.md)
