### ISSUE TITLE
verify_slashable_attestation with custody bits all 0 OR all 1

### ISSUE THREAD

**Issue by kirk-baird** [ethereum/eth2.0-specs#651]
In `verify_slashable_attestation` if all `slashable_attestation.custody_bitfield` bits are the same (i.e. all 0 or all 1) then the `aggregate_pubkey` for the other will either not be initialised or the point will be set to infinity.

e.g. 
Say `custody_bitfield` is all 0. 
Then `custody_bit_1_indices` will be empty.
Hence `bls_aggregate_pubkeys([state.validator_registry[i].pubkey for i in custody_bit_1_indices]),` will either return an uninitialized public key or infinity neither of which can return true for `bls_verify_multiple()`

```
...
    custody_bit_0_indices = []
    custody_bit_1_indices = []
    for i, validator_index in enumerate(slashable_attestation.validator_indices):
        if get_bitfield_bit(slashable_attestation.custody_bitfield, i) == 0b0:
            custody_bit_0_indices.append(validator_index)
        else:
            custody_bit_1_indices.append(validator_index)

return bls_verify_multiple(
        pubkeys=[
            bls_aggregate_pubkeys([state.validator_registry[i].pubkey for i in custody_bit_0_indices]),
            bls_aggregate_pubkeys([state.validator_registry[i].pubkey for i in custody_bit_1_indices]),
        ],
        message_hashes=[
            hash_tree_root(AttestationDataAndCustodyBit(data=slashable_attestation.data, custody_bit=0b0)),
            hash_tree_root(AttestationDataAndCustodyBit(data=slashable_attestation.data, custody_bit=0b1)),
        ],
        signature=slashable_attestation.aggregate_signature,
        domain=get_domain(state.fork, slot_to_epoch(slashable_attestation.data.slot), DOMAIN_ATTESTATION),
    )
```

A quick solution could be to add these to the pubkeys and message_hashes if the list of indices is not empty.
e.g.
```
...
    custody_bit_0_indices = []
    custody_bit_1_indices = []
    for i, validator_index in enumerate(slashable_attestation.validator_indices):
        if get_bitfield_bit(slashable_attestation.custody_bitfield, i) == 0b0:
            custody_bit_0_indices.append(validator_index)
        else:
            custody_bit_1_indices.append(validator_index)

    pubkeys = []
    message_hashes = []

    if not custody_bit_0_indices.is_empty():
        pubkeys.append(bls_aggregate_pubkeys([state.validator_registry[i].pubkey for i in custody_bit_0_indices]))
         message_hashes.append(hash_tree_root(AttestationDataAndCustodyBit(data=slashable_attestation.data, custody_bit=0b0)))
    if not custody_bit_1_indices.is_empty():
        pubkeys.append(bls_aggregate_pubkeys([state.validator_registry[i].pubkey for i in custody_bit_1_indices]))
         message_hashes.append(hash_tree_root(AttestationDataAndCustodyBit(data=slashable_attestation.data, custody_bit=0b1)))

return bls_verify_multiple(
        pubkeys=pubkeys,
        message_hashes=message_hashes,
        signature=slashable_attestation.aggregate_signature,
        domain=get_domain(state.fork, slot_to_epoch(slashable_attestation.data.slot), DOMAIN_ATTESTATION),
    )
```

**Comment by djrtwo** [comment]
nice catch! At first glance, I think your solution is appropriate

**Comment by JustinDrake** [comment]
> will either not be initialised or the point will be set to infinity

`bls_aggregate_pubkeys()` returns the the identity element (neither uninitialised nor "infinity") with the empty array, which should work just fine with `bls_verify` and `bls_verify_multiple`. (This is similar to empty integer sums being 0, and empty integer products being 1.)

**Comment by hwwhww** [comment]
> `bls_aggregate_pubkeys()` returns the the identity element (neither uninitialised nor "infinity") with the empty array, which should work just fine with `bls_verify` and `bls_verify_multiple`.

1. Can confirm that it works fine.
2. I think it's also fine to apply this fix to pass a one-item array `messages` and `pubkeys` to reduce the  computation?

**Comment by JustinDrake** [comment]
1. For those wondering, when `pubkey = g` and `signature = hash_to_G2(message_hash, domain)` then `e(pubkey, hash_to_G2(message_hash, domain)) == e(g, signature)` trivially holds.
2. No need to complicate the spec! Implementers can skip the pairing check when `pubkey == g`. I wonder if the BLS signature libraries already implement this.

**Comment by djrtwo** [comment]
Thanks for the recon @hwwhww and @JustinDrake.
Closing the issue unless you or @kirk-baird need further conversation/clarification

**Comment by kirk-baird** [comment]
Yep, make sense to me.
What is the (x, y, z) or (x, y) of the identity for the pubkey curve?

**Comment by JustinDrake** [comment]
The signature for multiple messages in the context of `bls_verify_multiple` is the sum of the signatures for individual messages in the context of `bls_verify`. Let:

* `h0 = hash_to_G2(hash{attestation data, 0}, domain)`
* `h1 = hash_to_G2(hash{attestation data, 1}, domain)`
* `pk0 = x0 * g` be the aggregated public key for 0 custody bits for some "aggregated secret" `x0`.
* `pk1 = x1 * g` be the aggregated public key for 1 custody bits for some "aggregated secret" `x1`.

The individual signatures are `x0 * h0` and `x1 * h1` and the final aggregated signature is `x0 * h0 + x1 * h1`.

The aggregated secret is a sum over the integers, so the natural zero element is 0. So when all custody bits are 0 then `x1 = 0` (so that `pk1 = 0 * g`) and the final signature is `x0 * h0`.

Note that this is *not* what I was claiming above 🤦‍♂️. The natural zero element for public keys is indeed the point at infinity (which matches the Python code). To answer your original question, notice no special handling is required when the public key is the point at infinity because `e(0 * g, h0) == e(g, 0 * x0)`.

**Comment by kirk-baird** [comment]
Ohh yep I see where you're coming from now!

The aggregate signature doesn't need to be changed because we would be adding the additive identity since sk1 = 0:
```
sig0 = sk0 * h0
sig1 = 0 * h1
agg_sig = sig0 + sig1 = sig0 + 0 = sig0
```

Also the LHS of `verify_multiple` doesn't need to be changed as e(h1, 0) represents the multiplicative identity hence
`e(h0, pk0) * e(h1, 0) = e(h0, pk0)`

Therefore the whole equation would look like:

`e(h0, pk0) == e(sig0, g)` 

Which is the same a verifying a single aggregate signature.

Thanks for the explanation :smile:
