### ISSUE TITLE
Gracefully handle bad proofs of possession

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#657]
At the moment we `assert` that proofs of possession are correct:

```
    assert bls_verify(
        pubkey=deposit_input.pubkey,
        message_hash=signed_root(deposit_input, "proof_of_possession"),
```

This `assert` is bad for a few reasons:

1) The "logic to ensure that deposits from 1.0 chain are processed in order" may prevent "skipping" deposits.
2) User funds go in a black hole.

My suggestion would be to process the deposit (no `assert`) and make validator status go directly to "withdrawn".

**Comment by djrtwo** [comment]
We already handled (1) in master. Looks like a cleanup messed up the functionality.

See [`process_deposit` in master](https://github.com/ethereum/eth2.0-specs/blob/master/specs/core/0_beacon-chain.md#process_deposit). We do the following to keep processing moving forward even if the validation failed.

```python
if not proof_is_valid:
    return
```

As for (2), I'm more amenable to black holes than you are :)
Is there any security risk in moving the user funds to withdrawable if they failed their PoP?

**Comment by JustinDrake** [comment]
> We already handled (1) in master.

👍 

> Is there any security risk in moving the user funds to withdrawable if they failed their PoP?

I don't see any security risk. One benefit is that it would unlock the possibility to (intentionally) make deposits without having to be a validator, e.g. by leaving the PoP all zeros.

**Comment by hwwhww** [comment]
closing via #687
