### ISSUE TITLE
Fix `verify_merkle_branch`

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#659]
### Issue

After we use progressive Merkle tree for the deposits, the deposit validation needs to updated to https://github.com/ethereum/deposit_contract/pull/13 since now the non-leaf empty nodes are also merkleized.

### Proposed solution
1. Update the spec when https://github.com/ethereum/deposit_contract/pull/13 is merged.
2. (Recommend) Rename `verify_merkle_branch` to `verify_merkle_proof` because it's proof, not just branch.

**Comment by NIC619** [comment]
I was mistaken for how processing deposits works and also `verify_merkle_branch` is agnostic of the implementation details of the tree.
Closing https://github.com/ethereum/deposit_contract/pull/13 and this issue. Though 2. probably still stands.

**Comment by JustinDrake** [comment]
I think this can be closed. Please reopen if not :)
