### ISSUE TITLE
Add the description of deposit Merkle proof in validator guide

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#660]
### Issue
When using `verify_merkle_branch`, the Merkle proof is against `state.latest_eth1_data.deposit_root`, not the `deposit_root` right after the deposit. The `Deposit` makers have to generate Merkle proof with `state.latest_eth1_data.deposit_root` locally.

### Proposed solution
There might be various ways to generate Merkle proof and can be optimized so I'm not sure if we need to make it in-spec. But, at least it would be nice to add the format description of Merkle proof in the validator guide.

**Comment by djrtwo** [comment]
There is a note here https://github.com/ethereum/eth2.0-specs/blob/dev/specs/validator/0_beacon-chain-validator.md#deposits
