### ISSUE TITLE
Use custom types in data structures

### ISSUE THREAD

**Issue by Nashatyrev** [ethereum/eth2.0-specs#667]
As soon as there are strict custom types for helper functions may be it makes sense to use them appropriately for data structures members like below.
```python
BeaconState
{
    # Misc
    'slot': Slot,
    'genesis_time': 'uint64',
    'fork': Fork,  # For versioning hard forks

    # Validator registry
    'validator_registry': [Validator],
    'validator_balances': [Gwei],
    'validator_registry_update_epoch': Epoch,

    # Randomness and committees
    'latest_randao_mixes': [Bytes32],
    'previous_shuffling_start_shard': Shard,
    'current_shuffling_start_shard': Shard,
    'previous_shuffling_epoch': Epoch,
    'current_shuffling_epoch': Epoch,
    'previous_shuffling_seed': Bytes32,
    'current_shuffling_seed': Bytes32,
...
```
In our Java implementation we already converted the structures members (like [this](https://github.com/harmony-dev/beacon-chain-java/blob/1ec9b9b10c9a474c7e06ff1f473e3b99c15605a5/core/src/main/java/org/ethereum/beacon/core/BeaconState.java#L39)) and constants (like [this](https://github.com/harmony-dev/beacon-chain-java/blob/335e0d91df44882adf4245e91bde102fea887c5a/core/src/main/java/org/ethereum/beacon/core/spec/InitialValues.java#L21)) to custom types (where applicable) which significantly improved readability and type safety.

**Comment by JustinDrake** [comment]
Agreed this improves readability! We can even define a `Hash` custom type.

**Comment by Nashatyrev** [comment]
Cool! I can take care of PR then. 
We also added `Time` type (aka number of seconds), though it's not too widespread.
Another question: is there any means to specify the array index type, like ?
```
  'validator_balances': [ValidatorIndex => Gwei],
...
  'latest_block_roots': [Slot => Hash],
  'latest_index_roots': [Epoch => Hash],
```

**Comment by hwwhww** [comment]
I'm not sure if I like it or not. Some notes:
1. The current data structure section is defined with SSZ serialization types. I’d say let's not mix custom type and SSZ in the same section; so if we want to use custom types to describe data structure, do it **fully**. That said, some other types like `Bitfield: bytes`, `Bool: bool` (#658) would need to be defined as well.
    - Then we will find that `'justification_bitfield': 'uint64'` is suspicious but correct…ahhh..  (see #371)
3. However, declaimed, in Python, the `typing` custom types are not strict. So it won’t improve type safety in programming-level (helper functions), only in readability-level.

**Comment by Nashatyrev** [comment]
1. I would consider custom types as *alias types* for SSZ serialization types so nothing should change from SSZ point of view. 
We currently have the following additional types: 
- `Hash`
- `Time`
- `Bitfield` for `Attesstaion`
- `Bitfield64` for justification_bitfield

What's left 'raw' `UInt64`: 
- `Eth1DataVote.vote_count`
- `Deposit.index`
- `ForkData.previous/current_version`
- different flags

(some may be outdated or missing since we didn't yet migrate from Spec v0.1)

2. Sure I suppose the type-safety is about implementation not the spec.

**Comment by JustinDrake** [comment]
Closing in favour of #1156 :)

Sorry it too this long @Nashatyrev. Feel free to review that PR.
