### ISSUE TITLE
Get genesis epoch committee assignment

### ISSUE THREAD

**Issue by terenc3t** [ethereum/eth2.0-specs#668]
In current validator doc, there's the responsibility look ahead which is implemented by `get_next_epoch_committee_assignment`. Similarly we should have   `get_gensis_epoch_committee_assignment` for genesis epoch assignment. So when validators try to get their genesis assignment they don't end up getting slots" `genesis_epoch + 64 .. genesis_epoch + 127` 😛 

Let me know if this is already specified somewhere and I'd be happy to open a PR

**Comment by djrtwo** [comment]
Ah, you're right. They would need to use `get_crosslink_committees_at_slot` directly for hte current epoch. I'll either mod the helper or add something new to make it explicit how to do so
