### ISSUE TITLE
justified_block_hash.slot != justified_slot

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#67]
With reference to the following:

> Verify that the `justified_slot` and `justified_block_hash` given are in the chain and are equal to or earlier than the `last_justified_slot` in the crystallized state.

Is it intended that the block identified by `justified_block_hash` has a `slot_number` that does not equal `justified_slot`? In other words, can an `AttestationRecord` point to a `justified_slot` which contains a block other than `justified_block_hash`?

With the present wording in the spec, I believe that is possible.

Thanks!

**Comment by djrtwo** [comment]
How about:
> Verify that `justified_slot` is equal to or earlier than `last_justified_slot`, and verify that `justified_block_hash` is the block in the chain at the slot defined by `justified_slot`

This puts the easy check first and then makes sure that the justified_hash and slot match up.

**Comment by paulhauner** [comment]
LGTM.

Maybe they could be separate points? Your call.

If we need to read the `justified_block_hash` slot from the DB, is there still a purpose for having `justified_slot` in the `AttestationRecord`?

**Comment by djrtwo** [comment]
Yeah, much easier to slash. Can tell if two attestations are conflicting without having to do a db lookup.

Might be easier to prove things to light clients to (?)

**Comment by djrtwo** [comment]
separate points works.
