### ISSUE TITLE
Clarification on block roots inclusion  

### ISSUE THREAD

**Issue by terencechain** [ethereum/eth2.0-specs#670]
In validator design spec, under [Attestations](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/validator/0_beacon-chain-validator.md#attestation-data). To include the following block roots in attestation we do:

**Epoch boundary root**: `get_block_root(state, get_epoch_start_slot(slot_to_epoch(head.slot)))`
**Justified block root**: `get_block_root(state, justified_epoch)`

There's a few special cases that the spec did not mention:
1.) For genesis slot: what do attesters put for epoch boundary root and justified block root:
2.) Before the first block gets justified: what do attesters put for justified block root:
3.) During epoch boundary slot: what do attesters put for epoch boundary root? the previous epoch boundary root?

**Comment by JustinDrake** [comment]
@terencechain is this still an issue?

**Comment by terencechain** [comment]
Nope, the questions have been addressed
