### ISSUE TITLE
Slashing condition slot issue

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#690]
# Issue

Both `is_surround_vote` and `is_double_vote` use `attestation.data.slot` to figure out the "target" epoch (in FFG terms). This assumes that the "target" epoch is the same as the epoch the validator has been assigned. If there is high latency or low block production participation, the target epoch might be some previous epoch, and in such a case, the just checking if the validator made two different votes during a single epoch is not sufficient (for `is_double_vote`).

For example:
* During epoch N, validator votes on some block B1 with the epoch boundary N1 as the start block of that epoch.
* During epoch N+1, the validator votes on block B2 (from epoch N rather than from epoch N+1) with an the epoch boundary N2 (where `N1 != N2`).
* The validator voted on two conflicting blocks at the same slot height (for ffg) but the `is_double_vote` does not catch it because `attestation.data.slot` is not equal.

Adding another field `beacon_block_slot` would provide enough information to resolve this issue, but I'm not entirely convinced this is the proper route. Need to mull over these exceptional cases when no blocks are being produced a bit more

(Thanks @krzhang. This came up in a chat we had about formalizing the [ffg pos mini spec](https://ethresear.ch/t/beacon-chain-casper-mini-spec/2760))

Edit: This is somewhat related to another issue -- should a validator transition through empty slots from the head they see locally up to the slot at which they are assigned when grabbing the state to attest to. I am 95% sure the answer to this is yes.

**Comment by vbuterin** [comment]
Don't think I understand the distinction. The target epoch is the same as the epoch the validator has been assigned by definition. The epoch the attestation gets _included_ could be later, but we're already taking that into account in other ways.

> The validator voted on two conflicting blocks at the same slot height (for ffg) but the `is_double_vote` does not catch it because `attestation.data.slot` is not equal.

Slot height for FFG in this case _is_ the block that's being attested to (ie. `attestation.data.slot`).

Also, I thought we're not voting for the start block of an epoch, we're voting for the most recent block _before_ an epoch?

**Comment by hwwhww** [comment]
@djrtwo 
Is it fine to close now?

**Comment by djrtwo** [comment]
This has been clarified in the validator guide noting that a validator must transition through state to the slot they are attesting to. A validator is essentially attesting to a (slot, block) tuple rather than jsut a block
