### ISSUE TITLE
Commutative rewards processing

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#700]
Rewards are currently [processed serially](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#justification-and-finalization) which means that `base_reward(state, index)` can change from one micro-incentive to the next. My suggestion would be to always use the same `base_reward(state, index)` for rewards.

Making rewards processing commutative has various benefits:

* Cleaner
* More flexible and less brittle for developers
* More opportunity for parallelism

**Comment by djrtwo** [comment]
The intention already in the spec is to _fix_ `base_reward` per validator before reward calculations and to add as needed.
I think we just need to make it clearer

**Comment by JustinDrake** [comment]
> I think we just need to make it clearer

If that's already the intention then great. I see Prysmatic does things serially (see [here](https://github.com/prysmaticlabs/prysm/blob/master/beacon-chain/core/state/transition.go#L295)) as currently specified.

**Comment by djrtwo** [comment]
Yeah, earlier we had these things helpers more clearly as singular defs rather than functions to be called repeatedly. I imagine due to the wording that most people are doing it like Prysmatic right now.

**Comment by hwwhww** [comment]
Duplicated issue to #677

**Comment by vbuterin** [comment]
#711 implicitly fixes this by separating calculation and application of deltas :smile:

**Comment by JustinDrake** [comment]
Closing in favour of #711.
