### ISSUE TITLE
Use all 64 bits in fork_version

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#706]
This was brought up by @protolambda. We are inconsistent on the handling of `fork_version`:

* We define it as a `uint64`.
* We use it as a `uint32` when doing `fork_version * 2**32 + domain_type`.

I think it would be cleaner if the final signing logic used `hash(message_hash + bytes8(fork_version) + byte1(domain))` as opposed to `hash(message_hash + bytes8(domain))`.

**Comment by djrtwo** [comment]
Defined `fork_version` as a `uint64` for consistency of 64-bit types everywhere, but clearly only intend to use it up to 32bits.

To be clear, you are suggesting changing the bls functions to accept `fork_version, domain` rather than just `domain`?

**Comment by JustinDrake** [comment]
> you are suggesting changing the bls functions to accept `fork_version, domain` rather than just `domain`?

Right, but ideally there's something cleaner.

**Comment by JustinDrake** [comment]
A clean solution (idea taken from @vbuterin) is to define `fork_version` as a `byte[4]`. It also makes more sense semantically because we're not doing no arithmetic on it. We can also define `domain_type` as a `byte[4]`, which again makes more sense semantically. We then replace `return fork_version * 2**32 + domain_type` with `return fork_version + domain_type`.
