### ISSUE TITLE
MIN_VALIDATOR_WITHDRAWABILITY_DELAY applied twice

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#712]
The `MIN_VALIDATOR_WITHDRAWABILITY_DELAY` is applied twice:

* In `prepare_validator_for_withdrawal()` it is included in `validator.withdrawable_epoch`.
* In `process_exit_queue()` it is used for `eligible()`.

---

<img width="457" alt="screenshot 2019-03-01 at 15 36 19" src="https://user-images.githubusercontent.com/731743/53644833-d1120e00-3c37-11e9-9432-40a787e1af7f.png">

**Comment by vbuterin** [comment]
It's definitely intended for both stages of the validator lifecycle to have the delay. Welcome suggestions for what to rename it to.

**Comment by JustinDrake** [comment]
Would it be fair to say that (for phase 0 at least) the logic is roughly equivalent to removing the delay in `process_exit_queue` and doubling the delay in `prepare_validator_for_withdrawal`? My guess is that this is ground work for the phase 1 custody game, but I can't quite put my finger on it.

On this topic, do we want to change the rate limiting logic based on [this Ethresear.ch post](https://ethresear.ch/t/rate-limiting-entry-exits-not-withdrawals/4942)?

**Comment by vbuterin** [comment]
> Would it be fair to say that (for phase 0 at least) the logic is roughly equivalent to removing the delay in process_exit_queue and doubling the delay in prepare_validator_for_withdrawal? 

I don't think it's *quite* equivalent to either of those. If `x` is the queue length, then `max(x, 2)`, `max(x, 1) + 1` and `x + 2` are all different functions.

> On this topic, do we want to change the rate limiting logic based on this Ethresear.ch post?

My heart wants to, my "let's do things now as an investment in making future phases easier" side also does, but my "we have to ship and we need to ban making nontrivial new changes at some point" side says no.....

**Comment by JustinDrake** [comment]
Closing in favour of #675 item 23 "Improved rate limiting".

I'm inclined to improve rate limiting now :)
