### ISSUE TITLE
Prevent balance underflow 

### ISSUE THREAD

**Issue by hwwhww** [ethereum/eth2.0-specs#727]
### Issue
- There are several places that we deduct the `state.validator_balances[validator_index]` for penalties.
- Logically, the validator would be ejected before the balance field is under the risk of underflow.
- But, when we read the function separately, do we need to add some protection to prevent balance underflow? For example, change
```python
state.validator_balances[index] -= penalty
```
to
```python
state.validator_balances[index] = max(state.validator_balances[index] - penalty, 0)
```

**Comment by vbuterin** [comment]
One way to fix this generally would be to define `decrement_balance` in that way in #728.

**Comment by JustinDrake** [comment]
`decrement_balance` implemented 🎉
