### ISSUE TITLE
When pow_chain_reference is orphaned

### ISSUE THREAD

**Issue by redsquirrel** [ethereum/eth2.0-specs#74]
Upon first reading of https://github.com/ethereum/eth2.0-specs/blob/master/specs/beacon-chain.md I'm wondering how it's possible to trust a PoW block hash to exist via `pow_chain_reference`, when it could be orphaned via temporary fork. Please set me straight!

**Comment by djrtwo** [comment]
We will set the follow distance beyond any reasonable reorg. Say 1000 blocks behind the head if the pow chain. 

If there is a (incredibly unlikely) reorg while we are still bound in this way, we will coordinate extra protocol to resolve the issue.

**Comment by redsquirrel** [comment]
Thanks

**Comment by vbuterin** [comment]
That's definitely the approach. The PoW chain link should be maximally simple; it doesn't need to be very efficient at keeping up closely with the main chain, and if the PoW chain suffers a big attack doing a hard fork to remedy it is totally fine.

**Comment by djrtwo** [comment]
closing. Holler if you have anymore questions regarding this.
