### ISSUE TITLE
Store prev/current justified root

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#742]
# issue

Attestation processing assumes that the previous/current block root will be available in `state.latest_block_roots` when processing attestations. 

```python
attestation.data.justified_block_root == get_block_root(
        state, get_epoch_start_slot(attestation.data.justified_epoch)
)
```

The call to `get_block_root` fails if more than `SLOTS_PER_HISTORICAL_ROOT` have passed since latest justified block. This is currently only about ~13 hours which requires liveness wrt justification in this period for the chain to continue to function. Oh no!

## proposed solution

Add `previous_justified_root` and `current_justified_root` directly to state to eliminate this lookup to a potentially unavailable slot.

(Thanks @arnetheduck for running your non-justifying chain for 8192 slots!)

**Comment by arnetheduck** [comment]
It might not necessarily have to be part of the state (duplicate info, kind of).. we can cache it somewhere in the client as well - we already keep a few other book-keeping fields like this around anyway.

**Comment by djrtwo** [comment]
State transition should be self contained wrt `pre_state, block`.
I'm not currently aware of any other book keeping fields that are _required_ in the state transition (that said, I expect clients to cache things in various ways as they decide worthwhile).

**Comment by arnetheduck** [comment]
fair enuff, I was still on a version that required the previous block.

**Comment by arnetheduck** [comment]
actually, there's nuance here. it doesn't look like the fields are needed to *apply* a block state transition - they're needed to fill out a block when you're proposing one, no?

**Comment by tdmllc1** [comment]
Deposit 500000000000000 in binanace account for account tdmllc1@outlook.com liquid trading capital NFA ID 0356535

**Comment by tdmllc1** [comment]
> Deposit 500000000000000 in binanace account for account [tdmllc1@outlook.com](mailto:tdmllc1@outlook.com) liquid trading capital NFA ID 0356535

Thank You

**Comment by tdmllc1** [comment]
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by djrtwo** [comment]
> actually, there's nuance here. it doesn't look like the fields are needed to apply a block state transition - they're needed to fill out a block when you're proposing one, no?

@arnetheduck which fields? access to the root of the justified epoch is needed both when creating an attestation and when validating it.

**Comment by tdmllc1** [comment]
"1518368749000" deposit tdmllc1@outlook.com USD

**Comment by arnetheduck** [comment]
>  when validating it.

right, my bad. missed this one.
