### ISSUE TITLE
Change shuffling to facilitate more optimizations [experimental idea]

### ISSUE THREAD

**Issue by protolambda** [ethereum/eth2.0-specs#747]
So I thought of some more optimizations for shuffling, other than hashing. After pushing the possible hash-performance with Justin, Carl and Dankrad during EthCC, I was looking for other bottlenecks. A hash does not have to be the only bottleneck currently.

Writing many times in arbitrary non-cached RAM could also be bad. (Tested with Justin, but benchmarks of shuffling without the code line that swaps seemed to return funny results, so I'm not making claims on this yet). If we change the sourcing of the bits to a different way (while still being permute-index and unshuffle compatible), we could achieve large optimizations here.

I've written up my ideas in the README.md of a new shuffling repo (as opposed to my previous optimized eth2 shuffling), link here: https://github.com/protolambda/eth2-shuffle-experiment

Suggestions welcome!

FYI: continuing work on executable Go spec starting from tomorrow (at ETHParis hackathon). Will work on shuffling later at some point. This is very much just an experimental sleep-deprived idea during this ETH week in Paris, but possibly very effective changes (hope to get > 2x speed up, > 10x with parallelization). :sweat_smile:

**Comment by vbuterin** [comment]
To be clear this is a different implementation of the same spec, so the results line up with the naive implementation exactly, correct?

Or are there spec changes that you are recommending too?

**Comment by protolambda** [comment]
Like the title says: these are changes to the spec. However, it's still swap-or-not (conceptually). The only thing that would change is the way pivots and swap-or-not bits (`bitV`) are determined. For the former, it's just an optimization for permute-index, since we're only using 8 bytes per pivot hash (32 bytes). For the latter, you could think of it as transposing the randomness bitfield we currently use. We still get the same behavioral properties; the described idea supports "permute-index" and both list-wise and permute-index can be reversed (in pretty much the same way as now, i.e. reverse round order)

The thing is, besides possibly some more optimizations in hashing, the current shuffling algorithm can't be optimized much better. It has a lower optimization ceiling. By this "transposing" of the randomness, we can go further with optimizations, and hopefully win a 2x, if not more (less writes + parallelization + CPU data cache fitting)

Just an idea, I'm not prioritizing it over my executable spec work, but even faster shuffling would be nice.

**Comment by protolambda** [comment]
Closing this. Turns out that although you can reduce writes pretty well with a little bit more hashing, you are still reading from a big chunks of memory, making it run slow.

How to improve shuffling from here, untested:

- implement simple pivot improvement for permute-index (4->1 hash reduction)
- split up your hashing function in layers (one for each round), and parallelize
