### ISSUE TITLE
This repository has no license.

### ISSUE THREAD

**Issue by atoulme** [ethereum/eth2.0-specs#748]
I believe this repository needs a license to ensure its intellectual property can be used in implementations.

See https://choosealicense.com/no-permission/ for a detailed description.

Quoting from that page:
>If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

Would maintainers be OK with licensing the repository under the MIT license?

**Comment by djrtwo** [comment]
Each document is marked as under "creative commons".

Agreed that it would be better to add a blanket license. @vbuterin does MIT make sense for a spec or should stick with Creative Commons?

**Comment by atoulme** [comment]
This is not indicated on the SSZ spec or the BLS doc. Not seeing it on the phase 0 spec either. Which creative commons license did you have in mind?

**Comment by djrtwo** [comment]
it's at the base of the phase 0 spec
https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#copyright

**Comment by djrtwo** [comment]
same with ssz https://github.com/ethereum/eth2.0-specs/blob/master/specs/simple-serialize.md#copyright
