### ISSUE TITLE
Inclusion slots and attestations [bug]

### ISSUE THREAD

**Issue by protolambda** [ethereum/eth2.0-specs#749]
Not every active validator may have an included attestation in the previous epoch (unlikely, but possible and enactable).

Now if the rewards are calculated, the proposer is awarded, based on inclusion distance to all active validators. There is no known distance however for such an active (as in activated) but inactive (as in not attesting in previous epoch) validator.

```python

for index in get_active_validator_indices(state.validator_registry, get_previous_epoch(state)):
    ...
    proposer_index = get_beacon_proposer_index(state, inclusion_slot(state, index))
```

This should be checking if there was any such attestation, and only then get the proposer index based on the inclusion slot.

If you don't have attestations for an active validator, the chain gets stuck because of an error. Should be an easy fix however.

**Comment by djrtwo** [comment]
This is already being addressed in #744 :)
