### ISSUE TITLE
Brain dump and proposed way forward on Serialization formats

### ISSUE THREAD

**Issue by pipermerriam** [ethereum/eth2.0-specs#754]
Full content can be found here:  https://notes.ethereum.org/QF8jgOQbRTWUhK1zoi8D4Q#

Opening this issue for visibility and discussion purposes.

**Comment by djrtwo** [comment]
Is option C suggesting two very related but slightly different formats? one for the networking and one for protocol?

**Comment by pipermerriam** [comment]
> Is option C suggesting two very related but slightly different formats? one for the networking and one for protocol?

Yes, two different serialization formats with a large degree of overlap.
