### ISSUE TITLE
When to add new validators via `add_validator`

### ISSUE THREAD

**Issue by djrtwo** [ethereum/eth2.0-specs#76]
# Issue
It is not currently clearly defined _when_ we should call `add_validator` to process new PoW logs other than at the beginning to process the initial validator set.

# Proposed Implementation
Call `add_validators_from_pow_logs` right before calling `change_validators` during a validator change. Do this _before_ activating/withdrawing in an effort to optimistically induct new validators from the pow chain if possible.

`validator_logs` includes _all_ deposit logs from the PoW chain up until the pow_chain_reference of the current block.

```python
def add_validators_from_pow_logs(validators: List[ValidatorRecord],
                                 validator_logs: List[ValidatorLog],
                                 current_slot: int) -> None:
    for validator_log in validator_logs:
        add_validator(
            validators=validators,
            pubkey=validator_log.pubkey,
            proof_of_possession=validator_log.proof_of_possession,
            withdrawal_shard=validator_log.withdrawal_shard,
            withdrawal_address=validator_log.withdrawal_address,
            randao_commitment=validator_log.randao_commitment,
            current_slot=current_slot
        )
```

**Comment by vbuterin** [comment]
This is covered by the last part of #71:

> Add a new type of SpecialObject, which consists of the entire hash-linked-list of HashChainValue logs since the previous PROCESSED_HASH_ROOT up to the POW_CHAIN_HASH_ROOT. If a valid such hash-linked-list is submitted, then we run add_validator with the given values for each record, and set PROCESSED_HASH_ROOT = POW_CHAIN_HASH_ROOT. This does mean that deposit processing is not "automatic"...

I will grant that automatic inclusion vs manual inclusion is a significant tradeoff that could be worth discussing more. I preferred manual inclusion because it significantly simplifies the consensus complexity of beacon chain <-> PoW chain interaction, but we could potentially go either way.

**Comment by djrtwo** [comment]
After reviewing your proposal, I think the more loose coupling is superior.

Closing in favor of #71
