### ISSUE TITLE
Is MAX_VALIDATOR_CHURN_QUOTIENT wrong?

### ISSUE THREAD

**Issue by jamesray1** [ethereum/eth2.0-specs#80]
> At most `1/MAX_VALIDATOR_CHURN_QUOTIENT` of the validators can change during each validator set change.

MAX_VALIDATOR_CHURN_QUOTIENT = 2^5 = 32

So this equates to saying

At most 1/32 of the validators can change during each validator set change.

So clearly there is a mistake. Perhaps MAX_VALIDATOR_CHURN_QUOTIENT = 2^(-5)?

**Comment by hwwhww** [comment]
I think that means the proportion? `1/32 of the validators` sounds correct to me.

**Comment by jamesray1** [comment]
Oh right that makes sense, for some reason I didn't see "of the"! Should've read more carefully!
