### ISSUE TITLE
Churn queue bypass

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#802]
A rational validator may bypass the churn queue by voluntarily slashing himself if he's in a hurry to get his money. Because of partial slashing the validator only loses 1/32nd of its balance at stake in the best case.

Should we replace `exit_validator` by `initiate_validator_exit` in `slash_validator` to avoid this queue bypass? This would also be a cleaner way of handling #785 and would simplify the validator state machine since all exits (voluntary exits, ejections, slashings) would go through the same exit pipeline stages.

**Comment by vbuterin** [comment]
That's what the longer 36-day time-to-exit if you get slashed is meant to discourage. I would say when we do the validator queue -> exit queue reform, set that time to exit to be equal to the time needed to go through the queue if you were behind every currently bonded validator.

**Comment by JustinDrake** [comment]
This is addressed in the exit/withdrawal queue refactor https://github.com/ethereum/eth2.0-specs/pull/850
