### ISSUE TITLE
Clean up untriggerable asserts

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#803]
In the context of testing/fuzzing, we may want every `assert` to be triggerable by a state transition test (this is arguably part of "100% test coverage").

There are currently 53 `assert`s in `0_beacon-chain.md`. The following 9 seem untriggerable by a bad block. We should consider removing them (e.g. changing them to `sys.exit(1)`) to clarify that those assertions are for sanity checking and/or documentation and are not expected to trigger.

```python
# get_permuted_index
assert index < list_size
assert list_size <= 2**40

# get_crosslink_committees_at_slot
assert previous_epoch <= epoch <= next_epoch

# get_block_root
assert slot < state.slot <= slot + SLOTS_PER_HISTORICAL_ROOT

# get_state_root
assert slot < state.slot <= slot + SLOTS_PER_HISTORICAL_ROOT

# get_randao_mix
assert get_current_epoch(state) - LATEST_RANDAO_MIXES_LENGTH < epoch <= get_current_epoch(state)

# get_active_index_root
assert get_current_epoch(state) - LATEST_ACTIVE_INDEX_ROOTS_LENGTH + ACTIVATION_EXIT_DELAY < epoch <= get_current_epoch(state) + ACTIVATION_EXIT_DELAY

# get_beacon_proposer_index
assert previous_epoch <= epoch <= next_epoch

# integer_squareroot
assert n >= 0
```

**Comment by djrtwo** [comment]
many of these are for usage _outside_ of the state transition function. If someone wanted to run `get_block_root` against a slot/state, they need to have some sort of bounds checking.

For example clients run `get_crosslink_committees_at_slot` often locally to figure out assignments for the current and next epoch. They should have explicit guidance in the def of the function to show the bounds so that they know to handle the exception when they try to do something like get assignments for two epochs in advance.

**Comment by JustinDrake** [comment]
I'm not sure what is the most Pythonic way to discriminate "spec code" from "implementer guidance". In the Go executable spec the distinction is made between `return err` (for expected error handling in the spec) and `panic(err)` (for implementer guidance that is not expected to trigger in the context of the spec).

**Comment by hwwhww** [comment]
@JustinDrake A Pythonic way is that we can define a custom exception for the spec error; in Py-EVM there's a `ValidationError` (`class ValidationError(Exception): pass`), and we can raise `ValidationError` explicitly.

I think we did consider it but also worried about that might be *too Pythonic* compare to simple `assert` for the readers.

@djrtwo What do you think about it?

**Comment by arnetheduck** [comment]
`assert` lgtm as an explicit way to document pre-conditions and valid argument values in a spec - there are similar hidden pythonisms (such as array-out-of-bounds accesses etc) that are best brought to light this way, I believe.

one problem we've had in the past with these assertions was that they were expressed in terms of a block-transition-in-progress - that has substantially improved with the shifted epoch processing, but I would be keen to see / know if there are any exceptions to that rule, where certain functions can only be used at certain points of the transition function.

**Comment by JustinDrake** [comment]
We're down to just three untriggerable asserts 🎉 (#1237 removes the assert in `integer_squareroot`):

```python
# shuffle_index
assert index < list_size
assert list_size <= 2**40

# get_block_root_at_slot
assert slot < state.slot <= slot + SLOTS_PER_HISTORICAL_ROOT
```

**Comment by JustinDrake** [comment]
Down to two:

```python
# compute_shuffled_index
assert index < index_count

# get_block_root_at_slot
assert slot < state.slot <= slot + SLOTS_PER_HISTORICAL_ROOT
```
