### ISSUE TITLE
Add explicit guidance on when to run fork choice?

### ISSUE THREAD

**Issue by terencechain** [ethereum/eth2.0-specs#804]
We are currently working on integrating LMD GHOST into our prysm client. I'm wondering if the beacon chain spec should have some explicit guidance on _when_ a client should run fork choice.

**Comment by protolambda** [comment]
We have a separate fork-choice doc for over a month now. ([here](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_fork-choice.md). Closing this issue. Feel free to re-open and suggest any additions to the doc if you feel like something essential to the spec is missing.
