### ISSUE TITLE
Explicitly pass state to `eligible` function

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#813]
The `eligible` function uses the `state` object implicitly. (Also missing type hinting.)

```python
    def eligible(index):
        validator = state.validator_registry[index]
...
```

**Comment by djrtwo** [comment]
The eligible function has access to the scope of the function in which it is defined.
This is entirely valid and executes properly.

**Comment by JustinDrake** [comment]
> This is entirely valid and executes properly.

Yes, but it's ugly and this function is also referred to in the phase 1 spec with "note that it is not a pure function because `state` is declared in the surrounding scope"

**Comment by vbuterin** [comment]
Yeah, making it into a pure function seems reasonable.

**Comment by JustinDrake** [comment]
The `eligible` function is gone in https://github.com/ethereum/eth2.0-specs/pull/850
