### ISSUE TITLE
Rename `Transactions` back to `Operations`

### ISSUE THREAD

**Issue by decanus** [ethereum/eth2.0-specs#822]
A few of us implementers have been talking about the naming of `Transactions` and believe it is best renamed back to `Operations` to lower confusion and potentially mistaking `Transactions` with transactions in the classical sense. The only thing that should be known as a `Transaction` is a `Transfer`.

If not, it would be great to know what the reason behind the rename was.

**Comment by GregTheGreek** [comment]
+1

**Comment by djrtwo** [comment]
I'm pro :)
Spent a long time coming up with the name Operations and was sad to see it go

**Comment by JustinDrake** [comment]
> it would be great to know what the reason behind the rename was

Abstractly, a "blockchain" is a chain of "blocks" that advance "state", where the blocks contain signed messages called "transactions". The beacon chain is a "system blockchain" which has "system blocks", "system state" and... "system transactions".

In summary, the word "transaction" was picked to fit the block/state/transaction framework. While I think the nomenclature is natural I can see how it can be confusing. Looks like people are in favour of the rename :)

**Comment by decanus** [comment]
@justindrake thanks for the full clarification. As we have user transactions on the beaconchain now I’d definitely support going back to operations.

**Comment by JustinDrake** [comment]
> As we have user transactions on the beaconchain now I’d definitely support going back to operations.

Sure. (As a side note, transfers are a temporary thing to be removed in phase 2.)
