### ISSUE TITLE
Potential attack on the beacon chain by rational validators: The Gatekeeping Attack

### ISSUE THREAD

**Issue by Mikerah** [ethereum/eth2.0-specs#832]
Special thanks to @adlerjohn  for initial discussions on this.

Currently, to become a validator, one has to make a deposit on the ETH1 chain and have it processed by the beacon chain. Once the deposit is made, a validator has to wait ~6 hours before 1) ETH1 data gets added to a beacon block and then 2) until the potential validator gets processed within 2 epochs.

The spec as currently written doesn't take into account the [_gatekeeping attack_](https://arxiv.org/abs/1811.00742) in which individually rational proposers will choose to exclude deposit receipts, as each new validator strictly decreases their rewards. This is because [the total reward scales with the square root of the total balance](https://github.com/ethereum/eth2.0-specs/blob/v0.5.0/specs/core/0_beacon-chain.md#rewards-and-penalties).

There are at least 2 independent ways to fix this:

1. Change the current sub-linear issuance model to a linear issuance model (i.e., set `adjusted_quotient = get_previous_total_balance(state) // BASE_REWARD_QUOTIENT`). Since individual validator rewards no longer decrease with each new validator, there is no incentive to prevent new validators from joining.
1. Have other validators act as whistleblowers and actively monitor the proposer for an epoch in which new validators get onboarded. When censoring occurs, whistleblowers can submit a proof from ETH1 data since the ETH1 chain contains a total ordering of deposits. Deposits may need to be augmented with a nonce, or the timestamp of deposits could suffice. If the proof is correct, the proposer for that epoch gets penalized. Attestors do not need to be penalized as they are not the ones censoring, and we don't want them to abstain from signing a block that provably censors deposit receipts.

Thoughts?

**Comment by vbuterin** [comment]
> Change the current sub-linear issuance model to a linear issuance model (i.e., set adjusted_quotient = get_previous_total_balance(state) // BASE_REWARD_QUOTIENT). Since individual validator rewards no longer decrease with each new validator, there is no incentive to prevent new validators from joining.

The problem with this is that it imposes on the network too much uncertainty of two types: (i) uncertainty of total issuance, (ii) uncertainty of the level of security on the network. That is, if it turns out that whatever rate we set is not enough, almost no one will participate, whereas the inv-sqrt mechanism adds some natural self-correcting pressure against this.

**Comment by vbuterin** [comment]
I updated the design rationale doc to mention this: https://notes.ethereum.org/s/rkhCgQteN#Base-rewards

**Comment by Mikerah** [comment]
Thanks @adlerjohn again for discussions on this.

First, I would like to note that the gatekeeping attack and discouragement attacks are different. In the gatekeeping attack, there's no cost for the malicious proposer to censor deposits whereas in discouragement attacks, the malicious proposer incurs some cost to themselves to attack other validators in the protocol. As such, the inv-sqrt issuance does not fix gatekeeping attacks since gatekeeping attacks are free.

Second, we can tweak 2) to leverage the fact that ETH1 data is voted on. For this, we need to include additional data in the Merkle proofs from the deposit logs that proves the correct number of deposit logs. Additional logic when voting for the correctness of ETH1 data should include a check that the number of deposit logs being included in a block do in fact match up with the probable number of deposits.

**Comment by djrtwo** [comment]
There are two types of gate-keeping

1. Validators conspire to prevent new eth1 deposit root from being successfully updated. This requires an attacker from having more than 50% of the proposers during an eth1 voting period which is highly unlikely given a 2/3 honesty assumption. This is potentially easier to conduct in early days of the beacon chain when validation numbers are lower and this is exactly why the `CHAIN_START_DEPOSIT_THRESHOLD` was increased to `65536` full deposits or (~2M ETH). This type of attack is also _very_ easy to detect extra protocol and can be coordinated if actually becomes a problem. This would also show us that our honestly assumption is broken in the early days which is better than finding that out in say phase 2.
2. Validators do not process deposits into the beacon chain. This is almost entirely mitigated by the new addition of enforced deposit processing. If for the current eth1 data deposit root there are unprocessed deposits, a validator _must_ include up to `MAX_DEPOSITS` deposits in their block for the block to be considered valid. A validator that wants to censor incoming deposits via this method can only do so my skipping block proposing (losing profit) and the deposits will certainly just be picked in the next block.

**Comment by adlerjohn** [comment]
Looks like #758 essentially implements the check described in proposal 2.

**Comment by Mikerah** [comment]
@djrtwo indeed mandatory deposits is a simplified implementation of proposal 2. 
Thanks for the replies

**Comment by adlerjohn** [comment]
Upon further consideration, I think the gatekeeping attack should be considered from two facets: (1) rational validators excluding deposits and (2) rational validators excluding activations. Making deposit processing mandatory only solves (1). Rational validators will still exclude activation transactions from being included in the canonical beacon chain.

There are two ways I can think of preventing this. First is to also allow activations to be sent to a contract on the ETH1 chain, and making processing of these activation transactions mandatory. This of course is predicated on the perpetual existence of the PoW chain and the beacon chain's reliance on it. Second is to set base rewards to a constant rate, i.e., `B = k * Di`, which removes the incentive to perform a gatekeeping attack.

[This paper](https://arxiv.org/abs/1811.00742) claims to provide a solution to this problem contained within a single PoS system, though I have not vetted it.

**Comment by djrtwo** [comment]
Copied from gitter:

> There is no such thing as an “activation transaction”, once a deposit is processed and is of a minimum size, the activation occurs during the natural processing of the chain. There is a maximum churn that dictates the speed but no external transactions

**Comment by adlerjohn** [comment]
For continuity, the relevant Gitter conversion starts here: https://gitter.im/ethereum/sharding?at=5c991f5c52c7a91455f4e2c2. It expands and clarifies several points made earlier in this thread.

**Comment by djrtwo** [comment]
general approach is large enough initial v-set, honest assumption, and forced deposits
