### ISSUE TITLE
Bigint support for SSZ

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#842]
We should consider adding a type `Bigint`, which exists as a wrapper over `bytes` (itself a wrapper over `[uint8]`), except with the validity condition that it cannot have leading zero bytes (so as in eth1, 0 would be represented as `b''`, not `b'\x00'`).

The immediate use case I am thinking of is generalized indices in [the light client spec](https://github.com/ethereum/eth2.0-specs/blob/b91dfd6244f7196827a311d879aa29ad7eb83f05/specs/light_client/merkle_proofs.md) (the "indices" array should be `[BigInt]`, not`["uint64"]` to be able to handle deep SSZ objects), but there are other possible use cases in the future, particularly if SSZ is used as an ABI for bigints for cryptographic operations, and also coin balances.

**Comment by jannikluhn** [comment]
One downside would be that it reintroduces a big endian integer type. But I'm not sure how much this actually matters, given that it would require a separate parser anyways.

**Comment by vbuterin** [comment]
We can preserve the norm that nothing in the phase 0 or 1 consensus layers requires them if that helps.

**Comment by JustinDrake** [comment]
Closing this for a couple reasons:

1) There's rough consensus to not implement SSZ bigint for now.
2) If `uint64` is too small one can use `uint128` or `uint256` (which *are* currently supported by SSZ) to handle deep SSZ objects.

Feel free to reopen :)
