### ISSUE TITLE
Define vector as an alias

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/eth2.0-specs#844]
A vector is serialized in the same way a container is that uses the same type for all elements. We therefore could define it as an alias. This would simplify the spec and reduce the number of test vectors.

The only difference between the two is the way the hash tree root algorithm works in the case of basic elements: Containers hash each element and merkleize, vectors pack and merkleize. With composite elements there's no difference. I don't know if this is an important special case, but I can't see a reason for it. So I think we can just use pack for containers of basic types as well.

**Comment by JustinDrake** [comment]
Interesting! Packing vectors of basic types makes sense, and the spec simplification is nice 👍

**Comment by JustinDrake** [comment]
Closing with #853.
