### ISSUE TITLE
Make Eth2Genesis log produce a serialized object

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#846]
For cleanliness we could have the `Eth2Genesis` log produce a serialized object, similar to how `Deposit` logs produce serialized objects. The `Eth2Genesis` object could be something like:

```python
{
    'genesis_time': 'uint64',
    'deposit_root': Hash,
    'deposit_count': 'uint64',
}
```

**Comment by hwwhww** [comment]
@JustinDrake 

Ah just realized it's a 23-day ago issue after assigning myself.

The `Deposit` log will be fields instead of serialized data after  https://github.com/ethereum/deposit_contract/pull/31, and it's okay to close this issue?

**Comment by JustinDrake** [comment]
Logging the fields is the best 👍
