### ISSUE TITLE
Disallow empty containers or vectors

### ISSUE THREAD

**Issue by jannikluhn** [ethereum/eth2.0-specs#854]
Empty containers/vectors are represented by an empty string. Therefore, lists of empty containers are always `0x 00 00 00 00`, regardless of the length of the list. As a data structure that's always empty is pretty useless anyway, I think it's safe to just disallow them.

**Comment by pipermerriam** [comment]
Maybe worth pointing out that this extends to *any* composite of **only** empty Vectors and Containers always serialize to the empty string (under the new SOS layout).

I can't immediately come up with any compelling use case for empty Vectors/Containers which makes me lean towards disallowing it in the spec.  Maybe worth surfacing in the next call if only to bring this to peoples attention in case someone comes up with something worthwhile.

**Comment by dankrad** [comment]
The only application would be to have a "Null" object that can be used in a (to be added) Option type that would allow nullable fields. While this is not needed inside the spec, it would allow SSZ to also be used in networking, and seems a fairly easy change.
Then we could disallow any empty containers except for the "Null" object.

**Comment by vbuterin** [comment]
Sounds good to me; lists of empty containers/vectors do break the invariant that SSZ serialization is injective within each type (ie. two different things of the same SSZ type always serialize to different values), so banning empty containers/vectors and making the empty string be the serialization of Null makes sense.

**Comment by dankrad** [comment]
This was actually implemented in #893, closing
