### ISSUE TITLE
Merkle root of a single element

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#859]
The SSZ spec declares the function `merkleize` as:

> merkleize: Given ordered `BYTES_PER_CHUNK`-byte chunks, if necessary append zero chunks so that the number of chunks is a power of two, Merkleize the chunks, and return the root.

I wanted to clarify that  `merkleize(0x00 * 32) == 0x00 * 32` and `merkleize(0x00 * 32) != hash(0x00 * 32)`.

**Comment by JustinDrake** [comment]
> I wanted to clarify that `merkleize(0x00 * 32) == 0x00 * 32` and `merkleize(0x00 * 32) != hash(0x00 * 32)`.

That's correct :) We are going to make the SSZ spec more explicitly executable to avoid these ambiguities. (It already is executable, see [here](https://github.com/ethereum/eth2.0-specs/blob/dev/utils/phase0/minimal_ssz.py).)

**Comment by djrtwo** [comment]
This is still not noted explicitly in the simple-serialize spec, correct @JustinDrake ?
I agree explicit on this case is probably better

**Comment by JustinDrake** [comment]
ccing @protolambda who is working on the executable SSZ. He may replace the current language with code soon :)

**Comment by dankrad** [comment]
I think explicit language would be good. Imagine that SSZ leaks outside the protocol, and someone at some point does not realise that merkleize is not preimage resistant (which it is in most cases). One single line could avoid this problem easily.

**Comment by djrtwo** [comment]
I concur @dankrad

**Comment by ralexstokes** [comment]
as long as it is somewhere... just spent some time looking at the deposit contract to verify the manual hash tree root calculation there and while it does check out, you have to infer that `merkleize` on a single 'chunk' is just that chunk.

**Comment by JustinDrake** [comment]
Sorry guys, this will get fixed soon. There's an SSZ rewrite in progress :)
