### ISSUE TITLE
get_block_root(state.justified_epoch) != current_justified_epoch

### ISSUE THREAD

**Issue by paulhauner** [ethereum/eth2.0-specs#860]
I noticed this during testing and I raise it for consideration.

Consider the genesis hash is `0x42 * 32` and we're at slot `GENESIS_SLOT + 1`.

- `state.current_justified_root == 0x00 * 32`
- `get_block_root(state, get_epoch_start_slot(state.current_justified_epoch)) == 0x42 * 32`

There are two, seemingly valid ways to read the `current_justified_root` and they return different values.

**Comment by djrtwo** [comment]
Correct. chicken and egg problem with the state and block roots again.

I see two solutions:
* Locally use `b'\x00'*32` as a synonym to the genesis block root wrt to finality (don't revert past 0x00 means do revert past genesis block)
* We can "surgically" add in previous and current justified_root as well as finalized_root in `cache_state` on the first transition after the genesis_slot. This would require putting a little bit of exceptional logic into the validator guide to explicitly handle attesting to his case.

**Comment by ralexstokes** [comment]
shall we favor the former (the alias route)? refer: https://github.com/ethereum/eth2.0-specs/pull/1023

**Comment by djrtwo** [comment]
I'm inclined to go with the alias (I suppose that's obvious as I merged the PR). I actually tried surgically adding it to the state in a future slot and it significantly complicated the attestation logic with an exceptional rule. 

Closing this issue. Happy to reopen if the debate is not yet done
