### ISSUE TITLE
RPC-Libp2p Determining Request/Response data

### ISSUE THREAD

**Issue by AgeManning** [ethereum/eth2.0-specs#861]
Currently Requests/Responses are encoded with SSZ and sent across the wire. 

SSZ requires a known schema in order to decode the serialized message. 

For a message received on the libp2p-RPC stream, one needs to know whether the message is a request or response to decode the message appropriately. Messages could include a prefix bit, specifying which object should be decoded.

Is there a better way to handle this? Should we specify this in the spec?

**Comment by djrtwo** [comment]
Another alternative is to put requests and responses on a different libp2p protocol -- `/eth/serenity/beacon/rpc/requests/1` vs `/eth/serenity/beacon/rpc/responses/1`.

What do you think @mslipper

**Comment by mslipper** [comment]
Hmm this is true. I'm kind of in favor of exploring alternative serialization formats/a message envelope to get around this issue. Having alternative libp2p protocols seems like a hack IMO.

**Comment by AgeManning** [comment]
I agree with @mslipper . Currently we (lighthouse) are building an SSZ req/resp object which has a prepended boolean which specifies whether its a request/response. 
I think in our discussions we seem to favour pre-pending a byte/bit in the serialization to distinguish the two?

**Comment by AgeManning** [comment]
Closing to keep discussion in #871
