### ISSUE TITLE
[Question][SSZ]To get item count from SSZ data

### ISSUE THREAD

**Issue by NAKsir-melody** [ethereum/eth2.0-specs#876]
Hi, 
I'm trying to integrate SSZ into trie structure.
And I have a question about getting item count from ssz serialized data.

When generating trie from DB,
Aleth & Geth use item count to decide node type. 

but with ssz spec, It seems that the only way to getting item count is decoding all serialized data.
Am I right?

And  what is best way of generating trie with serialized data which structured like below table?
(SOS is more suitable?)

State MPT | node hash | key | value
-- | -- | -- | --
Extension Node | bytes32(hash(ssz(k) + ssz(v)) | bytes | bytes32(hash)
|  |   | Variable-size | fixed-size
Leaf node | bytes32(hash(ssz(k) + ssz(v)) | bytes | bytes(state object)
|  |   | Variable-size | Variable-size
Branch node | bytes32(hash(ssz(k) + ssz(v)) | byte[17] | Bytes32[16] + bytes
|  |   | fixed-size | [0:15]fixed-size, [16] Variable-size

**Comment by JustinDrake** [comment]
> but with ssz spec, It seems that the only way to getting item count is decoding all serialized data.
Am I right?

We're likely going with [a new serialisation format](https://github.com/ethereum/eth2.0-specs/pull/787) which is more friendly to lengths. You'll be able to get the length of variable-length sub-objects without deserialising the full object.
