### ISSUE TITLE
A proposal for shard blocks (rough draft / outline)

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#90]
EDIT 2018.11.09: this is now a pull request. https://github.com/ethereum/eth2.0-specs/pull/123

### Constants

* `CHUNK_SIZE`: 256 bytes

### Block structure and validation

A `ShardBlock` object has the following fields:

```python
{
    # Slot number
    'slot': 'uint64',
    # Parent block hash
    'parent_hash': 'hash32',
    # Beacon chain block
    'beacon_chain_ref': 'hash32',
    # Depth of the Merkle tree
    'data_tree_depth': 'uint8',
    # Merkle root of data
    'data_root': 'hash32'
    # State root (placeholder for now)
    'state_root': 'hash32',
    # Attestation (including block signature)
    'attester_bitfield': 'bytes',
    'aggregate_sig': ['uint256'],
}
```

To validate a block on shard `shard_id`, compute as follows:

* Verify that `beacon_chain_ref` is the hash of the `slot`'th block in the beacon chain.
* Let `cs` be the crystallized state of the beacon chain block referred to by `beacon_chain_ref`. Let `validators` be `[validators[i] for i in cs.current_persistent_committees[shard_id]]`.
* Assert `len(attester_bitfield) == ceil_div8(len(validators))`
* Let `curblock_proposer_index = hash(cs.randao_mix + bytes8(shard_id)) % len(validators)`. Let `parent_proposer_index` be the same value calculated for the parent block.
* Make sure that the `parent_proposer_index`'th bit in the `attester_bitfield` is set.
* Generate the group public key by adding the public keys of all the validators for whom the corresponding position in the bitfield is set to 1. Verify the `aggregate_sig` using this as the pubkey and the `parent_hash` as the message.
* Verify the data (see below)

Note that we expect blocks to be broadcasted along with the signature from the `curblock_proposer_index`'th validator in the validator set for that block.

### Data root

* Let `data_size = calc_block_maxbytes(cs)` (function TBD; think of it as a function that returns values between ~1024 and ~100k, always multiples of `CHUNK_SIZE`)
* Verify that `2**data_tree_depth = next_power_of_2(data_size //  CHUNK_SIZE)`
* Verify the availability of the data in the tree as a tree of depth `data_tree_depth`
* Verify that all data after `data_size` bytes (ie. starting from chunk `data_size // CHUNK_SIZE`) is all set to zero bytes

### Fork choice rule

The fork choice rule is a two-part fork choice rule. First, use as a root the block referred to in the most recent successful crosslink for that shard in the beacon chain's fork choice. To find the head from there, use LMD GHOST, ie. given a choice between two child blocks of a given parent, choose the block that has more most-recent (ie. highest-slot-number) attestations (including attestations of its descendants) from the validators that are active in the most recent validator set.

### Modifications to crosslinks

Crosslinks also commit to the "combined data root", a Merkle root of the data roots of all blocks since the last crosslink created using the following process:

```python
def get_zeroroot_at_depth(n):
    o = b'\x00' * CHUNK_SIZE
    for i in range(n):
        o = hash(o + o)
    return o

def mk_combined_data_root(depths, roots):
    default_value = get_zeroroot_at_depth(max(depths))
    data = [default_value for _ in range(next_power_of_2(len(roots)))]
    for i, (depth, root) in enumerate(zip(depths, roots)):
        value = root
        for j in range(depth, max(depths)):
            value = hash(value, get_zeroroot_at_depth(depth + j))
        data[j] = value
    return compute_merkle_root(data)
```

Notice that this is equivalent to padding each block's data up to the power of two equal to or above the largest block's data, then concatenating the data, then padding the result with zero bytes to the next power of two, and taking the Merkle root of the result.

Crosslink participants should only sign data roots if the data roots match up with the result of this calculation.

Crosslink records also commit to the proof of custody computation of this data.

**Comment by vbuterin** [comment]
This is now a pull request: https://github.com/ethereum/eth2.0-specs/pull/123

**Comment by hwwhww** [comment]
close via #123
