### ISSUE TITLE
Unnecessary materialization of intermediate data in `verify_indexed_attestation`

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/eth2.0-specs#901]
Refer https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#verify_indexed_attestation

This line:
```python
total_attesting_indices = len(custody_bit_0_indices + custody_bit_1_indices)
```

The Python semantics are to materialize the intermediate list (concatenation of bit_1 onto bit_0 indices) and then compute the length. We can avoid the O(n) operation by just summing the two lengths of each individual list.

I'll admit this is a fairly minor issue and if there isn't enough support we can just close this issue :) I would imagine this won't be an issue, even as we use this code in the executable spec or testing.

If we want to take this optimization now (e.g. we could also wait until official spec freeze and then make a quick pass on this type of stuff), then I'm happy to make a PR.

**Comment by djrtwo** [comment]
Yeah, this is fine. Will merge
