### ISSUE TITLE
Reasoning for explicitly creating `Vector` types?

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/eth2.0-specs#905]
If you refer to the `BeaconState` creation during `get_genesis_beacon_state`, you'll see some ssz vector types are constructed w/ an explicit `Vector` function (while others are not).

I expect this is the result of a bad merge and happy to clean it up if so. If the calls to `Vector` are supposed to be there, can we get some explanation? I can't find a reference elsewhere across the specs.

**Comment by JustinDrake** [comment]
> I expect this is the result of a bad merge and happy to clean it up if so

Yes, we should be consistent. Having said that, SSZ initialisation will be massively cleaned up with default initial values (see [here](https://github.com/ethereum/eth2.0-specs/pull/843)).

**Comment by ralexstokes** [comment]
Gotcha, we can wait on #843 then
