### ISSUE TITLE
Alternate withdrawal mechanism (specified proposal)

### ISSUE THREAD

**Issue by vbuterin** [ethereum/eth2.0-specs#91]
See https://ethresear.ch/t/suggested-average-case-improvements-to-reduce-capital-costs-of-being-a-casper-validator/3844 for more theoretical discussion.

When a validator is removed from the active set via `exit_validator(...)`, they are assigned a `queue_id` (there is an incrementing `next_queue_id` variable in the `crystallized_state` that keeps track of what ID to assign). During every state recalculation, the `VALIDATOR_WITHDRAW_COUNT` validators with the lowest `queue_id`s are withdrawn.

We set `VALIDATOR_WITHDRAW_COUNT` to 2^3 = 8. Rationale: if ~12m (3 * 2^22) ETH (or 2^17 validators) are trying to exit at the same time following an attack, it will take them 2^14 cycles (= 2^23 seconds ~= 3.3 months) to exit.

This mechanism serves a triple purpose (see the ethresear.ch thread above). First, it makes the withdrawal time longer if more validators are participating, and shorter if fewer validators are participating, reducing the long-run uncertainty in the number of validators, though at some cost to long-run certainty in the safe weak subjectivity duration (though a validator will know when they will have to come back online next at the time that they go offline).

Second (less important), it creates further anti-centralization pressure because larger deposits will on average have to wait longer than small deposits.

Third, and most important, it makes withdrawals potentially very quick in the average case where few validators are exiting, and slower in the case where more validators are exiting. This changes the philosophy of validating somewhat, from "you are definitely committing your ETH for a long time", to "you retain high liquidity much of the time, but you agree that in the event that an attack appears you may be conscripted and required to stick around for a few months longer than you may have expected".

**Comment by djrtwo** [comment]
Closed via #112
