### ISSUE TITLE
Specs for sharding manager contract

### ISSUE THREAD

**Issue by jamesray1** [ethereum/eth2.0-specs#931]
It would be good if this repo hosted the specs for the sharding manager contract (versions 1 and 2, with collators then notaries), in order to act as a single reference point for Eth 2. Ideally the specs would also be hosted on a Jekyll theme GitHub hosted site, to be more user-friendly.

**Comment by JustinDrake** [comment]
The sharding manager contract (SMC) is long gone, replaced by the beacon chain! Good riddance :)
