### ISSUE TITLE
Make rewards transparent

### ISSUE THREAD

**Issue by dankrad** [ethereum/eth2.0-specs#943]
The BASE_REWARD_QUOTIENT parameter dictates the per-epoch reward. It corresponds to ~2.54% annual interest assuming 10 million participating ETH in every epoch.

Is there a source for how this figure was computed? (I can get something close, ca. 2.1%, but not this exact figure)
I also would suggest that the maximum reward computation should become part of the spec. Then we could write a test case for it and if rewards are modified to not match this formula we would notice, which I would see as an advantage. Small changes could make a big difference here.

**Comment by djrtwo** [comment]
There is some discussion on this here https://notes.ethereum.org/s/rkhCgQteN#Base-rewards
Note that this is missing the "source" reward and should be 1/5

I haven't re-run the numbers, but I imagine the 2.54% is compounding whereas the 2.1% is not. 

> I also would suggest that the maximum reward computation should become part of the spec.

Do you mean a formula showing how this is derived?

**Comment by dankrad** [comment]
> I haven't re-run the numbers, but I imagine the 2.54% is compounding whereas the 2.1% is not.

Compounding make a tiny difference of 0.03% here, so it's not that. I guess I am unsure how many times exactly the base_reward can be applied, the block proposer reward is not obvious. Also relates to #944 -- is the number 5 exact there? Because I feel it's not.

> Do you mean a formula showing how this is derived?
I would even go as far as including a function that computes the expected rewards per time period. Then we could add a test case and be sure that rewards will be what we expect them to be, no matter how we change the spec later :)

**Comment by JustinDrake** [comment]
In #1159 I've recalculated the appropriate value for `BASE_REWARD_FACTOR` (previously called `BASE_REWARD_QUOTIENT`) based on the policy that max issuance is about 2^21 ETH when the total effective balance is 2^17 ETH.

> Is there a source for how this figure was computed?

In the PR description I put the script used to calculate `BASE_REWARD_FACTOR`.

**Comment by JustinDrake** [comment]
> I also would suggest that the maximum reward computation should become part of the spec.

At some point we should have a "design rationale" document justifying, among other things, the constants.

**Comment by JustinDrake** [comment]
Closing in favour of #1344

**Comment by nathan-at-least** [comment]
> > I also would suggest that the maximum reward computation should become part of the spec.
> 
> At some point we should have a "design rationale" document justifying, among other things, the constants.

I've glanced at #1344 and it's only a calculator without the 'design rationale' part. I'm hunting for the rationale. Is there a good link for that yet?

**Comment by mratsim** [comment]
It should live in the annotated specs, though they go well into the rationale behind penalties and slashings and arguably not enough in the rewards:

- https://github.com/ethereum/annotated-spec/blob/master/phase0/beacon-chain.md#rewards-and-penalties=
- https://benjaminion.xyz/eth2-annotated-spec/phase0/beacon-chain/#rewards-and-penalties
