### ISSUE TITLE
generate_seed mixes in get_active_index_root

### ISSUE THREAD

**Issue by dankrad** [ethereum/eth2.0-specs#945]
In the definition
```python
def generate_seed(state: BeaconState,
                  epoch: Epoch) -> Bytes32:
    """
    Generate a seed for the given ``epoch``.
    """
    return hash(
        get_randao_mix(state, epoch - MIN_SEED_LOOKAHEAD) +
        get_active_index_root(state, epoch) +
        int_to_bytes32(epoch)
    )
```
Is there any reason to mix in the get_active_index_root? Currently this does not seem dangerous, but also does not provide any advantage as far as I can see. So with simplification in mind we could just remove it.
Also to protect RANDAO from biasability, it is advantageous to keep the seed as clean as possible. In case there would be any "instant changes" to the validator set, possibly introduced in some unforeseen spec version in the future, it would be unwise to have this in the mix.

**Comment by djrtwo** [comment]
This was added in #476 as per issue #459.

The specific rational is

> We add the active index root into the shuffling seed to make sure that it is not possible to affect the shuffling in predictable ways by entering or exiting the validator set (there is a Fiat-Shamir-heuristic-like argument here: even if the attacker can "choose" the validator set, the protocol randomly chooses the shuffling after they do that)

**Comment by dankrad** [comment]
Ah so we need it for light clients. Thanks
