### ISSUE TITLE
Clarify "per-epoch processing"

### ISSUE THREAD

**Issue by dankrad** [ethereum/eth2.0-specs#946]
When reading through the spec, I noticed that during epoch processing, the "current epoch" actually refers to the previous epoch, whereas in the block processing, the "current slot" corresponds to the slot of the given block.

To make this less confusing, I suggest renaming it to "end of epoch processing"?

**Comment by JustinDrake** [comment]
We have

```python
def get_current_epoch(state: BeaconState) -> Epoch:
    return state.slot // SLOTS_PER_EPOCH
```

and (see [state_transition.py](https://github.com/ethereum/eth2.0-specs/blob/dev/test_libs/pyspec/eth2spec/phase0/state_transition.py))

```python
def state_transition_to(state: BeaconState, up_to: Slot) -> BeaconState:
    while state.slot < up_to:
        spec.cache_state(state)
        if (state.slot + 1) % spec.SLOTS_PER_EPOCH == 0:
            process_epoch_transition(state)
        spec.advance_slot(state)
```

In other words, `process_epoch_transition` happens at slot `SLOTS_PER_EPOCH * k + SLOTS_PER_EPOCH - 1` for `k = 0, 1, 2, ...`, where the "current epoch" is `k`.

This does seem to contract this sentence in the spec:

> The per-epoch transitions, which happens at the start of the first slot of every epoch."

@djrtwo: Should it say "The per-epoch transitions, which happens at the start of the last slot of every epoch."?

**Comment by dankrad** [comment]
> @djrtwo: Should it say "The per-epoch transitions, which happens at the start of the last slot of every epoch."?

I think it should actually be

- after the last slot of every epoch
- before the first slot of every epoch

(I prefer the first variant and suggest, to make it clearer, to call them "end of epoch" transition, because the epoch number at the time of the transition is the old epoch rather than the new one)

**Comment by djrtwo** [comment]
> The per-epoch transitions, which happens at the start of the first slot of every epoch."

At the start of the state transition of the first slot of every epoch.

yes, the slot isn't incremented yet at that point in the state transition but it is certainly during the state transition of the 1st slot of the epoch.

That said, the debate really seems to be in #1043 😂

**Comment by JustinDrake** [comment]
Closing in favour of #1043
