### ISSUE TITLE
`validator.randao_last_change` is never updated

### ISSUE THREAD

**Issue by benjaminion** [ethereum/eth2.0-specs#95]
Two issues with respect to RANDAO commitment handling:
 
 * `randao_last_change` is set when a validator is inducted, but is not changed when the validator's commitment is updated in response to the `RANDAO_REVEAL` special.

 * A variable `V.randao_last_reveal` appears but is not defined. Suspect a typo for `V.randao_last_change`.

**Comment by djrtwo** [comment]
Yes indeed. Will make a PR. 

- unify two vars
- pass slot through the special record to update the `validator.randao_last_reveal` in the state recalc
