### ISSUE TITLE
Remove inclusion_slot

### ISSUE THREAD

**Issue by JustinDrake** [ethereum/eth2.0-specs#956]
The `inclusion_slot` is used three places:

* In `get_earliest_attestation`. It turns out that it is not required there because `state.previous_epoch_attestations` and `state.current_epoch_attestations` are already ordered by `inclusion_slot`.
* To compute inclusion delay for incentivisation. This is not required because incentivisation can be done on a per-block basis with `process_proposer_attestation_rewards`.
* In `process_proposer_attestation_rewards`. It's not required there because filtering by `inclusion_slot` is already done by looking at `block.body.attestations`.

I think we can remove `inclusion_slot` from `PendingAttestation` (in addition to `custody_bitfield`—see #955).

**Comment by djrtwo** [comment]
What about the reward/penalty for inclusion speed?

**Comment by JustinDrake** [comment]
> What about the reward/penalty for inclusion speed?

That's the second bullet point about "inclusion delay" (renamed to be consistent with `MIN_ATTESTATION_INCLUSION_DELAY` constant). The incentivisation can be done on a per-block basis alongside `process_proposer_attestation_rewards`.

Without `inclusion_slot` we can get rid of `PendingAttestation` and simplify the code throughout 🎉

**Comment by djrtwo** [comment]
In the worst case, updating inclusion speed rewards on a per block basis can affect 1/8 (128/1024) validators and associated balances. Is it reasonable to take this hashing hit?

@paulhauner do you have relevant benchmarks that can shed light on the time hit of rehashing this fraction of the validator state?

**Comment by JustinDrake** [comment]
One idea to remove `inclusion_slot` (and hence `PendingAttestation`) while not taking the hashing hit is to make `previous_epoch_attestations` and `current_epoch_attestations` vectors of length `MAX_ATTESTATIONS * SLOTS_PER_EPOCH` and infer the `inclusion_slot` based on the vector index.

**Comment by JustinDrake** [comment]
Probably too hacky
