### ISSUE TITLE
Access Client Interface

### ISSUE THREAD

**Issue by nivida** [ethereum/eth2.0-specs#983]
### Questions 

- Is there an idea around to add a method which is returning the node information? 
- Is it planned to have the possibility to create for example an in-browser peer which is just sending transactions to the network? (I think it would be great to send transactions in a decentralized manner) 

### Idea - Access Client Interface

The idea is to create an in-browser/client peer for discovering full and light nodes. The discovered full and light nodes should be used to get data from the chain history. Subscriptions and sending of transactions should be done directly by the in-browser/client peer. 

I think we should move as much as possible from the nodes to the client.

### RPC Interface

The RPC interface would have to be extended with the possibility to return the latest Block of a discovered peer. 

**NodeInfo**

Method:
```javascript
{
  id: 0;
  method_id: 14;
  body: {};
}
```

Response:

```javascript
NodeInfo {
  latestBlock: Block;
}
```

**Account**

The accounts handling can't be specified until we have this [discussion](https://ethereum-magicians.org/t/brainstorming-the-token-standard-in-eth2/3135/6) finalized.

- getBalance

**History**

We can use the existing [rpc-interface](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/networking/rpc-interface.md) methods and probably extend the list with some aliases for having a simpler API.

### GossipSub

- [gossipsub-js](https://github.com/ChainSafe/gossipsub-js/tree/gossip_implementation)

The idea is to subscribe directly to the "block stream" and to filter for the desired blocks. 
A possible filter mechanism could be implemented in JS or with WASM if there are any performance issues. 

**Transaction**

A transaction should get broadcasted to the correct mesh of peers and we will listen with the locally generated transaction hash if the transaction will appear in one of the next blocks. 

[devp2p Transaction](https://github.com/ethereum/devp2p/blob/master/caps/eth.md#transactions-0x02)

**Comment by oscar-fonseca** [comment]
I think that moving the relayer networks into clients, even as optional, would be a great decision moving forward. There are metatransaction relayers of different kinds, such as Griffith's, 0x Relayers, or TXCast. These are also cryptographically secure, we but have to add extra steps to make this happen. We could take these, which are already WIP, and adapt them for native ETH2.0 transactions. There is an EIP that would benefit from this, addressing "headless transaction" i.e. one payload signer, one transaction fee payer signer.

People directly working on ETH2.0 clients will know if adapting relayer networking into native clients is nonsense, but it would be a great addition, since it would enable many services, less relying on Infura, and a standard for off-chain interfaces.

**Comment by MicahZoltu** [comment]
Can you explain the advantages this has over running a light client directly in the browser?

How would clients in this P2P network validate the data they are receiving?  What protects them from malicious peers giving them faulty information?

**Comment by nivida** [comment]
> Can you explain the advantages this has over running a light client directly in the browser?

It uses not the same amount of resources as a light node which is important for older devices or low-end devices. 

> How would clients in this P2P network validate the data they are receiving? What protects them from malicious peers giving them faulty information?

It will be possible to define a trusted peer if you don't trust the discovered peers.

**Comment by nivida** [comment]
This idea isn't possible because I can't trust the discovered peers and their data. I would always have to verify the data I've got which will end up in a light client. The only thing which is possible is to send a transaction from a local peer.
